[runtime-security] introduce grand parent discarders
DataDog/datadog-agent pull request #10396
Opened 2022-01-03 11:20 UTC by safchain

### What does this PR do?

Add support for detecting grand parent discarders. It refactors the parent discarder discovering process so that it can detect deeper level of parent discarders. It fixes also the glob handling, introducing the use of `**` to match multiple levels of folder.

### Motivation

Discard more, reduce events.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-01-03 14:46 UTC, Gui774ume approved these changes
2 nits and 2 potential improvements ?
Otherwise lgtm :+1:

2022-01-03 14:46 UTC, Gui774ume commented on pkg/security/probe/discarders.go
> +		if err := discarderEvent.SetFieldValue(field, dirname); err != nil {
Should we delete this ?

2022-01-03 14:46 UTC, Gui774ume commented on pkg/security/probe/discarders.go
> +		if isDiscarder, _ := rs.IsDiscarder(discarderEvent, field); !isDiscarder {
Should we delete this ?

2022-01-03 20:43 UTC, maycmlee requested changes

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    CWS makes use of `**` pattern for subfolder matching instead of `*`.
```suggestion
    CWS uses `**` for subfolder matching instead of `*`.
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    Before `*` could be used in order to match files and subfolders. With this
```suggestion
    Previously, `*` was used to match files and subfolders. With this
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    release `*` will match only files and folders and the same level. `**` can
```suggestion
    release, `*` will match only files and folders at the same level. Use`**`
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    be used at the end of a path in order to match files and subfolders. `**` is
```suggestion
    at the end of a path to match files and subfolders. `**` must be
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    only supported at the end of a path. In order to keep the same behaviors the
```suggestion
    used at the end of the path. For example, the rule `open.file.path == "/etc/*"`
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    rules like `open.file.path == "/etc/*"` as to be converted to
```suggestion
    has to be converted to `open.file.path == "/etc/**"`.
```

2022-01-03 20:43 UTC, maycmlee commented on releasenotes/notes/cws-add-globstar-cd94c2cde6535b40.yaml
> +    `open.file.path == "/etc/**"`.
```suggestion
```

2022-01-04 14:55 UTC, maycmlee approved these changes

2022-01-07 16:48 UTC, merged