Raise the logs agent max HTTP batch size to 1000
DataDog/datadog-agent pull request #10400
Opened 2022-01-03 19:29 UTC by gh123man

### What does this PR do?

Raise the max batch payload size to `1000` elements. This is the maximum size according to [our docs](https://docs.datadoghq.com/api/latest/logs/#send-logs). 

This effectively raises the maximum throughput of logs (with an assumed 50ms of HTTP latency) from `~1.7 MB/sec` to `~9 MB/Sec`. This has no impact on lower throughput scenarios. 

CPU usage raises proportionally to the extra log throughput, but did not exceed `900` mcores in my benchmarks. 

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Send a high rate of logs to the intake. Spot check that none are missing. 

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-01-03 20:00 UTC, sgnn7 approved these changes
@gh123man LGTM though it may be worthy of a release note

2022-01-04 09:49 UTC, olivielpeau commented
I think this changes the default for all components sending to an event platform intake, not only logs, so let's update the PR description accordingly, communicate this changes to the affected teams and add them for QA. Also, does this limit of `1000` items apply consistently for all event platform intakes?

2022-01-06 17:43 UTC, ruthnaebeck requested changes

2022-01-06 17:43 UTC, ruthnaebeck commented on releasenotes/notes/raise_max_batch_size-c8fd6a98468ae675.yaml
> +    Logs and events max batch size raised from `100` to `1000` elements. Improves
```suggestion
    Raised the max batch size of logs and events from `100` to `1000` elements. Improves
```

2022-01-06 19:10 UTC, olivielpeau approved these changes

2022-01-06 19:46 UTC, xcoderzach approved these changes

2022-01-06 20:02 UTC, ruthnaebeck approved these changes
👍  for docs

2022-01-06 21:37 UTC, merged