[CWS] Introduce TC classifier, investigate kernel space DNS event
DataDog/datadog-agent pull request #10553
Opened 2022-01-16 14:54 UTC by Gui774ume

### What does this PR do?

This PR introduces the first steps required to start working with BPF TC classifiers within CWS. TC classifiers are filters of the Linux Traffic Control subsystem that can be used monitor and shape the network traffic on a host. TC classifiers are attached to qdiscs, which are themselves attached to network interfaces. A TC classifier can only see the ingress and egress traffic of its network interface, which means that we need to attach to all interfaces if we want to monitor the local traffic too. As such, this PR tracks the creation of new network interfaces so that we can dynamically add new TC classifiers on them. Since network interfaces are namespaced, we also needed to track network namespaces so that we can interact with them (and attach TC classifiers).

Another big part of this PR is to be able to route the ingress (or egress) traffic to the destination (or source) process that will receive (or that has emitted) the network traffic we intercept. This is done by monitoring the ports and IP addresses that are bound by the running processes on the host. A snapshot of these bindings was also added so that we can route the traffic of existing connections.

In between interfaces, various netfilter hook points can be used to redirect or mangle with network packets. Since we match processes with their binding ports and IP addresses, we also need to track any network address translation that might occur through the netfiler ABI. For now, we are only tracking the operations made by the `nat` table.

Last but not least, in order to test these features, we implemented a kernel space DNS request parser and introduced the `dns` event. The following fields are exported:
- `dns.id`: the DNS request ID
- `dns.qdcount`: the number of questions in the DNS request
- `dns.qclass`: the class of the DNS request
- `dns.qtype`: the type of the DNS request
- `dns.dns_server_ip`: the IP address of the DNS server
- `dns.name`: the name of the DNS server

Example rule:
```
---
version: 1.0.0
macros:
 - id: CRYPTOMINER_DOMAINS
   expression: |-
     [ "asia1.ethpool.org", "ca.minexmr.com", "cn.stratum.slushpool.com", "de.minexmr.com",
     "eth-ar.dwarfpool.com", "eth-asia.dwarfpool.com", "eth-asia1.nanopool.org", "eth-au.dwarfpool.com",
     "eth-au1.nanopool.org", "eth-br.dwarfpool.com", ... ]
     
rules:
 - id: potential_cryptominer
   description: A process resolved a DNS name associated to cryptomining activity
   expression: dns.name in CRYPTOMINER_DOMAINS
```

### Motivation

The goal of this PR is to start working with TC classifiers on a very simple example.

### Additional Notes

This PR is blocked on the following `ebpf-manager` PRs:
- https://github.com/DataDog/ebpf-manager/pull/22
- https://github.com/DataDog/ebpf-manager/pull/23
- https://github.com/DataDog/ebpf-manager/pull/25
- https://github.com/DataDog/ebpf-manager/pull/26

### Describe how to test/QA your changes

Functional tests were added to test the new `dns` event type.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-01-17 15:21 UTC, kayayarai approved these changes

2022-01-18 18:44 UTC, djmitche reviewed
`pkg/config/config.go` change looks good for agent-core

2022-03-10 10:15 UTC, lebauce requested changes

2022-03-10 10:15 UTC, lebauce commented on pkg/security/probe/namespace_resolver.go
> +	resolvers *Resolvers
resolvers doesn't seem to be used

2022-03-10 10:15 UTC, lebauce commented on pkg/security/probe/namespace_resolver.go
> +	nr.Lock()
RLock/RUnlock seems to be enough here

2022-03-10 10:15 UTC, lebauce commented on pkg/security/probe/namespace_resolver.go
> +				continue
netns.Unlock()

2022-03-10 10:43 UTC, Gui774ume commented on pkg/security/probe/namespace_resolver.go
> +				continue
Nice catch 😱

2022-03-10 10:44 UTC, Gui774ume commented on pkg/security/probe/namespace_resolver.go
> +	nr.Lock()
👍🏻

2022-03-10 10:45 UTC, Gui774ume commented on pkg/security/probe/namespace_resolver.go
> +	resolvers *Resolvers
👍🏻

2022-03-11 11:52 UTC, lebauce approved these changes

2022-03-24 16:39 UTC, paulcacheux approved these changes

2022-03-24 16:40 UTC, merged