[Logs] Be more lenient when filtering docker container with labels.
DataDog/datadog-agent pull request #1058
Opened 2018-01-16 14:03 UTC by mnshdw

### What does this PR do?

This PR changes the way we filter Docker container when there is a `label` in the configuration.

Previously, we took the whole label and checked whether there was a container that had that label as a key.

With this change, we now accept a comma separated list of labels that can be formatted either as `key:value`, `key=value`, or simply `key`.

### Motivation

This should address https://github.com/DataDog/datadog-agent/issues/946.

2018-01-16 14:31 UTC, ajacquemot reviewed
This looks good to me, I just left a tiny comment. I am wondering if Kenafeh has not implemented this feature already, did you check on your side ?

2018-01-16 14:31 UTC, ajacquemot commented on pkg/logs/input/container/scanner.go
> +			if _, ok := container.Labels[label]; ok || len(parts) == 2 && container.Labels[parts[0]] == parts[1] {
I'd rather use `exists` than `ok`

2018-01-16 15:27 UTC, tmichelet requested changes
One regression, otherwise 👍

2018-01-16 15:27 UTC, tmichelet commented on pkg/logs/input/container/scanner.go
> +	if source.Image != "" {
Why are we changing this?

2018-01-17 10:10 UTC, ajacquemot approved these changes

2018-01-19 14:52 UTC, tmichelet approved these changes

2018-01-19 15:46 UTC, merged