Db/merge no docker
DataDog/datadog-agent pull request #1065
Opened 2018-01-17 17:15 UTC by derekwbrown

### What does this PR do?

Allows code to be built without the 'docer' tag

2018-01-17 17:38 UTC, hkaj submitted a review, later dismissed

2018-01-17 17:38 UTC, hkaj commented on pkg/util/container/providers_stub.go
> +// Copyright 2017 Datadog, Inc.
nit but it's 2018 🎉

2018-01-17 20:12 UTC, hkaj requested changes

2018-01-17 20:12 UTC, hkaj commented on pkg/collector/autodiscovery/autoconfig.go
> +		log.Errorf("%v: unable to load the check '%s': %s", loader, config.Name, err) // TODO: temp - delete me
This was temporary, it should go back to a `Debugf`.

2018-01-17 20:36 UTC, derekwbrown commented on pkg/util/container/providers_stub.go
> +// Copyright 2017 Datadog, Inc.
Heh.  Copy/paste error.

2018-01-22 22:35 UTC, hkaj approved these changes
Lgtm

2018-01-22 23:22 UTC, merged