Add the possibility to specify multiple config files to the Agent.
DataDog/datadog-agent pull request #10753
Opened 2022-02-02 15:50 UTC by vboulineau

### What does this PR do?

The command line is modified to accept multiple --cfgpath parameters.
The configurations are merged, in order, from left to right (ritghmost file has highest priority).
All files still have less priority than environment variables.

### Motivation

Allow proper override between default/generated configuration and user provided configuration.

### Additional Notes

### Possible Drawbacks / Trade-offs

Loosing the ability to use any other file format than YAML (a PR to our fork could enable it again).

### Describe how to test/QA your changes

Nothing should change when using a single configuration file (default setup).
When multiple files are given on the command line, the resulting `agent config` should show the rightmost values for overridden fields.
Setting a value through ENV Var should always override any value from file.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-02-02 18:21 UTC, djmitche requested changes
It's worth noting that many of the diff hunks in this PR are linting changes (adding/removing whitespace, changing between variants of variable declarations, etc.), presumably made by an editor?  Scrolling past them isn't awful, but it is distracting and may later generate unnecessary merge conflicts.

A few notes below, and it also looks like windows-unit-tests has identified some places that didn't get updated.

I'm not sure where this should be documented, but some clarification on what it means to "merge" would be good.  For example, are arrays concatenated or replaced or merged item-by-item?

2022-02-02 18:21 UTC, djmitche commented on pkg/config/config.go
> +		}
Why is this change required here?

2022-02-02 18:21 UTC, djmitche commented on pkg/config/viper.go
> +// ReadInConfig wraps Viper for concurrent access
Fix doc comment

2022-02-17 10:08 UTC, hush-hush requested changes
Since we use the configuration file location in a few places using `ConfigFileUsed` (like the GUI), let's verify that nothing broke with this change and document the limitation.

2022-03-02 19:50 UTC, brycekahle commented on cmd/system-probe/config/config.go
> +	_, err := aconfig.LoadWithoutSecret("system-probe", []string{configPath}, true)
This previously did not error on missing, so I think we want `false` here.

2022-03-02 19:55 UTC, brycekahle commented on pkg/config/config.go
> +	for _, confFilePath := range confFilePaths {
I think you might want to check if `len(confFilePath) > 0`, since it is an empty string by default (at least in the system-probe).

2022-05-09 10:01 UTC, closed without merging