[Windows] add process agent support
DataDog/datadog-agent pull request #1075
Opened 2018-01-18 22:19 UTC by derekwbrown

### What does this PR do?

Adds process agent support.

2018-01-22 17:58 UTC, ofek requested changes

2018-01-22 20:35 UTC, derekwbrown commented on omnibus/config/software/datadog-process-agent-win.rb
> +  #command "go get github.com/Masterminds/glide", :env => env
yes.  Gets a newer version of glide, which doesn't work on windows :(.  Fortunately, we're moving to dep.

2018-01-22 20:37 UTC, ofek submitted a review, later dismissed

2018-02-06 21:13 UTC, gmmeyer submitted a review, later dismissed
🚢 👍

2018-02-06 21:13 UTC, gmmeyer commented on omnibus/config/projects/agent.rb
> +if not osx?
Not a blocker but idiomatic ruby uses `!` instead of `not`

2018-02-06 21:50 UTC, gmmeyer submitted a review, later dismissed
:shipit:

2018-02-12 16:37 UTC, truthbk approved these changes
Looks good! 🚀

2018-02-12 16:37 UTC, merged