update doc for docker/kube features
DataDog/datadog-agent pull request #1108
Opened 2018-01-25 18:30 UTC by xvello

Update the docs reflecting the state of `beta9`.

2018-01-26 08:04 UTC, masci requested changes
Left a couple of comments, otherwise 💯

2018-01-26 08:04 UTC, masci commented on docs/agent/changes.md
> +    agent. Those only lists supports `image` name and `container` name (instead of
Not sure this sentence is working well, can we rephrase?

2018-01-26 08:04 UTC, masci commented on docs/agent/changes.md
> +  * The (work-in-processs) `kubernetes_apiserver` check retrieving events and
s/work-in-process/work-in-progress

2018-01-26 08:04 UTC, masci commented on docs/beta.md
> +* kubernetes [to be replaced by new checks](changes.md#kubernetes-support)
🍰

2018-01-27 12:11 UTC, CharlyF requested changes
Thanks a bunch for this PR! Left a few comments.
There are 3 dead links, happy to approve when they are updated

2018-01-27 12:11 UTC, CharlyF commented on docs/agent/changes.md
> +* [Docker]((#docker-check))
Seems broken https://github.com/DataDog/datadog-agent/blob/4853eb4b2c99e15a3a44a95910f0acee0e5d41b9/docs/agent/(#docker-check)

2018-01-27 12:11 UTC, CharlyF commented on docs/agent/changes.md
Worth listing the DCA ?

2018-01-27 12:11 UTC, CharlyF commented on docs/agent/changes.md
> +While we are continuing to ship the python libraries that shipped with Agent 5,
"the python libraries that shipped with Agent 5" > "the python libraries that ship with Agent 5" ?

2018-01-27 12:11 UTC, CharlyF commented on docs/beta.md
> +* kubernetes [to be replaced by new checks](changes.md#kubernetes-support)
Seems like the two above links 404

2018-01-29 10:10 UTC, xvello commented on docs/agent/changes.md
>  The `kube_service` tagging depends on the `Datadog Cluster Agent`, which is not released yet.
Once we officially release the DCA, we'll need a `docs/cluster-agent` folder and update that part and the kubernetes events section to link to it, indeed.

My first impression is that we should link from the dockerfiles readme to the doc, not the other way around, WDYT?

2018-01-30 08:45 UTC, CharlyF commented on docs/agent/changes.md
>  The `kube_service` tagging depends on the `Datadog Cluster Agent`, which is not released yet.
yeah, that's fair 👍

2018-01-30 10:25 UTC, CharlyF approved these changes

2018-01-30 10:26 UTC, merged