[ksm] make time based metrics comparable.
DataDog/datadog-agent pull request #11394
Opened 2022-03-21 21:26 UTC by bjhaid

### What does this PR do?

Prior to this patch the ksm collector would call
`time.Now().Unix.()-metric.Val` at every point a `_time` metric is
computed, this leads to the values collected in the same loop not being
comparable since their values skews based on the value of `time.Now()`
at the time metric was collected.

For an example of the impact of the above, to compute how long it takes a
pod to start after being created we create a function:

```
avg:kubernetes_state.pod.age{pod_name:filebeat-lf6hz} by {pod_name}
- avg:kubernetes_state.pod.uptime{pod_name:filebeat-lf6hz} by {pod_name}
```

When this is plotted on a dashboard we end up with values fluctuating
between negative and positive.

To ensure the values are comparable the `currentTime` is snapshotted at
the start of the Run loop and the value is reused in all places that had
previously called `time.Now()`.

### Motivation

We need to determine how long our pods take from creation to starting, to
measure control plane overhead. The screenshot below depicts the problem
this patch is attempting to solve:

![image](https://user-images.githubusercontent.com/593852/159366482-89b28b27-0268-4ef0-b63a-e6dad360dd44.png)

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-03-21 22:33 UTC, kayayarai requested changes
Please confirm, but I think you need to delete the sections you aren't using ("upgrade" "feature" etc) from the release note template.

2022-03-21 22:33 UTC, kayayarai commented on releasenotes/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +    [ksm] make time based metrics comparable.
```suggestion
    [ksm] KSM Time-based metrics are now comparable.
```

2022-03-22 10:11 UTC, ahmed-mez reviewed
Thank you for the contribution @bjhaid ! The code change looks good.

The Datadog Cluster Agent can run the KSM Core check, could you also copy the release note file in the `releasenotes-dca/notes` folder as well? 

Thanks!

2022-03-22 10:11 UTC, ahmed-mez commented on releasenotes/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +  - |
```suggestion
---
fixes:
  - |
    Time-based metrics (e.g `kubernetes_state.pod.age`, `kubernetes_state.pod.uptime`) are now comparable in the Kubernetes state core check.
```

2022-03-22 15:09 UTC, bjhaid commented on releasenotes/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +    [ksm] make time based metrics comparable.
thanks! addressed, along with @ahmed-mez 's feedback below

2022-03-22 15:09 UTC, bjhaid commented on releasenotes/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +  - |
thanks! addressed

2022-03-23 15:55 UTC, ahmed-mez approved these changes
> do you have an estimate on when the release schedule for v1.20 is? Thanks!

We're actively working on releasing v1.19 right now - v1.20 is expected to be released in ~2 months.

Thanks for the contribution!

2022-03-24 21:25 UTC, bjhaid commented
@kayayarai PTAL, thanks!

2022-03-24 21:59 UTC, kayayarai approved these changes
An edit suggestion to change the latinate abbreviation to English. Otherwise 👍  for docs.

2022-03-24 21:59 UTC, kayayarai commented on releasenotes-dca/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +    Time-based metrics (e.g `kubernetes_state.pod.age`, `kubernetes_state.pod.uptime`) are now comparable in the Kubernetes state core check.
```suggestion
    Time-based metrics (for example, `kubernetes_state.pod.age`, `kubernetes_state.pod.uptime`) are now comparable in the Kubernetes state core check.
```

2022-03-24 21:59 UTC, kayayarai commented on releasenotes/notes/ksm-comparable-metrics-b31f1f1fcbae1753.yaml
> +    Time-based metrics (e.g `kubernetes_state.pod.age`, `kubernetes_state.pod.uptime`) are now comparable in the Kubernetes state core check.
```suggestion
    Time-based metrics (for example, `kubernetes_state.pod.age`, `kubernetes_state.pod.uptime`) are now comparable in the Kubernetes state core check.
```

2022-03-25 09:15 UTC, merged

2022-03-25 14:15 UTC, bjhaid commented
@ahmed-mez @kayayarai thanks a lot for your reviews, very much appreciated!

2022-06-29 21:50 UTC, bjhaid commented
@ahmed-mez do you have an ETA for v1.20?

2022-06-30 07:33 UTC, ahmed-mez commented
Hey @bjhaid Cluster Agent 1.20 was released last week