Add cache on kubelet podlist
DataDog/datadog-agent pull request #1144
Opened 2018-01-30 14:23 UTC by mfpierre

### What does this PR do?

Add a caching layer to the `/pods` endpoint of the kubelet API.

### Motivation

Avoid stressing the kubelet + performance

2018-01-30 15:02 UTC, JulienBalestra requested changes
Two nits, thanks for the ResetCache !

2018-01-30 15:02 UTC, JulienBalestra commented on pkg/util/kubernetes/kubelet/kubelet.go
> +	if !hit {
We can return fast here:
```go
if hit {
return pods.Items, nil
}
```

2018-01-30 15:02 UTC, JulienBalestra commented on pkg/util/docker/docker_util.go
> +	if !hit {
I think we can return if hit is true.

2018-01-30 15:45 UTC, JulienBalestra submitted a review, later dismissed

2018-01-31 08:48 UTC, xvello commented
Looks great, the caching/reset logic could use a dedicated unit test though.
You can test we didn't send a request by using a select on the chan:
```go
select {
	case <-kubelet.Requests:
		assert.FailNow("podlist request should have been cached")
	default:
}
```

2018-01-31 19:34 UTC, JulienBalestra approved these changes
lgtm, :+1: for the cleanup

2018-02-01 09:18 UTC, merged