[pkg/otlp] Deprecate `metrics.report_quantiles` in favor of `metrics.summaries.mode`
DataDog/datadog-agent pull request #11451
Opened 2022-03-25 10:55 UTC by mx-psi

### What does this PR do?

Add a new configuration option, `metrics.summaries.mode` to replace `metrics.report_quantiles`.

### Motivation

Counterpart to open-telemetry/opentelemetry-collector-contrib#8846

### Additional Notes

As on #11406, no link to the Collector issue, to avoid confusion

### Describe how to test/QA your changes

#### Test one

Run the OTLP pipeline with `metrics.report_quantiles` set to true or false:

```yaml
otlp_config:
  receiver:
    protocols:
      grpc:
  metrics:
    report_quantiles: true|false
```

Send OTLP Summary metrics. To do this, since Summary metrics are not produced by the SDK, you will need to use a Collector and produce them with e.g. [the `statsdreceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/statsdreceiver):

```yaml
receivers:
  statsd:
    endpoint: 0.0.0.0:9999 # to not conflict with the Agent
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "summary"

exporters:
  otlp:
    endpoint: '0.0.0.0:4317'
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [otlp]
```

and then send a histogram to the statsd endpoint (`0.0.0.0:9999`) using, for example, the `datadog-go` library.

Check that:

- [ ] Quantiles are reported or not for these summaries depending on the `report_quantiles` value
- [ ] A warning is logged telling users to switch to `metrics.summaries.mode`

#### Test two

Run the OTLP pipeline with `metrics.summaries.mode` set to `noquantiles` or `gauges`.

```yaml
otlp_config:
  receiver:
    protocols:
      grpc:
  metrics:
    summaries:
      mode: noquantiles|gauges
```

Send OTLP summary metrics (see above for details) and check that:

- [ ] Quantiles are reported or not for these summaries depending on the mode, mathing the `report_quantiles` behavior (true -> gauges, false -> noquantiles)
- [ ] No deprecation warning is logged

#### Test three

Run the OTLP pipeline with both `metrics.report_quantiles` and `metrics.summaries.mode`:

```yaml
otlp_config:
  receiver:
    protocols:
      grpc:
  metrics:
    report_quantiles: true|false
    summaries:
      mode: noquantiles|gauges
```

Check that:

- [ ] The OTLP pipeline fails to start with an error indicating that both settings should not be used at the same time

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-03-25 11:09 UTC, KSerrania approved these changes

2022-03-25 11:09 UTC, KSerrania commented on pkg/config/config_template.yaml
> +        ## - `noquantiles` to no report quantile metrics.
```suggestion
        ## - `noquantiles` to not report quantile metrics.
```

2022-03-25 11:14 UTC, hush-hush requested changes

2022-03-25 11:14 UTC, hush-hush commented on pkg/config/config_template.yaml
> +    ## DEPRECATED: [v7.36] Use `summaries.mode` instead. Will be removed in v7.37.
```suggestion
    ## DEPRECATED: [v7.36 / v6.36] Use `summaries.mode` instead. Will be removed in v7.37 / 6.36.
```

2022-03-25 11:14 UTC, hush-hush commented on releasenotes/notes/otlp-report-quantiles-74692bf1b8066614.yaml
> +    OTLP ingest: ``metrics.report_quantiles`` has been deprecated in favor of ``metrics.summaries.mode``. ``metrics.report_quantiles`` will be removed in v7.37.
```suggestion
    OTLP ingest: ``metrics.report_quantiles`` has been deprecated in favor of ``metrics.summaries.mode``. ``metrics.report_quantiles`` will be removed in v7.37 / v6.36.
```

2022-03-25 11:29 UTC, mx-psi commented on releasenotes/notes/otlp-report-quantiles-74692bf1b8066614.yaml
> +    OTLP ingest: ``metrics.report_quantiles`` has been deprecated in favor of ``metrics.summaries.mode``. ``metrics.report_quantiles`` will be removed in v7.37.
```suggestion
    OTLP ingest: ``metrics.report_quantiles`` has been deprecated in favor of ``metrics.summaries.mode``. ``metrics.report_quantiles`` will be removed in v7.37 / v6.37.
```

2022-03-25 15:35 UTC, urseberry approved these changes

2022-03-28 09:23 UTC, hush-hush approved these changes

2022-03-28 12:22 UTC, merged