Add integration trace flag
DataDog/datadog-agent pull request #11520
Opened 2022-03-31 21:22 UTC by coignetp

### What does this PR do?

Adding a `--m-trace` hidden flag to the `agent check` command so the check run traces of the integration run are uploaded.
How to use it:
* Enable `apm` in the `datadog.yaml`
* Restart the agent
* Run the check command `agent check --m-trace <INTEGRATION>` (traces can be seen with an additional `-l debug`)
* Find the trace in the datadog UI under `service:<INTEGRATION>-integration`

### Motivation

In order to debug issue in support cases we use logs, but we should also use trace to ease this support. With this change, customer can use `datadog-agent check --m-trace <INTEGRATION_NOT_WORKING>` so it's uploaded and it becomes easier to debug
<img width="997" alt="Capture d’écran 2022-03-31 à 17 20 24" src="https://user-images.githubusercontent.com/26168335/161151226-8eaf10b1-65c3-4bb7-a516-4b2f7b967869.png">

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-03-31 21:38 UTC, ofek requested changes
🔥

2022-03-31 21:38 UTC, ofek commented on cmd/agent/common/commands/check.go
> +				os.Setenv("DDEV_TRACE_ENABLED", "true")
Rather than env vars, is it possible to modify check config directly like we do for memory profiling?

2022-04-01 13:32 UTC, hush-hush approved these changes

2022-04-01 21:09 UTC, ofek approved these changes

2022-04-01 21:15 UTC, merged