Arbll/dogstatsd forward packets
DataDog/datadog-agent pull request #1163
Opened 2018-02-01 13:34 UTC by arbll

### What does this PR do?

Adds optional forwarding of dogstatsd packets to another UDP server

### Motivation

Agent5 functionality used by some customers.

2018-02-01 14:43 UTC, masci requested changes
Good stuff! Left a couple of comments but this LGTM.

2018-02-01 14:43 UTC, masci commented on pkg/config/config.go
> +	Datadog.SetDefault("statsd_forward_port", "")
can we use an `int`, same as `dogstatsd_port`?

2018-02-01 14:43 UTC, masci commented on pkg/dogstatsd/server.go
> +			s.packetIn = forwardedPacketChanel
can we assign `s.packetIn = make(chan *listeners.Packet, 100)` directly?

2018-02-02 07:40 UTC, masci approved these changes

2018-02-02 09:39 UTC, merged

2018-02-02 14:52 UTC, olivielpeau commented
@arbll could you document the new options in the `config_template` ? unless we don't want to advertise the feature