Fix dropped ContainerID field in split trace stats payloads
DataDog/datadog-agent pull request #12184
Opened 2022-05-27 19:01 UTC by markadev

### What does this PR do?

When an APM stats payload is split the ContainerID field was not being
copied to the new payloads, resulting in it being lost. This could cause
a missing second primary tag on trace metrics from Fargate tasks or some
other containerized deployment environments.

### Motivation

Bug fix

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-05-27 19:22 UTC, ajgajg1134 approved these changes
looks good!

2022-05-27 21:56 UTC, kayayarai approved these changes

2022-05-30 09:52 UTC, gbbr requested changes, later dismissed

2022-05-30 09:52 UTC, gbbr commented on releasenotes/notes/fix-containerid-when-payload-split-9d886c013c07d58b.yaml
> +    Fix the loss of trace metric container information when large payloads need to be split.
```suggestion
    APM: Fix the loss of trace metric container information when large payloads need to be split.
```

2022-05-31 13:25 UTC, gbbr approved these changes

2022-05-31 13:26 UTC, gbbr commented on pkg/trace/writer/stats_test.go
> +				ContainerID:      "container-id",
If time allows, or perhaps in a follow-up PR, it may make sense to have a regression test. Or does this change cover it?

2022-05-31 14:58 UTC, merged