[prometheus] Skip checks metrics parsing to avoid breaking multiple possible formats
DataDog/datadog-agent pull request #12318
Opened 2022-06-07 20:16 UTC by sschepens

### What does this PR do?

Makes Prometheus Instance Metrics an array of `json.RawMessage` so we avoid parsing them and breaking the format.

### Motivation

Fixes https://github.com/DataDog/datadog-agent/issues/12317

### Additional Notes

### Possible Drawbacks / Trade-offs

If tests pass, there should be no drawback to this change.

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-06-08 18:37 UTC, djmitche approved these changes

2022-06-09 07:30 UTC, ahmed-mez reviewed
Hi @sschepens 

Thank you for the contribution! Could you just add a release note - the process is documented here https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno

2022-06-09 13:30 UTC, sschepens commented
@ahmed-mez added release notes

2022-06-09 13:31 UTC, ahmed-mez approved these changes
Thank you!

2022-06-09 14:09 UTC, jtappa requested changes

2022-06-09 14:09 UTC, jtappa commented on releasenotes/notes/fix-prometheus-checks-metrics-07509580eb216c76.yaml
> +    Fix prometheus check Metrics parsing, don't enforce a list of strings
```suggestion
    Fix prometheus check Metrics parsing by not enforcing a list of strings.
```

2022-06-09 14:11 UTC, sschepens commented
@jtappa accepted suggestion

2022-06-09 14:46 UTC, jtappa approved these changes

2022-06-09 14:49 UTC, merged

2022-06-09 16:51 UTC, sschepens commented
@ahmed-mez is it possible to include this fix in a patch? or do I have to wait for a full release?

2022-06-10 07:19 UTC, ahmed-mez commented
@sschepens this fix will be available in agent v7.38 (to be released in ~2 months)