[KSM Core] Add ingress metrics
DataDog/datadog-agent pull request #12344
Opened 2022-06-09 09:45 UTC by ahmed-mez

### What does this PR do?

Collect `kubernetes_state.ingress.count` and `kubernetes_state.ingress.path`.

### Motivation

FR

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Enable the ingress collector if it's not enabled, make sure the metrics are collected and the tags are remapped as expected

![image](https://user-images.githubusercontent.com/38987709/172817453-7649a77f-3b40-409a-a454-775b74a12868.png)

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-06-09 09:47 UTC, ahmed-mez commented on pkg/collector/corechecks/cluster/ksm/kubernetes_state.go
> -var podLabelsMapperOverride = map[string]string{"phase": "pod_phase"}
This is a bit out of scope but multiple check instances can run concurrently by the same agent - global variables shouldn't be used. see https://github.com/DataDog/datadog-agent/pull/11652

2022-06-09 10:05 UTC, clamoriniere commented on pkg/collector/corechecks/cluster/ksm/kubernetes_state.go
> +			"service_name": "ingress_service_name",
since we use already internal `kube_service` tag, it can be good to use the same tag. to ease dashboard creation and metrics filtering

2022-06-09 10:18 UTC, clamoriniere commented on pkg/collector/corechecks/cluster/ksm/kubernetes_state.go
> +			"host":         "ingress_host",
I was thinking that maybe we can have `kube_` prefix too. like for other `kubernetes_state` tags

2022-06-09 13:24 UTC, AntoineEsteve commented on pkg/collector/corechecks/cluster/ksm/kubernetes_state.md
> +: Number of ingresses. Tags:`kube_namespace`.
It's not mentioned but I guess those metrics have the `kube_cluster_name` tag (like the other metrics defined in this file), right?

2022-06-09 14:07 UTC, jtappa requested changes

2022-06-09 14:42 UTC, jtappa approved these changes

2022-06-10 08:54 UTC, clamoriniere approved these changes

2022-06-10 08:56 UTC, merged