Use go.uber.org/atomic in cmd/system-probe
DataDog/datadog-agent pull request #12423
Opened 2022-06-16 14:38 UTC by djmitche

### What does this PR do?

Uses go.uber.com/atomic to ensure alignment of atomic access in cmd/system-probe.

### Motivation

Alignment issues with atomic access.  See #11716.  The uses of atomic were very simple in these modules, and did not have bugs -- but the intent is to eliminate use of `sync/atomic` so that the module's bugs don't tempt us.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Any basic system-probe QA should detect issues here.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-06-17 12:32 UTC, brycekahle commented on cmd/system-probe/modules/oom_kill_probe.go
> +	lastCheck: atomic.NewInt64(0),
This variable is unused, and is only for type checks. I think you want this initialization on line 35 instead.

2022-06-17 12:33 UTC, brycekahle commented on cmd/system-probe/modules/process.go
> +	lastCheck: atomic.NewInt64(0),
Move to line 40

2022-06-17 12:33 UTC, brycekahle commented on cmd/system-probe/modules/tcp_queue_tracer.go
> +	lastCheck: atomic.NewInt64(0),
Move to line 34

2022-06-17 13:00 UTC, brycekahle requested changes
Minor changes needed to TCPQ Length, Process, and OOM Kill checks

2022-06-17 14:12 UTC, djmitche commented
face -> palm

That will teach me to make PRs during meetings

(..honestly, it probably won't)

2022-06-17 14:15 UTC, brycekahle approved these changes

2022-06-17 14:33 UTC, djmitche commented
(unit test failures fixed in https://github.com/DataDog/datadog-agent/pull/12438)

2022-06-20 17:46 UTC, djmitche commented
(rebased for lint fixes)

2022-06-23 14:32 UTC, sgnn7 commented
Merging since @djmitche will be returning after the freeze

2022-06-23 14:33 UTC, merged