Add windows systray process
DataDog/datadog-agent pull request #1251
Opened 2018-02-13 19:08 UTC by derekwbrown

### What does this PR do?

Adds windows system tray.  Current functionality allows
- start service
- stop service
- restart service
- launch of gui
- create flare
- exit (of tray) 

### Motivation

feature parity with agent5

### Additional Notes

Anything else we should know when reviewing?

2018-02-15 01:20 UTC, ofek requested changes
LGTM, just a few things.

2018-02-16 01:28 UTC, derekwbrown commented on cmd/systray/systray.go
> +	menuitems = append(menuitems, menuItem{label: "E&xit", handler: onExit, enabled: true})
No.  The & indicates which character has the accelerator.  So, for instance, "Exit" is always E&xit because "x" is the accellerator.

2018-02-16 01:30 UTC, derekwbrown commented on tasks/systray.py
> +AGENT_TAG = "datadog/agent:master"
This is copy/paste from tasks/agent.py.  Unsure what the correct value should be.

2018-02-16 02:04 UTC, ofek commented on cmd/systray/systray.go
> +	menuitems = append(menuitems, menuItem{label: "E&xit", handler: onExit, enabled: true})
Thanks for explaining!

2018-02-16 02:13 UTC, ofek commented on tasks/systray.py
> +AGENT_TAG = "datadog/agent:master"
Yes we should change this, pending https://github.com/DataDog/datadog-agent/pull/1270

2018-02-16 02:14 UTC, ofek submitted a review, later dismissed

2018-02-16 15:44 UTC, ofek commented on tasks/systray.py
> +AGENT_TAG = "datadog/agent:master"
All good!

2018-02-16 17:15 UTC, olivielpeau requested changes
(pushed a small change to hopefully fix the windows build)

Also, added a comment on what's breaking the linux build on gitlab, let me know what you think @derekwbrown!

2018-02-16 17:15 UTC, olivielpeau commented on omnibus/config/software/datadog-agent.rb
> +  command "invoke systray.build --rebuild --use-embedded-libs --no-development", env: env
this breaks the linux build (see gitlab pipeline: https://gitlab.ddbuild.io/datadog/datadog-agent/pipelines/214967) and probably the mac build too. I think we should only run this build command on windows

2018-02-16 17:21 UTC, masci submitted a review, later dismissed
Left few comments about the invoke task

2018-02-16 17:21 UTC, masci commented on tasks/systray.py
> +    if invoke.platform.WINDOWS:
I'd put
```
if not invoke.platform.WINDOWS:
  print "systray only build on Windows"
  return
```

2018-02-16 17:21 UTC, masci commented on tasks/systray.py
> +        inv agent.build --build-exclude=snmp
`systray.build`

2018-02-16 17:21 UTC, masci commented on tasks/systray.py
> +def system_tests(ctx):
you can remove this task I guess?

2018-02-16 17:21 UTC, masci commented on tasks/systray.py
> +    ctx.run("rm -rf ./bin/agent")
this should be fixed

2018-02-21 11:24 UTC, truthbk approved these changes
I tested this on windows and it works as designed (I believe) - it was a bit misleading to me that when we click on the "datadog agent manager" then that's when the icon shows up. I had been expecting the systray icon to come up automatically.

Unexpected behavior for me as a user:
- Agent GUI doesn't show up after clicking on the icon - you need to go to the systray and launch from there.

Unwanted behavior:
- systray icon will appear multiple times if "datadog agent manager" clicked on.

2018-02-21 11:28 UTC, olivielpeau approved these changes

2018-02-21 11:37 UTC, merged