[install_script] add support for fips mode
DataDog/datadog-agent pull request #12603
Opened 2022-07-01 11:33 UTC by vickenty

### What does this PR do?

Add support for FIPS mode to the install script.

In FIPS mode, install additional proxy package and configure agent to
talk to it instead of the DD app directly.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-07-19 17:34 UTC, sgnn7 approved these changes

2022-08-02 08:06 UTC, bkabrda requested changes
Thanks for sending this PR. It looks good, but I left a minor comment to address inline. You will also need to provide a changelog entry for installscript.

2022-08-02 08:06 UTC, bkabrda commented on cmd/agent/install_script.sh
> +  else
Let's print a message here about configuring the agent for the FIPS proxy, something like the messages in the `if` clause of this condition.

2022-08-02 13:24 UTC, bkabrda approved these changes

2022-08-02 17:02 UTC, kayayarai approved these changes
Minor wording suggestion for the release notes, but 👍

2022-08-02 17:02 UTC, kayayarai commented on releasenotes-installscript/notes/fips-be6e112db1a0b58d.yaml
> +    proxy.
```suggestion
    When the `DD_FIPS_MODE` environment variable is set, the install script
    installs an additional FIPS proxy package and configures Agent to direct 
    all traffic to the backend through the FIPS proxy.
```

2022-08-03 11:08 UTC, merged