duplicate panic
DataDog/datadog-agent pull request #12633
Opened 2022-07-05 15:24 UTC by nammn

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-07-20 14:30 UTC, xlucas commented on pkg/collector/corechecks/cluster/orchestrator/collector_bundle.go
> +	informerSynced := map[cache.SharedInformer]struct{}{}
I think it's good enough like this, maybe you could make the map value a bool instead of struct to match kube internals but no big deal

2022-07-20 14:39 UTC, xlucas approved these changes

2022-07-20 15:56 UTC, xlucas requested changes
Sorry I approved a bit quickly and didn't think about the new `HasStarted` in client-go when we call `informer.Run`. I think this new behaviour means you can't ever `Run` an informer ever again, so if the check is cancelled and rescheduled on a node where it ran before, we'd still have an issue.

2022-07-20 17:33 UTC, buraizu reviewed
Minor edit for consistency

2022-07-20 17:33 UTC, buraizu commented on releasenotes/notes/fix-cancel-panic-1311d497ce5dd63d.yaml
> +    [orchestrator check] Fixes informer resource release if the check gets unscheduled
```suggestion
    [orchestrator check] Fixes informer resource release if the check gets unscheduled.
```

2022-07-21 14:15 UTC, nammn commented
Closing this one in favour of: https://github.com/DataDog/datadog-agent/pull/12828 

I might re-open once we have a proper way to handle stale informers (fixing the resource leak bug actually surfaces another bug)

2022-07-21 14:15 UTC, closed without merging