[system-probe] Do not use `tcp_cleanup_rbuf` for tcp receive tracking
DataDog/datadog-agent pull request #12660
Opened 2022-07-07 20:46 UTC by hmahmood

### What does this PR do?

Use kprobes on `tcp_recvmsg` and `tcp_read_sock` instead of `tcp_cleanup_rbuf` for tcp receive tracking. `tcp_cleanup_rbuf` is also called for retransmits, which would overcount tcp receives.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-07-07 21:01 UTC, brycekahle commented on pkg/network/ebpf/c/tcp-recv.h
> +    if (recv < 0) {
Can we do this first? It could save a lot of work.

2022-07-08 08:21 UTC, nplanel requested changes
We probably need a tcp splice() unit test to be safe in our CI, but we can address that in another PR

2022-07-08 08:21 UTC, nplanel commented on pkg/network/ebpf/c/tcp-recv.h
> +    bpf_map_delete_elem(&tcp_recvmsg_args, &pid_tgid);
I would copy the pointer on the stack (line 72) before deleting the map entry

2022-07-08 08:21 UTC, nplanel commented on pkg/network/ebpf/c/tcp-recv.h
> +    bpf_map_delete_elem(&tcp_recvmsg_args, &pid_tgid);
I would copy the pointer on the stack (line 41) before deleting the map entry

2022-07-11 10:00 UTC, nplanel commented on pkg/network/ebpf/c/tcp-recv.h
> +    bpf_map_delete_elem(&tcp_recvmsg_args, &pid_tgid);
Even if it's working, (and would probably possibly failed on high load/high nb cpus TBC), the semantic is wrong, would you use a pointer after free() ? Would you guarantee that the kernel will not pollute the value at the end of delete call ? Still surprise the verifier don't check that. PR with the remaining fixes https://github.com/DataDog/datadog-agent/pull/12687

2022-07-11 12:52 UTC, nplanel approved these changes

2022-07-11 18:33 UTC, merged