[docker] disable APM by default, document changes
DataDog/datadog-agent pull request #1268
Opened 2018-02-15 16:42 UTC by xvello

### What does this PR do?

- set `DD_APM_ENABLED` to false by default on the docker image (breaking change)
- hardcode `DD_LOGS_ENABLED=false` and `DD_DOGSTATSD_NON_LOCAL_TRAFFIC=false` in the docker image to be future-proof
- update the documentation

### Motivation

Be consistent with dsd not listening to the network by default (but running for jmxfetch and other agents)

### Additional Notes

This requires RC2 to be built with https://github.com/DataDog/datadog-trace-agent/releases/tag/6.0.0-rc.2

2018-02-15 16:46 UTC, LotharSee commented on docs/agent/changes.md
> +In the Docker image, the APM agent is enabled by default. You can enable it by setting
Typo.

> In the Docker image, the APM agent is disabled by default.

2018-02-15 17:16 UTC, LotharSee submitted a review, later dismissed

2018-02-16 14:08 UTC, masci requested changes
left a couple of nits

2018-02-16 14:08 UTC, masci commented on Dockerfiles/agent/README.md
> +These features are disabled by default, you can choose to enable them:
can we add "for security reasons" or something like that?

2018-02-16 14:08 UTC, masci commented on releasenotes/notes/disable-apm-default-f32eaa7cb3d7f157.yaml
> +    Normal installations: APM now listens to localhost only be default, you need to set
typo: s/be/by

2018-02-16 14:15 UTC, masci submitted a review, later dismissed

2018-02-16 15:26 UTC, merged