Fix a bug in AD simple ConfigManager that would not pass the same config to scheduler between Schedule and Unschedule calls
DataDog/datadog-agent pull request #12781
Opened 2022-07-18 13:48 UTC by vboulineau

### What does this PR do?

Fix a bug in AD ConfigManager that would pass the same config to scheduler between Schedule and Unschedule calls.

### Motivation

Bugfix found on running database cluster checks.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Two possible setups, first on standalone infra:
- Deploy the Agent, Cluster Agent and Cluster Checks Runner on Kubernetes. (easier with a single Cluster Checks Runner)
All the components should be setup with a secret backend (could be [Kubernetes secrets](https://github.com/DataDog/datadog-agent/tree/main/Dockerfiles/agent/secrets-helper#kubernetes-secrets)).
The Cluster Agent must be deployed with `secret_backend_skip_checks` set to `true`.

- Define a Cluster Check with at least one field being a secret (e.g. `ENC[]`). Also define a random tag to easily identify the check config version, like `debug:1`.
- Observe the Cluster Check being scheduled properly with `debug:1`.
- Change the Cluster Check configuration tag to `debug:2`.
- Observe that the old check is unscheduled (not showing up in `agent status` of the Cluster Checks Runner).
- Observe that the new check is scheduled.
- Verify in Datadog that metrics are now produced with `debug:2` and not `debug:1` anymore.

Second option is to use existing internal setup on staging, ping me for details.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-07-18 13:58 UTC, djmitche requested changes
Looks good!

I suspect we'll need a similar change for configmanager.go (or, at least a test demonstrating this issue does not affect it)

2022-07-18 14:22 UTC, vboulineau commented
> Looks good!
> 
> I suspect we'll need a similar change for configmanager.go (or, at least a test demonstrating this issue does not affect it)

I checked it and sounded ok, but in fact it was not. The unit test was fine as well because the `decrypt` was NOT called at all (scheduling or unscheduling). Improved the unit test to validate content as well.

2022-07-18 16:52 UTC, hestonhoffman approved these changes

2022-08-01 09:17 UTC, ahmed-mez approved these changes

2022-08-01 09:17 UTC, ahmed-mez commented on pkg/autodiscovery/configmgr_test.go
> +  "github.com/mohae/deepcopy"
```suggestion
    "github.com/mohae/deepcopy"
```

2022-08-01 12:54 UTC, djmitche approved these changes

2022-08-03 10:01 UTC, merged