[Security] allow auth token file path to be set in the config
DataDog/datadog-agent pull request #1289
Opened 2018-02-19 05:36 UTC by gmmeyer

### What does this PR do?

The auth token location should be able to be changed via a config setting. This will enable us to do that easily.

### Motivation

On Cloud Foundry, the config folder is destroyed and recreated every time it's deployed. So, the next run doesn't have access to the auth token and it cannot stop the agent easily. (It's much messier, at least.)

2018-02-19 06:49 UTC, ofek requested changes

2018-02-19 06:49 UTC, ofek commented on pkg/api/security/security.go
> +		authTokenFile = config.Datadog.GetString("auth_token_file")
`auth_token_file_path`

2018-02-19 16:15 UTC, gmmeyer commented on pkg/api/security/security.go
> +		authTokenFile = config.Datadog.GetString("auth_token_file")
thanks! I resolved this!

2018-02-19 16:18 UTC, ofek submitted a review, later dismissed

2018-02-20 16:19 UTC, arbll approved these changes

2018-02-20 18:47 UTC, merged