[epforwarder] Make input chan size configurable
DataDog/datadog-agent pull request #12933
Opened 2022-08-01 08:29 UTC by AlexandreYang

### What does this PR do?

[epforwarder] Make input chan size configurable

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-08-01 14:58 UTC, djmitche approved these changes

2022-08-01 15:08 UTC, vickenty requested changes
Please add QA instructions as well.

2022-08-01 15:08 UTC, vickenty commented on pkg/config/config.go
> +	config.BindEnvAndSetDefault(prefix+"input_chan_size", DefaultInputChanSize) // Used by EP Forwarder
This isn't sufficient: the new setting needs to be read and passed to the Endpoints explicitly, similar to various batch settings: https://github.com/DataDog/datadog-agent/blob/5a0c401120878fbbaa1597e8d3d734008d3a9f63/pkg/logs/config/config.go#L285-L290

Please also add tests.

2022-08-01 15:08 UTC, vickenty commented on pkg/logs/config/endpoints.go
> +	InputChanSize          int
The new field probably needs to be set in `NewEndpoints` and other constructors.

2022-08-02 15:25 UTC, vickenty approved these changes

2022-08-02 15:55 UTC, merged