[snmp] adding check
DataDog/datadog-agent pull request #132
Opened 2017-01-26 20:20 UTC by truthbk

### What does this PR do?

Adds the SNMP check to agent6. Note that it depends on the net-snmp libraries being available on the host.

### Motivation

We're going to need this check in agent 6. It was about time!

### Testing Guidelines

Added pertinent tests. We do not actually test all functionality, the snmpGet function is a little hard to test given its IO nature. We have "skipped" it in the tests and provide fake varbind results in its place. Also pending are "table" varbind results, these are a little harder to mock so I've left them for a future implementation.

Added `snmp` dependencies to CircleCI.

### Additional Notes

We should discuss InitConfig, I am currently ignoring it and just going with the defaults. The reason being that the snmp library can only really be initialized once, so we have to gauge if we should be enforcing this kind of thing in the core, or in the check, there should be no issues with the second approach.

An elegant failure mechanism should be put in place if the snmp libraries are not available.

2017-01-27 11:21 UTC, masci requested changes
I didn't go deeply the SNMP implementation b/c I don't have the expertise, feel free to ping someone for further review!

2017-02-01 16:22 UTC, masci approved these changes

2017-02-07 01:57 UTC, olivielpeau reviewed
Only had a very quick look at the logic but overall this looks good. I made a few comments here and there (many of them are open questions)

2017-02-27 19:48 UTC, olivielpeau approved these changes
LGTM!

Feel free to merge once these are 👍 :

* There are some merge conflicts :(
* The omnibus build is failing on a health check for the netsnmp lib, could you have a look? https://gitlab.datad0g.com/datadog/datadog-agent/pipelines/44368
* Let's not forget to switch the default `omnibus-software` branch back to `master`

2017-03-17 02:21 UTC, merged