[DCA][Admission] Inject variables and volume mounts to init containers
DataDog/datadog-agent pull request #13324
Opened 2022-09-01 13:39 UTC by L3n41c

### What does this PR do?

Enhance the cluster-agent admission controller to inject variables and volume mounts to the init containers in addition to the regular ones.

### Motivation

The init containers might also benefit from the injected variables and auto-instrumentation.

### Additional Notes

[Datadog admission controller documentation](https://docs.datadoghq.com/containers/cluster_agent/admission_controller/)

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Enable the cluster agent admission controller and start a pod annotated with `admission.datadoghq.com/enabled=true`.
Check that the injected variables and instrumentation appears not only on regular containers, but also on the init containers.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-09-01 17:54 UTC, jtappa requested changes

2022-09-01 17:54 UTC, jtappa commented on releasenotes-dca/notes/admission-init-containers-9ab4783dbd736e5f.yaml
> +    The admission controller now injects variables and volume mounts to init containers in addition to regular one.
```suggestion
    The admission controller now injects variables and volume mounts to init containers in addition to regular containers.
```

2022-09-01 21:04 UTC, jtappa approved these changes

2022-09-07 08:09 UTC, ahmed-mez approved these changes
We can add test case in the e2e tests :)

2022-09-07 11:56 UTC, merged