add support for %%env_%% AD template tag
DataDog/datadog-agent pull request #1339
Opened 2018-02-23 10:19 UTC by xvello

### What does this PR do?

As discussed in https://github.com/DataDog/datadog-agent/issues/1250, add a new tag in AD templates, to inject environment variables during template resolution.

This allows to inject kubernetes downwards API information, or credentials, in templates.

For example, if I want to monitor a pod running on host networking, and already injected my node's IP in the `$KUBERNETES_KUBELET_HOST` envvar, I can use the following template:

```yaml
ad_identifiers:
  - redis

init_config:

instances:
  - host: "%%env_KUBERNETES_KUBELET_HOST%%"
    port: "1234"
```

2018-02-23 10:31 UTC, mfpierre commented on pkg/collector/autodiscovery/common_test.go
> +type dummyService struct {
nice addition for testing 👍

2018-02-23 10:37 UTC, mfpierre requested changes
Nice stuff 👏 

I think we're just missing a reno note and a readme update here https://github.com/DataDog/datadog-agent/blob/master/pkg/collector/listeners/README.md

2018-02-28 09:32 UTC, mfpierre approved these changes
🍰

2018-02-28 09:38 UTC, merged

2018-03-02 10:45 UTC, xvello commented
@l0k0ms any idea where to best document this new feature?

2018-03-02 12:09 UTC, l0k0ms commented
@xvello either here: https://github.com/DataDog/documentation/blob/master/content/agent/autodiscovery.md#setting-up-check-templates

or https://github.com/DataDog/documentation/blob/master/content/agent/autodiscovery.md#example-apache-check

or maybe in all AD templates?

2018-03-02 12:21 UTC, xvello commented
Yup, so we don't currently have a table of supported template vars.
Do you think I could add a section to
https://github.com/DataDog/documentation/blob/master/content/agent/autodiscovery.md#reference
?

On Fri, Mar 2, 2018 at 1:10 PM, Gus <notifications@github.com> wrote:

> @xvello <https://github.com/xvello> either here:
> https://github.com/DataDog/documentation/blob/master/
> content/agent/autodiscovery.md#setting-up-check-templates
>
> or https://github.com/DataDog/documentation/blob/master/
> content/agent/autodiscovery.md#example-apache-check
>
> or maybe in all AD templates?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DataDog/datadog-agent/pull/1339#issuecomment-369904885>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF87O1OYTQ10iBsHNPRlZi7UWkWWprR2ks5taTaagaJpZM4SQqp6>
> .
>

2018-03-02 12:28 UTC, l0k0ms commented
yup it's a really good idea! I'm here if you need help for it

2018-03-05 17:28 UTC, pussinboots commented
Thanks for that feature. That make it possible to get ride of some awful bash script replace code. 
👍