Hide FinalizeInstall property
DataDog/datadog-agent pull request #13442
Opened 2022-09-09 15:44 UTC by julien-lebot

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-09-09 16:53 UTC, iglendd approved these changes

2022-09-09 18:12 UTC, clarkb7 approved these changes

2022-09-09 18:33 UTC, clarkb7 requested changes
see dm

2022-09-12 14:44 UTC, clarkb7 commented on omnibus/resources/agent/msi/source.wxs.erb
> -    <CustomAction Id='SetUninstallProperty' Return='check' Property='DoUninstall'
need to remove [declaration](https://github.com/DataDog/datadog-agent/pull/13442/files#diff-d6158508805a99eaed5c28596a83246becbca20978d481d7d87d14cc754e128aR477) too

2022-09-12 15:17 UTC, iglendd approved these changes

2022-09-12 15:34 UTC, clarkb7 approved these changes
LGTM

2022-09-12 15:44 UTC, merged