Upgrade to go1.18.6 (7.39.x)
DataDog/datadog-agent pull request #13493
Opened 2022-09-14 16:30 UTC by djmitche

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-09-14 16:33 UTC, sgnn7 requested changes
@djmitche Couple of nits and a comment

2022-09-14 16:33 UTC, sgnn7 commented on .github/workflows/go_mod_tidy.yml
> +        go-version: '1.18.6
```suggestion
        go-version: '1.18.6'
```

2022-09-14 16:33 UTC, sgnn7 commented on .github/workflows/windows-unittests.yml
> +          go-version: '1.18.6
```suggestion
          go-version: '1.18.6'
```

2022-09-14 16:33 UTC, sgnn7 commented on releasenotes/notes/go118-b3ac691999dd0015.yaml
> +    The Agent is built with go1.18.6.
Should we include the extra comment here from the other PR around the mem tweaking here as well?

2022-09-14 18:45 UTC, sgnn7 approved these changes

2022-09-14 20:10 UTC, kayayarai approved these changes

2022-09-14 20:22 UTC, paulcacheux approved these changes

2022-09-15 08:56 UTC, mx-psi reviewed
For the `dependencies` CircleCI failing job I would suggest doing the same as in the builders repo: modifying the `requirements.txt` file https://github.com/DataDog/datadog-agent/blob/a4f7ee649e2d6c1830d67e56f286310d5f561fc9/requirements.txt#L2 so that it points to `7.39.x` instead of `main`, to ensure that the requirements used are the same as in the 7.39.0 build.

2022-09-16 19:27 UTC, closed without merging