Attach kprobes using kprobe_events ABI
DataDog/datadog-agent pull request #13641
Opened 2022-09-23 15:34 UTC by usamasaqib

### What does this PR do?
This PR changes how the kprobes for network tracer are attached, to use debugfs.

### Motivation
We can now get telemetry about kprobe hits and misses.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-09-27 20:48 UTC, brycekahle commented
Is this something we might want to control via config? We don't currently report this telemetry on customer machines, so it would be better to use the perf ABI in that case.

2022-09-28 17:08 UTC, brycekahle requested changes

2022-09-28 17:08 UTC, brycekahle commented on pkg/ebpf/config.go
> +		AttachKprobesWithKprobeEventsABI: cfg.GetBool(key(spNS, "attach_kprobes_with_kprobe_events_abi")),
You need to define `key(spNS, "attach_kprobes_with_kprobe_events_abi")` in `pkg/config/system_probe.py`

2022-09-30 15:42 UTC, hmahmood approved these changes

2022-09-30 19:53 UTC, brycekahle requested changes

2022-09-30 19:53 UTC, brycekahle commented on pkg/network/tracer/tracer_test.go
> +func TestKprobeAttachWithKprobeEvents(t *testing.T) {
I think this needs to be in `tracer_linux_test.go`

2022-10-03 19:51 UTC, brycekahle approved these changes
This looks good. We should explore adding a manager-level option as a default, to simplify things.

2022-10-04 15:47 UTC, brycekahle approved these changes

2022-10-06 08:27 UTC, usamasaqib commented
> This looks good. We should explore adding a manager-level option as a default, to simplify things.

The manager would default to using the perf ABI incase nothing is specified.

2022-10-06 08:32 UTC, guyarb requested changes

2022-10-06 08:51 UTC, guyarb approved these changes
LGTM

2022-10-06 16:16 UTC, hmahmood approved these changes

2022-10-06 16:32 UTC, merged