[Forwarder] Add first and simple version of the forwarder.
DataDog/datadog-agent pull request #137
Opened 2017-01-31 10:59 UTC by hush-hush

### What does this PR do?

Add a new Forwarder process transaction to different endpoint/domains with a retry policy for failed ones.

2017-02-01 16:20 UTC, masci requested changes
Sorry for the wall of comments, most are to address naming things though, the overall design is 👍

2017-02-01 20:06 UTC, olivielpeau requested changes
Agree with Massi on all his comments + added a few of my own. Overall this looks great! 👏

2017-02-02 15:39 UTC, olivielpeau approved these changes
one small thing, otherwise LGTM 👍

2017-02-02 18:00 UTC, masci requested changes

2017-02-03 10:25 UTC, masci approved these changes

2017-02-03 10:26 UTC, merged