Remove support for Android (comp/core changes)
DataDog/datadog-agent pull request #13717
Opened 2022-10-03 15:01 UTC by djmitche

### What does this PR do?

This is a followup to #13699 that removes support for Android in the code in #13662, which is still pending review.

### Motivation

### Additional Notes

I'll rebase this PR against main once #13662 lands.

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Same as #13622.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-06 13:00 UTC, ogaca-dd requested changes

2022-10-06 13:00 UTC, ogaca-dd commented on comp/core/internal/params.go
> +func (params BundleParams) LogToFile(logFile string) BundleParams {
This function seems only to be used in unit test. Is it expected?

2022-10-06 15:00 UTC, djmitche commented
(holding off on merging this until we hear confirmation from @derekwbrown that this is unused)

2022-10-10 20:31 UTC, truthbk approved these changes

2022-10-11 08:04 UTC, ogaca-dd approved these changes

2022-10-11 23:39 UTC, djmitche commented
Failures look like the usual system-probe errors.

2022-10-11 23:39 UTC, merged

2022-10-11 23:53 UTC, djmitche commented
It seems that `core.BundleParams#LogToFile` was removed from #13662 and ended up being re-added by this PR.  I suspect that was due to some merge conflicts at some point.

It should be there (it's used in #13722), but should have been introduced in #13662 and not this PR.  So, it's fine.