New Windows installer add unit tests
DataDog/datadog-agent pull request #13800
Opened 2022-10-07 18:13 UTC by julien-lebot

### What does this PR do?
This PR adds unit tests for the next-gen Windows installer. It uses [xUnit](https://xunit.net/) with [Moq](https://github.com/moq/moq4) for the mocking framework, and [AutoFixtures](https://github.com/AutoFixture/AutoFixture) for generating sample data.

### Motivation
Better test coverage.

### Additional Notes
This PR also introduces an interface `ISession` that proxies the real [`Session` object](https://learn.microsoft.com/en-us/windows/win32/msi/session-object) for unit testing purposes.

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-07 20:48 UTC, clarkb7 requested changes

2022-10-07 20:48 UTC, clarkb7 commented on tools/windows/DatadogAgentInstaller/CustomActions/ConfigCustomActions.cs
> +            var configFolder = session.Property("APPLICATIONDATADIRECTORY");
`configFolder` var unused in following streams

2022-10-07 20:48 UTC, clarkb7 commented on tools/windows/DatadogAgentInstaller/WixSetup/Datadog/AgentCustomActions.cs
>              // We need to explicitly set the ID since that we are going to reference before the Build* call.
Github wouldn't let me add comment below.
Should we add `HideTarget()` to the `WriteConfig` CA because it has `APIKEY` and `PROXY_PASSWORD`?

2022-10-07 20:48 UTC, clarkb7 commented on tools/windows/DatadogAgentInstaller/WixSetup/Datadog/AgentInstaller.cs
> +                    Domain = "[DDAGENTUSER_DOMAIN]",
question: Does the user have to specify `DDAGENTUSER_DOMAIN` on the command line now?

2022-10-07 20:48 UTC, clarkb7 commented on tools/windows/DatadogAgentInstaller/WixSetup/Datadog/AgentInstaller.cs
> +                    new DirPermission("[WIX_ACCOUNT_USERS]", GenericPermission.All),
Users shouldn't have access to ProgramData\Datadog

2022-10-07 20:48 UTC, clarkb7 commented on tools/windows/DatadogAgentInstaller/WixSetup/Datadog/AgentInstaller.cs
> +                new Dir(new Id("APPLICATIONDATADIRECTORY"), @"%CommonAppData%\Datadog",
I can't find MSDN docs on `%CommonAppData%`. Some forums make it seem like a legacy var from when the program data path was `C:\Documents and Settings\All Users\Application Data\`.
I don't have the env var on my host, we use `%ProgramData%` instead.

2022-10-12 14:57 UTC, clarkb7 approved these changes

2022-10-13 18:59 UTC, iglendd approved these changes
Supercool tests!

2022-10-20 08:46 UTC, merged