use builtins adapted from cilium
DataDog/datadog-agent pull request #13871
Opened 2022-10-13 16:04 UTC by usamasaqib

### What does this PR do?
This PR adds builtins which take advantage of the fact that ebpf stack memory is guaranteed to be aligned to generate efficient bytecode.

### Motivation
TODO: 
1. Instruction count change
2. Data on the average reduction in the number of ops executed.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-13 19:55 UTC, brycekahle commented
Two things:
1. If we are still working on the results/justification for this change, let's move it back to Draft status.
2. If we pulled code from cilium, let's ensure we retain their copyright/license comments.

2022-10-14 14:30 UTC, hmahmood approved these changes

2022-10-14 21:43 UTC, brycekahle requested changes
We should try to follow "include what you use". It makes it simpler to reason about the requirements of specific files, and you don't get surprise compiler errors.

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/runtime/conn-tuple.h
> +    bpf_memset(t, 0, sizeof(conn_tuple_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/runtime/conntrack.c
> +#include "bpf_builtins.h"
Excess include?

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/prebuilt/sock.h
> +    bpf_memset(t, 0, sizeof(conn_tuple_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/prebuilt/offset-guess.c
> +#include "bpf_builtins.h"
Excess include?

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/ip.h
> +    bpf_memset(info, 0, sizeof(skb_info_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/https.h
> +    bpf_memset(&http, 0, sizeof(http));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/http.h
> +    bpf_memcpy(&batch->txs[batch->pos], http, sizeof(http_transaction_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/conntrack.h
> +    bpf_memset(t, 0, sizeof(conntrack_tuple_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/http-buffer.h
> +    bpf_memset(buffer, 0, HTTP_BUFFER_SIZE);
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/runtime/skb.h
> +    bpf_memset(&iph, 0, sizeof(struct iphdr));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/sockfd.h
> +    bpf_memcpy(&pid_fd_copy, pid_fd, sizeof(pid_fd_t));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/tracer-events.h
> +        bpf_memcpy(&batch_copy, batch_ptr, sizeof(batch_copy));
This file should include `bpf_builtins.h`

2022-10-14 21:43 UTC, brycekahle commented on pkg/network/ebpf/c/tracer-stats.h
> +    bpf_memset(&empty, 0, sizeof(conn_stats_ts_t));
This file should include `bpf_builtins.h`

2022-10-16 03:00 UTC, guyarb requested changes
Agreed with @brycekahle comments

2022-10-17 21:02 UTC, brycekahle approved these changes

2022-10-20 11:07 UTC, guyarb approved these changes
LGTM

2022-10-20 13:11 UTC, merged