Make windows service commands consistently dashed
DataDog/datadog-agent pull request #13870
Opened 2022-10-13 14:55 UTC by djmitche

### What does this PR do?

Fixes this inconsistency:
```
  installservice    Installs the agent within the service control manager
  start-service     starts the agent within the service control manager
  stopservice       stops the agent within the service control manager
  remove-service    Removes the agent from the service control manager
  restart-service   restarts the agent within the service control manager
```

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

QA for other 7.41 changes will cover this.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-13 14:57 UTC, clarkb7 approved these changes

2022-10-13 17:44 UTC, buraizu requested changes
Thanks, just noticed what looks like an extra space, but let me know if that's intentional. Also, made one small suggestion that can improve readability for some screen readers.

2022-10-13 17:44 UTC, buraizu commented on releasenotes/notes/service-command-consistent-d7d8040e43798785.yaml
> +    ``start-service``, etc.).  The names without dashes are supported as
```suggestion
    ``start-service``, and so on). The names without dashes are supported as
```

2022-10-13 22:58 UTC, buraizu approved these changes

2022-10-18 08:00 UTC, ogaca-dd approved these changes

2022-10-18 20:54 UTC, merged