Fix 0-value for config poller interval and file polling
DataDog/datadog-agent pull request #13955
Opened 2022-10-19 21:45 UTC by vboulineau

### What does this PR do?

Testing #13777 revealed that Config poller makes the Agent panic if polling interval is <=0.

### Motivation

Bugfix.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

#13777 Modified with QA instructions.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-19 23:18 UTC, buraizu requested changes
Thanks, just a small update for punctuation consistency.

2022-10-19 23:18 UTC, buraizu commented on pkg/config/config_template.yaml
> +## This value must be >= 1 (i.e. 1 second)
```suggestion
## This value must be >= 1 (i.e. 1 second).
```

2022-10-20 15:59 UTC, djmitche approved these changes

2022-10-20 16:53 UTC, buraizu approved these changes

2022-10-26 10:45 UTC, juliogreff approved these changes

2022-10-28 15:13 UTC, merged