Replace PDH_REFRESH_INTERVAL with configurable value
DataDog/datadog-agent pull request #13951
Opened 2022-10-19 18:54 UTC by clarkb7

### What does this PR do?

Replaces the hardcoded PDH_REFRESH_INTERVAL value with the `windows_counter_refresh_interval` configuration option

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-19 19:29 UTC, iglendd commented
On one hand my changes make refreshment code irrelevant but on the other hand I foresee a narrow scope optimization (for my change) which require some form of refresh

2022-10-19 20:43 UTC, iglendd approved these changes

2022-10-19 22:13 UTC, buraizu requested changes

2022-10-19 22:13 UTC, buraizu commented on releasenotes/notes/go-pdhutil-configurable-refresh-limit-1010228fe8a9d537.yaml
> +    intialization in golang. This replaces the previously hardcoded limit
```suggestion
    initialization in golang. This replaces the previously hardcoded limit
```

2022-10-20 16:52 UTC, buraizu approved these changes

2022-10-20 18:31 UTC, merged