[WIP] Auto set trace-agent cpu limit based on any k8s limit
DataDog/datadog-agent pull request #14014
Opened 2022-10-24 18:33 UTC by ajgajg1134

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-10-26 20:32 UTC, buraizu requested changes

2022-10-26 20:32 UTC, buraizu commented on releasenotes/notes/traceAgentK8sLimit-165e630cca46f6a0.yaml
> +    APM: Trace-Agent will now set internal CPU rate limiter based on detected Kubernetes CPU Limit. To continue ONLY using the K8S cpu limit you must set `apm_config.max_cpu_percent` or `DD_APM_MAX_C
```suggestion
    APM: Trace-Agent now sets the internal CPU rate limiter based on the detected Kubernetes CPU limit. To continue using only the K8S CPU limit, you must set `apm_config.max_cpu_percent` or `DD_APM_MAX_CPU_PERCENT` to 0.
```

2022-10-27 09:02 UTC, vboulineau requested changes
I think there's a possible more straightforward, config-less approach.
We're providing a way to get self cgroup data using in `pkg/util/cgroups/self_reader.go`.

It's already used by DSD to get its own memory limit:
https://github.com/DataDog/datadog-agent/blob/main/pkg/dogstatsd/listeners/ratelimit/cgroup_memory_usage_linux.go

You could reuse it to get CPU Limit. This approach has the benefit to work everywhere on Linux (not only Kubernetes).
(Note: it does not work on Windows, we could think of a way to make it work on Windows when possible, if that's a requirement)

Also, if I may, the Agent CPU limits are normally low compared to host CPU, so using 90% to 95% of allocated CPU should not be a problem.
Hence, if the limiter is accurate enough I'd bump the the default `80%` to `90/95`

2022-10-27 14:56 UTC, buraizu approved these changes

2022-11-03 10:08 UTC, vboulineau commented on cmd/trace-agent/config/config_linux.go
> +	"github.com/DataDog/datadog-agent/pkg/util/pointer"
I'm not sure you can import `util/pointer` and `util/system` unfortunately.

2022-11-03 10:08 UTC, vboulineau commented on cmd/trace-agent/config/config_linux.go
> +	reader, err := cgroups.NewSelfReader("/proc", true)
You cannot pass `true` as second parameter. Cgroups limit can also be set through `systemd` (host install)

2023-04-07 14:21 UTC, closed without merging