Add comp/core/stopper
DataDog/datadog-agent pull request #14195
Opened 2022-11-04 18:25 UTC by djmitche

### What does this PR do?

This adds a component that can be used to stop a running app when that's required.  There are three ways an agent can be stopped:
 * signals
 * API request (`agent stop` or via GUI)
 * windows service shutdown

The latter is not handled by this component, but that can be added later.

### Motivation

This is preliminary to making the core agent an actual app (with `fxutil.Run`).  At the moment, nothing uses `fxutil.Run` and thus nothing instantiates this component.  

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Unused, so nothing to test.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-11-23 16:23 UTC, ogaca-dd requested changes

2022-12-05 13:10 UTC, djmitche commented
It looks like I don't get notifications for this repo anymore, so I missed this.  I think GitHub still has a setting to send messages for this repo to my datadog email address, but doesn't allow me to _change_ that setting. @sgnn7 was going to check into this.

These are all reasonable suggestions, though!  If I recall, the reason to still use the old approach if the component is not defined was to allow a different order for landing changes -- for example, the IPC call used for `agent stop` could land and work whether the process was running as a component or not.  But depending on the plan for order of landing things, that may not be necessary.

At any rate, just to be clear I'm not planning to fix this PR, but if there are questions I can answer please do get in touch (just not through GitHub comments, apparently..)

2023-03-23 00:31 UTC, djmitche commented
I'll close this now, but the branch is still here if anyone wants to revive it.

2023-03-23 00:31 UTC, closed without merging

2023-03-31 09:21 UTC, ogaca-dd commented
@djmitche : Thanks for the PR. I think we will want to revive it as it solve an important use case.