Separate lint and unit tests in CI
DataDog/datadog-agent pull request #14621
Opened 2022-12-06 13:15 UTC by KSerrania

### What does this PR do?

Splits the `test` invoke task into two tasks:
- the existing `test` task remains, but doesn't run linters by default. The `--run-linters` option can be passed to run linters.
- a new `lint-go` task is added, to run only the linters.

All CI jobs that used to do unit tests are now split into two jobs, one to run unit tests, the other to run linters.

### Motivation

This allows unit tests to run even when linters fail.
This should reduce the total time spent on the unit testing stage by 3~4 minutes, at the cost of .

### Additional Notes

To run linters & unit tests at once locally (the old behavior of `inv test`, run the `inv test --run-linters` command.

### Possible Drawbacks / Trade-offs

This splits the Windows scripts into two

### Describe how to test/QA your changes

Check the result of the new CI jobs.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2022-12-07 16:01 UTC, clarkb7 approved these changes
[system-probe](https://github.com/DataDog/datadog-agent/blob/main/tasks/winbuildscripts/sysprobe.ps1#L33-L38) has its own lint call that could be split out.

2022-12-08 07:53 UTC, bkabrda approved these changes

2022-12-08 17:14 UTC, KSerrania commented
Since that would require a review from another team, I'll take care of splitting the system-probe lint and test jobs in a separate PR, and merge this one as-is.

2022-12-08 18:46 UTC, KSerrania commented on .github/workflows/windows-lint-go.yml
> +      - name: Set git to use LF # needed so gofmt doesn't think every file needs reformatting
Done!

2023-03-23 18:28 UTC, rtrieu requested changes
Minor suggestion but looks good.

2023-03-23 18:28 UTC, rtrieu commented on README.md
> +You can add the `--skip-linters` option to skip go linters and only run the unit tests.
```suggestion
You can add the `--skip-linters` option to skip go linters and run just the unit tests.
```

2023-03-23 18:28 UTC, rtrieu commented on README.md
> +You can also use `invoke lint-go` to only run the go linters.
```suggestion
You can also use `invoke lint-go` to run just the go linters.
```

2023-03-29 03:40 UTC, sgnn7 approved these changes

2023-04-05 16:10 UTC, rtrieu approved these changes
Looks good!

2023-04-07 12:49 UTC, merged