adds agent version to the flare
DataDog/datadog-agent pull request #1486
Opened 2018-03-19 22:20 UTC by gmmeyer

### What does this PR do?

Adds the agent version to the flare form

2018-03-19 22:26 UTC, masci requested changes
Can we add a test asserting that the field is there using an http.TestServer?

2018-03-19 22:34 UTC, gmmeyer commented
Yes we can

2018-03-20 19:26 UTC, gmmeyer commented
@masci how do you feel about this?

2018-03-21 14:24 UTC, masci approved these changes

2018-03-21 14:26 UTC, merged