[WIP] Duong.nguyen/log source latency stats
DataDog/datadog-agent pull request #15038
Opened 2023-01-11 22:27 UTC by DDuongNguyen

### What does this PR do?
Getting rid of log latency from source but instead push them to InforProvider to centralize all log attributes.

### Motivation

Creating a centralized place so logs attribute can be rendered from 1 singular place

### Additional Notes

Still working on testing actual log files to see if the latency is accurate 

### Describe how to test/QA your changes
- Render both Agent Status and Agent GUI to see if log latency stats would show up from InfroProvider interface.  
- Check if log latency stats are accurate.

2023-01-13 15:25 UTC, gh123man commented on pkg/util/stats_tracker.go
> +		"Average Latency (ms): " + strconv.FormatInt(RecentAvgLatency, 10),
NIT: I'd prefer using `SPrintF` over `FormatInt`
```suggestion
		fmt.Sprintf("Average Latency (ms): %d", RecentAvgLatency)
```
(as well as for the others below)

2023-01-13 15:25 UTC, gh123man commented on pkg/util/stats_tracker.go
> +	return "Latency Stats"
```suggestion
	return "Pipeline Latency"
```

I think this is slightly more descriptive of what the metrics mean.

2023-01-13 15:26 UTC, gh123man commented on pkg/logs/status/status.go
> +	// AllTimeAvgLatency  int64 `json:"all_time_avg_latency"`
Can remove these commented lines.

2023-01-13 15:28 UTC, gh123man requested changes
Just some minor comments. Overall looks great.

2023-01-18 18:15 UTC, gh123man approved these changes

2023-01-20 08:35 UTC, Kaderinho approved these changes

2023-01-20 14:57 UTC, merged