[CWS] Compute workloads SBOMs to enrich CWS events and Activity Dumps
DataDog/datadog-agent pull request #15085
Opened 2023-01-16 16:00 UTC by Gui774ume

*Disclaimer: this PR might be moved to 7.44 - timeline is TBD*

### What does this PR do?

This PR introduces a way to generate SBOMs by calling a modified version of Trivy, directly from system-probe. This modified version of Trivy will fetch the files owned by each package so that we can resolve the package names and versions involved in a CWS event.

This new feature is experimental and controller with these new configuration parameters:
- runtime_security_config.sbom.enabled : controls if this feature should be enabled (set to false by default)
- runtime_security_config.sbom.workloads_cache_size : controls the size of the SBOM cache (indexed by image name and version) that we introduced to prevent the scanner from scanning the same container images over and over again.

### Motivation

This PR introduces powerful new features for CWS:
- the ability to write a rule that will trigger a CWS event as soon as a vulnerable package is loaded in memory
- new metadata on which to base a "risk score" for CWS's activity dumps feature

### Describe how to test/QA your changes

1) Add this rule to your policy:

```bash
 - id: package_test
   expression: exec.file.name != "" && exec.file.package.name == "bash"
```

2) Enable the configuration parameter and start a Debian container. Since the scanning is asynchronous (for performance & coverage reasons), wait a little bit and then run "bash". You should see an event trigger.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-01-16 21:38 UTC, kayayarai requested changes

2023-01-16 21:38 UTC, kayayarai commented on releasenotes/notes/runtime-security-sbom-95c989ca4e9413c8.yaml
> +  - CWS activity dumps are enriched with SBOM data
```suggestion
  - CWS generates an SBOM for any running workload on the machine.
  - CWS events are enriched with SBOM data.
  - CWS activity dumps are enriched with SBOM data.
```

2023-01-16 21:38 UTC, kayayarai commented on docs/cloud-workload-security/agent_expressions.md
> +| `process.ancestors.file.package.version` | string | Full version of the package provided this file |  |
Here and throughout this file: Should this say "... of the package provided in this file" or maybe "provided by this file"? There's a word missing.

2023-02-19 13:13 UTC, Gui774ume commented
Closed in favor of https://github.com/DataDog/datadog-agent/pull/15680

2023-02-19 13:13 UTC, closed without merging