Mute 60-sysprobe-check.sh in the absence of config
DataDog/datadog-agent pull request #15188
Opened 2023-01-20 12:00 UTC by artyom

Closes https://github.com/DataDog/datadog-agent/issues/15187

### What does this PR do?

Mutes `grep: /etc/datadog-agent/system-probe.yaml: No such file or directory` message coming from `60-sysprobe-check.sh` in the Docker image, where such file is not present.

### Motivation

See #15187

### Additional Notes

Alternative solution is to build custom docker image and maintain this fix separately.

### Possible Drawbacks / Trade-offs

N/a

### Describe how to test/QA your changes

N/a

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-02-13 15:35 UTC, L3n41c requested changes
Hi !
Thanks for your submission !

Indeed, the `system-probe.yaml` configuration file isn’t mandatory anymore.
Rather than completely hiding all errors, I left a suggestion to leverage an option of `grep` to silent only errors about nonexistent files.

2023-02-13 15:35 UTC, L3n41c commented on Dockerfiles/agent/cont-init.d/60-sysprobe-check.sh
> +if grep -Eq '^ *enable_tcp_queue_length *: *true' /etc/datadog-agent/system-probe.yaml 2>/dev/null || [[ "$DD_SYSTEM_PROBE_CONFIG_ENABLE_TCP_QUEUE_LENGTH" == "true" ]]; then
`grep` has a dedicated option to suppress error messages about nonexistent or unreadable files:

```suggestion
if grep -Eqs '^ *enable_tcp_queue_length *: *true' /etc/datadog-agent/system-probe.yaml || [[ "$DD_SYSTEM_PROBE_CONFIG_ENABLE_TCP_QUEUE_LENGTH" == "true" ]]; then
```

2023-02-13 15:35 UTC, L3n41c commented on Dockerfiles/agent/cont-init.d/60-sysprobe-check.sh
> +if grep -Eq '^ *enable_oom_kill *: *true' /etc/datadog-agent/system-probe.yaml 2>/dev/null || [[ "$DD_SYSTEM_PROBE_CONFIG_ENABLE_OOM_KILL" == "true" ]]; then
`grep` has a dedicated option to suppress error messages about nonexistent or unreadable files:

```suggestion
if grep -Eqs '^ *enable_tcp_queue_length *: *true' /etc/datadog-agent/system-probe.yaml || [[ "$DD_SYSTEM_PROBE_CONFIG_ENABLE_TCP_QUEUE_LENGTH" == "true" ]]; then
```

2023-02-13 16:41 UTC, artyom commented
@L3n41c thank you for your suggestion! Indeed, -s option fits much nicer — please see the updated change.

2023-02-13 16:51 UTC, L3n41c approved these changes

2023-02-13 16:54 UTC, L3n41c commented
@artyom : The CircleCI seems to fail because of an authentication issue. See this [link](https://app.circleci.com/pipelines/github/DataDog/datadog-agent/68695).
Could you try to sign out of CircleCI and then to log back on GitHub and then on CircleCI as suggested to see if it fixes it.

2023-02-13 17:01 UTC, artyom commented
@L3n41c I don't have a CircleCI account. Should I create one to unblock the pipeline?

2023-02-13 18:11 UTC, L3n41c commented
@artyom I think you may need to sign up with your GitHub account. I’m not 100% sure.

2023-02-13 19:07 UTC, artyom commented
@L3n41c ok, I signed up to CircleCI with my GitHub account, please see if that helped. I cannot re-run the workflow myself.

2023-09-25 02:10 UTC, st-cyrill commented
@L3n41c 
I faced the same problem. I hope this pull request will be merge.
Can you help us take the next action?

2026-02-20 15:37 UTC, jacjtito commented
Hi,

We are closing this PR as there was no recent activity on it. Feel free to reopen it if you still need the feature.
Thanks

2026-02-20 15:37 UTC, closed without merging