[USM] new java agent arguments format : support multiple arguments
DataDog/datadog-agent pull request #15314
Opened 2023-01-30 11:28 UTC by nplanel

### What does this PR do?

New java agents arguments format
Support multiple arguments k=v separated by space

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-01-30 12:38 UTC, val06 requested changes
cred

2023-01-30 12:38 UTC, val06 commented on pkg/network/java/hotspot.go
> +	for _, c := range strings.SplitN(cmd, " ", 4) {
add a comment:

> //we split by space for at most 4 words, since our longest command is "load instrument false <javaagent=args>" which is 4 words

2023-01-30 12:38 UTC, val06 commented on pkg/network/java/hotspot.go
> +	}
why making the map in the first place if we transform into string?
let's simplify and get all the arguments as 1 string

2023-01-30 12:38 UTC, val06 commented on pkg/network/protocols/http/ebpf_javatls.go
> +	agentArgs["dd.usm.authID"] = strconv.FormatInt(authID, 10)
add a `java_agent_cmd_args` as a new parameter under service_monitoring config section.
it is default value should be: `dd.appsec.enabled=false dd.trace.enabled=false dd.usm.enabled=true` then concat the dd.usm.authId to that string

2023-01-30 13:19 UTC, val06 requested changes
cred

2023-01-30 13:19 UTC, val06 commented on pkg/network/config/config.go
> +		JavaAgentArgs:        cfg.GetBool(join(smNS, "java_agent_args")),
`GetString` ?

2023-01-30 13:19 UTC, val06 requested changes
cred

2023-01-30 13:23 UTC, val06 approved these changes

2023-02-01 15:48 UTC, hmahmood approved these changes

2023-02-01 23:31 UTC, merged