Splitting the forwarder to have one per domain.
DataDog/datadog-agent pull request #1537
Opened 2018-03-28 16:15 UTC by hush-hush

### What does this PR do?

The forwarder class has been split in two: forwarder and
domainForwarder.

We now spawn one instance of domainForwarder per domain
in the configuration. This avoids slowing down one domain when the
another one is down.

We also split the health report for the forwarder to its own class. To
ease testing.

Test coverage has been pushed from 78.4% to 92.4% and the README has been
updated.

2018-04-10 01:05 UTC, ofek requested changes
This looks fantastic!

2018-04-10 01:05 UTC, ofek commented on pkg/forwarder/forwarder_test.go
> +	// Overwrite domainForwarders input channel
Could you please write a bit more about what this tests?

2018-04-12 17:53 UTC, ofek submitted a review, later dismissed

2018-04-23 21:24 UTC, ofek submitted a review, later dismissed

2018-04-25 17:29 UTC, truthbk reviewed
A couple of minor questions, but this is some really awesome work. Big PR, and I practically don't have any comments for it  🏆

 I'll give it another pass in case I missed anything!

2018-04-26 13:51 UTC, truthbk commented on pkg/forwarder/forwarder_health.go
> +				return
So here you are assuming the backend is always doing the right thing. I'm not sure you can assume that. Also, how would you respond to a 500 from us or some intermediate proxy or whatever? That would trigger a failed health check, and then we'd never recover.

2018-04-26 17:30 UTC, truthbk reviewed
Couple of typos after a second pass, this looks almost ready! 👌

2018-05-14 20:31 UTC, hush-hush commented on pkg/forwarder/README.md
> +one domain (ie: "http(s)://<domain>/<endpoint>"). The blacklist time will grow,
Added it in the title.

2018-05-16 16:06 UTC, ofek approved these changes
LGTM now, awesome job here!

2018-05-16 16:43 UTC, truthbk approved these changes
Looks good 🍰

2018-05-16 17:13 UTC, merged