[system-probe] Enable dnat tests for protocol classification
DataDog/datadog-agent pull request #15612
Opened 2023-02-14 19:35 UTC by hmahmood

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-02-15 15:53 UTC, guyarb requested changes

2023-02-15 15:53 UTC, guyarb commented on pkg/network/tracer/tracer_classification_test.go
> -	}
revert, this test cannot run on NAT (regardless of your fix)

2023-02-15 15:53 UTC, guyarb commented on pkg/network/tracer/tracer_classification_test.go
> +	skipFunc := skipIfNotLinux
revert, this test cannot run on NAT (regardless of your fix)

2023-02-15 17:17 UTC, guyarb commented on pkg/network/tracer/tracer_classification_test.go
> +	assert.Failf(t, "", "couldn't find incoming and outgoing connections with protocol %d for "+
yes

2023-02-15 17:18 UTC, guyarb approved these changes

2023-02-16 05:52 UTC, guyarb approved these changes

2023-02-23 05:06 UTC, guyarb approved these changes

2023-02-23 05:07 UTC, guyarb commented
The PR didn't trigger kitchen tests, triggering them manually

2023-02-23 06:40 UTC, guyarb requested changes
CI is failing
https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/232833493

2023-02-23 15:28 UTC, hmahmood commented
> CI is failing https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/232833493

This looks to be a flake. I can't reproduce this locally.

2023-02-23 16:31 UTC, brycekahle commented
> This looks to be a flake

Does it consistently fail in CI?

2023-02-23 17:10 UTC, guyarb commented
> > This looks to be a flake
> 
> Does it consistently fail in CI?

no, it is flaky


> > CI is failing https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/232833493
> 
> This looks to be a flake. I can't reproduce this locally.

I know, even before we couldn't reproduce it locally (happened to me once)
it reproduced "very easily" in the CI

2023-02-27 21:45 UTC, guyarb commented
@hmahmood how do you want to proceed?

2023-02-27 22:01 UTC, hmahmood commented
> @hmahmood how do you want to proceed?

At this point it looks like we're failing on the `rhel-86` `runtime` variant of the tests for kafka. I plan on looking into this more this week.

2023-03-21 16:37 UTC, guyarb approved these changes

2023-03-27 21:11 UTC, merged