[USM] add TLS to protocol stack if TLS static tags are present
DataDog/datadog-agent pull request #15753
Opened 2023-02-23 10:04 UTC by Yumasi

### What does this PR do?

This PR adds TLS to the protocol stack if one of the TLS static tags are present.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Change is covered by automated tests.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-02-23 10:16 UTC, guyarb requested changes

2023-02-23 10:16 UTC, guyarb commented on pkg/network/encoding/format_usm_test.go
> +			},
1. let's use the consts
2. let's mix the tests, one test with unknown, one with http and the left with db protocol
3. let's add a test for unsupport tag (assume `1 << 10`)

2023-02-23 10:16 UTC, guyarb commented on pkg/network/encoding/format.go
> +	if staticTags&tlsTagsMask > 0 {
i think we should create a function `IsTLSTag` next to `GetStaticTag`
and check it there. furthermore, add a comment next to the definitions of the TLS tags

2023-02-23 10:16 UTC, guyarb commented on pkg/network/encoding/format.go
> +	stack := make([]model.ProtocolType, 0)
```suggestion
	stack := make([]model.ProtocolType, 0, 1)
```

2023-02-23 10:16 UTC, guyarb commented on pkg/network/encoding/format.go
> +func formatProtocol(protocol network.ProtocolType, staticTags uint64) *model.ProtocolStack {
modify the documentation above

2023-02-23 11:49 UTC, guyarb approved these changes
Looks good, leaving a suggestion for improvement

2023-02-23 11:49 UTC, guyarb commented on pkg/network/tags_linux.go
> +const tlsTagsMask = http.GnuTLS | http.OpenSSL | http.Go
consider adding a comment to `http_types.go` a comment above the definition of the tags, so people will add here their new tags, or move the definition of `tlsTagMask` to `http_types.go`

2023-02-27 17:00 UTC, hmahmood approved these changes

2023-02-27 21:45 UTC, merged