Adds optional environment file for SystemD service
DataDog/datadog-agent pull request #16017
Opened 2023-03-08 09:49 UTC by ian28223

### What does this PR do?

Provides an easier way to define environment variables for the Agent service running on SystemD.
The absence of the file should not affect the Datadog Agent service from starting. 
Users can simply 
 - create `/etc/datadog-agent/environment` with any needed env vars (example below)
```
FOO=BAR
GODEBUG=x509ignoreCN=0,x509sha1=1
GOTRACEBACK=crash
``` 
 - or create a symlink to `/etc/environment` if system-wide environment variables are desired
    -  `/etc/datadog-agent/environmen -> /etc/environment`

... without having to run `daemon-reload`, persists upgrades, only requiring a service restart

### Motivation

- AGENT-9291
- AGENT-9180
- AGENT-6550
- AGENT-8565

### Additional Notes

This will probably need a public facing doc to let users know this is possible.

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-03-09 12:51 UTC, soheil reviewed
Thank you for sharing this PR. I appreciate your effort for adding optional environment file for SystemD service. It provides an easier way to define environment variables for the Agent service running on SystemD. The absence of the file should not affect the Datadog Agent service from starting.

I went through the provided code snippet and documentation. I have a few comments to make about the changes before we can merge it.

1. As per the code changes, you have added lines 9 and 10 of the snippet below.

- Before

    ```
    Type=simple
    PIDFile=<%= install_dir %>/run/agent.pid
    User=dd-agent
    Restart=on-failure
    ExecStart=<%= install_dir %>/bin/agent/agent run -p <%= install_dir %>/run/agent.pid
    ```

- After

    ```
    Type=simple
    PIDFile=<%= install_dir %>/run/agent.pid
    User=dd-agent
    Restart=on-failure
    EnvironmentFile=-<%= etc_dir %>/environment
    ExecStart=<%= install_dir %>/bin/agent/agent run -p <%= install_dir %>/run/agent.pid
    ```
    
    However, your proposed changes do not seem complete. You need to add details about the new file and update the documentation for the change being made.

2. I would suggest adding a test case to make sure that the file is being read correctly and that the service can restart with the new environment variables.

3. The additional notes state that the change may need a public-facing doc to communicate this new feature to users. I believe this is a valid point and suggest that it should be included as soon as possible.

4. Lastly, we need to make sure that the line numbers provided in the output are valid as it is crucial in understanding where the changes have been made.

Looking forward to seeing the changes soon. Thanks again for sharing this wonderful piece of code!

2023-03-09 12:51 UTC, soheil commented on omnibus/config/templates/datadog-agent/systemd.service.erb
>  Restart=on-failure
This is a useful approach as it avoids running `daemon-reload` and the service can be restarted right away. Good thinking! However, we should also include a test case to make sure that the file is read correctly and that the service restarts as expected.

2023-03-28 13:25 UTC, bkabrda requested changes
The code change itself looks good to me. Could you please add a release note and also provide QA instructions in the PR description?

2023-03-29 16:52 UTC, hestonhoffman approved these changes

2023-03-30 12:31 UTC, bkabrda approved these changes

2023-04-06 08:11 UTC, merged