Run process monitor in root network namespace
DataDog/datadog-agent pull request #16291
Opened 2023-03-27 13:29 UTC by Yumasi

### What does this PR do?

This PR runs the netlink based process monitor in the root network namespace. Netlink is affected by NetNS, and in case system-probe is running in a containerised environment, it would only see the events of the container, instead of the host machine.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-03-27 13:34 UTC, nplanel approved these changes

2023-03-28 06:31 UTC, guyarb requested changes
Such a PR cannot be merged without proper UTs or QA steps

2023-03-28 09:12 UTC, guyarb requested changes

2023-03-28 09:12 UTC, guyarb commented on pkg/process/monitor/process_monitor_test.go
> +	require.NoError(t, err, "could not subscribe to EXEC events")
on error, `unsubscribeExec` is nil
```suggestion
	require.NoError(t, err, "could not subscribe to EXEC events")
	defer unsubscribeExec()
```

2023-03-28 09:12 UTC, guyarb commented on pkg/process/monitor/process_monitor_test.go
> +	require.True(t, captured, "did not capture process EXEC from root namespace")
wrap it with `require.Eventually` to ensure the test is not flaky due to raced

2023-03-28 09:14 UTC, guyarb commented
did you deploy it on k8s and verified it works correctly?

2023-03-28 11:53 UTC, Yumasi commented
> did you deploy it on k8s and verified it works correctly?

Yes, it's been used in the load testing environment as a fix for hooking Java processes.

2023-03-28 12:34 UTC, guyarb approved these changes

2023-03-28 14:55 UTC, xornivore approved these changes

2023-03-28 16:03 UTC, merged