- added support for java Async frameworks ioctl messages
DataDog/datadog-agent pull request #16346
Opened 2023-03-29 18:14 UTC by val06

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-05-09 07:09 UTC, guyarb requested changes

2023-05-09 07:09 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/java/erpc.h
> +        log_debug("[handle_connection_by_peer] failed reading hostname location for pid %d\n", peer_key.pid);
i'm not sure hostname location is the best description to the code, did I miss anything?

2023-05-09 07:09 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/java/erpc.h
> +      u8           operation;  // REQUEST, CLOSE_CONNECTION, HOST, PLAIN
REQUEST? PLAIN?

2023-05-09 07:09 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/java/erpc.h
general suggestion, it looks like we have code duplication in the different methods here, I do suggest to go over the functions and extract common code and use macro / functions for them.

2023-05-09 13:27 UTC, val06 commented on pkg/network/ebpf/c/protocols/tls/java/maps.h
> +#endif
what do you mean? i kinda copied that from kafka [implementation](https://github.com/DataDog/datadog-agent/blob/main/pkg/network/ebpf/c/protocols/kafka/maps.h#L10)

2023-05-09 13:33 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/java/maps.h
> +#endif
ignore that, it was an old comment from the first time I reviewed the PR

2023-05-10 09:30 UTC, val06 commented on pkg/network/ebpf/c/protocols/tls/java/erpc.h
do you have any examples? 
The only code block i could think of is reading the `conn_tuple_t` from the buffer which i felt doesn't deserve its own helper method.

2023-05-16 06:57 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/java/erpc.h
yes, talked about the conn_tuple_t reading, but it is negligible

2023-05-22 11:10 UTC, guyarb requested changes

2023-05-22 11:26 UTC, guyarb approved these changes, later dismissed

2023-05-30 15:24 UTC, guyarb approved these changes

2023-06-12 13:01 UTC, merged