Unified KeyTuple into a new type called FourTuple. Also introduced Fo…
DataDog/datadog-agent pull request #16425
Opened 2023-04-04 09:25 UTC by DanielLavie

…urTuplesFromConn which is the merged version of HTTPKeyTuplesFromConn and KafkaKeyTuplesFromConn

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-04-04 11:00 UTC, guyarb requested changes

2023-04-04 11:00 UTC, guyarb commented on pkg/network/types/four_tuple.go
i'm not a big fan of the naming
let's go with something that represents it like `ConnectionKey` or something that represents the meaning, and not the implementation

saying, tomorrow we might add another indicator (maybe pid? maybe tcp/udp?) and then fourtuple won't be a good enough name.

2023-04-04 11:00 UTC, guyarb commented on pkg/network/encoding/http.go
> +// they generate the same four tuple
same same

2023-04-04 14:03 UTC, DanielLavie commented on pkg/network/types/four_tuple.go
Changed to ConnectionKey

2023-04-04 14:03 UTC, DanielLavie commented on pkg/network/encoding/http.go
> +// they generate the same four tuple
Changed to connection key

2023-04-04 15:02 UTC, guyarb approved these changes

2023-04-04 16:27 UTC, hmahmood approved these changes

2023-04-04 16:57 UTC, heyronhay approved these changes

2023-04-05 05:15 UTC, derekwbrown approved these changes

2023-04-05 05:21 UTC, merged