usm: remove gotos
DataDog/datadog-agent pull request #16625
Opened 2023-04-17 09:01 UTC by guyarb

### What does this PR do?

Remove gotos

### Motivation

Code simplification

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-04-17 09:07 UTC, DanielLavie approved these changes

2023-04-17 09:13 UTC, DanielLavie approved these changes

2023-04-17 10:47 UTC, nplanel requested changes

2023-04-17 10:47 UTC, nplanel commented on pkg/network/java/hotspot.go
> +			return err
This will not work on java 1.8, if the java process running with nobody and sysprobe is root

2023-04-18 08:15 UTC, nplanel commented on pkg/network/java/hotspot.go
> +			return err
sorry, I miss read the diff

2023-04-18 08:15 UTC, nplanel approved these changes

2023-04-25 07:57 UTC, merged