Fix tag duplication
DataDog/datadog-agent pull request #16690
Opened 2023-04-20 14:40 UTC by ojung

### What does this PR do?

Fixes a bug introduced in https://github.com/DataDog/datadog-agent/pull/16409/. The tags variable wasn't reassigned and hence accumulated tags between requests.

The PR introducing the bug targets 7.45.0.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-04-20 17:05 UTC, cimi reviewed
:+1: Thanks for finding and fixing this before the release! 

I haven't approved yet because I haven't read the tests, will do tomorrow morning 😃

2023-04-20 17:44 UTC, ojung commented on pkg/trace/api/debugger.go
> +		tags = tags[0:maxLen]
Yep, that was my thinking. 👍

2023-04-20 20:39 UTC, ajgajg1134 requested changes, later dismissed
Overall looks good from APM just one small change in the tests

2023-04-20 20:39 UTC, ajgajg1134 commented on pkg/trace/api/debugger_test.go
> +		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
Can you add a `defer srv.Close()` for this and the other test to ensure the test server is closed?

2023-04-20 20:39 UTC, ajgajg1134 commented on pkg/trace/releasenotes/notes/apm-fix-tag-accumulation-4b9faf652f692706.yaml
> +    APM: Fixes a bug in the debugger endpoint that would accumulate tags between unrelated requests.
Yeah as long as this fix makes it in such that the bug is never released I think it's fine to skip the release note here

2023-04-21 07:39 UTC, ahmed-mez approved these changes

2023-04-21 10:57 UTC, cimi approved these changes

2023-04-21 11:46 UTC, merged