Add metric for logs agent status
DataDog/datadog-agent pull request #1669
Opened 2018-05-03 13:15 UTC by eplanet

### What does this PR do?
Add metric for logs agent status.

### Motivation
Because I need to configure a monitor that would be triggered when the logs agent stops reporting. Currently I do it with a custom check written in Python and I would prefer the agent to report it natively.

2018-05-03 14:38 UTC, hush-hush requested changes
The  current solution add a hard link between the aggregator and the logs agent. And we have different build flavour that build without it (puppy agent for example).

We also would like to keep the aggregator as simple as possible. I don't think it should be aware of all other possible part of the agent. The design was for other parts to send data to the aggregator and not for the aggregator to pull.

I think you should do this from within the log agent, sending a gauge to the aggregator every X second. You could look at the `Sender` class used by the go check.

2018-10-04 08:49 UTC, iksaif commented
I'll give it a shot, but I'm tempted to use "expvar" for this instead.

2018-10-04 09:41 UTC, iksaif commented
You can follow https://github.com/DataDog/datadog-agent/pull/2408

2018-10-04 09:44 UTC, eplanet commented
OK cool! I think I should close that PR then.

2018-10-04 09:44 UTC, closed without merging