[core] Add a req file to list all the Python checks shipped with the agent
DataDog/datadog-agent pull request #1701
Opened 2018-05-16 13:00 UTC by masci

### What does this PR do?

Adds a requirement file detailing which checks are included in a certain version of the agent. At the moment this file is not used anywhere in the build process, mid-term goal will be using `pip` to actually install and include in the package the desired checks at Agent build time.

### Motivation

At the moment, determining which checks were shipped with which Agent is a complex and esoteric procedure. We need a single source of truth to determine the list of packages built with the agent.

2018-05-16 15:13 UTC, ofek reviewed
Great idea! Just a few remarks:

2018-05-16 15:13 UTC, ofek commented on requirements-integrations-core.txt
> +zk==1.2.0; sys_platform != 'windows'
`zk` check has no deps

2018-05-16 16:29 UTC, ofek requested changes
Also https://github.com/DataDog/integrations-core/pull/1557#discussion_r188690143

2018-05-17 14:13 UTC, ofek submitted a review, later dismissed

2018-05-17 14:14 UTC, olivielpeau reviewed
one nit (there might be other small platform exclusion mistakes I've missed though)

2018-05-17 14:14 UTC, olivielpeau commented on requirements-integrations-core.txt
> +kubelet==1.2.0; sys_platform != 'win32'
should be `linux` only (i.e. mac should be excluded too)

2018-05-17 16:56 UTC, ofek approved these changes

2019-01-08 11:50 UTC, masci commented
Closing, we eventually hosted the file in `integrations-core`

2019-01-08 11:50 UTC, closed without merging