Do not add otlp batch processors when running in serverless.
DataDog/datadog-agent pull request #17088
Opened 2023-05-11 21:08 UTC by purple4reina

### What does this PR do?

In serverless, we need to be able to flush all data at the end of each invocation because it is not guaranteed that there will be another invocation before the container shuts down.  It is okay however for the data to finish completely flushing when the container fully shuts down.

The batch processor gets in the way of this forced flushing.  Even when shutting down the collector explicitly, it is still possible for data to remain "stuck" in the batch processor.

### Motivation

The test `TestServerlessOTLPAgentReceivesTraces` [increased in duration](https://app.datadoghq.com/ci/test-runs?query=test_level%3Atest%20%40ci.pipeline.name%3A%22DataDog%2Fdatadog-agent%22%20%40test.is_flaky%3Atrue%20%40test.codeowners%3A%22%40DataDog%2Fserverless%22%20%40test.status%3Afail%20&cols=%40test.name%2C%40duration%2C%40test.service%2C%40git.branch&currentTab=performance&eventStack=AgAAAYgF7qFo0t1S4wAAAAAAAAAYAAAAAEFZZ0Y3cUZvQUFDQzhUZkFUWnFqSjFJOQAAACQAAAAAMDE4ODA1ZjYtMmU1Ni00ZGJiLThiZTMtZjhiZDI4ZWRjYWVh&index=citest&spanID=4418668816220785778&spanViewType=errors&testId=AgAAAYgF7qFo0t1S4wAAAAAAAAAYAAAAAEFZZ0Y3cUZvQUFDQzhUZkFUWnFqSjFJOQAAACQAAAAAMDE4ODA1ZjYtMmU1Ni00ZGJiLThiZTMtZjhiZDI4ZWRjYWVh&trace=AgAAAYgF7qFo0t1S4wAAAAAAAAAYAAAAAEFZZ0Y3cUZvQUFDQzhUZkFUWnFqSjFJOQAAACQAAAAAMDE4ODA1ZjYtMmU1Ni00ZGJiLThiZTMtZjhiZDI4ZWRjYWVh&start=1683233795100&end=1683838595100&paused=false) on April 14, 2023 from 5 seconds to 20 seconds. This was causing intermittent flaky failures in the test due to the 10 second timeout waiting for spans to arrive.

Using git bisect, I discovered https://github.com/DataDog/datadog-agent/commit/f49e9f7ba5ca8acbff9eefff4d2b0c677b02c6d1 which was committed on April 14, 2023. That commit added batch processors to the metrics and traces otlp collector.

It was only by luck that I had chosen 10 seconds for the timeout in this test which matches the 10 seconds for the batch processor. Due to this great luck, the test became flaky and was then noticed and investigated.

To better ensure we do not see issues like this again in the future, I decreased the test's timeout to 1 second. This is the amount of time the daemon waits before shutting down its http server and thus can be a good stand in for the amount of time available to fully flush data.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

I tested this change by deploying a lambda function instrumented with otlp and called it only once. Before this change, no trace was ever received. After this change, a trace was received almost immediately and displayed to the user in APM.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-05-12 16:50 UTC, DarcyRaynerDD approved these changes
LGTM from serverless side

2023-05-12 17:28 UTC, maxday commented
nit: since this is decided at build time, you could also use the serverless build tag to avoid adding if serverless in the code
here is an example of serverless+nonserverless implementation: https://github.com/DataDog/datadog-agent/blob/main/pkg/util/log/log_not_serverless.go

2023-05-12 18:56 UTC, purple4reina commented
> nit: since this is decided at build time, you could also use the serverless build tag to avoid adding `if serverless` in the code. Here is an example of serverless+nonserverless implementation: https://github.com/DataDog/datadog-agent/blob/main/pkg/util/log/log_not_serverless.go

Yes, this is a good idea. I'll implement it now and push so we can see what that alternative looks like.

2023-05-15 09:46 UTC, mx-psi requested changes
Code LGTM, but we should change CODEOWNERS to add serverless as an owner of the serverless files

2023-05-15 16:44 UTC, mx-psi approved these changes

2023-05-17 16:13 UTC, merged