Return an error when the GCE metadata API responds with an empty body
DataDog/datadog-agent pull request #1721
Opened 2018-05-19 11:16 UTC by nstapelbroek

### What does this PR do?

Hey there :wave:, 

After updating my agent instances to 6 this morning, my datadog lost a lot of data needed for metrics and alerts.
After a short investigation it turns out that the hostname autoresolving stopped working on my swarm setup and it assigns an empty hostname to all agents running.
Below you can see the excerpt of the logs that lead to this conclusion:

```
[services.d] done.
[ AGENT ] 2018-05-19 10:00:30 UTC | INFO | (start.go:156 in StartAgent) | Starting Datadog Agent v6.2.0
[ AGENT ] 2018-05-19 10:00:30 UTC | DEBUG | (hostname.go:108 in GetHostname) | Unable to get the hostname from the config file: host name is empty
[ AGENT ] 2018-05-19 10:00:30 UTC | DEBUG | (hostname.go:109 in GetHostname) | Trying to determine a reliable host name automatically...
[PROCESS] 2018-05-19 10:00:30 INFO (tagger.go:78) - starting the tagging system
[ AGENT ] 2018-05-19 10:00:30 UTC | DEBUG | (hostname.go:118 in GetHostname) | GetHostname trying GCE metadata...
[ TRACE ] 2018-05-19 10:00:30 INFO (main.go:175) - trace-agent not enabled.
[ TRACE ] Set env var DD_APM_ENABLED=true or add
[ TRACE ] apm_enabled: true
[ TRACE ] to your datadog.conf file.
[ TRACE ] Exiting.
[ AGENT ] 2018-05-19 10:00:30 UTC | INFO | (start.go:174 in StartAgent) | Hostname is: 
[ AGENT ] 2018-05-19 10:00:30 UTC | INFO | (security.go:132 in FetchAuthToken) | Saved a new authentication token to /etc/datadog-agent/auth_token
[ AGENT ] 2018-05-19 10:00:30 UTC | INFO | (start.go:191 in StartAgent) | GUI server port -1 specified: not starting the GUI.
[ AGENT ] 2018-05-19 10:00:30 UTC | DEBUG | (start.go:202 in StartAgent) | Starting forwarder
[ AGENT ] 2018-05-19 10:00:30 UTC | INFO | (forwarder.go:235 in Start) | DefaultForwarder started (1 workers), sending to 1 endpoint(s): "https://6-2-0-app.agent.datadoghq.com" (1 api key(s))
```

Turns out that the line https://github.com/DataDog/datadog-agent/blob/6.2.x/pkg/util/gce/gce.go#L56 is hit because my setup is returning a valid response:
```
# curl http://169.254.169.254/computeMetadata/v1/instance/hostname -vvv
*   Trying 169.254.169.254...
* TCP_NODELAY set
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /computeMetadata/v1/instance/hostname HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Sat, 19 May 2018 10:14:50 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Expires: Sat, 19 May 2018 10:14:49 GMT
< Cache-Control: no-cache
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 169.254.169.254 left intact
```
### Motivation

Instead of investigating who/what is running on this endpoint or figuring out a way to bypass the GCE hostname discovery I'd figured it would probably be a good thing to assert a non-empty response body for all GCE related calls.

### Additional Notes
- Besides the unit test, is there a way to functionally assert the behavior?
- I'm still new to golang, any feedback is welcome

Let me know what you think!

2018-05-19 11:18 UTC, nstapelbroek commented on pkg/util/gce/gce.go
>  		return "", fmt.Errorf("GCE hostname, error reading response body: %s", err)
Just noticed that this line uses "GCE hostname" in its message while its placed in the generic `getResponse` func. Should we perhaps remove this?

2018-05-28 18:05 UTC, nstapelbroek commented
@olivielpeau Hey Olivier, do you need anything from me to get this reviewed? I'm happy to change anything :)

2018-05-29 20:39 UTC, hush-hush requested changes
Thanks for the PR @nstapelbroek !

A few nitpicks but the PR seems good to go otherwise.

2018-05-29 20:39 UTC, hush-hush commented on pkg/util/gce/gce_test.go
> +	assert.Equal(t, lastRequest.URL.Path, "/instance/hostname")
The second argument of `Equal` is actually the expected value: https://godoc.org/github.com/stretchr/testify/assert#Equal

2018-05-29 20:39 UTC, hush-hush commented on pkg/util/gce/gce_test.go
> +	assert.Equal(t, "", val)
We should user `assert.Empty(t, val)` here

2018-05-29 20:39 UTC, hush-hush commented on pkg/util/gce/gce.go
> +	if len(all) <= 0 {
Could you add a quick comment explaining why we have to check for an empty body ?

2018-06-08 16:34 UTC, nstapelbroek commented
Sweet, thanks for the review @hush-hush 

Let me know if you need anything else changed :)

2018-06-08 18:16 UTC, hush-hush approved these changes
Look good, thanks for this PR @nstapelbroek  !

2018-06-08 18:16 UTC, merged