Use agent hostname as hostname for docker events.
DataDog/datadog-agent pull request #1729
Opened 2018-05-23 18:50 UTC by devonboyer

### What does this PR do?

Use the same hostname as the agent so that host tags (like `availability-zone:us-east-1b`) are attached to Docker events from this host. The hostname from the docker api may be different than the agent hostname depending on the environment (like EC2 or GCE).

### Motivation

Host tags (like `availability-zone:us-east-1b` when running in AWS) were not getting attached to Docker events.

2018-05-24 11:08 UTC, hkaj requested changes
LGTM, but can you add a release note with `reno` before we merge?

2018-05-24 19:17 UTC, devonboyer commented
It still looks like the AWS tags are not getting added after changing the hostname of the docker events. The fix may not be this trivial. I'll keep looking into it.

<img width="969" alt="screen shot 2018-05-24 at 3 15 42 pm" src="https://user-images.githubusercontent.com/5367914/40506999-6ae45322-5f65-11e8-9dc6-5abfee27b67d.png">

2018-05-24 20:20 UTC, devonboyer commented
I forgot to add the IAM role to my ec2 instance. After doing that the tags seem to show up on docker events.

<img width="969" alt="screen shot 2018-05-24 at 4 19 48 pm" src="https://user-images.githubusercontent.com/5367914/40511641-5567744e-5f6e-11e8-8544-39b2b2bc1f14.png">

2018-05-25 13:55 UTC, hkaj approved these changes

2018-05-25 15:13 UTC, merged