Adding missing err check
DataDog/datadog-agent pull request #1760
Opened 2018-05-30 16:46 UTC by antoinepouille

### What does this PR do?

This adds the check on an err that was missing, and could go uncatched

### Motivation

Catching a potential I/O error there

2018-06-04 16:48 UTC, xvello requested changes
Error handling for the read itself should stay consistent with the normal mode. It's handled in lines 115-124.

Can we just change the variable name of the tagging error, to avoid overwriting `err`?
`container, taggingErr := processUDSOrigin(oob[:oobn])`

2018-06-05 11:54 UTC, antoinepouille commented
That's more simple indeed. Didn't notice the err check further was supposed to consider this `err`.
I also changed something that I think is a typo?

2018-06-05 12:54 UTC, xvello approved these changes
👍

2018-06-08 11:12 UTC, truthbk approved these changes
:shipit:

2018-06-08 11:12 UTC, merged