Allow VMs to run on CI and do not require parameters in runner
DataDog/datadog-agent pull request #17616
Opened 2023-06-13 14:46 UTC by vboulineau

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-06-14 09:05 UTC, ogaca-dd approved these changes
LGTM

2023-06-16 08:01 UTC, pducolin requested changes
We probably need the `set +x ... set -x` to mute possible leaks back, not convinced by the refactoring that removes the 2 more readable function to set a parameter or set a secret parameter

2023-06-19 17:25 UTC, vboulineau commented on .gitlab/e2e.yml
> +    - aws ssm get-parameter --region us-east-1 --name ci.datadog-agent.ssh_key --with-decryption --query "Parameter.Value" --out text > $E2E_PRIVATE_KEY_PATH
It's not necessary `set -x` is not default and the command does not leak information. We have usage all over the CI.

2023-06-19 17:25 UTC, vboulineau commented on test/new-e2e/runner/configmap.go
> +	AWSPrivateKeyPath = commonconfig.DDInfraConfigNamespace + ":" + "aws/defaultPrivateKeyPath"
It's private

2023-06-19 17:29 UTC, vboulineau commented on test/new-e2e/runner/configmap.go
> -func SetConfigMapFromSecret(secretStore parameters.Store, cm ConfigMap, paramName parameters.StoreKey, configMapKey string) error {
It's either 1 generic or 3 (generic + two public variants) functions. IMHO not worth it considering the usage of the function.

2023-06-23 09:04 UTC, pducolin commented on test/new-e2e/runner/configmap.go
> +	AWSPrivateKeyPath = commonconfig.DDInfraConfigNamespace + ":" + "aws/defaultPrivateKeyPath"
For other params we first moved params to public in test-infra and then imported them here, I understand it is pedantic but it helps discoverability and readability in the end.

2023-06-23 09:07 UTC, pducolin commented on test/new-e2e/runner/configmap.go
> -func SetConfigMapFromSecret(secretStore parameters.Store, cm ConfigMap, paramName parameters.StoreKey, configMapKey string) error {
```go
err = SetConfigMapFromParameter(profile.SecretStore(), cm, parameters.APPKey, AgentAPPKey, true)
```

is less explicit and readable than

```go
err = SetConfigMapFromSecret(profile.SecretStore(), cm, parameters.APPKey, AgentAPPKey)
```

A reader falling on the first will have to click and follow the inner code to understand what the `true` is about, while it is explicit on the second. Not worth the refactoring to one single function.

2023-06-23 09:10 UTC, pducolin commented on .gitlab/e2e.yml
> +    - aws ssm get-parameter --region us-east-1 --name ci.datadog-agent.ssh_key --with-decryption --query "Parameter.Value" --out text > $E2E_PRIVATE_KEY_PATH
Asking as @KSerrania  asked for this change on the preview PR and it was applied, so I was wondering why changing it back.

2023-06-26 15:05 UTC, pducolin approved these changes
Thank you for addressing the comments and for allowing running tests on the CI !

2023-06-27 07:31 UTC, merged