usm: Replace kprobes with tracepoints
DataDog/datadog-agent pull request #17698
Opened 2023-06-18 21:00 UTC by guyarb

### What does this PR do?

Converts SOWatcher kprobes into tracepoints.

### Motivation

Using tracepoints is encouraged as the ABI is stable and change less over the years, furthermore, unlike kprobes, tracepoints does not suffer from misses.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-06-19 06:43 UTC, val06 approved these changes

2023-06-19 08:26 UTC, usamasaqib reviewed
This PR does not address the root cause of kprobe misses. The kprobe misses you are likely noticing are not actual misses. These happen because the kernel registers a miss if a page fault occurs during the handling of a kprobe (the kprobe is still executed though). This behavior was removed after 5.14. In `do_sys_open` we are using the `bpf_probe_read_user` helper which is susceptible to page faults.
The new method will suppress false kprobe misses, but it won't solve the problem caused by the use of `bpf_probe_read_user`

A more robust solution could be to read the path once it has been read into kernel memory to avoid failures due to page faults.

2023-06-19 08:46 UTC, guyarb commented
> This PR does not address the root cause of kprobe misses. The kprobe misses you are likely noticing are not actual misses. These happen because the kernel registers a miss if a page fault occurs during the handling of a kprobe (the kprobe is still executed though). This behavior was removed after 5.14. In do_sys_open we are using the bpf_probe_read_user helper which is susceptible to page faults.
The new method will suppress these false kprobe misses, but it won't solve the problem caused by the use of bpf_probe_read_user
A more robust solution could be to read the path once it has been read into kernel memory to avoid failures due to page faults.

it already happens in `do_sys_open_helper_enter`

2023-06-19 08:57 UTC, usamasaqib reviewed
> it already happens in do_sys_open_helper_enter

`fill_path_safe` uses the same pointers as passed to `bpf_probe_read_user`. So it would also fail due to a page fault.

2023-06-19 10:39 UTC, guyarb commented
> > it already happens in do_sys_open_helper_enter
> 
> `fill_path_safe` uses the same pointers as passed to `bpf_probe_read_user`. So it would also fail due to a page fault.

The same implemented in other location of the code
https://github.com/DataDog/datadog-agent/blob/c2d3ed1914483cfc10d4970267ff8393fae421de/pkg/network/ebpf/c/protocols/http/buffer.h#L20-L34

what is the difference?

2023-06-21 21:02 UTC, brycekahle commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    trace_common unsued;
typo
```suggestion
    trace_common unused;
```

2023-06-21 21:02 UTC, brycekahle commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    trace_common unsued;
typo
```suggestion
    trace_common unused;
```

2023-06-21 21:31 UTC, brycekahle commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +} trace_common;
I think using a separate struct can cause padding to be inserted at the end, thus potentially causing alignment issues. I see that CWS always uses a single struct and doesn't embed anything.

2023-06-21 21:35 UTC, brycekahle commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    long syscall_nr;
I think this should be `int` based on `/sys/kernel/tracing/events/syscalls/sys_enter_openat/format`: `field:int __syscall_nr;	offset:8;	size:4;	signed:1;`

2023-06-21 21:37 UTC, brycekahle commented on pkg/network/usm/shared_libraries_test.go
> +					EBPFFuncName: fmt.Sprintf("tracepoint__syscalls__sys_enter_%s", openatSysCall),
I think it makes sense to extract a common function for the enter/exit `fmt.Sprintf`.

2023-06-22 03:33 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    trace_common unsued;
irrelevant after removing trace_common

2023-06-22 03:33 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    trace_common unsued;
irrelevant after removing trace_common

2023-06-22 19:45 UTC, brycekahle requested changes

2023-06-23 06:14 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    long __syscall_nr;
making that change cause the tests to fail, as there is an alignment issue
```
guy@arbitman:~ $ sudo cat /sys/kernel/tracing/events/syscalls/sys_enter_openat2/format
[sudo] password for guy: 
name: sys_enter_openat2
ID: 636
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:int dfd;	offset:16;	size:8;	signed:0;
	field:const char * filename;	offset:24;	size:8;	signed:0;
	field:struct open_how * how;	offset:32;	size:8;	signed:0;
	field:size_t usize;	offset:40;	size:8;	signed:0;
```
see __syscall_nr

2023-06-23 17:04 UTC, brycekahle commented on pkg/network/ebpf/c/protocols/tls/sowatcher-types.h
> +    long __syscall_nr;
I see, there is an extra `4` bytes of offset after `__syscall_nr`.

2023-06-23 17:07 UTC, brycekahle approved these changes

2023-06-24 09:35 UTC, merged