[WIP] pkg/obfuscate: create redis obfuscation setting to remove all arguments
DataDog/datadog-agent pull request #17844
Opened 2023-06-26 20:49 UTC by hannahkm

### What does this PR do?

This PR creates and implements a new obfuscation variable, `apm_config.obfuscation.redis.remove_all_args`. This variable, when enabled, allows the user to obfuscate all arguments for any given Redis command to a single "?".

### Motivation

Motivated by customer request (link).

### Describe how to test/QA your changes

Changes will be tested by unit tests. For manual testing, set environment variable `DD_APM_OBFUSCATION_REDIS_REMOVE_ALL_ARGS` and/or config variable `apm_config.obfuscation.redis.remove_all_args` to true. The change should be read correctly by the agent and reflected in logs. 

Run `curl localhost:5012/debug/vars` to dump the runtime config of the agent. This should contain the configured values in the env vars mentioned previously.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-06-29 22:05 UTC, aliciascott approved these changes
Release notes look good for docs!

2023-06-30 08:35 UTC, Kaderinho approved these changes

2023-06-30 08:39 UTC, ogaca-dd approved these changes
LGTM for files owned by shared components.

2023-07-03 15:27 UTC, knusbaum requested changes
This looks really good.

I only have a couple comments.

2023-07-03 15:27 UTC, knusbaum commented on pkg/obfuscate/redis.go
> +			if arg == "SET" || arg == "GET" || arg == "INCRBY" {
Above, we checked `strings.ToUpper(cmd)`.
Could these command args also be lower-case?

2023-07-03 15:55 UTC, knusbaum approved these changes
Looks great!

2023-07-03 15:55 UTC, knusbaum commented on pkg/obfuscate/redis.go
> +				out.WriteString(strings.Join([]string{"", a, "?"}, " "))
Good attention keeping the original `a` here. :+1:

2023-07-03 17:57 UTC, merged