Migrating the 'resources' metadata payload to component
DataDog/datadog-agent pull request #18099
Opened 2023-07-10 14:04 UTC by hush-hush

### What does this PR do?

Migrating the  `resources` metadata to a component.

### Describe how to test/QA your changes

Run the new version of the agent and check that the `resources` payload is still sent with the correct format.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-07-18 08:43 UTC, ogaca-dd requested changes
Great PR!
I have selected `Request changes` as there are some important questions to answer before merging this PR.

2023-07-18 08:43 UTC, ogaca-dd commented on comp/metadata/runner/runner.go
> +			cancel()
Note: This is strictly not needed as `cancel` is called [here](https://github.com/DataDog/datadog-agent/pull/18099/files#diff-effd0202d7ac04db2a5ed611246a121d1d512c137dfb2288c9e1b250427d7288R104)

2023-07-19 13:09 UTC, hush-hush commented on comp/core/config/config.go
> +func newMock(deps mockDependencies, t testing.TB) (Mock, error) {
I forgot to update this after our latest discussion around mocking config. Thanks for catching it.

2023-07-19 13:22 UTC, hush-hush commented on comp/metadata/resources/resources.go
> +)
Totally, copy paste from the old code :+1:

2023-07-19 13:23 UTC, hush-hush commented on comp/metadata/resources/resources.go
> +	// platform. This is legacy behavior from Agent V5.
It used to be defined here: https://github.com/DataDog/datadog-agent/pull/18099/files/7f6558f67796703bada78f545682bf85bf2e73de#diff-96fff4e95d733d53c0d6fad999b9b29d126e5ffc020f3cf96194f2ea161f3b8aL49

2023-07-19 13:30 UTC, hush-hush commented on comp/metadata/resources/resources_test.go
> +			Config: config.Component(c),
No we needed to cast to satisfy the compiler. But I remove the logic to edit the conf after init, so this cast is no longer needed.

2023-07-19 13:38 UTC, hush-hush commented on comp/metadata/runner/runner.go
> +type MetadataProvider func(context.Context, serializer.MetricSerializer) time.Duration
I forgot to edit this :+1:. Now that we have the serializer in FX we don't need the runner to centralize the serializer initalization.

2023-07-19 13:47 UTC, hush-hush commented on cmd/agent/subcommands/run/command.go
> +			return aggregator.InitAndStartAgentDemultiplexer(log, sharedForwarder, opts, hostnameDetected), nil
Yes, this should be fine unless I miss something.

2023-07-19 13:49 UTC, hush-hush commented on comp/metadata/resources/resources_non_supported.go
> +func newResourcesProvider(log log.Component, config config.Component) provides {
I think we do need the comp in `provides` so FX holds a ref to the `resources` struct preventing the GC to collect it, no ?

2023-07-21 08:12 UTC, ogaca-dd commented on comp/metadata/resources/resources_non_supported.go
> +func newResourcesProvider(log log.Component, config config.Component) provides {
What do you mean by `resources` struct?

2023-07-21 10:17 UTC, hush-hush commented on comp/metadata/resources/resources_non_supported.go
> +func newResourcesProvider(log log.Component, config config.Component) provides {
Actually  we need this type or FX will error-out:

Ex:
```
Failed: cannot provide function "github.com/DataDog/datadog-agent/comp/metadata/resources".newResourcesProvider (C:/dev/go/src/github.com/DataDog/datadog-agent/comp/metadata/resources/resources_non_supported.go:21): func(log.Component, config.Component) resources.provides must provide at least one non-error type
```

2023-07-21 12:30 UTC, ogaca-dd approved these changes

2023-07-24 12:23 UTC, truthbk approved these changes

2023-07-24 16:17 UTC, merged