[usm] extract http2 protocol
DataDog/datadog-agent pull request #18191
Opened 2023-07-16 08:25 UTC by guyarb

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-07-16 12:35 UTC, DanielLavie requested changes

2023-07-16 12:35 UTC, DanielLavie commented on dummy
> +a
Remove

2023-07-16 12:35 UTC, DanielLavie commented on pkg/network/usm/monitor.go
> +	"syscall"
Fix order

2023-07-17 15:13 UTC, hmahmood approved these changes

2023-07-18 16:48 UTC, derekwbrown approved these changes

2023-07-18 20:25 UTC, guyarb commented on dummy
> +a
done

2023-07-18 20:26 UTC, guyarb commented on pkg/network/usm/monitor.go
> +	"syscall"
done

2023-07-18 20:27 UTC, guyarb commented on pkg/network/protocols/http2/protocol.go
> +// - Set the `http_in_flight` map size to the value of the `max_tracked_connection` configuration variable.
done

2023-07-18 20:27 UTC, guyarb commented on pkg/network/protocols/grpc/monitor_test.go
> +	"github.com/DataDog/datadog-agent/pkg/network/protocols"
done

2023-07-19 06:57 UTC, DanielLavie approved these changes

2023-07-19 06:58 UTC, merged