fix: When creating filers we now trim any that begin with '"'
DataDog/datadog-agent pull request #18344
Opened 2023-07-24 16:40 UTC by carlosroman

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-07-25 09:49 UTC, L3n41c requested changes
I think there are some confusion here.

The quotes are not meant to be passed to the agent in the environment variable value.

When the documentation provides a `docker run …` command as an example, it assumes that it would be a command passed to a shell.
That’s the implicit meaning of the leading `$` prompt in

```shell
$ docker run -d --name datadog-agent \
             --cgroupns host \
  […]
```

In shell, quotes are used to prevent the tokenisation of strings containing spaces. But they are not passed to the child process.

If we try to set the environment variable as documented, we can validate that the value doesn’t contain any quote:

```
lenaic@lenaic-agent-dev:~$ docker run -ti --rm -e DD_CONTAINER_EXCLUDE="name:datadog-agent" gcr.io/datadoghq/agent:latest /bin/bash

root@d26088e91c8d:/# echo $DD_CONTAINER_EXCLUDE
name:datadog-agent

root@d26088e91c8d:/# echo ">>>$DD_CONTAINER_EXCLUDE<<<"
>>>name:datadog-agent<<<
```

In order to really put quotes in the value of the environment variable, we need to do some extra effort, which is not what is documented:

```
lenaic@lenaic-agent-dev:~$ docker run -ti --rm -e DD_CONTAINER_EXCLUDE="\"name:datadog-agent\"" gcr.io/datadoghq/agent:latest /bin/bash

root@5eedd902808b:/# echo $DD_CONTAINER_EXCLUDE
"name:datadog-agent"
```

or

```
lenaic@lenaic-agent-dev:~$ docker run -ti --rm -e DD_CONTAINER_EXCLUDE='"name:datadog-agent"' gcr.io/datadoghq/agent:latest /bin/bash

root@8676048ebf0a:/# echo $DD_CONTAINER_EXCLUDE
"name:datadog-agent"
```

So, the `DD_CONTAINER_EXCLUDE` environment variable isn’t supposed to contain any quote to be stripped in the agent code.
If the documentation was suggesting things that would result in having quotes inside `DD_CONTAINER_EXCLUDE`, I think it would be better to fix the doc.
But I don’t think it’s the case here. In the doc example, quotes are consumed by the shell and not passed to docker.

In the case of the docker `compose.yaml` file provided in the description, it’s different : it’s a yaml file, so, there’s no shell interpreter pass. That’s why, with this file, we get quotes inside the environment variable value.

But, if the `compose.yaml` had contain:
```yaml
    environment:
      - "DD_CONTAINER_EXCLUDE=image:datadog/agent:<version>"
```

then, we would have had something similar : the yaml parser would have consumed the quote and we would have got `DD_CONTAINER_EXCLUDE` set to `image:datadog/agent:<version>` and not `"DD_CONTAINER_EXCLUDE` set to `image:datadog/agent:<version>"`.

2023-07-25 17:57 UTC, rtrieu requested changes
Suggestion for some clarity.

2023-07-25 17:57 UTC, rtrieu commented on releasenotes/notes/Fix-AD-container-exclude-include-filter-ad218d5784c91f4a.yaml
> +    the `DD_CONTAINER_EXCLUDE` or `DD_CONTAINER_INCLUDE` environment variable would not work as Agent would not trim `"` from the variable
```suggestion
    the `DD_CONTAINER_EXCLUDE` or `DD_CONTAINER_INCLUDE` environment variable would not work, as the Agent would not trim `"` from the variable,
```

2023-07-25 17:57 UTC, rtrieu commented on releasenotes/notes/Fix-AD-container-exclude-include-filter-ad218d5784c91f4a.yaml
> +    resulting in the following warning in the logs `Container filter "\"name:datadog-agent\"" is unknown, ignoring it. The supported filters are 'image', 'name' and '
```suggestion
    which resulted in the following warning in the logs `Container filter "\"name:datadog-agent\"" is unknown and the variable being ignored. The supported filters are 'image', 'name' and '
```

2023-07-26 09:20 UTC, carlosroman commented
That makes sense, will update the documentation with note about not quoting the value when using Docker Compose.

2023-07-26 09:20 UTC, closed without merging