Use gostreamer for HTTP
DataDog/datadog-agent pull request #18408
Opened 2023-07-26 15:10 UTC by leeavital

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-29 18:05 UTC, estherk15 reviewed
No docs review required

2023-08-30 03:58 UTC, guyarb requested changes
Generally looks great, having couple of suggestions and questions

p.s., please update the PR labels

2023-08-30 03:58 UTC, guyarb commented on pkg/network/encoding/http.go
> +					}
why do we check `code != 0`? it is not possible as we're checking it earlier in the process

2023-08-30 20:40 UTC, leeavital commented on pkg/network/encoding/encoding_test.go
> +		actual.Conns[i].HttpAggregations = expected.Conns[i].HttpAggregations
Fair question! 

It is intentional, and I added a comment explaining why.

2023-08-30 20:40 UTC, leeavital commented on pkg/network/encoding/http_test.go
> +	fmt.Printf("%v", aggregations)
Nope, this was a mistake, removed

2023-08-30 20:40 UTC, leeavital commented on pkg/network/encoding/http.go
> +func (e *httpEncoder) GetHTTPAggregationsAndTags(c network.ConnectionStats, builder *model.ConnectionBuilder) (uint64, map[string]struct{}) {
Good point, I wound up re-naming the field builder since I set a  soft convention that parameters be named `builder`

2023-08-30 20:45 UTC, guyarb approved these changes

2023-09-05 16:19 UTC, hmahmood approved these changes

2023-09-05 20:11 UTC, merged