[CWS] Properly set process exec child for runtime events
DataDog/datadog-agent pull request #18487
Opened 2023-07-31 10:30 UTC by lebauce

### What does this PR do?

Set IsExecChild according to parent's IsThread attribute

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-01 11:40 UTC, safchain commented on pkg/security/security_profile/activity_tree/activity_tree.go
> +			node.Process.IsExecChild = entry.Parent != nil && entry.Ancestor.Parent != nil && entry.Ancestor.Parent.Pid == entry.Process.Pid
Is this still required ?

2023-08-01 11:40 UTC, safchain commented on pkg/security/secl/model/process_cache_entry.go
> +	entry.Process.IsExecChild = !pc.IsThread
IsExecExec

2023-08-01 21:56 UTC, rtrieu requested changes
Some small change requests, but otherwise looks good.

2023-08-01 21:56 UTC, rtrieu commented on docs/cloud-workload-security/backend.schema.json
> +          "description": "Indicates wether the process is an exec following an other exec"
```suggestion
          "description": "Indicates whether the process is an exec following another exec"
```

2023-08-01 21:56 UTC, rtrieu commented on docs/cloud-workload-security/backend.schema.json
> +          "description": "Indicates wether the process is an exec following an other exec"
```suggestion
          "description": "Indicates whether the process is an exec following another exec"
```

2023-08-02 16:08 UTC, rtrieu requested changes
Hi, still seeing one small typo

2023-08-08 17:19 UTC, rtrieu requested changes
Hey sorry not sure if I missed them before, but seeing typos of the same word.

2023-08-08 17:19 UTC, rtrieu commented on docs/cloud-workload-security/backend.schema.json
> +          "description": "Indicates wether the process is an exec following another exec"
```suggestion
          "description": "Indicates whether the process is an exec following another exec"
```

2023-08-08 17:19 UTC, rtrieu commented on docs/cloud-workload-security/backend.schema.json
> +          "description": "Indicates wether the process is an exec following another exec"
```suggestion
          "description": "Indicates whether the process is an exec following another exec"
```

2023-08-08 17:19 UTC, rtrieu commented on pkg/security/secl/model/model.go
> +	IsExecExec bool `field:"-"`         // Indicates wether the process is an exec following another exec
```suggestion
	IsExecExec bool `field:"-"`         // Indicates whether the process is an exec following another exec
```

2023-08-17 12:49 UTC, spikat approved these changes

2024-02-12 17:32 UTC, rtrieu approved these changes
Looks good!

2024-02-13 17:57 UTC, lebauce commented
/merge

2024-02-13 19:23 UTC, merged