Revert "[pkg/otlp] Correctly set serializer exporter capabilities"
DataDog/datadog-agent pull request #18697
Opened 2023-08-08 20:27 UTC by songy23

Reverts DataDog/datadog-agent#18626

With https://github.com/DataDog/opentelemetry-mapping-go/pull/148 and https://github.com/DataDog/datadog-agent/pull/18606 we are no longer mutating the input metrics, thus DataDog/datadog-agent#18626 is not needed.

2023-08-08 20:39 UTC, songy23 commented
Same comment as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25098#issuecomment-1670273429, not sure if we need this revert PR.

2023-08-08 22:32 UTC, urseberry approved these changes

2023-08-09 08:14 UTC, mx-psi submitted a review, later dismissed

2023-08-09 09:42 UTC, mx-psi requested changes
As stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25098#pullrequestreview-1569159399, we would need to refactor https://github.com/DataDog/opentelemetry-mapping-go/blob/0a32610fd1a87d46b4b499bc3e70ef1f23b169e4/pkg/otlp/metrics/metrics_remapping.go#L73 to do this

2023-08-09 13:55 UTC, closed without merging