[pkg/otlp] Default OTLP logs ingestion to disabled
DataDog/datadog-agent pull request #18781
Opened 2023-08-11 21:29 UTC by IbraheemA

### What does this PR do?

Previously, OTLP log ingestion was enabled by default. So, when logs-agent was not enabled as well, the agent would crash (logs-agent needs to be running to use logs ingestion.)

Previously, when `otlp_config: logs: ` was included in the config, logs would be enabled; now `otlp_config: logs: enabled: true` must be specified in full.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-11 22:24 UTC, brett0000FF requested changes
Small docs suggestion for clarity in the release note.

2023-08-11 22:24 UTC, brett0000FF commented on releasenotes/notes/default_otlp_logs_enabled_false-6d98a23f7a76f153.yaml
> +    OTLP logs ingestion is now disabled by default, and otlp_config: logs: enabled: true must be specified to enable
```suggestion
    OTLP logs ingestion is now disabled by default. To enable it, set otlp_config.logs.enabled to true.
```
I think dot notation is a bit easier to read ^

2023-08-13 16:40 UTC, songy23 reviewed
Have you verified:
1. When logs is not present in otlp_config, does the OTel pipeline start successfully
2. The env var can still enable otlp log ingestion

2023-08-14 15:18 UTC, IbraheemA commented
> Have you verified:
> 
> 1. When logs is not present in otlp_config, does the OTel pipeline start successfully
> 2. The env var can still enable otlp log ingestion

Yes, added these to the QA section

2023-08-14 15:50 UTC, brett0000FF approved these changes

2023-08-14 15:57 UTC, songy23 approved these changes

2023-08-14 15:58 UTC, sgnn7 approved these changes

2023-08-14 16:34 UTC, songy23 commented on pkg/otlp/pipeline_validator_serverless.go
> +	if pcfg.LogsEnabled(cfg) {
```suggestion
	if pcfg.LogsEnabled {
```

2023-08-17 18:47 UTC, IvanTopolcic approved these changes

2023-08-17 18:57 UTC, merged