Add k8s health check
DataDog/datadog-agent pull request #18826
Opened 2023-08-15 14:58 UTC by zhuminyi

-->
### What does this PR do?
Port over the logic and check run metrics for the /healthz endpoint from integration-core (python) to datadog-agent

### Motivation
To ease development and improve memory footprint and performance, we eventually want to migrate the entirety of the kubelet python check over here as a corecheck.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-16 21:43 UTC, buraizu requested changes
Thanks, just requesting some minor updates to the release note

2023-08-16 21:43 UTC, buraizu commented on releasenotes/notes/add-healthz-status-check-to-agent-94afeee4b93d4df9.yaml
> +    Add kubelet healthz check (check_run.kubernetes_core.kubelet.check) to agent corecheck to replace old check kubenetes.kubelet.check which is generated from python.
```suggestion
    Add kubelet healthz check (check_run.kubernetes_core.kubelet.check) to the Agent's core checks to replace the old kubernetes.kubelet.check generated from Python.
```

2023-08-17 15:11 UTC, sblumenthal approved these changes
lgtm, great job!

2023-08-17 17:19 UTC, buraizu approved these changes

2023-08-17 18:03 UTC, merged