usm: Fixed payload size calculation
DataDog/datadog-agent pull request #18951
Opened 2023-08-22 13:30 UTC by guyarb

### What does this PR do?

Calculating the payload's real size instead of relying on `skb->len`
Currently fixing a limited scope of functions, as `is_payload_empty` and the calculation of payload length in the protocol dispatcher.
This is meant to fix a bug introduced by removing the check of `is_ack` by #18673 

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

1. Run system probe with usm enabled (http monitoring)
2. Run `curl example.com`
3. Pull the http payloads `sudo curl --unix /opt/datadog-agent/run/sysprobe.sock http://unix/network_tracer/debug/http_monitoring` expect to see the request from above

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-22 19:18 UTC, p-lambert approved these changes
changes LGTM and I don't want to block the PR because we're already on 7.48 release cycle, but please find a way to test the code you're adding since your QA steps are passing even without your change.

2023-08-23 10:51 UTC, nplanel commented
Seems it's missing lot's of `skb->len` changes, shall we use `skbinfo->data_end` everywhere and not relay on skb->len ?

http (http_allow_packet) seems mandatory
`pkg/network/ebpf/c/protocols/http/http.h:    bool empty_payload = skb_info->data_off == skb->len;`

2023-08-23 10:53 UTC, nplanel requested changes
Seems it's missing lot's of skb->len changes, shall we use skbinfo->data_end everywhere and not relay on skb->len ?

http (http_allow_packet) seems mandatory
pkg/network/ebpf/c/protocols/http/http.h:    bool empty_payload = skb_info->data_off == skb->len;

2023-08-23 11:16 UTC, guyarb commented
> Seems it's missing lot's of `skb->len` changes, shall we use `skbinfo->data_end` everywhere and not relay on `skb->len` ?
> 
> http (http_allow_packet) seems mandatory `pkg/network/ebpf/c/protocols/http/http.h: bool empty_payload = skb_info->data_off == skb->len;`

please read again the description of the PR

2023-08-25 13:59 UTC, nplanel approved these changes

2023-08-25 14:03 UTC, nplanel approved these changes

2023-08-25 14:03 UTC, merged