Fix host metadata to correctly reflect running on Windows 11
DataDog/datadog-agent pull request #18952
Opened 2023-08-22 14:11 UTC by julien-lebot

### What does this PR do?
This PR fixes the call to `BrandingFormatString`, previously we were checking for the `err` returned from https://github.com/golang/sys/blob/master/windows/dll_windows.go#L165 but `BrandingFormatString` doesn't return an error, nor sets `LastError`.

### Motivation
Correct OS display in Datadog.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes
Run the Agent on Windows 11 and ensure that in Datadog it displays correctly as Windows 11 and not Windows 10.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-22 14:59 UTC, clarkb7 requested changes

2023-08-22 14:59 UTC, clarkb7 commented on pkg/gohai/platform/platform_windows.go
> +			os, _, _ := procBrandingFormatString.Call(uintptr(unsafe.Pointer(&magicString[0])))
we should check that os isn't 0/NULL

2023-08-22 15:26 UTC, clarkb7 approved these changes

2023-08-22 20:25 UTC, cswatt approved these changes
a grammar fix to release notes. approving so as to not block

2023-08-22 20:25 UTC, cswatt commented on releasenotes/notes/fix-windows-11-host-metadata-06fdf71ccb85e790.yaml
> +    On Windows the host metadata correctly reflects Windows 11 version.
```suggestion
    On Windows, the host metadata correctly reflects the Windows 11 version.
```

2023-08-23 15:22 UTC, pgimalac approved these changes

2023-08-23 20:54 UTC, merged