Add `gce-container-declaration` to default excluded GCE host tags
DataDog/datadog-agent pull request #19009
Opened 2023-08-25 11:47 UTC by tbavelier

### What does this PR do?

* Updates `config.go` to include `gce-container-declaration` in the list of GCE host tags that are excluded by default
* Updates `config_template.yaml` to reflect the current list of excluded default tags

### Motivation

* Support case where a customer was seeing their logs enriched with this tag since it was a host-level tag, which can contain sensitive data (docker run command, where credentials could be present) : 
> Compute Engine stores your container settings in [instance metadata](https://cloud.google.com/compute/docs/storing-retrieving-metadata) under the gce-container-declaration metadata key.

per https://cloud.google.com/compute/docs/containers/deploying-containers#how_deploying_containers_on_works
<img width="842" alt="Image 2023-08-25 at 1 39 42 PM" src="https://github.com/DataDog/datadog-agent/assets/97530782/a0ece5fb-8afb-4cfe-8cd7-b614f07622ba">
* While doing the PR, I noticed the `config_template.yaml` file was not properly reflecting the current list of excluded tags, so took the opportunity to update it and order it alphabetically

### Possible Drawbacks / Trade-offs

N/A

### Describe how to test/QA your changes

1. Deploy a GCE VM with a container optimized OS and a container with a docker run command : https://cloud.google.com/compute/docs/containers/deploying-containers#how_deploying_containers_on_works. Metadata access should be allowed.
2. Deploy the Agent with the installation script.
3. Ensure the metadata GCE tag `gce-container-declaration` is absent from the list of host tags in `sudo datadog-agent status`.
4. Verify other GCE excluded tags are absent

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-08-25 15:44 UTC, urseberry approved these changes

2023-08-28 10:12 UTC, hush-hush requested changes
Looks good, added a quick comment on the releasenote. Since it is aimed at customers we should add as much context as possible.

2023-08-28 10:12 UTC, hush-hush commented on releasenotes/notes/exclude_gce_container_declaration_host_tag-395b1829e41ba26b.yaml
> +    Add `gce-container-declaration` to default GCE excluded host tags.
```suggestion
    Add ``gce-container-declaration`` to default GCE excluded host tags. See ``exclude_gce_tags`` configuration settings for more.
```

2023-08-28 11:52 UTC, hush-hush approved these changes

2023-08-29 16:00 UTC, merged