usm: http2: use gostreamer
DataDog/datadog-agent pull request #19533
Opened 2023-09-18 18:20 UTC by guyarb

### What does this PR do?
Applying https://github.com/DataDog/datadog-agent/pull/18408 changes on http2

### Motivation
Performance improvements 

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-09-18 19:39 UTC, hmahmood approved these changes

2023-09-21 09:05 UTC, Yumasi requested changes
Just a small comment, otherwise looks good

2023-09-21 09:31 UTC, guyarb commented on pkg/network/encoding/format.go
> +	_, _ = http2Encoder.GetHTTP2AggregationsAndTags(conn, builder)
it's not a side effect
we're not loading into memory the marshaled connections, but instead directly writing it into the writer/builder

2023-09-22 08:39 UTC, Yumasi commented on pkg/network/encoding/format.go
> +	_, _ = http2Encoder.GetHTTP2AggregationsAndTags(conn, builder)
My main point was that the name does not convey what the function actually does.

2023-09-22 13:42 UTC, guyarb commented on pkg/network/encoding/format.go
> +	_, _ = http2Encoder.GetHTTP2AggregationsAndTags(conn, builder)
How about `GenerateHTTP2AggregationsAndTags`?

2023-09-26 10:33 UTC, Yumasi approved these changes

2023-09-26 13:35 UTC, merged