(rc) document inventories_checks_configuration_enabled being enabled …
DataDog/datadog-agent pull request #19803
Opened 2023-09-28 12:49 UTC by arbll

…by default

### What does this PR do?

`inventories_checks_configuration_enabled` is now set to `true` by default since https://github.com/DataDog/datadog-agent/pull/19485.

Document it in the release note and config template.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-09-28 13:49 UTC, ogaca-dd approved these changes

2023-09-28 14:27 UTC, hush-hush requested changes

2023-09-28 14:27 UTC, hush-hush commented on releasenotes/notes/send-integration-config-default-05a00f3e99612e6b.yaml
> +    soon be available in the Datadog UI. The configurations are scrubbed of any sensitive information.
```suggestion
    The agent now sends its integration / checks configuration to the backend by default. They will
    soon be available in the Datadog UI. The configurations are scrubbed of any sensitive information.
    Set `inventories_checks_configuration_enabled` to false to disable this feature.
```

2023-09-28 21:40 UTC, alai97 approved these changes
Suggestions to the release note!

2023-09-28 21:40 UTC, alai97 commented on pkg/config/config_template.yaml
> +## By default the Agent sends its integrations / checks configuration to Datadog to be displayed in the UI.
```suggestion
## By default the Agent sends its integrations and checks configuration to Datadog to be displayed in the UI.
```

2023-09-28 21:40 UTC, alai97 commented on releasenotes/notes/send-integration-config-default-05a00f3e99612e6b.yaml
> +    The agent now sends its integration / checks configuration to the backend by default. They will
```suggestion
    The Agent now sends its integration and checks configuration to the backend by default. They will
```

2023-09-28 21:40 UTC, alai97 commented on releasenotes/notes/send-integration-config-default-05a00f3e99612e6b.yaml
> +    soon be available in the Datadog UI. The configurations are scrubbed of any sensitive information.
```suggestion
   be available in the Datadog UI. The configurations are scrubbed of any sensitive information.
```

2023-09-28 22:05 UTC, sgnn7 approved these changes
+1 on Austin's comments but overall LGTM

2023-10-03 14:05 UTC, hush-hush approved these changes
Small nit-pick, feel free to merge after :+1:

2023-10-03 14:05 UTC, hush-hush commented on pkg/config/config_template.yaml
> +## By default the Agent sends its integrations and checks configuration to Datadog to be displayed in the UI.
I think we use `integration` for customers
```suggestion
## By default the Agent sends the configuration for integrations being run to Datadog to be displayed in the UI.
```

2024-01-24 18:49 UTC, closed without merging