fix panic when log_level >= error
DataDog/datadog-agent pull request #1981
Opened 2018-07-12 16:09 UTC by arbll

### What does this PR do?

Another option to fix the issue described in https://github.com/DataDog/datadog-agent/pull/1977

2018-07-12 16:27 UTC, hush-hush requested changes

2018-07-12 17:05 UTC, arbll commented on pkg/util/log/log_test.go
> +func TestFormatErrorf(t *testing.T) {
Added some testing for a few scenarios, was it what you had in mind ?

2018-07-12 18:20 UTC, hush-hush submitted a review, later dismissed

2018-07-13 11:24 UTC, truthbk reviewed
Almost good, but there's a couple of nits

2018-07-13 11:50 UTC, truthbk approved these changes
👍

2018-07-13 12:23 UTC, merged