feat(serverless): process API Gateway Lambda Authorizer payloads
DataDog/datadog-agent pull request #20017
Opened 2023-10-10 08:28 UTC by RomainMuller

### What does this PR do?

Adds support for API Gateway Lambda Authorizer payloads, tracking the payload contents as well as HTTP trace tagging that can be extracted from the payload (varies depending on whether the authorizer is typed `TOKEN` or `REQUEST`).

### Motivation

This provides ability for ASM signals to be found (and possibly blocked) in API Gateway Lambda Authorizers.

### Additional Notes

The `TOKEN` payload provides very little information, in particular it misses the source IP address and does not specify the header name that it got the token off of. The implementation blindly reports this as `Authorization: <token>` and does not report a source IP address (the later might make it difficult to effectively block attackers at the authorizer level).

### Describe how to test/QA your changes

Deployed a custom build of the extension layer to an API Gateway (v1) endpoint and used both the `TOKEN` and `REQUEST` payloads to trigger ASM signals (successfully).

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-10-10 17:31 UTC, estherk15 approved these changes

2023-10-11 08:43 UTC, Julio-Guerra requested changes

2023-10-11 16:23 UTC, purple4reina approved these changes

2023-10-12 08:48 UTC, RomainMuller commented on pkg/serverless/appsec/httpsec/proxy.go
> +		event = &events.APIGatewayCustomAuthorizerRequestTypeRequest{}
Yep, I've noticed the same thing and it definitely bothers me as well. I fought the urge to overhaul this entirely as it'd have blown out the scope of this PR way beyond the intent...

2023-10-12 09:11 UTC, Julio-Guerra approved these changes

2023-10-12 09:12 UTC, merged

2023-10-12 17:20 UTC, purple4reina commented on pkg/serverless/appsec/httpsec/proxy.go
> +		event = &events.APIGatewayCustomAuthorizerRequestTypeRequest{}
Well, I give you my full support if you wish to do the refactor in a different PR. 😄