omnibus: remove pg_config during finalize step
DataDog/datadog-agent pull request #20149
Opened 2023-10-16 07:43 UTC by chouquette

### What does this PR do?

This PR is the continuation of https://github.com/DataDog/omnibus-software/pull/481
We can only remove pg_config after psycopg has been built

### Motivation

This binary isn't used for anything once psycopg is built, so we don't need to ship it
APL-2361

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-10-18 15:45 UTC, chouetz approved these changes

2023-10-18 15:45 UTC, chouetz commented on release.json
> +        "OMNIBUS_SOFTWARE_VERSION": "chouquette/remove_pgsql_bin",
You can revert this change now :)

2023-10-18 15:50 UTC, chouetz reviewed
You have failures in the CI as well
```
[HealthCheck] E | 2023-10-18T07:48:22+00:00 | The following libraries have unsafe or unmet dependencies:
    --> /opt/datadog-agent/embedded/lib/python3.9/site-packages/pyodbc.cpython-39-aarch64-linux-gnu.so
    DEPENDS ON: libodbc.so.2    
```
Could you have removed too many things?

2023-10-18 15:51 UTC, chouetz requested changes
Can you please double check the CI error?

2023-10-19 07:43 UTC, chouquette commented
> Can you please double check the CI error?

I believe this is because I needed to rebase to include `6c04f4cd63131da32a8a400b7fed18da8526f826`, this is now done, let's see :)

2023-10-20 12:43 UTC, chouetz approved these changes

2023-10-20 12:51 UTC, merged