change http2_in_flight from LRU map to HASH map
DataDog/datadog-agent pull request #20393
Opened 2023-10-25 13:09 UTC by amitslavin

### What does this PR do?

Changs the `http2_in_flight` from LRU map to HASH map.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-11-07 23:23 UTC, guyarb requested changes

2023-11-07 23:23 UTC, guyarb commented on pkg/network/protocols/http2/protocol.go
> +		log.Errorf("error getting http_in_flight map: %s", err)
```suggestion
		log.Errorf("error getting %q map: %s", inFlightMap, err)
```

2023-11-07 23:23 UTC, guyarb commented on pkg/network/protocols/http2/protocol.go
> +	mapCleaner, err := ddebpf.NewMapCleaner(http2Map, new(netebpf.ConnTuple), new(EbpfTx))
```suggestion
	mapCleaner, err := ddebpf.NewMapCleaner(http2Map, new(http2StreamKey), new(EbpfTx))
```

2023-11-07 23:23 UTC, guyarb commented on pkg/network/protocols/http2/protocol.go
> +	ttl := p.cfg.HTTP2IdleConnectionTTL.Nanoseconds()
```suggestion
	ttl := p.cfg.HTTPIdleConnectionTTL.Nanoseconds()
```

2023-11-07 23:23 UTC, guyarb commented on pkg/network/protocols/http2/protocol.go
> +	mapCleaner.Clean(p.cfg.HTTP2MapCleanerInterval, func(now int64, key, val interface{}) bool {
```suggestion
	mapCleaner.Clean(p.cfg.HTTPMapCleanerInterval, func(now int64, key, val interface{}) bool {
```

2023-11-07 23:23 UTC, guyarb commented on pkg/network/config/config.go
revert

2023-11-08 13:42 UTC, val06 commented
can you fill the "Motivation" section of the PR?

2023-11-08 13:46 UTC, guyarb approved these changes

2023-11-08 15:18 UTC, merged