[wip] jmxfetch origin metrics
DataDog/datadog-agent pull request #20567
Opened 2023-11-01 14:25 UTC by rayz

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-11-01 20:26 UTC, scottopell requested changes

2023-11-01 20:26 UTC, scottopell commented on pkg/metrics/metricsource.go
> +func CheckNameToMetricSource(name string) MetricSource {
Not necessary now, but once we have core checks and python checks, it will be useful for clarity

2023-11-01 20:26 UTC, scottopell commented on pkg/metrics/metricsource.go
> +	case "dogstatsd":
Don't think dogstatsd belongs here

2023-11-01 20:26 UTC, scottopell commented on pkg/metrics/metricsource.go
> +	case "jmx-custom-check":
the check name will never have this value will it?

2023-11-01 20:26 UTC, scottopell commented on pkg/metrics/metricsource.go
> +		return MetricSourceJmxCustom
This `default` case means that this function needs to be specific to JMX

2023-11-01 20:26 UTC, scottopell commented on comp/dogstatsd/server/enrich.go
> +			metricSource = metrics.CheckNameToMetricSource(checkName)
maybe add a unit test for this as well. At least the "don't forward `jmx_check_name` as part of the metric" behavior

2023-11-02 20:13 UTC, scottopell requested changes

2023-11-02 20:13 UTC, scottopell commented on comp/dogstatsd/server/enrich.go
>  		} else if strings.HasPrefix(tag, jmxTagPrefix) {
On further thought, we should remove the old way of checking jmx in favor of this new tag.
so lets get rid of `jmxTagPrefix` and the associated check altogether. It doesn't offer us anything that `jmx_chec_name` doesn't.

2023-11-03 15:34 UTC, estherk15 approved these changes

2023-11-09 17:00 UTC, scottopell approved these changes
Change looks good!

2023-11-09 18:15 UTC, merged