[USMON-623] Mitigate races causing Go TLS test failures
DataDog/datadog-agent pull request #20829
Opened 2023-11-13 19:22 UTC by p-lambert

### What does this PR do?

Mitigates 2 race scenarios currently causing Go TLS test flakiness:
* Race in `connection_protocol` deletion;
* Race in HTTP termination code, where FIN packets are processed before uprobe programs handling the response data;

### Motivation

### Additional Notes

There is an internal document where those issues are explained in more detail: https://datadoghq.atlassian.net/wiki/spaces/UT/pages/3275687462/Go+TLS+test+flakiness

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-11-14 09:34 UTC, guyarb requested changes

2023-11-14 09:34 UTC, guyarb commented on pkg/network/ebpf/c/tracer/stats.h
> +static __always_inline void mark_protocol_direction(conn_tuple_t *pre_norm_tuple, conn_tuple_t *norm_tuple, protocol_stack_t *protocol_stack) {
please document the function

2023-11-17 20:28 UTC, p-lambert commented on pkg/network/ebpf/c/protocols/http/http.h
> +static __always_inline bool is_uprobe_context(skb_info_t *skb_info) {
yeah, this is an exception that I thought it was fine to leave out of the comments
it doesn't really matter in my case (I want to handle the case where we're handling a request or response segment).
Do you think it's fine to keep `is_uprobe_context` as it is and add a comment noting this edge-case?

2023-11-18 07:21 UTC, guyarb commented on pkg/network/ebpf/c/protocols/http/http.h
> +static __always_inline bool is_uprobe_context(skb_info_t *skb_info) {
I think you can easily improve the `is_uprobe_context` by 
`return skb_info==NULL || skb_info->data_end == 0;`
That will work for both cases without any problem

2023-11-20 19:53 UTC, p-lambert commented on pkg/network/ebpf/c/protocols/http/http.h
> +static __always_inline bool is_uprobe_context(skb_info_t *skb_info) {
Good idea, I'll update it

2023-11-21 03:22 UTC, guyarb approved these changes

2023-11-28 16:47 UTC, hmahmood approved these changes
Only for one file owned by Networks

2023-11-29 19:22 UTC, merged