inventory: report feature_cspm_host_benchmarks_enabled
DataDog/datadog-agent pull request #20886
Opened 2023-11-15 07:36 UTC by lebauce

### What does this PR do?

Report whether compliance host benchmarks are enabled to the inventory.

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-11-15 21:43 UTC, sgnn7 requested changes

2023-11-15 21:43 UTC, sgnn7 commented on comp/metadata/inventoryagent/inventoryagent.go
> +	ia.data["feature_cspm_host_benchmarks_enabled"] = ia.conf.GetBool("compliance_config.host_benchmarks.enabled")
@lebauce Can you also update the [README](https://github.com/DataDog/datadog-agent/tree/main/comp/metadata/inventoryagent#format)?

2023-11-15 21:43 UTC, sgnn7 commented on comp/metadata/inventoryagent/inventoryagent.go
> +	ia.data["feature_cspm_host_benchmarks_enabled"] = ia.conf.GetBool("compliance_config.host_benchmarks.enabled")
There's also tests missing for the added functionality.

2023-11-21 13:58 UTC, hush-hush approved these changes

2023-11-21 14:03 UTC, sgnn7 approved these changes

2023-11-23 15:40 UTC, merged