[Fleet] Doc update for agent config sources
DataDog/datadog-agent pull request #20891
Opened 2023-11-15 10:08 UTC by julesmcrt

### What does this PR do?

* Lower `inventories_min_interval` to 1min https://github.com/DataDog/datadog-agent/pull/19669
* Add new fields to the inventories payload https://github.com/DataDog/datadog-agent/pull/20591

### Motivation
Keep the doc up to date with the code

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-11-15 10:18 UTC, hush-hush requested changes

2023-11-15 10:18 UTC, hush-hush commented on comp/metadata/inventoryagent/README.md
> +        "provided_configuration": "api_key: \"***************************aaaaa\"\ncheck_runners: 4\ncmd.check.fullsketches: false\ncontainerd_namespace: []\ncontainerd_namespaces: []\npython_version:
Please also update the `Format` section (line 35)

2023-11-15 10:18 UTC, hush-hush commented on comp/metadata/inventoryagent/README.md
> +update every minute (see `inventories_min_interval`).
The interval is still 5 minutes I think: https://github.com/DataDog/datadog-agent/blob/main/comp/metadata/internal/util/inventory_payload.go#L71

2023-11-17 10:12 UTC, julesmcrt commented on comp/metadata/inventoryagent/README.md
Sure thing!

2023-11-28 13:37 UTC, hush-hush approved these changes

2023-11-28 13:38 UTC, hush-hush commented on comp/metadata/inventoryagent/README.md
> +        "cli_configuration": "log_level: \"warn\""
```suggestion
        "provided_configuration": "api_key: \"***************************aaaaa\"\ncheck_runners: 4\ncmd.check.fullsketches: false\ncontainerd_namespace: []\ncontainerd_namespaces: []\npython_version: \"3\"\ntracemalloc_debug: false\nlog_level: \"warn\"",
        "file_configuration": "check_runners: 4\ncmd.check.fullsketches: false\ncontainerd_namespace: []\ncontainerd_namespaces: []\npython_version: \"3\"\ntracemalloc_debug: false",
        "environment_variable_configuration": "api_key: \"***************************aaaaa\"",
        "remote_configuration": "log_level: \"debug\"",
        "cli_configuration": "log_level: \"warn\""
```

2023-11-28 14:44 UTC, pgimalac approved these changes

2023-11-28 14:44 UTC, pgimalac commented on comp/metadata/inventoryagent/README.md
> -        "cloud_provider": "AWS",
Thanks :)

2023-11-28 16:05 UTC, merged