improve the `defining a component` documentation
DataDog/datadog-agent pull request #21248
Opened 2023-12-01 16:47 UTC by GustavoCaso

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-12-01 18:21 UTC, hush-hush approved these changes

2023-12-01 18:21 UTC, hush-hush commented on docs/components/defining-components.md
> +func newMockFoo(deps dependencies) Component {
We don't need to repeat the package name in its methods:
```suggestion
func newMock(deps dependencies) Component {
```

2023-12-04 07:31 UTC, urseberry requested changes

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +### You can use the invoke task `inv new-component comp/<bundleName>/<component>` to generate a scaffold for your new component.
```suggestion
You can use the invoke task `inv new-component comp/<bundleName>/<component>` to generate a scaffold for your new component.
```
This sentence instructs the user. It should not be a section heading.

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +      The `Module` is defined in a separate package from the component, allowing a package to just import the interface without having to import that entire implementation..
```suggestion
      The `Module` is defined in a separate package from the component, allowing a package to import the interface without having to import the entire implementation.
```

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +The Component interface is implemented in the file ``comp/<bundleName>/<component>/<component>impl/<component>.go`. Also, the `Module` definition.
```suggestion
The Component interface is implemented in the file `comp/<bundleName>/<component>/<component>impl/<component>.go` and the `Module` definition. 
```
The second sentence in this line is a fragment. I made my best guess as to the meaning and fixed it. Please make further edits if I missed the intended meaning.

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +The Module defintion function **must** be private.
```suggestion
The Module definition function **must** be private.
```

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +The completed ``comp/<bundleName>/<component>/<component>impl/<component>.go` looks like this:
```suggestion
The completed `comp/<bundleName>/<component>/<component>impl/<component>.go` looks like this:
```

2023-12-04 07:31 UTC, urseberry commented on docs/components/defining-components.md
> +  Such assumptions are difficult to verify, so where possible try to make every method callable concurrently, at all times.
```suggestion
  Such assumptions are difficult to verify. Where possible, try to make every method callable concurrently, at all times.
```

2023-12-04 16:51 UTC, urseberry approved these changes
Found one more formatting issue. Approving so I don't hold up the PR.

2023-12-04 16:51 UTC, urseberry commented on docs/components/defining-components.md
> +  * `comp/<bundleName>/<component>/<component>impl/<component>.go
```suggestion
  * `comp/<bundleName>/<component>/<component>impl/<component>.go`
```

2023-12-11 11:12 UTC, merged