usm: http2: Fix http2_frames_parser cleanup
DataDog/datadog-agent pull request #21267
Opened 2023-12-04 12:02 UTC by guyarb

### What does this PR do?

When we're failing to get the telemetry object, we are at a point in which we already have the context of an iteration, so we need to delete it instead of leaking it and returning.

### Motivation

Fixing the cleanup

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-12-04 14:01 UTC, Yumasi approved these changes

2023-12-04 15:06 UTC, amitslavin requested changes

2023-12-04 15:07 UTC, amitslavin commented on pkg/network/ebpf/c/protocols/http2/decoding.h
> +        goto delete_iteration;
One more thing, if we fail for some reason to get the map do we want to drop the current iteration? we can still try and process regardless to the telemetry

2023-12-04 17:25 UTC, guyarb commented on pkg/network/ebpf/c/protocols/http2/decoding.h
> +        goto delete_iteration;
> why this change is only in this lookup? we are trying to get this map in 2 more places

this is the only tail call that has a special termination logic

> One more thing, if we fail for some reason to get the map do we want to drop the current iteration? we can still try and process regardless to the telemetry

It is not tied to "failing to get telemetry map", but calling the proper cleanup for the tail call

2023-12-05 08:38 UTC, amitslavin approved these changes

2023-12-05 08:45 UTC, merged