Guy.arbitman/usmon 658 http2 user mode dynamic table
DataDog/datadog-agent pull request #21521
Opened 2023-12-12 22:29 UTC by guyarb

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2023-12-18 11:20 UTC, amitslavin requested changes

2023-12-18 11:50 UTC, amitslavin commented
Adding here a comment for us to remember adding load test results and dogfooding

2023-12-21 11:00 UTC, guyarb commented on pkg/network/protocols/http2/model_linux.go
> +	buf := make([]byte, 2*maxHTTP2Path)
addressed in https://github.com/DataDog/datadog-agent/pull/21701

2023-12-21 11:01 UTC, guyarb commented on pkg/network/ebpf/c/protocols/http2/decoding.h
> +    bool dummy_value = true;
the value is not important (it can be false as well), we only for the existence in the map

2023-12-21 11:01 UTC, guyarb commented on pkg/network/protocols/http2/dynamic_table.go
> +	dummyValue := true
the value is not important (it can be false as well), we only for the existence in the map

2023-12-21 13:12 UTC, guyarb commented on pkg/network/ebpf/c/protocols/http2/decoding-defs.h
> +#define HTTP_ROOT_PATH_INDEX    0xffffffffffffff00
done

2024-01-22 03:44 UTC, closed without merging