Allow custom configuration for debugger diagnostics proxy
DataDog/datadog-agent pull request #22306
Opened 2024-01-24 12:48 UTC by cimi

### What does this PR do?

This PR allows custom configuration of the Live Debugger / Dynamic Instrumentation diagnostics proxy endpoint in the trace agent, in the same way we can configure the debugger proxy endpoint which forwards dynamic logs.

### Motivation

In environments where we publish data to multiple datacenters, the debugger diagnostics endpoint uses the default api key which is not necessarily the same one as for the default intake URL.

A possible solution would have been to reuse the API key set for the debugger proxy endpoint, since diagnostics and dynamic logs should always go to the same datacenter. For completeness, we allow the same configuration settings on the diagnostics endpoint like we do for the debugger proxy and the symdb proxy.

We do not dual / multi-publish debugger data at the moment, everything goes to a single datacenter (which is expected to be the datacenter the service is running in).

### Possible Drawbacks / Trade-offs

N/A this is adding new functionality. This functionality should only be used on the Datadog backend.

### Describe how to test/QA your changes

Added new unit tests, they all pass.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2024-01-24 12:56 UTC, ojung approved these changes
Thanks, looking good from Dynamic Instrumentation / debugger
 perspective.

2024-01-25 09:25 UTC, ogaca-dd approved these changes

2024-01-30 16:31 UTC, ajgajg1134 requested changes
Overall looks good for trace-agent. Is there any documentation that needs to be updated here? Is this configuration something that customers will be using? If so can you add a changelog for this so that it's easy to determine from the release notes which version of the agent added support for these new variables?

2024-01-30 16:41 UTC, cimi commented
> Overall looks good for trace-agent. Is there any documentation that needs to be updated here? Is this configuration something that customers will be using? If so can you add a changelog for this so that it's easy to determine from the release notes which version of the agent added support for these new variables?

Thanks for reviewing! AFAIK these configurations are not intended / used by customers. We use them internally when publishing data to multiple DCs.

Here's a similar PR that didn't add any other docs except the release note: https://github.com/DataDog/datadog-agent/pull/16409 

I'll add a release note here too :+1:

2024-01-30 17:05 UTC, ajgajg1134 approved these changes

2024-01-30 17:57 UTC, maycmlee approved these changes
Small nit, but approving.

2024-01-30 17:57 UTC, maycmlee commented on releasenotes/notes/dynamic-instrumentation-diagnostics-dual-publishing-c23591af95b397d0.yaml
> +    Add DD_APM_DEBUGGER_DIAGNOSTICS_DD_URL, DD_APM_DEBUGGER_DIAGNOSTICS_API_KEY
```suggestion
    Add DD_APM_DEBUGGER_DIAGNOSTICS_DD_URL, DD_APM_DEBUGGER_DIAGNOSTICS_API_KEY,
```

2024-01-31 10:41 UTC, cimi commented
/merge

2024-01-31 12:01 UTC, merged