[windows] add implementation of getSystemFQDN() for Windows
DataDog/datadog-agent pull request #2233
Opened 2018-08-30 19:21 UTC by derekwbrown

companion doc PR https://github.com/DataDog/datadog-agent/pull/2250

2018-08-31 10:25 UTC, arbll submitted a review, later dismissed
LGTM,

https://docs.microsoft.com/en-us/windows/desktop/api/winsock/ns-winsock-hostent

hostent.Name should return the FQDN.

2018-08-31 10:38 UTC, olivielpeau requested changes
In general, when making a change that could potentially change the canonical hostname reported by the Agent (such as this change), we have to be very careful of the impact on existing users.

In this specific case, I think we should use a different config flag for this. Explanation:

The `hostname_fqdn` flag, when enabled, is meant to reproduce the behavior of Agent v5 wrt hostname resolution, and we want to switch the default to `true` at some point in the future (see https://github.com/DataDog/datadog-agent/blob/master/docs/agent/hostname-resolution.md).

On Windows, Agent v5 never used the FQDN (as returned by the `GetHostByName` syscall) as the Agent hostname, so if we introduce this change as-is, and still recommend users to use `hostname_fqdn: true` when upgrading to v6, the hostname reported will change, which is undesirable.

Whereas, if we use a different config flag (disabled by default for now), we can ask windows users who want the new behavior to enable the flag, while users upgrading from Agent v5 will keep their hostnames unchanged.

2018-08-31 18:01 UTC, olivielpeau submitted a review, later dismissed
just nits, other than that LGTM

2018-08-31 18:01 UTC, olivielpeau commented on releasenotes/notes/add-fqdn-support-windows-5a9b960c9df7c7aa.yaml
> +    host reported by DataDog will be the fully qualified hostname.
nit: correct case is `Datadog` :p

2018-08-31 18:01 UTC, olivielpeau commented on pkg/util/hostname.go
> +			log.Warnf("The agent resolved your hostname as '%s', and will be reported this way maintain compatibility with version 5. To enable reporting as %s, please enable the `hostname_fqdn` flag in the c
missing word: `this way to maintain`

2018-09-03 10:05 UTC, olivielpeau submitted a review, later dismissed
Addressed the nits, this should be ready for a merge

2018-09-03 10:18 UTC, arbll reviewed
Two small nits

2018-09-03 10:41 UTC, arbll approved these changes

2018-09-03 11:07 UTC, merged