[Doc] Add linters documentation
DataDog/datadog-agent pull request #22613
Opened 2024-02-06 13:11 UTC by amenasria

### What does this PR do?

This PR adds some documentation about the linters we're using on the datadog-agent repository.

### Motivation

Better developer experience.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2024-02-06 13:16 UTC, KevinFairise2 approved these changes

2024-02-06 17:47 UTC, buraizu requested changes
Thanks for the PR, I left some mostly minor suggestions, but also reordered the last section a bit for clarity. Let me know any questions or feedback!

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +Welcome to our linters documentation ! Linters are tools that check our source code for errors, bugs, and stylistic inconsistencies. They're essential for maintaining code quality and consistency.
```suggestion
Welcome to the Datadog Agent linters documentation! Linters are tools that check our source code for errors, bugs, and stylistic inconsistencies. They're essential for maintaining code quality and consistency.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +Here are the linters we're using on the datadog-agent repository depending on the language:
```suggestion
Here are the linters used on the datadog-agent repository depending on the language:
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +The `linters` key define the list of linters we're using:
```suggestion
The `linters` key defines the list of linters we're using:
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +To run the linters locally run `inv lint-go`.
```suggestion
To run the linters locally, run `inv lint-go`.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +> In your code, you can ignore a lint on line by prepending it with [the nolint directive](https://golangci-lint.run/usage/false-positives/#nolint-directive) e.g  `//nolint:linter_name`.
```suggestion
> In your code, you can ignore linter issues on a line by prepending it with [the nolint directive](https://golangci-lint.run/usage/false-positives/#nolint-directive), for example,  `//nolint:linter_name`.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +- [vulture](https://github.com/jendrikseipp/vulture) to find unused code.
```suggestion
- [flake8](https://flake8.pycqa.org/en/latest), a style linter.
- [black](https://black.readthedocs.io/en/stable/), a code formatter.
- [isort](https://pycqa.github.io/isort/), to sort the imports.
- [vulture](https://github.com/jendrikseipp/vulture), to find unused code.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +To run the linters locally run `inv lint-python`.
```suggestion
To run the linters locally, run `inv lint-python`.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +> In your code, you can ignore a lint on line by prepending it with `# noqa: error_code`.
```suggestion
> In your code, you can ignore linter issues on a line by prepending it with `# noqa: error_code`.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +### Go Q&A
```suggestion
### Go
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +A: This could come from several reasons:
```suggestion
A: This could have several causes:
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +- Your tools versions are not aligned with ours:
```suggestion
- Your tool versions are not aligned with ours:
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +- You're testing OS specific code, running locally the linters will only get the results for your local OS.
```suggestion
- You're testing OS specific code; running locally, the linters only get the results for your local OS.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +- You didn't run `inv tidy-all` in the repository making some dependencies in the remote env outdated compare to your local env.
```suggestion
- You didn't run `inv tidy-all` in the repository, making some dependencies in the remote env outdated compared to your local env.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +At some point we wanted to introduce the `revive` linter in th codebase. It was burdensome because enabling it made hundreds of errors appear in the CI. [We hence started using the `new-from-rev` par
```suggestion
Introducing the `revive` linter in the codebase caused hundreds of errors to appear in the CI. As such, [the `new-from-rev` parameter](https://github.com/DataDog/datadog-agent/blob/fcb19ce078e7969d285565beec5d374c5fd623e1/.golangci.yml#L65-L68) was added to only display linter issues from changes made after the commit that enabled `revive`. [See the Golang documentation](https://golangci-lint.run/usage/faq/#how-to-integrate-golangci-lint-into-large-project-with-thousands-of-issues) for more information.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +Let's say I have a legacy file hello.go with 100 lints (i.e linter errors). The new-from-rev parameter will silence them all. But if I rename this file to hello_world.go or move it to another folder
```suggestion
In a scenario where you have a legacy file hello.go with 100 linter issues, the new-from-rev parameter removes them all. But if you rename the file to hello_world.go, or move it to another folder, all the linter issues reappear. See [issue 4349](https://github.com/golangci/golangci-lint/issues/4349) in the golangci repo for more information.
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +For Go we're using [golangci-lint](https://golangci-lint.run/), a Go linters aggregator. Its configuration is defined [in the .golangci.yml file](https://github.com/DataDog/datadog-agent/blob/main/.g
```suggestion
For Go, we're using [golangci-lint](https://golangci-lint.run/), a Go linters aggregator. Its configuration is defined [in the .golangci.yml file](https://github.com/DataDog/datadog-agent/blob/main/.golangci.yml).
```

2024-02-06 17:47 UTC, buraizu commented on docs/dev/linters.md
> +For Python we're using ([see invoke task](https://github.com/DataDog/datadog-agent/blob/dffd3262934a5540b9bf8e4bd3a743732637ef37/tasks/linter_tasks.py/#L17-L33)):
```suggestion
For Python, we're using ([see invoke task](https://github.com/DataDog/datadog-agent/blob/dffd3262934a5540b9bf8e4bd3a743732637ef37/tasks/linter_tasks.py/#L17-L33)):
```

2024-02-08 17:12 UTC, buraizu approved these changes

2024-02-08 19:37 UTC, merged