Guy.arbitman/migrate sockfd to usm
DataDog/datadog-agent pull request #22634
Opened 2024-02-07 08:23 UTC by guyarb

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2024-02-07 15:39 UTC, hmahmood approved these changes

2024-02-08 12:40 UTC, nplanel approved these changes

2024-02-08 12:59 UTC, DanielLavie requested changes

2024-02-08 12:59 UTC, DanielLavie commented on pkg/network/ebpf/c/protocols/sockfd-probes.h
> +    // Copy map value to stack before re-using it (needed for Kernel older kernels)
```suggestion
    // Copy map value to stack before re-using it (needed for older kernels)
```

2024-02-08 13:00 UTC, DanielLavie approved these changes

2024-02-08 13:08 UTC, guyarb commented
/merge

2024-02-08 15:05 UTC, merged