usm: ebpf: Automatically set max active limit on kretprobes
DataDog/datadog-agent pull request #22641
Opened 2024-02-07 12:20 UTC by guyarb

### What does this PR do?

For every kretprobe in usm, we automatically set its max active limit to 128, unless explicitly was set

### Motivation

Ensure all kretprobes has a limit.

### Additional Notes
Inspired by NPM implementation - https://github.com/DataDog/datadog-agent/blob/67c9f3c029edf864909b5ecd9a6b5c8111a899bd/pkg/network/tracer/connection/kprobe/manager.go#L119-L121

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2024-02-07 17:44 UTC, brycekahle commented on pkg/network/usm/ebpf_main.go
> +			probe.KProbeMaxActive = maxActive
You can set the manager option `DefaultKProbeMaxActive` instead of doing this.

2024-02-08 08:19 UTC, val06 requested changes

2024-02-08 08:19 UTC, val06 commented on pkg/network/usm/ebpf_javatls.go
> -			KProbeMaxActive: maxActive,
setting this to const value can actually decrease the [default size](https://elixir.bootlin.com/linux/latest/source/kernel/kprobes.c#L2227) (consider a host with a large number of CPUs).

maybe switch to `max(num_of_cpus*2, max_active)`?

P.S: in older kernel versions the maxactive was [set](https://elixir.bootlin.com/linux/v5.2/source/kernel/kprobes.c#L1908) based on the `[CONFIG_PREEMPT](https://elixir.bootlin.com/linux/v5.2/K/ident/CONFIG_PREEMPT)` flag

2024-02-08 09:23 UTC, val06 commented on pkg/network/usm/ebpf_javatls.go
> -			KProbeMaxActive: maxActive,
we can track (and compare in a load-test) the `nmissed` field of that kprobe. I'll approve this PR, as i agree with "currently it feels as an overkill".

But do consider making that test

2024-02-08 09:24 UTC, val06 approved these changes

2024-02-08 09:32 UTC, guyarb commented
/merge

2024-02-08 10:17 UTC, merged