Write JMXFetch go check
DataDog/datadog-agent pull request #230
Opened 2017-04-21 20:42 UTC by zippolyte

### What does this PR do?

Add a go check to run the JMXFetch jar in a long running check

### Testing

For now I've only tested on my mac with an instance of kafka running.

### Additional Notes

There has been some difficulties adapting this check to the new way we have of reading configs and instantiating checks. 
What was agreed upon was to have a `jmx.yaml` file in the conf directory of the agent, in which we would list the config files of the jmx checks we want under a single instance. 
e.g. : 
```
instances:
  - files: 
    - activemq.yaml
    - activemq_58.yaml
    - cassandra.yaml
    - jmx.yaml
    - solr.yaml
    - tomcat.yaml
    - kafka.yaml
```

The actual config files of the checks have to be in a `jmx` folder in the `conf.d` directory.

2017-04-24 09:45 UTC, hush-hush requested changes
Quick review on the code (I don't know much on how we handle jmx check).

Could you also add some unit tests. At least configuration parsing and error could be tested.

For testing the whole, you can look into our system tests.

2017-04-24 15:35 UTC, hush-hush approved these changes

2017-04-24 22:22 UTC, olivielpeau reviewed
Looks good overall, thanks @zippolyte!

I've added a few comments here and there. I agree with @hush-hush that we should have at least some basic unit tests. System tests would be nice, but feel free to do it in a separate PR I'd say (maybe after you add the JAR to the build as that sounds more urgent to me).

Also, more generally, we should be careful about writing files at runtime in the `dist/...` path. At some point we should use a `run/` dir as we do on agent5. Let's add `FIXME` comments when we use `dist/`.

One last thing, on which platforms have you been able to test this? Let's document it so that we don't forget to test it on other platforms too.

2017-04-25 15:44 UTC, olivielpeau approved these changes
Added a couple of comments, but it's ready to merge IMO 👍 

Could you move the related card to the `Needs non-unit tests` column and specifically mention on the card which platforms haven't been tested at all yet?

2017-04-25 23:17 UTC, merged