update ECS v4 client
DataDog/datadog-agent pull request #23248
Opened 2024-02-28 14:14 UTC by kangyili

Update ECS V4 client and types.  This PR is used by https://github.com/DataDog/datadog-agent/pull/21836

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-03-08 13:02 UTC, L3n41c requested changes
I think there is an issue with the fact that `V4FromCurrentTask(…)` uses the same `globalUtil.initV3orV4` `sync.Once` object as `V3orV4FromCurrentTask(…)`.

If both functions are called, only one of the two will be allowed to setup its retrier.
The other will panic when calling `TriggerRetry`.

2024-03-11 08:45 UTC, kangyili commented on pkg/util/ecs/metadata/clients.go
> +	return globalUtil.v3or4, nil
Nice catch. I created a new v4 field
https://github.com/DataDog/datadog-agent/pull/23248/commits/9244446431e3dd4ea773617a249cb4ec8fdf94b9

2024-03-11 08:47 UTC, kangyili commented on pkg/util/ecs/metadata/v3or4/types.go
> +	AvailabilityZone        string             `json:"AvailabilityZone,omitempty"`
Yes, we will need all fields as we're going to add a new core check to collect ecs tasks. The check will use workloadmeta. 

- https://github.com/DataDog/datadog-agent/pull/21836
- 
- https://github.com/DataDog/datadog-agent/pull/22060

2024-03-11 16:53 UTC, L3n41c approved these changes
I only left minor simplification suggestions.

2024-03-11 16:53 UTC, L3n41c commented on pkg/util/ecs/metadata/clients.go
> +}
The `if` may not be necessary.

```suggestion
func initV4() (err error) {
	globalUtil.v4, err = newClientV4ForCurrentTask()
	return err
}
```

2024-03-11 16:53 UTC, L3n41c commented on pkg/util/ecs/metadata/v3or4/client_test.go
> +		ClusterName:   "arn:aws:ecs:us-east-1:123457279990:cluster/ecs-cluster",
`expected` may not need to be a function.

```suggestion
	require.Equal(t, expected, task)
}

// expected generates an expected Task from ./testdata/task.json
var expected := &Task{
		ClusterName:   "arn:aws:ecs:us-east-1:123457279990:cluster/ecs-cluster",
```

2024-03-12 09:22 UTC, merged