run kind e2e tests for multiple kube versions and os descriptors
DataDog/datadog-agent pull request #23485
Opened 2024-03-06 13:10 UTC by adel121

### What does this PR do?

Runs the containers E2E tests for the kind scenario for multiple kubernetes versions and multiple OS descriptors.

### Motivation

Run the E2E tests on multiple environments (i.e. multiple versions of k8s and os descriptors)

### Additional Notes

### Possible Drawbacks / Trade-offs

- Increases cost of running e2e, because we are spawning one gitlab runner per version / os descriptor. However, doing all the tests for all versions in one gitlab runner is challenging and not straightforward. The challenge is in handling parallelism and test log management. If we run all versions in one gitlab runner only sequentially, it will take a very long time to finish the tests. If we run them in parallel within the same gitlab runner, the logs would not be comprehensible.

### Describe how to test/QA your changes

2024-03-06 16:46 UTC, L3n41c requested changes
I [tried to run the tests](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/29605745) and they’re not passing:
![image](https://github.com/DataDog/datadog-agent/assets/1437785/182ec47c-1ade-491b-a73a-74b45f35a473)

Given [the error](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/452319975):
```
error: the stack is currently locked by 1 lock(s). Either wait for the other process(es) to end or delete the lock file with `pulumi cancel`.
s3://dd-pulumi-state?region=us-east-1&awssdk=v2&profile=agent-qa-ci/.pulumi/locks/organization/e2eci/ci-29605745-4670-kind-cluster/59a1bba2-6fa8-449f-bdce-8fb1a63142e5.json: created by root@runner-8xeqodak-project-4670-concurrent-5g82mj (pid 17189) at 2024-03-06T16:00:15Z
```
it seems that all the GitLab jobs running in parallel are trying to update the same single pulumi stack.

2024-03-11 15:46 UTC, L3n41c commented on test/new-e2e/pkg/runner/ci_profile.go
GitLab can schedule several jobs on the same runner. So, using the runner ID isn’t a guarantee of unicity.
It would be smarter to use the job ID instead.
Moreover, in case of issue that requires investigation, it will be easier to find the GitLab job that created a given pulumi stack with its ID than with its runner ID.

2024-03-11 15:46 UTC, L3n41c commented on test/new-e2e/pkg/runner/ci_profile.go
>  	}
```suggestion
	// Building name prefix
	jobID, ok := os.LookupEnv("CI_JOB_ID")
	if !ok || jobID == "" {
		return nil, errors.New("unable to compute name prefix, missing environment variable CI_JOB_ID.")
	}
```

2024-03-11 15:46 UTC, L3n41c commented on test/new-e2e/pkg/runner/ci_profile.go
> +		ciUniqueID:  "ci-" + pipelineID + "-" + runnerID,
```suggestion
		ciUniqueID:  "ci-" + jobID,
```

2024-03-11 15:58 UTC, L3n41c reviewed
`TestKindSuite/TestControlPlane` tests are failing with Kube 1.19 because the control plane docker images have moved and are fetched from a different registry:

```
=== FAIL: tests/containers TestKindSuite/TestControlPlane/metric___kube_controller_manager.queue.adds{} (120.01s)
    base_test.go:138: 
        	Error Trace:	/go/src/github.com/DataDog/datadog-agent/test/new-e2e/tests/containers/base_test.go:170
        	            				/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.7.linux-amd64/src/runtime/asm_amd64.s:1650
        	Error:      	Received unexpected error:
        	            	unexpected tags: image_name:k8s.gcr.io/kube-controller-manager
        	            	missing tags: ^image_name:registry.k8s.io/kube-controller-manager$
        	Messages:   	Tags mismatch on `kube_controller_manager.queue.adds{}`
```

The tests need to be fixed by replacing all the lines like https://github.com/DataDog/datadog-agent/blob/caafdd50a2bc93494ba5d9cd0687298dd33b2e75/test/new-e2e/tests/containers/kindvm_test.go#L130 by
```
`^image_name:(?:k8s\.gcr\.io|registry\.k8s\.io)/kube-controller-manager$`,
```

2024-03-11 16:30 UTC, L3n41c commented on test/new-e2e/tests/containers/kindvm_test.go
> +				`^image_name:(?:k8s\.gcr\.io|registry\.k8s\.io)/kube-controller-manager$`,
```suggestion
				`^image_name:(?:k8s\.gcr\.io|registry\.k8s\.io)/kube-apiserver$`,
```

2024-03-11 16:30 UTC, L3n41c commented on test/new-e2e/tests/containers/kindvm_test.go
> +				`^image_name:(?:k8s\.gcr\.io|registry\.k8s\.io)/kube-controller-manager$`,
```suggestion
				`^image_name:(?:k8s\.gcr\.io|registry\.k8s\.io)/kube-scheduler$`,
```

2024-03-19 11:18 UTC, L3n41c approved these changes

2024-03-19 13:08 UTC, chouetz approved these changes

2024-03-19 13:08 UTC, chouetz approved these changes

2024-03-20 13:55 UTC, pducolin commented on .gitlab/e2e/e2e.yml
> +      - EXTRA_PARAMS: "--run TestKindSuite -c ddinfra:osDescriptor=ubuntu:22.04"
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution. -->
**❓ question**
Do you want to combine these to have `ddinfra:kubernetesVersion=1.19 ddinfra:osDescriptor=ubuntu:20.04`? Or is it ok to test each of them separately?

2024-03-25 10:12 UTC, pducolin commented on .gitlab/e2e/e2e.yml
> +      - EXTRA_PARAMS: "--run TestKindSuite -c ddinfra:osDescriptor=ubuntu:22.04"
Thank you!

2024-03-25 10:12 UTC, pducolin approved these changes

2024-03-25 10:13 UTC, adel121 commented
/merge

2024-04-19 14:44 UTC, adel121 commented
/merge --cancel

2024-04-23 08:25 UTC, adel121 commented
/merge

2024-04-23 08:31 UTC, adel121 commented
/merge --cancel

2024-05-31 11:11 UTC, davidor approved these changes

2024-05-31 14:20 UTC, adel121 commented
/merge

2024-05-31 14:44 UTC, merged