HPA Support for EKS
DataDog/datadog-agent pull request #2366
Opened 2018-09-24 22:18 UTC by CharlyF

### What does this PR do?

EKS released support for HPA as the aggregation layer was enabled.
To be successfully registered the APIService has to read the certificates from a ConfigMap called:
`extension-apiserver-authentication` (created by the APIServer).
In this ConfigMap are 2 crucial keys. `client-ca-file` and `requestheader-client-ca-file`.

The Cluster Agent implements the external metrics server as described in the [custom-metrics-apiserver](https://github.com/kubernetes-incubator/custom-metrics-apiserver) library.
It appears that the latest version (available as of today) pins the API Server at `15cbd7efdeb242a93307546b08843d55dcfddc33` which was promoted in [this PR](https://github.com/kubernetes/apiserver/commit/15cbd7efdeb242a93307546b08843d55dcfddc33).

However, there was [an issue](https://github.com/kubernetes/kubernetes/issues/65724) where basically if the  `client-ca-file` key was missing in the configmap, the APIService would not attempt to read the `requestheader-client-ca-file` and therefore would not start the  custom metrics server.
(either/both files can be configured in [the options](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) of the APIServer).

The fix was made in [this PR](https://github.com/kubernetes/kubernetes/pull/66394/files).

----

In this PR, we **temporarily** move away from the official library and point to the fork [here](https://github.com/CharlyF/custom-metrics-apiserver) which is just bumping the references to the upstream code and adapting the interfaces that changed to include the change in the apiserver code.
The references were gotten by using the appropriate commit ref in apiserver and using the references in the [Godeps.json](https://github.com/kubernetes/apiserver/blob/4e7be504bf8670b1b36388e3ce2d097c6347373a/Godeps/Godeps.json). For the non imported library, I looked up for the most up to date and compliant version.

----

As soon as the upstream library pins the next version (proven that it embeds the fix), we will move back to it.

In the meantime, this PR allows for the DCA to serve custom metrics to Kubernetes on EKS out of the box.

### Motivation

Enable the HPA on EKS.

2018-09-26 13:57 UTC, hkaj requested changes

2018-09-26 13:57 UTC, hkaj commented on pkg/clusteragent/custommetrics/provider.go
> +func (p *datadogProvider) GetMetricByName(name types.NamespacedName, info provider.CustomMetricInfo) (*custom_metrics.MetricValue, error) {
the comments here need fixing

2018-09-26 13:57 UTC, hkaj commented on pkg/util/kubernetes/apiserver/leaderelection/leaderelection_test.go
> +	require.Error(t, err)
can we qualify the expected error?

2018-09-27 09:30 UTC, CharlyF commented on pkg/clusteragent/custommetrics/provider.go
> +	"k8s.io/apimachinery/pkg/types"
fixing goimport here

2018-09-27 11:58 UTC, hkaj approved these changes

2018-09-27 12:01 UTC, merged