add `SHOW` as sql command for mysql, postgres protocol
DataDog/datadog-agent pull request #23905
Opened 2024-03-20 03:24 UTC by chengjoey

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-03-20 18:49 UTC, rtrieu requested changes
Some formatting feedback.

2024-03-20 18:49 UTC, rtrieu commented on releasenotes/notes/regrad-show-as-sql-command-e08c0a29ee46d396.yaml
> +    Ebpf network regard show as sql command for mysql, postgres protocol
```suggestion
    eBPF networks regard show as a SQL command for MySQL and Postgres protocols
```

2024-03-21 01:25 UTC, chengjoey commented on releasenotes/notes/regrad-show-as-sql-command-e08c0a29ee46d396.yaml
> +    Ebpf network regard show as sql command for mysql, postgres protocol
done~

2024-05-29 07:19 UTC, guyarb commented
Hey @chengjoey 👋🏻 

First of all, thank you for submitting this change, we appreciate the effort!
However, we intentionally decided to keep the list of commands limited as our overall code is pretty complex, which gives us very small room for modifications, as a more complicated code can lead us to reach to the eBPF verifier limitations (on number of branches in the code or number of instructions). We chose the most common commands to be added to the list, and unfortunately, `show` wasn't one of them. Furthermore, the code lives in our classification code, and for that, it is suffice for us to find a single matched command in the connection to classify it as postgres or as mysql, so the impact of unsupported commands (like show, begin, commit, etc) is narrowed down.

2024-05-29 07:19 UTC, closed without merging