[USMO] Fix dynamic counter table TLS leak
DataDog/datadog-agent pull request #24042
Opened 2024-03-24 09:49 UTC by amitslavin

### What does this PR do?

Add `tls_http2_finish` as part of the `tcp_close` function in order to prevent HTTP/2 TLS leaks in the http2_dynamic_counter table.

### Motivation

The cleanup of the map happens either in TCP termination or during TLS shutdown event. The TCP termination is manages by the socket filter, thus it cannot clean TLS entries, as it does not have the access to the PID and NETNS. The actual server is not shutting down the TLS connection before closing the socket, so we never clean the entries.

This PR creates `tls_http2_finish` for the http2 protocol which is being called when we see tcp_close.
Recently we added `tcp_close` probes in USM, those probes are kprobes and have the access to PID and NETNS, so I decided to add the cleanup mechanism to that probe.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-03-24 11:31 UTC, guyarb requested changes
The code is good for POC, but not for the mainline
Please redo, and try to make it more generic or to work with the current implementation that we have.

2024-03-25 08:30 UTC, amitslavin commented
> The code is good for POC, but not for the mainline Please redo, and try to make it more generic or to work with the current implementation that we have.

I have created a simpler implementation that currently does the work. However, we need to revisit our implementation to improve the design. I have created a [Jira](https://datadoghq.atlassian.net/browse/USMON-832) ticket for this task.

2024-03-25 23:01 UTC, guyarb commented on pkg/network/ebpf/c/protocols/sockfd-probes.h
> +    // Currently, we lack the pid and netns when cleaning the connection (in the http2_tls_termination function).
> we lack the pid and netns when cleaning the connection (in the http2_tls_termination function)

that's wrong...

2024-03-25 23:01 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/https.h
> +        if (skip_http) {return;}
at least document in the code

2024-03-26 14:30 UTC, guyarb approved these changes

2024-03-26 15:59 UTC, amitslavin commented
/merge

2024-03-26 16:29 UTC, merged