Update Go experimental libraries in all modules
DataDog/datadog-agent pull request #24356
Opened 2024-04-03 16:08 UTC by pgimalac

### What does this PR do?

Update all modules from the Go experimental repo.

### Motivation

Use up-to-date dependencies.
Often the root module of the repo is kept updated but individual modules are still indicating very old versions of some dependencies.
New versions can include bug and security fixes so we should use them if it doesn't break anything.

### Additional Notes

Used the task introduced by https://github.com/DataDog/datadog-agent/pull/24346:
```
inv modules.for-each "go get -u golang.org/x/arch golang.org/x/crypto golang.org/x/lint golang.org/x/mod golang.org/x/net golang.org/x/sync golang.org/x/sys golang.org/x/term golang.org/x/text golang.org/x/time golang.org/x/tools golang.org/x/xerrors"
inv tidy-all
```

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-04-03 17:40 UTC, paulcacheux requested changes

2024-04-03 17:40 UTC, paulcacheux commented on pkg/security/secl/go.mod
> +	golang.org/x/tools v0.19.0
Because of https://github.com/DataDog/datadog-agent/pull/24080, we cannot bump this

2024-04-08 08:09 UTC, paulcacheux approved these changes

2024-04-08 08:19 UTC, ahmed-mez approved these changes

2024-04-08 08:56 UTC, pducolin approved these changes

2024-04-09 11:48 UTC, TCheruy approved these changes

2024-04-09 11:48 UTC, robertjli approved these changes

2024-04-09 11:48 UTC, carlosroman approved these changes

2024-04-09 11:52 UTC, vickenty approved these changes

2024-04-09 12:03 UTC, wdhif approved these changes

2024-04-09 12:04 UTC, mackjmr approved these changes

2024-04-09 12:16 UTC, L3n41c approved these changes

2024-04-09 13:26 UTC, JLineaweaver approved these changes

2024-04-09 16:31 UTC, pgimalac commented
@julien-lebot done

2024-04-10 17:13 UTC, timothyalexandersoftware approved these changes

2024-04-10 18:27 UTC, chouetz approved these changes

2024-04-11 07:59 UTC, jeremy-hanna approved these changes

2024-04-11 13:50 UTC, jszwedko approved these changes

2024-04-12 14:19 UTC, merged