Adding IsLeader check to syncAutoscalers
DataDog/datadog-agent pull request #2455
Opened 2018-10-15 05:24 UTC by CharlyF

### What does this PR do?

Only the leader should be querying Datadog. This happens when a HPA is added or when the scope/metric name is changed in an existing HPA.

Updated test to support the leader case. No test for Non leader.

Also added real HasSync method to (attempt to) fix the flakyness of the metadataController test.

2018-10-15 13:48 UTC, mfpierre approved these changes

2018-10-15 14:10 UTC, mfpierre commented
This does not test the flakyness of the test, investigating 🔍

2018-10-15 16:08 UTC, mfpierre requested changes
This is not yet solving the flakyness issue

2018-10-17 10:14 UTC, hkaj approved these changes

2018-10-17 20:36 UTC, closed without merging