Create node agent diagnose command
DataDog/datadog-agent pull request #2468
Opened 2018-10-16 16:25 UTC by DylanLovesCoffee

### What does this PR do?

This adds a diagnosis for node agents to the DCA, by way of the agent `diagnose` command. 

### Motivation

In keeping with the congruency of being able to quickly monitor the connectivity of integrations reliant on an endpoint. The agent currently provides a diagnosis for the API server, and as the DCA will act as a proxy to the API server, we should be able to check connectivity.

### Testing
We expect a successful connection to the DCA to output `PASS` in the diagnosis: 
![image 2018-10-16 at 7 39 32 pm](https://user-images.githubusercontent.com/25290232/47078598-f0b61600-d203-11e8-94aa-f03aedf9eeb2.png) 

Otherwise it should result in a `FAIL` and log the connectivity issue: 
![image 2018-10-17 at 10 54 42 am](https://user-images.githubusercontent.com/25290232/47078744-4094dd00-d204-11e8-975f-1f4a42a34275.png)

2018-10-26 14:51 UTC, mfpierre requested changes
Could you rename the file to `diagnosis.go` to match the other ones?

Also I think `getClusterAgentEndpoint` only returns the URL, we should probably check for connectivity as well

2018-11-22 11:15 UTC, mfpierre commented
related https://github.com/DataDog/datadog-agent/pull/2693

2018-11-22 14:29 UTC, mfpierre approved these changes

2018-11-23 12:33 UTC, xvello approved these changes

2018-11-23 12:48 UTC, merged