Change OTel modules to go 1.21
DataDog/datadog-agent pull request #24688
Opened 2024-04-15 13:37 UTC by liustanley

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-04-15 15:51 UTC, paulcacheux requested changes

2024-04-15 15:51 UTC, paulcacheux commented on pkg/security/secl/go.mod
> +go 1.21.0
Please don't, `go 1.21` is done on purpose here

2024-04-15 15:51 UTC, paulcacheux commented on pkg/security/seclwin/go.mod
> +go 1.21.0
Same here

2024-04-15 15:58 UTC, paulcacheux approved these changes

2024-04-16 08:46 UTC, hush-hush approved these changes

2024-04-16 08:56 UTC, raphaelgavache commented
For fleet part there's an issue due to a file rename, I've prepared you a quick fix for you: https://github.com/DataDog/datadog-agent/pull/24721

2024-04-16 10:03 UTC, pgimalac commented on tasks/update_go.py
> +        _update_file(warn, mod_file, f"^go {PATTERN_MAJOR_MINOR}\r?$", f"go {major_minor}", dry_run=dry_run)
Thanks for updating this btw !

2024-04-16 14:43 UTC, FlorentClarret commented on tasks/update_go.py
> +            major_minor_zero = f"{major_minor}.0"
`major_minor` might not be initialized

2024-04-16 14:43 UTC, FlorentClarret commented on tasks/update_go.py
> +            major_minor_zero = f"{major_minor}.0"
oh nvm, you just fixed it

2024-04-16 14:44 UTC, CelianR approved these changes

2024-04-16 14:46 UTC, FlorentClarret approved these changes

2024-04-16 14:59 UTC, mx-psi approved these changes

2024-04-16 15:02 UTC, knusbaum approved these changes

2024-04-16 15:29 UTC, rayz approved these changes

2024-04-16 15:45 UTC, robertjli approved these changes

2024-04-16 15:51 UTC, pducolin approved these changes
Ok for Agent Developer Tools

2024-04-16 15:52 UTC, pgimalac approved these changes

2024-04-16 16:00 UTC, jszwedko approved these changes

2024-04-16 16:56 UTC, zoedt approved these changes

2024-04-16 18:06 UTC, gh123man approved these changes

2024-04-16 21:51 UTC, clarkb7 approved these changes

2024-04-17 19:02 UTC, raphaelgavache approved these changes

2024-04-18 13:56 UTC, BaptisteFoy approved these changes

2024-04-18 13:59 UTC, davidor approved these changes

2024-04-18 14:08 UTC, mfpierre approved these changes

2024-04-19 18:23 UTC, liustanley commented
/merge

2024-04-19 19:53 UTC, merged