usm: kafka: Add TLS support
DataDog/datadog-agent pull request #25083
Opened 2024-04-24 15:23 UTC by vitkyrka

### What does this PR do?

Add support for Kafka over TLS.

### Motivation

https://datadoghq.atlassian.net/browse/USMON-147

### Additional Notes

Load test pending.

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Tests are included in the PR.

2024-05-08 14:15 UTC, DanielLavie commented
Could you provide a description of what specifically you're comparing in the load test, particularly in terms of agent configuration?

2024-05-09 12:09 UTC, guyarb requested changes
A general comment - that's a great PR. Very well divided into commits with good commit messages and it was very easy to dive into the code

2024-05-13 07:49 UTC, vitkyrka commented
> Could you provide a description of what specifically you're comparing in the load test, particularly in terms of agent configuration?

I've added this information to the PR description now.

2024-05-13 07:50 UTC, vitkyrka commented on pkg/network/ebpf/c/protocols/kafka/pktbuf.h
> +}
Done.

2024-05-13 09:00 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/https.h
> +}
I know what's the problem here, I'll address it in a separate PR
I found the same during my work to modularize USM

2024-05-13 09:00 UTC, guyarb commented on pkg/network/ebpf/c/protocols/tls/https.h
> +}
you can resolve the ticket

2024-05-13 09:02 UTC, guyarb approved these changes

2024-05-14 11:37 UTC, vitkyrka commented
/merge

2024-05-14 11:48 UTC, vitkyrka commented
/merge -c

2024-05-14 13:59 UTC, vitkyrka commented
/merge

2024-05-14 14:30 UTC, merged