AMLII-1646 Add stream-logs output as flare command argument
DataDog/datadog-agent pull request #25414
Opened 2024-05-06 22:44 UTC by DDuongNguyen

### What does this PR do?
This PR introduces a new feature to the flare command. It adds a 60s output log file from the stream-logs command as an argument and attach that file to the flare as an agent log
 
### Motivation
The motivation behind this change is to provide users with more flexibility when using the flare command. By allowing users to attach the stream log output, they can easily save troubleshoot or send it to our support for troubleshooting

### Additional Notes
This PR also introduce the quiet mode while running stream-logs

### Describe how to test/QA your changes
- Run:
```
datad-agent flare -L
```
or
```
datad-agent flare --with-stream-logs
```

Logs should be output in the same [agent log directory
](https://docs.datadoghq.com/agent/configuration/agent-log-files/?tab=agentv6v7)
and attached to the flare

2024-05-07 12:31 UTC, Kaderinho approved these changes

2024-05-07 12:33 UTC, Kaderinho commented
Forgot to mention that during the review but you'll need to fix `cmd/systray/command/command.go` to include the new argument

2024-05-07 18:42 UTC, clarkb7 requested changes

2024-05-07 18:42 UTC, clarkb7 commented on cmd/agent/common/path/path_windows.go
> +	DefaultStreamlogsLogFile = "c:\\programdata\\datadog\\logs\\streamlogs_info\\streamlogs.log"
this should be updated in `init()`

2024-05-07 20:14 UTC, gh123man commented on cmd/agent/subcommands/flare/command.go
> +		fmt.Fprintln(color.Output, color.GreenString("Asking the agent to log the log-stream."))
NIT: Perhaps something like:
```suggestion
		fmt.Fprintln(color.Output, color.GreenString("Asking the agent to stream logs"))
```

2024-05-07 20:14 UTC, gh123man commented on cmd/agent/subcommands/streamlogs/command.go
> +	if _, err := os.Stat(dir); os.IsNotExist(err) {
Does it make sense to put the directory management code in `streamLogs` instead of duplicating it here and in `PreRunE`?

2024-05-08 18:30 UTC, clarkb7 approved these changes

2024-05-08 18:39 UTC, gh123man approved these changes

2024-05-08 19:01 UTC, DDuongNguyen commented
/merge

2024-05-08 20:15 UTC, merged