APM: do not replace tags on special dd tags
DataDog/datadog-agent pull request #25508
Opened 2024-05-10 14:16 UTC by ajgajg1134

### What does this PR do?
Alters the behavior of "match all" rules for replace_tags config such that they no longer affect internal datadog tags. (ie. those that start with "_dd."). Note that it is still possible to use replace tags on specific _dd. tags if that's required (this should not ever be required, but is left as an option "just in case"), just target the specific tag directly with a replace tags rule.

### Motivation
We rely on the _dd tags for various product features within APM, some customers with very strict replace tags rules experienced broken APM features when these rules unexpectedly replaced important datadog tags.

### Additional Notes

### Possible Drawbacks / Trade-offs
It's _possible_ someone is relying on the ability to redact data even within internal datadog tags, but this really should NOT be the case, and if they absolutely must do so then they are able to redact specific tags explicitly still. (But if you're reading this because you want to replace all _dd. tags please let us know via support so we can help support your exact use case!)

### Describe how to test/QA your changes
New unit tests change covers this change well!

2024-05-10 17:27 UTC, aliciascott requested changes
@ajgajg1134 Just a quick suggestion for spelling, please request re-review when updated, thanks!

2024-05-10 17:27 UTC, aliciascott commented on releasenotes/notes/noReplaceDD-5ea756d06f438f23.yaml
> +    APM: Fixes issue where match-all replace tags rules could inadvertantly affect required datadog tags. It is still possible to redact specific datadog tags by targetting them explicitly.
```suggestion
    APM: Fixes issue where match-all replace tags rules could inadvertently affect required datadog tags. It is still possible to redact specific Datadog tags by targeting them explicitly.
```

2024-05-10 17:57 UTC, aliciascott approved these changes
looks good

2024-05-13 18:29 UTC, knusbaum approved these changes
LGTM

2024-05-13 21:20 UTC, merged