Implement check metadata payloads
DataDog/datadog-agent pull request #2554
Opened 2018-11-06 03:02 UTC by ofek

### What does this PR do?

Implements a way for checks to send their own metadata. Each payload is just json that the backend will learn to work with in upcoming PRs to respective repos.

### Motivation

So we can track things like versions of applications monitored (MySQL, Redis, ...), configuration options used, etc.

2019-04-09 20:18 UTC, gzussa requested changes
Let's try to get this feature in but instead of sending infos to DD, let's add them to the flare cmd.
Also, let's get rid of the `metadata` name everywhere. What about using `infos` or `details`?

2019-04-10 09:12 UTC, olivielpeau commented
just realized this PR existed, so adding a note here: we have an OKR in Q2 about sending some more Agent telemetry, this could part of the effort (we have a stretch key result about sending more info about running agent integrations: version of integration, version of software that's monitored).

We should have a discussion/RFC in Q2 about what the payload should look like before reviewing this PR (having in mind the current backend contraints, and long-term goals)

2019-06-24 03:14 UTC, ofek commented
Just some info for those coming here:

1. This will be prioritized in just a few weeks
2. We're keeping `metadata` now that we renamed the impetus for that request

2019-09-26 16:14 UTC, ofek commented
Ported to RTLoader here: https://github.com/DataDog/datadog-agent/pull/4158

2019-09-26 16:14 UTC, closed without merging