[USMON-910] Introduce postgres TLS monitoring
DataDog/datadog-agent pull request #25729
Opened 2024-05-20 11:32 UTC by guyarb

### What does this PR do?

Introducing the ability to capture and encrypted postgres traffic (a.k.a postgres TLS).
The change uses `pktbuf` notation to share implementation between plaintext and TLS implementations.

### Motivation

Capture encrypted traffic between a client and a postgres server.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-05-26 12:31 UTC, amitslavin requested changes

2024-05-26 12:31 UTC, amitslavin commented on pkg/network/ebpf/c/protocols/postgres/decoding.h
> +    // On stack for 4.14
what?

2024-05-26 12:31 UTC, amitslavin commented on pkg/network/usm/postgres_monitor_test.go
> +	fixCount := func(count int) int {
maybe we can change from fix to adjust?

2024-05-26 12:42 UTC, amitslavin commented on pkg/network/ebpf/c/protocols/helpers/pktbuf.h
> +            read_into_user_buffer_##name(buffer, pkt.tls->buffer_ptr + offset);                          \
Just saw you changed it to a different PR so resolving

2024-05-26 12:45 UTC, guyarb commented on pkg/network/ebpf/c/protocols/helpers/pktbuf.h
> +            read_into_user_buffer_##name(buffer, pkt.tls->buffer_ptr + offset);                          \
To answer your question - it was a bug, we get an offset argument, so we should have used only the offset.
It worked as the code was used only in kafka-tls, and there we never modified data_off field
In postgres TLS I do modify data_off field, and thus the original code resulted in wrong reads from the buffer

2024-05-26 12:47 UTC, guyarb commented on pkg/network/ebpf/c/protocols/postgres/decoding.h
> +    // On stack for 4.14
elaborated

2024-05-26 12:48 UTC, guyarb commented on pkg/network/usm/postgres_monitor_test.go
> +	fixCount := func(count int) int {
changed

2024-05-26 12:51 UTC, amitslavin approved these changes

2024-05-27 11:46 UTC, guyarb commented
/merge

2024-05-27 12:24 UTC, merged