[CONTP-61] remove global variables in tagger
DataDog/datadog-agent pull request #25804
Opened 2024-05-22 06:27 UTC by zhuminyi

### What does this PR do?
[CONTP-61](https://datadoghq.atlassian.net/browse/CONTP-61)

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-05-22 09:06 UTC, davidor requested changes
The test `Test_taggerCardinality` in `comp/core/tagger/taggerimpl/tagger_test.go` need to be fixed.

Other than that the changes look good to me :+1:

2024-05-22 09:20 UTC, vickenty approved these changes

2024-05-28 12:09 UTC, davidor approved these changes

2024-05-28 15:44 UTC, L3n41c approved these changes

2024-05-29 00:48 UTC, zhuminyi commented
/merge

2024-05-29 01:11 UTC, merged