Add support for logs to the infra attributes processor.
DataDog/datadog-agent pull request #25835
Opened 2024-05-22 18:34 UTC by dinooliva

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-05-27 20:23 UTC, dineshg13 requested changes

2024-05-30 04:46 UTC, dinooliva commented on comp/otelcol/otlp/components/processor/infraattributesprocessor/logs.go
> +		originID := attributes.OriginIDFromAttributes(rattrs)
Done.

2024-06-11 16:24 UTC, dineshg13 approved these changes

2024-06-11 19:27 UTC, astuyve approved these changes

2024-06-11 20:18 UTC, dinooliva commented
/merge

2024-06-11 21:07 UTC, merged