[FA] Reduce inventory payload first run
DataDog/datadog-agent pull request #25951
Opened 2024-05-27 12:06 UTC by coignetp

### What does this PR do?

Reduce the default first run of the inventory payload to 15sec.
This metadata payload is used in Fleet Automation to show an agent, so sending them 1min after startup means we have at least 1min latency (+ the backend latency) to show up in Fleet.
The reason we send this payload seconds after startup is to make sure we have host tags, which is also needed when we send metrics payload.

Since the first metrics payload is usually 15sec after startup, let's sync these 2 duration.

This keeps https://github.com/DataDog/datadog-agent/issues/23875

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

* Enable debug logs
* Start agent
* See in the logs that the datadog_agent metadata payload is sent after 15s

2024-05-27 12:07 UTC, arbll approved these changes

2024-05-27 12:11 UTC, BaptisteFoy approved these changes
nice this will really help us

2024-05-27 13:53 UTC, ogaca-dd requested changes
Did you notice this [comment](https://github.com/DataDog/datadog-agent/commit/46f4f516634f7a016e43bec4870400841ce56745#diff-7f93404bf5d66536e9c38f3c97b39e81875b76163e0ea3c64a4d559ccbca8ffcR154-R161). 
@GustavoCaso is this change fine?

2024-05-27 14:04 UTC, coignetp commented
> Did you notice this [comment](https://github.com/DataDog/datadog-agent/commit/46f4f516634f7a016e43bec4870400841ce56745#diff-7f93404bf5d66536e9c38f3c97b39e81875b76163e0ea3c64a4d559ccbca8ffcR154-R161).

If we look at the postmortem from Gustavo and the different investigations, we see this is a host tags delay issue. In the description I mentioned that I think reducing it to 15s is safe because the metrics payload should hit the exact same issue and is sent 15s after agent startup. In any case, I think this should be fixed backend-side as much as possible, and having a 1min delay hardcoded in the agent is not great for the user experience. I'll wait for his review for sure, since he has some context

2024-05-29 11:58 UTC, hush-hush commented
Yes reducing this delay in first payload might lead to the creation of a host without host-tags in the backend (which means metrics will miss tags for the first 5 minutes).

We tried to reduce this in the past and had to revert the change.

2024-05-30 09:28 UTC, hush-hush requested changes

2024-05-30 09:28 UTC, hush-hush commented on pkg/config/setup/config.go
> +	config.BindEnvAndSetDefault("inventories_first_run_delay_checks", 0)
Wouldn't this create a host in the backend since they would pull host-tags (triggering the issue in the backend again) ?

2024-11-29 00:05 UTC, closed without merging