Update OTel collector deps to v0.102.0
DataDog/datadog-agent pull request #26353
Opened 2024-06-05 01:33 UTC by dineshg13

### What does this PR do?
PR updates the dependencies of OTel collector to v0.102.0 . 

### Motivation
Update to latest version to pull in the security fixes for a critical CVE. 

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-06-05 07:30 UTC, mx-psi reviewed
Looks like we need to address some deprecations on grpc-go

2024-06-05 14:21 UTC, ajgajg1134 approved these changes
looks good for agent-apm

2024-06-05 17:25 UTC, dustmop reviewed
There a bunch of changes here about `confmap.Converter` and the `ConfigProviderSettings`. Is this a consequence of the dependency version changes, or is it unrelated work? Either way, it would be good to have a description of this change in the PR description.

2024-06-05 17:25 UTC, dustmop commented on comp/otelcol/otlp/collector.go
> +				URIs: []string{fmt.Sprintf("map:%s", "hardcoded")},
Why not?
```suggestion
				URIs: []string{"map:hardcoded"},
```

2024-06-05 17:25 UTC, dustmop commented on comp/otelcol/otlp/internal/configutils/utils_test.go
> +			URIs: []string{fmt.Sprintf("map:%s", "hardcoded")},
Same question here

2024-06-05 17:25 UTC, dustmop commented on comp/otelcol/otlp/map_provider_not_serverless_test.go
> +			URIs: []string{fmt.Sprintf("map:%s", "hardcoded")},
Same here

2024-06-05 19:50 UTC, dineshg13 commented
@dustmop i have updated PR description with a link to upstream breaking changes.

2024-06-05 19:58 UTC, dustmop approved these changes
LGTM

2024-06-05 21:24 UTC, jszwedko approved these changes

2024-06-06 06:40 UTC, paulcacheux requested changes

2024-06-06 06:40 UTC, paulcacheux commented on go.mod
> +	github.com/DataDog/datadog-agent/comp/netflow/payload v0.55.0-rc.1
This is probably wrong

2024-06-06 08:19 UTC, mx-psi reviewed
Can you update the PR title to reference v0.102.1 instead?

2024-06-06 13:44 UTC, mackjmr approved these changes

2024-06-06 14:20 UTC, vickenty approved these changes

2024-06-06 14:35 UTC, paulcacheux approved these changes

2024-06-06 14:35 UTC, mx-psi approved these changes

2024-06-06 18:44 UTC, songy23 approved these changes
May be worth adding a changelog with a reference to https://github.com/open-telemetry/opentelemetry-collector/security/advisories/GHSA-c74f-6mfw-mm4v

2024-06-06 18:51 UTC, DylanLovesCoffee approved these changes

2024-06-06 18:59 UTC, FlorentClarret approved these changes

2024-06-06 19:01 UTC, purple4reina approved these changes

2024-06-06 19:26 UTC, robertjli approved these changes

2024-06-07 06:57 UTC, rafa-jago-scacap approved these changes

2024-06-07 09:58 UTC, CelianR approved these changes

2024-06-07 16:11 UTC, dineshg13 commented
/merge

2024-06-07 17:36 UTC, merged