Update the documentation to install the hooks
DataDog/datadog-agent pull request #26485
Opened 2024-06-10 09:05 UTC by FlorentClarret

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-06-10 09:05 UTC, FlorentClarret commented
* **#26485** <a href="https://app.graphite.dev/github/pr/DataDog/datadog-agent/26485?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @FlorentClarret and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-10 13:11 UTC, pducolin approved these changes

2024-06-10 18:27 UTC, rtrieu requested changes
Minor feedback to adhere to docs style guide, but otherwise looks good!

2024-06-10 18:27 UTC, rtrieu commented on docs/dev/agent_dev_env.md
> +We also provide an invoke task to perform some sanity checks and enable some tools. To use it you can run:
```suggestion
Datadog also provides an invoke task to perform some sanity checks and enable some tools. To use it, run:
```

2024-06-10 18:27 UTC, rtrieu commented on docs/dev/agent_dev_env.md
> +To install pre-commit, follow [these instructions](https://pre-commit.com/#installation). The `deva setup` will automatically enable the hooks but you can do it manually running: `pre-commit install`
```suggestion
To install pre-commit, follow [these instructions](https://pre-commit.com/#installation). The `deva setup` automatically enables the hooks, but you can do it manually running: `pre-commit install`.
```

2024-06-11 13:29 UTC, rtrieu approved these changes
Looks good!

2024-06-11 14:00 UTC, FlorentClarret commented
/merge

2024-06-11 14:25 UTC, merged