[ASCII-1521] - Moving common endpoints outside of API component implementation
DataDog/datadog-agent pull request #26683
Opened 2024-06-13 09:45 UTC by misteriaud

### What does this PR do?

To maintain the API component free from HTTP handlers and instead provide them through Fx value groups, this PR moves component-dependency-free endpoints to their own `fx.Module()`.

### Describe how to test/QA your changes

1. run `curl -L -k -H "authorization: Bearer $(sudo cat ./bin/agent/dist/auth_token)"  https://localhost:5001/agent/version`, it must return the current version of the Agent
2. run `curl -L -k -H "authorization: Bearer $(sudo cat ./bin/agent/dist/auth_token)"  https://localhost:5001/agent/hostname`, it must return the hostname of the running Agent
3. run `curl -L -k -H "authorization: Bearer $(sudo cat ./bin/agent/dist/auth_token)"  -X POST https://localhost:5001/agent/stop`, it must stop the Agent

2024-06-13 10:16 UTC, hush-hush requested changes

2024-06-13 11:40 UTC, misteriaud commented on comp/api/endpoints/common/common_api_endpoints.go
> +	w.Write(j)
I have no idea ... It might be safe to replace it by `w.Write([]byte(hname))`, right ?

2024-06-14 14:15 UTC, hush-hush approved these changes

2024-06-14 14:45 UTC, misteriaud commented
/merge

2024-06-14 16:06 UTC, merged