Add traces to the calls to the API Server
DataDog/datadog-agent pull request #2676
Opened 2018-11-16 03:40 UTC by CharlyF

### What does this PR do?

Leveraging the client-go integration of the dd-tracer to submit client side traces for the calls to the API Server.
Using the lib v1.5 which uses an audit log ID so that one can use the audit logs to submit server side tracing - Experimental, will be documented eventually.
 
### Motivation

New feature for 1.1.0

2018-11-19 20:45 UTC, JulienBalestra commented on cmd/cluster-agent/app/app.go
> +		tracer.WithDebugMode(traceDebug)
`WithDebugMode` is a `StartOption` and should be passed to `Start` in its variadic args.

Could be something like:
```go
		startOpts := []tracer.StartOption{
			tracer.WithAgentAddr(svc.config.TracerAddr),
		}
		if svc.config.TracerDefaultServiceName != "" {
			startOpts = append(startOpts, tracer.WithServiceName(svc.config.TracerDefaultServiceName))
		}
		tracer.Start(startOpts...)
```

2018-11-20 09:59 UTC, mfpierre commented on Gopkg.toml
> +    version = "=v1.5.0"
https://github.com/DataDog/dd-trace-go/releases/tag/v1.6.0. was just released with the support of `DD_AGENT_HOST` & `DD_TRACE_AGENT_PORT`

2018-11-20 15:41 UTC, mfpierre approved these changes

2018-11-20 15:52 UTC, mfpierre requested changes
Should pass the CI before merging

2020-05-11 14:14 UTC, closed without merging