[Oracle] - Depend on dba_tablespaces.status for tablespace statuses
DataDog/datadog-agent pull request #26789
Opened 2024-06-17 18:49 UTC by joelmarcotte

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-06-18 09:08 UTC, nenadnoveljic requested changes
There was another error in the query - the query did inner join which eliminated the offline tablespaces as their rows will disappear from `cdb_tablespace_usage_metrics`. Adding `(+)` converts the inner join to outer join.
`m.con_id(+) = t.con_id and m.tablespace_name(+) = t.tablespace_name and c.con_id(+) = t.con_id;`

2024-06-18 09:10 UTC, nenadnoveljic commented on pkg/collector/corechecks/oracle/tablespaces_test.go
> +	s.AssertMetricOnce(t, "Gauge", "oracle.tablespace.offline", 0, c.dbHostname, tags)
We could optionally also test if the `offline` metric emits `1` after the tablespace is taken offline with `alter tablespace tbs_test offline`.

2024-06-18 09:11 UTC, nenadnoveljic reviewed
-

2024-06-19 08:10 UTC, nenadnoveljic commented on pkg/collector/corechecks/oracle/tablespaces_test.go
> +	s.AssertMetricOnce(t, "Gauge", "oracle.tablespace.offline", 1, c.dbHostname, tags)
Can we put the tablespace `online` again to have a clean baseline for the new test? Alternatively, we can do that prior to testing if the tablespace is `offline`

2024-06-19 08:39 UTC, nenadnoveljic commented on pkg/collector/corechecks/oracle/tablespaces_test.go
> +	err := c.Run()
`err` is already defined, so `:` must be omitted in the assinggment.

2024-06-19 18:38 UTC, nenadnoveljic approved these changes

2024-06-19 18:39 UTC, nenadnoveljic commented
The release note is missing for the bug fix. The release note should start with `[oracle]`.

2024-06-19 21:09 UTC, kayayarai approved these changes
suggested edit

2024-06-19 21:09 UTC, kayayarai commented on releasenotes/notes/oracle-tablespace-status-7d80f4e243150e3e.yaml
> +    Fix oracle.tablespace.offline metric not emitting 1 when tablespace is offline.
```suggestion
    Fixes `oracle.tablespace.offline` metric not emitting 1 when tablespace is offline.
```

2024-06-20 16:59 UTC, joelmarcotte commented
/merge

2024-06-20 17:57 UTC, merged