[status] List of configured endpoints move visible in the status page
DataDog/datadog-agent pull request #2745
Opened 2018-12-05 16:10 UTC by remeh

### What does this PR do?

Adds an "Endpoints" section in the Agent GUI status page.

### Motivation

Endpoints information was deducible from the API key validity lines, however it was not clear, this is why we want a dedicated section.

### Additional Notes

Removed the endpoint info from the API key validity line.

2018-12-05 16:51 UTC, arbll commented
Can you add a screen of the changes ?  🖼

2018-12-05 16:56 UTC, remeh commented
Of course:

<img width="629" alt="capture d ecran 2018-12-05 a 17 54 45" src="https://user-images.githubusercontent.com/1798689/49529690-dff65800-f8b6-11e8-9b83-5a9b6eb05aff.png">

I've also tried a list for the api keys under each endpoint, but I wasn't convinced by the result. Also, most of the case they will be only one api key.
But let me know if you think it's better.

2018-12-05 17:25 UTC, hush-hush requested changes
Sadly we have 2 files for the status page: one for the GUI in HTML and one in pure text for the CLI status page.

This means you have to duplicate the change from `cmd/agent/gui/views/templates/generalStatus.tmpl` to `pkg/status/dist/templates/forwarder.tmpl` (or add another section).

2018-12-05 17:38 UTC, remeh commented on pkg/status/status.go
> +	rv := make(map[string]interface{})
Yep sorry, old habit (rv = returned value), thanks for the 👀

2018-12-05 17:38 UTC, remeh commented on cmd/agent/gui/views/templates/generalStatus.tmpl
> +         - Api key ending with: {{$apikey}}
Consider it done

2018-12-06 11:01 UTC, remeh commented
Update the GUI rendering and added the display in the cli status cmd:

![capture d ecran 2018-12-06 a 11 22 21](https://user-images.githubusercontent.com/1798689/49580184-9a856980-f94e-11e8-928f-fe8c940d0bae.png)

![capture d ecran 2018-12-06 a 11 22 09](https://user-images.githubusercontent.com/1798689/49580223-aec96680-f94e-11e8-8acb-9d5d8aea0ae3.png)

2018-12-06 16:07 UTC, hush-hush submitted a review, later dismissed
:ok_hand:

2018-12-20 14:06 UTC, xvello reviewed
LGTM 👍

2018-12-20 15:39 UTC, hush-hush approved these changes

2018-12-21 08:13 UTC, merged