[USM] add Redis decoding skeleton
DataDog/datadog-agent pull request #27562
Opened 2024-07-15 07:28 UTC by Yumasi

### What does this PR do?

This PR adds the "skeleton" for implementing Redis decoding in the future. This includes adding:
- Configuration options to enable Redis decoding
- a new protocol in USM, with its own statkeeper, map cleaner, etc..
- Dummy eBPF probes that will be dispatched to if classifying a Redis connection and decoding is enabled

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-07-15 08:21 UTC, guyarb commented on pkg/network/ebpf/c/protocols/redis/decoding.h
> +}
what about a stub for termination?

2024-07-15 08:22 UTC, ogaca-dd approved these changes
LGTM for files owned by ASC

2024-07-15 08:24 UTC, guyarb commented on pkg/network/protocols/redis/protocol.go
> +	if mapName == inFlightMap { // maps/postgres_in_flight (BPF_MAP_TYPE_HASH), key ConnTuple, value EbpfTx
maps/postgres

2024-07-15 08:24 UTC, guyarb commented on pkg/network/protocols/redis/protocol.go
> +func (p *protocol) processRedis(_ []EbpfEvent) {
processRedis(_ []EbpfEvent) > processRedis([]EbpfEvent)

2024-07-15 08:25 UTC, guyarb commented on pkg/network/protocols/redis/statskeeper.go
> +type StatsKeeper struct {
documentation

2024-07-15 08:25 UTC, guyarb commented on pkg/network/protocols/redis/statskeeper.go
> +func (s *StatsKeeper) Process(_ *EbpfEvent) {
documentation

2024-07-15 08:26 UTC, guyarb commented on pkg/network/protocols/redis/statskeeper.go
> +	defer s.statsMutex.Unlock()
redundant while the implementation is empty

2024-07-15 08:34 UTC, guyarb requested changes
Compared to https://github.com/DataDog/datadog-agent/pull/25416

there are still misses
please go over commit-commit to see the differences

2024-07-16 08:54 UTC, guyarb commented on pkg/network/ebpf/c/protocols/redis/types.h
> +#define REDIS_BATCH_SIZE 25
I'd start with the highest value possible, so we can always ensure we're maximizing the batches functionality

2024-07-17 08:12 UTC, guyarb commented on go.mod
> +	github.com/DataDog/agent-payload/v5 v5.0.125-0.20240715134148-a4cf7e9f7d52
needs to be merged

2024-07-17 08:13 UTC, guyarb approved these changes

2024-07-22 09:42 UTC, gjulianm approved these changes
LGTM for ebpf-platform files

2024-07-22 18:46 UTC, derekwbrown approved these changes
approved for (2) files owned by wkit

2024-07-23 14:56 UTC, hmahmood approved these changes

2024-07-23 15:56 UTC, merged