upgrade(fleet): Add new Remote Config File layer & loader
DataDog/datadog-agent pull request #28096
Opened 2024-07-31 15:26 UTC by BaptisteFoy

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-07-31 15:42 UTC, BaptisteFoy commented on comp/core/sysprobeconfig/sysprobeconfigimpl/params.go
> +}
Note: as the apply of that parameter requires changes of the `New` config method for sysprobe and has a broad impact on the agent as a whole, it'll be done in another PR.

2024-08-01 13:23 UTC, arbll approved these changes

2024-08-01 15:17 UTC, hush-hush requested changes

2024-08-01 16:00 UTC, BaptisteFoy commented on comp/metadata/inventoryagent/inventoryagentimpl/inventoryagent.go
> +			model.SourceFleetPolicies:      "fleet_policies",
Thanks for pointing that out. I didn't know about the security agent part, and I forgot the READMEs. It was fixed in [18f191a](https://github.com/DataDog/datadog-agent/pull/28096/commits/18f191a74f4c1d9d2e687c3025735dcc1e0313fe)

2024-08-02 12:48 UTC, hush-hush approved these changes

2024-08-02 12:51 UTC, BaptisteFoy commented
/merge

2024-08-02 13:14 UTC, merged