[CONTINT-4335] Add ECS agent version to host metadata to show on agent flare
DataDog/datadog-agent pull request #28404
Opened 2024-08-12 19:11 UTC by ewoodthomas

### What does this PR do?

https://datadoghq.atlassian.net/browse/CONTINT-4335

Adds the `ECS Agent Version` to the host metadata. This is included in the agent flare. 

### Motivation

The `ECS Agent Version` would be useful for debugging support tickets.

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

- Start up an ECS cluster and deploy the agent (image must be amd64 architecture)
- Check the `ECS Agent Version`
  - `aws ecs describe-container-instances --cluster <cluster name> --container-instances <cluster instance>`
- Exec into the agent task
  - `aws ecs execute-command \
  --cluster <cluster name> \
  --task <task id> \
  --container datadog-agent \
  --interactive \
  --command "/bin/bash"`
- Call `agent flare`
- Unzip the flare and look at `metadata/host.json` and verify the ECS agent version is present and the same as what was previously found

Additional QA:

- Deploy the agent on a kind cluster
- Exec into the agent and call `agent flare`
- Unzip the flare and look at `metadata/host.json` and very the ECS agent version is empty

2024-08-14 14:09 UTC, hush-hush requested changes
HI,

We should not modify the host metadata providers as it's critical to the backend and how we register new host.

If you want to extend the flare you should use a flare [provider](https://datadoghq.dev/datadog-agent/components/shared_features/flares/) instead of modifying the metadata.
The metadata are linked to product behavior in the backend and we add them to the flare for troubleshooting reasons.

2024-08-21 11:56 UTC, hush-hush approved these changes
Added a nit-pick but looks good to merge after that.

2024-08-21 11:56 UTC, hush-hush commented on pkg/flare/archive.go
> +	return jsonValue, nil
```suggestion
	return json.MarshalIndent(ecsMeta, "", "\t")
```

2024-08-21 19:30 UTC, sblumenthal approved these changes
One small note, otherwise it looks good

2024-08-21 19:30 UTC, sblumenthal commented on pkg/util/ecs/ecs.go
> +func GetECSInstanceMetadata(ctx context.Context) (string, string, error) {
This seems like a redundant function in its current form, given that it is only being used by `NewECSMeta`. I feel that either:
1) The logic of this function can be moved to `NewECSMeta`, or
2) The function should be renamed to `getECSInstanceMetadata`, as right now there is no reason to expose this function

I am personally leaning towards the first one, but in either case the matching file signature should be removed from `no_ecs.go`

2024-08-22 13:23 UTC, ewoodthomas commented
/merge

2024-08-22 13:44 UTC, merged