[Fleet Automation] Add OCI package for the Datadog Installer
DataDog/datadog-agent pull request #28439
Opened 2024-08-13 14:18 UTC by julien-lebot

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-08-28 08:29 UTC, BaptisteFoy approved these changes
I only quickly went over the windows specifics, but overall LGTM!

2024-08-28 08:29 UTC, BaptisteFoy commented on pkg/fleet/installer/service/msiexec.go
> +// or weird bugs from uninstalling a product with an installer from a different version).
Nice, thanks for the comment

2024-08-28 13:07 UTC, chouquette approved these changes
LGTM for agent-delivery

2024-08-28 15:53 UTC, clarkb7 requested changes

2024-08-28 15:53 UTC, clarkb7 commented on cmd/installer/subcommands/daemon/run_windows.go
> +	return s.App.Start(startCtx)
❓ question

Does the App/Daemon need to trigger exit? Or does the service only ever stop when receiving a SCM signal?

2024-08-28 15:53 UTC, clarkb7 commented on cmd/installer/subcommands/daemon/run_windows_test.go
> +	datadogYaml = "C:\\ProgramData\\Datadog\\datadog.yaml"
unit tests shouldn't modify the system. Accessing/modifying this file will fail unless the test is run as Admin.

Can we create a tempfile and provide the path to the config component instead?

Alternatively, we can run the test as an integration test
https://github.com/DataDog/datadog-agent/blob/d1ef19abd517f009a13ac710f8bda6d4f4330a88/tasks/agent.py#L570

2024-08-28 15:53 UTC, clarkb7 commented on pkg/fleet/daemon/daemon.go
> +		err = bootstrap.InstallExperiment(ctx, d.env, url)
❓ question

What does the `bootstrap.InstallExperiment` do differently from `installer.InstallExperiment` to warrant using it instead on Linux?

2024-08-28 15:53 UTC, clarkb7 commented on pkg/fleet/installer/service/datadog_agent_windows.go
> +	datadogAgent = "datadog-agent"
What is this variable? is it the fleet package name?

2024-08-28 15:53 UTC, clarkb7 commented on pkg/fleet/installer/service/datadog_installer_windows.go
> +	datadogInstaller = "datadog-installer"
What is this variable? is it the fleet package name?

2024-08-28 15:53 UTC, clarkb7 commented on pkg/fleet/installer/service/datadog_installer_windows.go
> +func StopInstallerExperiment(ctx context.Context) (err error) {
shouldn't this also uninstall -> install like `StopAgentExperiment` ?

2024-08-29 14:25 UTC, clarkb7 approved these changes

2024-08-29 15:15 UTC, merged