Update secrets troubleshooting doc on windows
DataDog/datadog-agent pull request #2846
Opened 2019-01-02 21:57 UTC by hush-hush

### What does this PR do?

Adding instruction to test user executable in the same condition the
agent would run it.

2019-01-14 18:29 UTC, derekwbrown requested changes
Just made some minor grammatical suggestions

2019-01-14 19:05 UTC, hush-hush commented on docs/agent/secrets_scripts/secrets_tester.ps1
> +"Waiting a second so the process can fetch the secrets"
issue is we're not really waiting for the process to fetch anything. If it take more than 1s we're not going to wait more.

2019-01-15 22:38 UTC, derekwbrown requested changes
couple more nits.  feel free to merge after changing.

2019-01-15 22:38 UTC, derekwbrown commented on docs/agent/secrets.md
> +   is never save anywhere). In Powershell run:
`saved`

2019-01-15 22:38 UTC, derekwbrown commented on docs/agent/secrets.md
> +3. Update the password to be use by `DatadogAgent` service in the Service
`to be used`

2019-01-15 22:38 UTC, derekwbrown commented on docs/agent/secrets.md
> +agent run your executable.
`runs`

2019-01-16 15:06 UTC, merged