Bump python to 3.12
DataDog/datadog-agent pull request #28492
Opened 2024-08-14 18:33 UTC by Kyle-Neale

### What does this PR do?
Bump Python 3 to 3.12.4

### Motivation
https://datadoghq.atlassian.net/browse/AI-4081

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-08-14 20:43 UTC, michaelcretzman approved these changes

2024-08-14 21:23 UTC, sgnn7 commented
@Kyle-Neale Just a heads up on this: https://github.com/DataDog/datadog-agent/blob/main/rtloader/three/three.cpp#L83-L88 (not sure if it's still relevant)

2024-08-15 15:04 UTC, vickenty approved these changes

2024-08-19 08:00 UTC, CelianR approved these changes

2024-08-19 14:41 UTC, CelianR approved these changes

2024-08-19 14:41 UTC, CelianR commented on docs/dev/agent_dev_env.md
> +sudo apt-get install 3.12-dev
```suggestion
sudo apt-get install python3.12-dev
```

2024-08-19 14:41 UTC, CelianR commented on docs/dev/agent_dev_env.md
> +PYTHONPATH="./venv/lib/3.12/site-packages:$PYTHONPATH" ./agent run ...
```suggestion
PYTHONPATH="./venv/lib/python3.12/site-packages:$PYTHONPATH" ./agent run ...
```

2024-09-05 13:38 UTC, paulcacheux requested changes, later dismissed

2024-09-05 13:38 UTC, paulcacheux commented on release.json
> +        "INTEGRATIONS_CORE_VERSION": "4b6dc11485e3ebef660b64d08ddc1e61b47732c5",
Shouldn't this stay "master" ?

2024-09-20 13:00 UTC, alopezz approved these changes

2024-09-20 13:09 UTC, FlorentClarret approved these changes

2024-09-25 08:45 UTC, kacper-murzyn approved these changes

2024-09-30 09:19 UTC, Kyle-Neale commented
/merge

2024-09-30 11:22 UTC, vivek-datadog approved these changes

2024-09-30 12:06 UTC, merged