Update the latest stable version
DataDog/datadog-agent pull request #28964
Opened 2024-09-02 13:50 UTC by FlorentClarret

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-09-02 13:52 UTC, paulcacheux approved these changes

2024-09-02 13:53 UTC, paulcacheux requested changes

2024-09-02 13:53 UTC, paulcacheux commented on 7562
maybe not ?

2024-09-02 13:54 UTC, FlorentClarret commented on 7562
Correct, thanks

2024-09-02 13:54 UTC, paulcacheux approved these changes

2024-09-02 13:54 UTC, carlosroman approved these changes

2024-09-02 14:01 UTC, AliDatadog approved these changes

2024-09-02 17:26 UTC, alexn-dd approved these changes

2024-09-03 07:17 UTC, FlorentClarret commented
/merge

2024-09-03 08:25 UTC, merged