Jaime/authtoken
DataDog/datadog-agent pull request #29069
Opened 2024-09-05 00:17 UTC by truthbk

### What does this PR do?

This PR ensures all requests to the flare/FA extension contain a valid authtoken to serve said requests.

### Motivation

Prevent snooping by unauthorized guests.

### Additional Notes

### Possible Drawbacks / Trade-offs

This work requires the modularization of the `comp/api/authtoken` component, which adds to the proliferation of modules. :(

`otel-agent` must have access to the `auth_token`, while most of our deployments already account for this, it's important for the `otel-agent` to have accesso to the *same* access token created by the core agent at startup.

### Describe how to test/QA your changes

2024-09-05 14:11 UTC, jackgopack4 commented
seeing the errors in the pipeline; instructions in https://github.com/DataDog/datadog-agent/blob/main/docs/dev/modules.md should help (I've been dealing with this with my ticket)

2024-09-05 14:18 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
> +	github.com/DataDog/datadog-agent/comp/core/config => ../../../comp/core/config
```suggestion
	github.com/DataDog/datadog-agent/comp/core/config => ../../core/config
	github.com/DataDog/datadog-agent/comp/core/flare/builder => ../../core/flare/builder
	github.com/DataDog/datadog-agent/comp/core/flare/secrets => ../../core/flare/secrets
	github.com/DataDog/datadog-agent/comp/core/log/def => ../../core/log/def
	github.com/DataDog/datadog-agent/comp/core/log/mock => ../../core/log/mock
	github.com/DataDog/datadog-agent/comp/core/secrets => ../../core/secrets
```

2024-09-05 14:20 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
> +	github.com/DataDog/datadog-agent/comp/def => ../../../comp/def
```suggestion
	github.com/DataDog/datadog-agent/comp/def => ../../def
```

2024-09-05 14:24 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
> +	github.com/DataDog/datadog-agent/pkg/util/fxutil => ../../../pkg/util/fxutil
```suggestion
	github.com/DataDog/datadog-agent/pkg/util/fxutil => ../../../pkg/util/fxutil
	github.com/DataDog/datadog-agent/pkg/util/hostname/validate => ../../../pkg/util/hostname/validate
```

2024-09-05 14:25 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
> +	github.com/DataDog/datadog-agent/pkg/util/log/setup => ../../../pkg/util/log/setup
```suggestion
	github.com/DataDog/datadog-agent/pkg/util/log/setup => ../../../pkg/util/log/setup
	github.com/DataDog/datadog-agent/pkg/util/optional => ../../../pkg/util/optional
	github.com/DataDog/datadog-agent/pkg/util/pointer => ../../../pkg/util/pointer
```

2024-09-05 14:26 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
> +	github.com/DataDog/datadog-agent/pkg/util/scrubber => ../../../pkg/util/scrubber
```suggestion
	github.com/DataDog/datadog-agent/pkg/util/scrubber => ../../../pkg/util/scrubber
	github.com/DataDog/datadog-agent/pkg/util/system => ../../../pkg/util/system
	github.com/DataDog/datadog-agent/pkg/util/system/socket => ../../../pkg/util/system/socket
	github.com/DataDog/datadog-agent/pkg/util/winutil => ../../../pkg/util/winutil
	github.com/DataDog/datadog-agent/pkg/version => ../../../pkg/version
```

2024-09-05 14:28 UTC, jackgopack4 commented on comp/api/authtoken/go.mod
not sure if all of the replaces for the implicit dependencies are necessary or not but put them here in case it helps

2024-09-05 19:10 UTC, jackgopack4 commented on go.mod
> +go 1.22.5
```suggestion
go 1.22.0
```

2024-09-05 19:11 UTC, jackgopack4 requested changes
Looks good to me but want to make sure you run another inv -e tidy after making sure you're using go version 1.22.0 so as to not change the version of the root go.mod, and make sure the modules are listed as `used_by_otel=True` in `modules.py`

2024-09-06 09:38 UTC, ogaca-dd approved these changes
LGTM for files owned by ASC (after fixing [jackgopack4](https://github.com/jackgopack4) comment)

2024-09-06 17:27 UTC, jackgopack4 reviewed
looks like line 214 of modules.py needs a used_by_otel=True, just pushed a change to do that

2024-09-06 17:31 UTC, jackgopack4 approved these changes

2024-09-09 11:09 UTC, GustavoCaso commented
@truthbk wondering if we need to increase the granularity with the module creation. Currently there are two implementations for authtoken. 

Should we create a separate module out of each implementation? I believe that was the intended use of the different implementation folder layout.

2024-09-09 14:42 UTC, GustavoCaso commented
@truthbk I here your concerns about the proliferation of Go modules. 

I just find that there is a discrepancy between the components documentation and the approach taken in this PR. 

In the component documentation we state that we should create different go modules for the interface, implementations and mocks https://datadoghq.dev/datadog-agent/components/creating-components/#go-module

2024-09-09 15:00 UTC, dustmop commented
@GustavoCaso One important thing to note is that the authtoken module in question is still using the "classic" style of definition, not the new layout with `def`, `impl`, `fx` folders. Converting it to the new format could be done, but I'm not sure there's an immediate need to do so. As long as its using the classic style, there's not much benefit to increasing the module granularity as you're describing, since the definition of the component is in the root folder. Anything depending on it will also be pulling in both child folders with the implementations.

2024-09-09 15:39 UTC, GustavoCaso commented
Thanks for the clarification @dustmop 

@truthbk I was confused about the file hierarchy of the authtoken component 🤦. Please discard my comment

2024-09-26 15:18 UTC, ankitpatel96 approved these changes

2024-09-27 07:28 UTC, CelianR approved these changes

2024-09-27 09:23 UTC, pducolin approved these changes

2024-09-27 12:27 UTC, truthbk commented
/merge

2024-09-27 12:47 UTC, merged