Cluster Agent HPA metrics case support
DataDog/datadog-agent pull request #2907
Opened 2019-01-18 17:58 UTC by CharlyF

### What does this PR do?

It was [brought up](https://github.com/kubernetes/kubernetes/issues/72996) to our attention that the Cluster Agent does not support the upper case on metrics.
The issue being that Kubernetes converts the resources to lower case. This PR forces the lower case on metrics and labels.

### Motivation

Better support for the external metrics provider.

2019-01-22 15:57 UTC, xvello requested changes
Looks solid, we might have missed a code branch though

2019-01-29 09:50 UTC, CharlyF commented on pkg/util/kubernetes/hpa/processor.go
> +		return fmt.Sprintf("%s{*}", strings.ToLower(name))
right, updating now

2019-01-29 10:12 UTC, xvello submitted a review, later dismissed

2019-01-29 16:41 UTC, xvello approved these changes

2019-01-29 16:42 UTC, merged