usm: Refactor SSL monitor to use new uprobe attacher
DataDog/datadog-agent pull request #29313
Opened 2024-09-12 15:32 UTC by gjulianm

### What does this PR do?

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

2024-09-13 09:56 UTC, gjulianm commented
/trigger-ci

2025-04-28 10:28 UTC, guyarb requested changes

2025-04-28 10:28 UTC, guyarb commented on pkg/network/usm/ebpf_ssl.go
> +	UsmTLSAttacherName = "usm_tls"
originally it was `shared_libraries`, what's going to be the impact?

2025-04-28 10:28 UTC, guyarb commented on pkg/network/usm/ebpf_ssl.go
> +		EnablePeriodicScanNewProcesses: false,
why false? there's a logic today to run periodic scan (inside the watcher)

2025-04-28 10:28 UTC, guyarb commented on pkg/network/usm/ebpf_ssl.go
> +	o.attacher, err = uprobes.NewUprobeAttacher(consts.USMModuleName, UsmTLSAttacherName, attacherConfig, m, nil, &uprobes.NativeBinaryInspector{}, monitor.GetProcessMonitor())
instead of nil, please use the `NopOnAttachCallback`

2025-04-28 10:28 UTC, guyarb commented on pkg/network/usm/ebpf_ssl.go
> +		PerformInitialScan:             true,
since we do provide the process monitor, why do need the initial scan? according to the documentation, those should be mutual exclusive

2025-04-29 16:54 UTC, gjulianm commented on pkg/network/usm/ebpf_ssl.go
> +	UsmTLSAttacherName = "usm_tls"
Effect is only for tests and debugging. I wasn't aware of the original name though, I can revert it back to `shared-libraries`.

2025-04-29 16:56 UTC, gjulianm commented on pkg/network/usm/ebpf_ssl.go
> +		PerformInitialScan:             true,
I don't think it's really needed, but the watcher does the same initial scan (https://github.com/DataDog/datadog-agent/blob/guillermo.julian/uprobe-attacher-ssl/pkg/network/usm/sharedlibraries/watcher.go#L226) so I replicated that.

2025-04-29 17:04 UTC, gjulianm commented on pkg/network/usm/ebpf_ssl.go
> +		EnablePeriodicScanNewProcesses: false,
Originally the watcher only scanned for dead processes, I wasn't aware of #32400. Will switch this to `true` in this PR, and also will make a separate one for the uprobe attacher to replicate the behavior of the multiple sync.

2025-04-29 17:04 UTC, gjulianm commented on pkg/network/usm/ebpf_ssl.go
> +	o.attacher, err = uprobes.NewUprobeAttacher(consts.USMModuleName, UsmTLSAttacherName, attacherConfig, m, nil, &uprobes.NativeBinaryInspector{}, monitor.GetProcessMonitor())
Changed

2025-04-29 17:36 UTC, guyarb commented
I'll run tomorrow a longer (24h) load-test of openssl to get more confidence in the change

2025-04-29 17:39 UTC, gjulianm commented on pkg/network/usm/ebpf_ssl.go
> +		EnablePeriodicScanNewProcesses: false,
In #32400 a process is scanned at most two times. In the case of the uprobe attacher, for shared libraries it will scan the libraries of a process every time it sees it instead. I just noticed this undesired behavior now, as the periodic scan previously was only enabled for processes so I was relying on the registry to avoid looking repeatedly into the same process.

2025-04-29 18:08 UTC, gjulianm commented
> I'll run tomorrow a longer (24h) load-test of openssl to get more confidence in the change

For openssl, can you wait until I merge the other PR for the attacher? Just to ensure that we're comparing with the same behavior.

2025-05-12 23:59 UTC, brycekahle approved these changes

2025-05-14 10:17 UTC, guyarb commented
load test results - 
[https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUs[…]penssl&from_ts=1747124945308&to_ts=1747197443353&live=false](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-http2-openssl-base&tpl_var_client-service%5B0%5D=python-k6-client-http2-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-http2-openssl-new&tpl_var_http.version%5B0%5D=http%2F2&tpl_var_kube_cluster_name%5B0%5D=usm2&tpl_var_server-service%5B0%5D=python-httpbin-http2-tls&tpl_var_tls.library%5B0%5D=openssl&from_ts=1747124945308&to_ts=1747197443353&live=false)
[https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUs[…]penssl&from_ts=1747124945308&to_ts=1747197443353&live=false](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-grpc-openssl-base&tpl_var_client-service%5B0%5D=python-k6-client-grpc-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-grpc-openssl-new&tpl_var_kube_cluster_name%5B0%5D=usm2&tpl_var_server-service%5B0%5D=python-grpcbin-tls&tpl_var_tls.library%5B0%5D=openssl&from_ts=1747124945308&to_ts=1747197443353&live=false)
[https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUs[…]penssl&from_ts=1747124945308&to_ts=1747197443353&live=false](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-http-openssl-base&tpl_var_client-service%5B0%5D=python-k6-client-http-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-http-openssl-new&tpl_var_http.version%5B0%5D=http%2F1.1&tpl_var_kube_cluster_name%5B0%5D=usm2&tpl_var_server-service%5B0%5D=python-httpbin-tls&tpl_var_tls.library%5B0%5D=openssl&from_ts=1747124945308&to_ts=1747197443353&live=false)


agreed with Guillermo, to wait until 7.67 cutoff

2025-05-17 07:40 UTC, guyarb approved these changes

2025-05-17 07:40 UTC, guyarb commented
/merge

2025-05-17 08:32 UTC, merged