Add option for JSON output to the check command
DataDog/datadog-agent pull request #2954
Opened 2019-01-25 06:43 UTC by ofek

### What does this PR do?

Add a `--json` flag to the `check` that will output all aggregator data as JSON.

### Motivation

Easier parsing for external consumers, particularly new e2e features coming to `ddev` very soon (next week)

### Additional Notes

I don't know how to remove/only access the redundant `series` mapping for metrics seemingly created by https://github.com/DataDog/datadog-agent/blob/b2d9527ec0ec0eba1a7ae64585df443c5b761610/pkg/metrics/series.go#L109-L122

### Example

```
$ "C:\Program Files\Datadog\Datadog Agent\embedded\agent.exe" check --json vault
=== JSON ===
{
  "metrics": {
    "series": [
      {
        "metric": "vault.is_leader",
        "points": [
          [
            1548396938,
            0
          ]
        ],
        "tags": [
          "instance:foobar",
          "is_leader:false"
        ],
        "host": "ozone",
        "type": "gauge",
        "interval": 0,
        "source_type_name": "System"
      }
    ]
  },
  "service_checks": [
    {
      "check": "vault.unsealed",
      "host_name": "ozone",
      "timestamp": 1548396938,
      "status": 0,
      "message": "",
      "tags": [
        "instance:foobar",
        "is_leader:false",
        "cluster_name:vault-cluster-beebc413",
        "vault_version:1.0.2"
      ]
    },
    {
      "check": "vault.initialized",
      "host_name": "ozone",
      "timestamp": 1548396938,
      "status": 0,
      "message": "",
      "tags": [
        "instance:foobar",
        "is_leader:false",
        "cluster_name:vault-cluster-beebc413",
        "vault_version:1.0.2"
      ]
    },
    {
      "check": "vault.can_connect",
      "host_name": "ozone",
      "timestamp": 1548396938,
      "status": 0,
      "message": "",
      "tags": [
        "instance:foobar",
        "is_leader:false",
        "cluster_name:vault-cluster-beebc413",
        "vault_version:1.0.2"
      ]
    }
  ]
}
=========
Collector
=========

  Running Checks
  ==============

    vault (1.3.1)
    -------------
      Instance ID: vault:918f116db5201c87 [OK]
      Total Runs: 1
      Metric Samples: Last Run: 1, Total: 1
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 3, Total: 3
      Average Execution Time : 14ms
```

2019-01-25 08:17 UTC, gzussa submitted a review, later dismissed
Looks good to me 👍

2019-01-25 16:21 UTC, nmuesch requested changes
Overall looks good. Left two comments.

2019-01-25 16:21 UTC, nmuesch commented on cmd/agent/app/check.go
> +	checkCmd.Flags().BoolVarP(&formatJSON, "json", "", false, "format aggregator output as json")
Can we update the help text a bit to reflect the fact that you don't get all the same data in json, only the series data? Or, better, could we serialize the Check status section to json as well?

2019-01-25 16:21 UTC, nmuesch commented on cmd/agent/app/check.go
> +		if formatJSON {
Can we put this in its own printJson function and just do the if branch once?

2019-01-28 08:39 UTC, remeh approved these changes
Left a few comments. Overall works well!

2019-01-28 08:39 UTC, remeh commented on cmd/agent/app/check.go
> +				checkStatus, _ := status.GetCheckStatus(c, s)
That's sad that even in the original code they were some errors silented on this.

2019-01-28 08:39 UTC, remeh commented on cmd/agent/app/check.go
> +				collectorJSON, _ := status.GetCheckStatusJSON(c, s)
This silented error is not dramatic but could lead to the next lines to crash, it may be better to handle them gracefully.

2019-01-28 08:39 UTC, remeh commented on cmd/agent/app/check.go
> +				json.Unmarshal(collectorJSON, &collectorData)
Here too (I know, the chances are ridiculously small...)

2019-01-28 08:39 UTC, remeh commented on cmd/agent/app/check.go
> +				checkRuns := collectorData["runnerStats"].(map[string]interface{})["Checks"].(map[string]interface{})[checkName].(map[string]interface{})
Same goes for those unchecked type asserts. At some point I'm wondering if we shouldn't create a special `struct` to Unmarshal this specific data? By doing this you would manipulate a cleaner object and you would only have to check the Unmarshal err to ensure you have the data you want.

2019-01-28 15:57 UTC, ofek commented
As discussed offline, this will be improved in a future PR

2019-01-28 16:01 UTC, nmuesch approved these changes
Thanks for addressing those, looks good to me!

2019-01-28 16:02 UTC, merged