[Fleet Automation] Sign and deploy the PowerShell script
DataDog/datadog-agent pull request #29605
Opened 2024-09-26 14:28 UTC by julien-lebot

### What does this PR do?
This PR adds a couple of jobs to sign and deploy the PowerShell install script.
It also deploys the bootstrapper executable for now until we do the changes in agent-release-management.
All the artifacts are uploaded for now in `dd-agent-omnibus` but we can update that later on.

### Motivation
https://datadoghq.atlassian.net/browse/WINA-1027

### Describe how to test/QA your changes

### Possible Drawbacks / Trade-offs
The final artifacts will have to be deployed to `ddagent-windows-stable`, be properly versioned and accounted for in `agent-release-management`.

### Additional Notes

2024-09-27 12:50 UTC, chouquette approved these changes
LGTM for agent-delivery

2024-09-27 13:20 UTC, clarkb7 approved these changes

2024-09-27 14:18 UTC, chouquette commented on .gitlab/powershell_script_deploy/powershell_script_deploy.yml
Since this is quite release related, should @DataDog/agent-delivery be co-owner?

2024-09-27 14:19 UTC, chouquette commented on .gitlab/powershell_script_signing/powershell_script_signing.yml
Same CODEOWNER related question as above

2024-09-27 17:50 UTC, chouetz requested changes
Request change for job owner addition and rule test. If not already done, you can also run a full pipeline.

2024-09-27 17:50 UTC, chouetz commented on .gitlab/powershell_script_deploy/powershell_script_deploy.yml
> +powershell_script_deploy:
Can you please add a JOBOWNERS entry for each new job you added?

2024-09-27 17:50 UTC, chouetz commented on .gitlab/powershell_script_deploy/powershell_script_deploy.yml
> +    !reference [.manual]
You might need a rule to exclude it from MQ pipeline generation. You can test it with `inv pipeline.test-mq` (non 100% sure of the task name)

2024-09-27 17:50 UTC, chouetz commented on .gitlab/powershell_script_deploy/powershell_script_deploy.yml
> +    - ls $WINDOWS_POWERSHELL_DIR
Nit: is it for tracing purpose? Is there a reason to use `before_script`?

2024-09-27 17:50 UTC, chouetz commented on .gitlab/powershell_script_signing/powershell_script_signing.yml
> +
Nit: new line warning

2024-09-30 12:33 UTC, chouetz approved these changes

2024-09-30 12:33 UTC, chouetz commented on .gitlab/powershell_script_deploy/powershell_script_deploy.yml
> +windows_bootsrapper_deploy:
🥜 
```suggestion
windows_bootstrapper_deploy:
```

2024-09-30 12:33 UTC, chouetz commented on .gitlab/JOBOWNERS
> +windows_bootsrapper_deploy             @DataDog/windows-agent
🥜 
```suggestion
windows_bootstrapper_deploy             @DataDog/windows-agent
```

2024-09-30 14:12 UTC, merged