add minimal test for otel agent BYOC Docker build
DataDog/datadog-agent pull request #29807
Opened 2024-10-04 16:01 UTC by jackgopack4

### What does this PR do?

### Motivation

### Describe how to test/QA your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-10-07 14:40 UTC, amenasria approved these changes
LGTM for Agent DevX Infra owned files !

2024-10-07 15:17 UTC, dineshg13 requested changes

2024-10-07 15:17 UTC, dineshg13 commented on .gitlab/integration_test/otel.yml
> +    - cp comp/otelcol/collector-contrib/impl/manifest.yaml /tmp/otel-ci/
can u modify manifest.yaml , by adding a component not present in the default build ? either metricstransform processor or something else

2024-10-09 17:10 UTC, jennchenn approved these changes
approving the change to have otel own the new test being added

2024-10-10 15:46 UTC, dineshg13 approved these changes

2024-10-10 17:02 UTC, jackgopack4 commented
/merge

2024-10-10 17:59 UTC, merged