Enable ReceiveResourceSpansV2 by default in OTel Agent
DataDog/datadog-agent pull request #30393
Opened 2024-10-22 19:10 UTC by IbraheemA

### What does this PR do?

Set `enable_receive_resource_spans_v2` flag by default in Converged Agent. This enables the refactor of the span receiver in trace agent, from https://github.com/DataDog/datadog-agent/pull/29435.

Also, honour the `DD_APM_FEATURES` env variable and the `apm_config.features` core config option if either of them is set. The former takes precedence over the latter. 

### Motivation

### Describe how to test/QA your changes

1. Run the otel agent with no APM features set, and verify that the V2 Receiver logic is correctly used (e.g. "resource-related values (container, env, hostname) [aren't checked for] in span attributes"

2. Run the otel agent with `DD_APM_FEATURES=""` and verify that the V1 receiver logic is used.

### Possible Drawbacks / Trade-offs

Users may be trying to set other DD_APM_FEATURES (e.g. they set `DD_APM_FEATURES=sql_cache`) and disable enable_receive_resource_spans_v2 without realizing. Open to suggestions for how we should address this while retaining the option for users to disable `enable_receive_resource_spans_v2` intentionally.

### Additional Notes

2024-10-22 19:57 UTC, dineshg13 requested changes

2024-10-22 19:57 UTC, dineshg13 commented on cmd/otel-agent/config/agent_config.go
> +		pkgconfig.Set("apm_config.features", strings.Split(apmConfigFeaturesEnv, ","), pkgconfigmodel.SourceEnvVar)
Check for `pkgconfig.Get("apm_config.features") != nil ` it should suffice . It should read from the env var as well.

2024-10-22 19:57 UTC, dineshg13 commented on cmd/otel-agent/config/agent_config.go
> +					}
it seems complicated and hard to follow. Can we simplify this

2024-10-22 20:36 UTC, jhgilbert approved these changes
Approved with minor suggestions for style, thank you!

2024-10-22 21:07 UTC, IbraheemA commented
@jhgilbert did you mean to add comments? I can't see any

2024-10-23 14:22 UTC, dineshg13 approved these changes
LGTM. Can you please add how to verify that v2 is running in the OTel Agent

2024-10-23 21:02 UTC, IbraheemA commented
/merge

2024-10-23 21:23 UTC, merged