Sopell/dev container deploy main
DataDog/datadog-agent pull request #31355
Opened 2024-11-21 19:27 UTC by spencergilbert

### What does this PR do?

### Motivation

### Describe how to test/QA your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-11-21 20:54 UTC, sblumenthal approved these changes

2024-11-22 08:19 UTC, FlorentClarret requested changes

2024-11-22 08:22 UTC, FlorentClarret commented on .gitlab/dev_container_deploy/docker_linux.yml
> +      allow_failure: true
If we are to modify the other job, I would keep both tags and run the job in parallel so we have both `master-py3` and `<hash>-py3`

2024-11-22 08:49 UTC, L3n41c requested changes
`docker.io/datadog/agent-dev` is most probably not what we want to run automated SMP tests.
It will generate tons of images that don’t deserve long term storage on a public registry.
And more importantly, **SMP tests stability will be affected by the Docker Hub pull rate limit.**

We had a similar need for e2e tests: being able to unambiguously identify docker images built from `main` commits without being confused by overwritten “floating” tags.
*I.e.* avoid the following scenario:
```
      Pipeline 1                Pipeline 2
          |                         |
          |                         |
    Build and push                  |
`agent-dev:master-py3`              |
  image from commit A               |
          |                         |
          |                         |
          |                   Build and push
          |               `agent-dev:master-py3`
          |                 image from commit B
          |                         |
          |                         |
   Run test with                    |
`agent-dev:master-py3`              |
 and pretends that’s                |
   about commit A                   |
          |                         |
          |                         |
          |                  Run test with
          |               `agent-dev:master-py3`
          |                and pretends that’s
          |                  about commit B
          |                         |
          |                         |
          V                         V
```
where the pipeline `1` would report test results about commit `A` after having tested a docker image built from commit `B` instead.

What we do for our e2e tests is that we publish images tagged by the git commit sha on the AWS private ECR registry of the AWS project where the e2e tests are run:
https://github.com/DataDog/datadog-agent/blob/45b588076d6ce9e474739c1256e124f70d2694ae/.gitlab/dev_container_deploy/e2e.yml#L3-L18
```console
$ AWS_PROFILE=exec-sso-agent-qa-account-admin crane ls 669783387624.dkr.ecr.us-east-1.amazonaws.com/agent
49612871-a1662149
49591768-8988d042
49691065-3b5f561e-7-ot-beta
49595815-86294db5
49642736-e899ec25-7-ot-beta
49643240-e94ccfc5
49691065-3b5f561e
[…]
```

I suppose we would need something similar for SMP tests.

Also, we shouldn’t forget to expire git commit sha-tagged docker image to avoid having to pay for their storage forever.

Ex. for the registry used by e2e tests:
```console
$ AWS_PROFILE=exec-sso-agent-qa-account-admin aws ecr get-lifecycle-policy --region us-east-1 --repository-name agent
{
    "registryId": "669783387624",
    "repositoryName": "agent",
    "lifecyclePolicyText": "{\"rules\":[{\"rulePriority\":1,\"description\":\"Delete all images older than 1 day\",\"selection\":{\"tagStatus\":\"any\",\"countType\":\"sinceImagePushed\",\"countUnit\":\"days\",\"countNumber\":1},\"action\":{\"type\":\"expire\"}}]}",
    "lastEvaluatedAt": "2024-11-22T02:49:58.629000+01:00"
}
```

2024-11-25 16:29 UTC, scottopell commented
I support this change for manually publishing `main` images, but I agree that we should work on a more stable workflow for any automation we build around testing `main` images.

As to @L3n41c 's concerns:
1. On accidentally using "torn" floating tags: 100% agree that is a risk, and one of my main drivers for asking for this feature, to disambiguate the `main-py3` tag.
2. On docker-hub rate limits: SMP does not pull directly from docker-hub, we manually mirror all images over to our ECR, so this isn't a concern.
3. On adding more full-featured support for pushing `main` images to SMP's ECR: we have some of this established already ([ref](https://github.com/DataDog/datadog-agent/blob/main/.gitlab/container_build/docker_linux.yml#L66-L77)), however we expire images too aggressively to rely on them existing for anything past a day or two old.

My desire for this is to simply have a way to manually publish a `main` commit to a  unique image ref, that we can then mirror via our existing workflows and run jobs.

2024-11-25 16:43 UTC, scottopell commented on .gitlab/dev_container_deploy/docker_linux.yml
> +        IMG_DESTINATIONS: agent-dev:${IMAGE_TAG}-py3-jmx
This is intentional from my perspective, my ask here is only to have a more stable identifier for _manually_ published images from the `main` branch.

Deferring a more systematic approach for later work, SMP already has images for most `main` commits in our ECR, they just expire too quick, so we can prioritize work to separate those out and expire them less aggressively

2025-01-15 14:09 UTC, closed without merging