Enable Operation/Resource name V2 by default in converged agent
DataDog/datadog-agent pull request #31359
Opened 2024-11-21 20:44 UTC by IbraheemA

### What does this PR do?

Enable updated logic for Operation/Resource name by default for converged agent customers. The v1 logic will be deprecated eventually.

If DD_APM_FEATURES or apm_features.config are specified manually and do not include enable_operation_and_resource_name_logic_v2, the new logic will be disabled.

### Motivation

### Describe how to test/QA your changes

Run otel-agent with no apm_features configured; verify that the new logic is enabled (e.g. by sending spans corresponding to an http server request, and verifying that the operation name is just "http.server.request" instead of a longer name prefixed with "io.opentelemetry."). Then, run otel-agent with DD_APM_FEATURES specified to exclude enable_operation_and_resource_name_logic_v2 and verify that the new logic is disabled.

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-11-22 10:49 UTC, mx-psi approved these changes

2024-11-22 17:25 UTC, drichards-87 approved these changes
Left a suggestion from Docs and approved the PR.

2024-11-22 17:25 UTC, drichards-87 commented on releasenotes/notes/enable-operation-name-v2-by-default-otel-agent-e62cc29df3658bdf.yaml
> +    alignment with OpenTelemetry specifications.
```suggestion
    The `enable_operation_and_resource_name_logic_v2` flag is now set to true by default in Converged Agent. This update changes how operation and resource names are derived from OTLP spans, resulting in shorter, more readable names and better alignment with OpenTelemetry specifications.
```

2024-11-22 17:46 UTC, IbraheemA commented
/merge -c --cancel

2024-11-22 17:46 UTC, IbraheemA commented
/merge -c

2024-11-22 18:54 UTC, IbraheemA commented
/merge

2024-11-25 16:07 UTC, truthbk requested changes

2024-11-25 16:07 UTC, truthbk commented on releasenotes/notes/enable-operation-name-v2-by-default-otel-agent-e62cc29df3658bdf.yaml
> +---
Please remove the changelog entry. We do not want these changes reflected in the chagelog at this time.

2024-11-26 09:12 UTC, truthbk approved these changes

2024-11-26 09:12 UTC, truthbk commented
/merge

2024-11-26 09:32 UTC, merged