[usm] Create entry in `connection_protocol` only if needed
DataDog/datadog-agent pull request #31524
Opened 2024-11-27 13:48 UTC by guyarb

### What does this PR do?

Fixes the current codebase to generate an entry in the `connection_protocol` map only when a connection was classified.

### Motivation

* The map has high utilization rate in production clusters. Once the map is full, we cannot insert new values, and then USM can suffer from inaccuracies when decoding a protocol, and NPM can report wrong protocol for the connection. 
* Reduce pressure on the `connection_protocol` map, but creating an entry only when needed (= when a connection is classified and supported).
* Don't generate entries on `tls_finish` callback.

### Describe how to test/QA your changes

#### UTs
Added a new test to ensure an unclassified connection does not create an entry in the map.
The test passes on the branch but fails on `main` branch prior to the change.
Test `TestUSMSuite/.*/TestProtocolClassification/.*/unclassified`

Other classification tests are passing.

#### Dogfooding

Ran on `oddish-c` without impacting the accuracy or yielding any error.

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-12-01 15:31 UTC, amitslavin requested changes

2024-12-01 15:48 UTC, guyarb commented on pkg/network/usm/tests/tracer_usm_linux_test.go
> +				// Writing a magic and the settings in the same packet to socket.
removed

2024-12-01 15:48 UTC, guyarb commented on pkg/network/usm/tests/tracer_usm_linux_test.go
> +				// Initiate a connection to the TCP server.
removed

2024-12-01 15:48 UTC, guyarb commented on pkg/network/usm/tests/tracer_usm_linux_test.go
> +	// http2 server init
removed

2024-12-01 15:48 UTC, guyarb commented on pkg/network/ebpf/c/protocols/classification/dispatcher-helpers.h
> +            }
yes, as the comment mentioned, it is header for the verifier to be happy

2024-12-01 15:50 UTC, guyarb commented on pkg/network/ebpf/c/protocols/classification/shared-tracer-maps.h
> +static __always_inline protocol_stack_t* get_or_create_protocol_stack(conn_tuple_t *skb_tup) {
`get_protocol_stack_if_exists` returns the stack if it exists in the map
`get_or_create_protocol_stack` returns the stack if if exists, and if not, we add it to the map and then return it

2024-12-01 15:50 UTC, guyarb commented on pkg/network/ebpf/c/protocols/classification/shared-tracer-maps.h
> +        return wrapper;
reason for what?

2024-12-01 16:08 UTC, amitslavin approved these changes

2024-12-02 15:51 UTC, hmahmood approved these changes

2024-12-02 16:20 UTC, guyarb commented
/merge

2024-12-02 16:40 UTC, merged

2025-01-08 12:44 UTC, guyarb commented on pkg/network/ebpf/c/protocols/classification/routing.h
> +    }
Before Adam's change, `has_available_program(__PROG_ENCRYPTION)` returned false, now it returns true

2025-01-08 12:44 UTC, guyarb commented on pkg/network/ebpf/c/protocols/classification/dispatcher-helpers.h
> -    stack->flags |= FLAG_USM_ENABLED;
maybe we should have kept those lines with the simple if clause of
```c
if (stack) {
    // This is used to signal the tracer program that this protocol stack
    // is also shared with our USM program for the purposes of deletion.
    // For more context refer to the comments in `delete_protocol_stack`
    stack->flags |= FLAG_USM_ENABLED;
}
```