Delete test/kitchen folder
DataDog/datadog-agent pull request #31525
Opened 2024-11-27 13:55 UTC by KevinFairise2

### What does this PR do?

Delete test/kitchen folder and update tests that were using this folder to store artifacts.

### Motivation

Cleanup things that we no longer use

### Describe how to test/QA your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-11-28 08:29 UTC, KevinFairise2 commented
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

2024-11-28 15:43 UTC, KevinFairise2 commented
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

2024-11-28 15:43 UTC, KevinFairise2 commented
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

2024-11-29 10:08 UTC, KevinFairise2 commented
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

2024-11-29 14:40 UTC, paulcacheux requested changes

2024-11-29 14:40 UTC, paulcacheux commented on test/new-e2e/tests/security-agent-functional/security_agent_test.go
> +	// flake.Mark(t)
Can you please let this one in for now, we still have a few flakes

2024-11-29 14:50 UTC, KevinFairise2 commented on tasks/security_agent.py
> +TEST_ARTIFACT_DIR = os.path.join(CI_PROJECT_DIR, "test", "new-e2e", "tests", "security-agent-functional", "artifacts")
Wanted to keep the same variable name for security_agent and system_probe. Let's call it `E2E_ARTIFACT_DIR` everywhere

2024-11-29 14:51 UTC, paulcacheux approved these changes

2024-11-29 15:07 UTC, amenasria approved these changes
<!-- Praises highlight something positive. Try to leave at least one of these comments per review (if it exists :^)  -->
**👏 praise:** -10.5k lines, ggwp that's a GOAT PR ❤️‏

2024-11-29 15:11 UTC, pducolin approved these changes

2024-11-29 15:39 UTC, FlorentClarret approved these changes

2024-11-29 16:25 UTC, tbavelier approved these changes

2024-12-02 15:51 UTC, hmahmood approved these changes

2024-12-02 18:00 UTC, AyyLam approved these changes

2024-12-03 16:26 UTC, alexn-dd approved these changes

2024-12-03 16:34 UTC, KevinFairise2 commented
/merge

2024-12-03 17:33 UTC, brycekahle commented on tasks/system_probe.py
> +    # test/files/default/tests/pkg/ebpf/bytecode/testsuite
These comments are not accurate, because it will be rooted in `./test/new-e2e/tests/sysprobe-functional/artifacts`

2024-12-03 17:34 UTC, brycekahle commented on tasks/kmt.py
> +    ctx.run("rm -rf ./test/files/default/tests/pkg")
This used to be `{KITCHEN_ARTIFACT_DIR}/pkg`, should it now be `{E2E_ARTIFACT_DIR}/pkg`?

2024-12-03 17:56 UTC, brycekahle commented on test/kitchen/site-cookbooks/dd-system-probe-check/.gitignore
This file may need to be modified and moved to the new location where these artifacts end up

2024-12-03 17:59 UTC, brycekahle commented on tasks/kernel_matrix_testing/ci.py
> +        junit_archive = self.artifact_file_binary(f"test/{junit_archive_name}", ignore_not_found=True)
This was `{DD_AGENT_TESTING_DIR}/{junit_archive_name}` before, so I think it still needs to match that. I believe the default directory is now `test/new-e2e/tests`.

2024-12-03 18:33 UTC, brycekahle requested changes
Looks like some paths need to synced up with the changes, rather than just removing the `kitchen` part of the path.

2024-12-04 09:15 UTC, KevinFairise2 commented
> Looks like some paths need to synced up with the changes, rather than just removing the `kitchen` part of the path.

Indeed, I first wanted to move the artifacts at the root of `test/` folder and then switched to a folder inside `test/new-e2e/tests` to do the same as what had already been done on security-agent tests. But look like I missed some by doing so.
I think I adressed all the comments, let me know if you see something more

2024-12-04 18:56 UTC, brycekahle approved these changes

2024-12-04 18:56 UTC, brycekahle approved these changes

2024-12-05 12:01 UTC, KevinFairise2 commented
/merge

2024-12-06 08:26 UTC, KevinFairise2 commented
/merge

2024-12-06 09:03 UTC, merged