gotls: Refactor monitor with new uprobe attacher
DataDog/datadog-agent pull request #31759
Opened 2024-12-04 16:00 UTC by gjulianm

### What does this PR do?

### Motivation

### Describe how you validated your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2025-04-28 08:27 UTC, guyarb requested changes

2025-04-29 17:10 UTC, gjulianm commented on pkg/network/usm/ebpf_gotls.go
> +		ScanProcessesInterval:          scanTerminatedProcessesInterval,
Documented `PerformInitialScan`, and changed `EnablePeriodicScanNewProcesses`.

2025-04-29 17:10 UTC, gjulianm commented on pkg/network/usm/ebpf_gotls.go
> +	attacher, err := uprobes.NewUprobeAttacher(consts.USMModuleName, GoTLSAttacherName, attacherCfg, mgr, nil, inspector, procMon)
Changed

2025-04-30 05:01 UTC, guyarb commented
Ran the following load soak-tests for usm - 
1. [http go-tls](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-http-go-tls-base&tpl_var_client-service%5B0%5D=golang-k6-client-http-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-http-go-tls-new&tpl_var_http.version%5B0%5D=http%2F1.1&tpl_var_kube_cluster_name%5B0%5D=usm3&tpl_var_server-service%5B0%5D=golang-httpbin-tls&tpl_var_tls.library%5B0%5D=go&from_ts=1745947900989&to_ts=1745989182000&live=false)
2. [http2 go-tls](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-http2-go-tls-base&tpl_var_client-service%5B0%5D=golang-k6-client-http2-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-http2-go-tls-new&tpl_var_http.version%5B0%5D=http%2F2&tpl_var_kube_cluster_name%5B0%5D=usm1&tpl_var_server-service%5B0%5D=golang-httpbin-http2-tls&tpl_var_tls.library%5B0%5D=go&from_ts=1745974541010&to_ts=1745988941010&live=false)
3. [grpc go-tls](https://dddev.datadoghq.com/dashboard/gqu-2wz-asy/usm-performance-evaluation-20?fromUser=true&refresh_mode=paused&tpl_var_base_agent-env%5B0%5D=pr-31759-grpc-go-tls-base&tpl_var_client-service%5B0%5D=golang-k6-client-grpc-tls&tpl_var_compare_agent-env%5B0%5D=pr-31759-grpc-go-tls-new&tpl_var_kube_cluster_name%5B0%5D=usm3&tpl_var_server-service%5B0%5D=golang-grpcbin-tls&tpl_var_tls.library%5B0%5D=go&from_ts=1745894666493&to_ts=1745981066493&live=false)

No impact was noticed, hence approving the PR

2025-04-30 05:01 UTC, guyarb approved these changes

2025-04-30 11:21 UTC, gjulianm commented
/merge

2025-04-30 12:01 UTC, merged