[AMLII-2146] Implement V1 of the analyze-logs subcommand
DataDog/datadog-agent pull request #32471
Opened 2024-12-23 18:14 UTC by andrewqian2001datadog

### What does this PR do?

### Motivation

### Describe how you validated your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2025-02-07 15:10 UTC, estherk15 approved these changes

2025-02-07 21:08 UTC, soberpeach reviewed
Looks good overall, just a few nits.

2025-02-07 21:08 UTC, soberpeach commented on cmd/agent/subcommands/analyzelogs/command.go
> +		absolutePath = wd + "/" + cliParams.LogConfigPath
It might be better to use something like `filepath.Join()` for this.

2025-02-07 21:48 UTC, gh123man requested changes

2025-02-07 21:48 UTC, gh123man commented on cmd/agent/subcommands/analyzelogs/command.go
> +	cmd.Flags().IntVarP(&cliParams.inactivityTimeout, "inactivity-timeout", "t", 1, "Time (seconds) that the program will wait for new logs before exiting (optional)")
Instead of an `Int` - we can use a duration. This allows users to specify the interval ex:
`1s` or `10m`

[Here is an example](https://github.com/DataDog/datadog-agent/blob/b06928ce6589f5a371b8bf5e96e023638b7b0cad/cmd/agent/subcommands/dogstatsdcapture/command.go#L67)

2025-02-07 21:48 UTC, gh123man commented on cmd/agent/subcommands/analyzelogs/command.go
> +	if outputChan == nil {
Instead of checking if `outputChan` is `nil` and printing errors from inside `runAnalizeLogsHelper` it would be more go idiomatic to return an error as the last return value for the function and check `if err != nil` here and then print the contents of that error

2025-02-07 21:48 UTC, gh123man commented on cmd/agent/subcommands/analyzelogs/command.go
> +	var sources []*sources.LogSource
runAnalyzeLogsHelper is doing a lot of stuff now. Perhapse we can break out the config resolution logic to it's own helper function? ex something like `func getSources() []*sources.LogSource` that encapsulates all the source resolution.

2025-02-07 21:48 UTC, gh123man commented on cmd/agent/subcommands/analyzelogs/command.go
> +	if sources == nil {
Maybe we should flip this logic around:

if `LogConfigPath` points to a valid path on disk, use that config and don't bother setting up autodiscovery, else if the path is invlaid assume it's a check name and spin up the AD logic. 

So something like (considering my above comment about abstracting out config resolution)

```go

fileConfig, err := resolveFileConfig(cliParams.LogConfigPath)

if err != nil {
    // assume it's a check name and not a file
    configs, err := resolveConfigs(cliParams.LogConfigPath)
    
    if err != nil {
    // print error with some context ex: invlaid path or check name
    return 
    } 
}

// Run analyze logs with configs resolved from one of the previous steps
```
(Pseudocode, feel free to restructure as you see fit)

2025-02-07 21:48 UTC, gh123man commented on releasenotes/notes/analyze-logs-v1-4424fd96ceabd42a.yaml
> +    Implements V1 of the analyze logs subcommand. Adds a flag for setting the inactivity timeout, adds support for "check name".
V1 is kind of an internal term for us, users reading our changelog won't know what it means - so i'd strip this down to just `Adds a flag for setting the inactivity timeout, adds support for "check name".`

2025-02-10 15:12 UTC, andrewqian2001datadog commented on cmd/agent/subcommands/analyzelogs/command.go
> +			fmt.Println("Cannot create source")
Think the debug level doesn't show logs, at least when I run something like 
`log.Errorf("WACKTEST")` it doesn't show in the console

2025-02-12 20:55 UTC, gh123man approved these changes

2025-02-12 20:55 UTC, gh123man commented on cmd/agent/subcommands/analyzelogs/command.go
> +		return nil, fmt.Errorf("Invalid file config path or check name")
Does it make sense to nest the underlying `err` (from line `160`)?
(If that error doesn't provide any actionable context, then you can ignore this comment)

2025-02-12 20:57 UTC, soberpeach approved these changes
lgtm

2025-02-14 14:14 UTC, andrewqian2001datadog commented
/merge

2025-02-14 14:41 UTC, merged