[NPM-3666] Add dmesg to agent flare
DataDog/datadog-agent pull request #32559
Opened 2024-12-30 17:55 UTC by pimlu

### What does this PR do?
This adds kernel dmesg to the agent flare.

It already existed in the security agent flare, but was not using system-probe - this PR updates it to query system-probe. The reason is, newer distros require root for dmesg because they are starting to turn on the sysctl `kernel.dmesg_restrict`. For example, this is enabled in [ubuntu 22](https://www.phoronix.com/news/Ubuntu-20.10-dmesg-Needs-Root) because of upstream changes from debian.

### Motivation
Dmesg can be useful to diagnose customer issues

### Describe how you validated your changes

Agent flare, view `system-probe/dmesg.log`

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-12-30 17:56 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +func readAllDmesg() ([]byte, error) {
`readAllDmesg()` is relocated from `flare/archive_linux.go`

2024-12-30 17:56 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +func parseDmesg(buffer []byte) (string, error) {
`parseDmesg()` is relocated from `flare/archive_linux.go`

2025-01-02 20:33 UTC, cswatt approved these changes

2025-01-03 16:55 UTC, misteriaud approved these changes

2025-01-06 16:10 UTC, hmahmood commented on pkg/flare/archive_security.go
> -	linuxKernelSymbols(fb)                        //nolint:errcheck
Did we need to refactor this function?

2025-01-06 19:17 UTC, brycekahle requested changes

2025-01-06 19:17 UTC, brycekahle commented on cmd/system-probe/api/debug/handlers_linux.go
> +	n, err := syscall.Klogctl(syslogActionSizeBuffer, nil)
```suggestion
	n, err := syscall.Klogctl(unix.SYSLOG_ACTION_SIZE_BUFFER, nil)
```

2025-01-06 19:17 UTC, brycekahle commented on cmd/system-probe/api/debug/handlers_linux.go
> +	m, err := syscall.Klogctl(syslogActionReadAll, b)
```suggestion
	m, err := syscall.Klogctl(unix.SYSLOG_ACTION_READ_ALL, b)
```

2025-01-06 19:17 UTC, brycekahle commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += parts[2] + "\n"
Is there a reason we are discarding the log level? It seems like it could be helpful in finding important messages. Perhaps we should translate from the number to the text version of the level and prefix the message?

2025-01-06 21:16 UTC, pimlu commented on pkg/flare/archive_security.go
> -	linuxKernelSymbols(fb)                        //nolint:errcheck
Relevant testing logic:
<img width="721" alt="Screenshot 2025-01-06 at 4 16 38 PM" src="https://github.com/user-attachments/assets/0571fe25-cffa-44b0-a64d-7f5b282247e4" />

2025-01-06 21:23 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +	n, err := syscall.Klogctl(syslogActionSizeBuffer, nil)
That's a good idea, I just moved this code to another file so I didn't read it too closely lol

2025-01-06 21:23 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += parts[2] + "\n"
That makes sense, will update

2025-01-07 15:06 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +	m, err := syscall.Klogctl(syslogActionReadAll, b)
Updated

2025-01-07 16:24 UTC, hmahmood approved these changes

2025-01-07 16:47 UTC, brycekahle commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += line
I think this should be defaulting to `info` level:
> Every text line in a message has its own loglevel. This level is DEFAULT_MESSAGE_LOGLEVEL - 1 (6) unless the line starts with `<d>` where d is a digit in the range 1-7, in which case the level is d

2025-01-07 18:02 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += line
That's a great callout - updated.

2025-01-07 18:29 UTC, hmahmood commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += line
So if `<d>` can be not present in some cases, will the reg exp match?

2025-01-07 19:09 UTC, brycekahle commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += line
The else branch is when the regexp does not match.

2025-01-07 19:10 UTC, pimlu commented on cmd/system-probe/api/debug/handlers_linux.go
> +			result += line
It will not match - in that situation the fields default to:
```
levelName := "info"
message := line
```

2025-01-07 19:10 UTC, brycekahle approved these changes

2025-01-07 19:13 UTC, pimlu commented
/merge

2025-01-07 19:57 UTC, pimlu commented
/remove

2025-01-07 20:06 UTC, pimlu commented
/merge

2025-01-07 21:42 UTC, merged