Add a linter to run type checking for python invoke task.
DataDog/datadog-agent pull request #32584
Opened 2024-12-31 15:48 UTC by ogaca-dd

### What does this PR do?
Add a linter to run type checking for python invoke task using `pyright`.
`pyright` is configured with [pyright.json](https://github.com/DataDog/datadog-agent/compare/olivierg/pyright?expand=1#diff-66feb0f689637045bcb19ac39eb648a7c62be517865f99607711493cd7025dec) which checks only  `python_type_check.py` for now.

### Motivation

### Describe how you validated your changes
Run the linters.

### Possible Drawbacks / Trade-offs

### Additional Notes

2024-12-31 17:07 UTC, pducolin commented
Thank you for the contribution. We are already running some python linters, better moved this to https://github.com/DataDog/datadog-agent/blob/dffd3262934a5540b9bf8e4bd3a743732637ef37/tasks/linter_tasks.py/#L17-L33

2024-12-31 17:09 UTC, pducolin requested changes
Thank you for your contribution.

We already have a python linter task, can you move this there? https://github.com/DataDog/datadog-agent/blob/dffd3262934a5540b9bf8e4bd3a743732637ef37/tasks/linter_tasks.py/#L17-L33

2025-01-02 13:41 UTC, amenasria approved these changes
Left a comment, otherwise LGTM !

2025-01-02 13:41 UTC, amenasria commented on tasks/pyright.json
> +    "extraPaths": [".."],
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❓ question:** ‏Is the `include` needed if the extraPaths is set to `..`?

2025-01-03 14:23 UTC, ogaca-dd commented on tasks/pyright.json
> +    "extraPaths": [".."],
"extraPaths" is needed because our py files import are relative from the root folder. Without `"extraPaths"` the line `"from tasks.go import  check_go_mod_replaces"` does not work because it suppose the code to be run from the root folder which contains the `tasks` folder.

2025-08-03 00:01 UTC, closed without merging