Adding logger best practice section in developer documentation
DataDog/datadog-agent pull request #32591
Opened 2024-12-31 19:11 UTC by misteriaud

### What does this PR do?

### Motivation

### Describe how you validated your changes

### Possible Drawbacks / Trade-offs

### Additional Notes

2025-01-15 12:38 UTC, CelianR approved these changes

2025-01-15 17:34 UTC, urseberry requested changes
Thank you for writing this detailed document!

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +It is accessible via `pkg/util/log` and the `comp/core/log` component wrapper.
```suggestion
You can access logging through `pkg/util/log` and the `comp/core/log` component wrapper.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  American English, British English, Canadian English, etc.
```suggestion
- Messages must be written in English. No preference on which specific English dialect is used, for example,
  American English, British English, or Canadian English.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +- Sentences must be capitalized, and end with a period.
```suggestion
- Sentences must be capitalized and end with a period.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  is simply an ask, but not a hard requirement.
```suggestion
- Use proper spelling and grammar when possible. Because not everyone is a native English speaker, this is an ask, not a hard requirement.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  anything of importance.
```suggestion
- Identifiers or passages of note should be called out by some means such as wrapping them in
  backticks or quotes. Wrapping with special characters can be helpful in drawing the user's eye to anything of importance.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +excess logging (even if we filter it out and it never makes it to the console).
```suggestion
Choosing the right level can be important. Appropriate log levels make it easy for users to understand what they should pay attention to. They also avoid the performance overhead of
excess logging, even if the logs are filtered and never show on the console.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  logging an event at all.
```suggestion
    Trace logging is typically used when instrumenting algorithms and core pieces of logic. Avoid adding trace logging to tight loops or commonly used codepaths. Even when the logs are disabled, logging an event can incur a small overhead.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  but in some cases -- i.e. if it happens every 1000th event, etc -- it can safely be used.
```suggestion
  Do not use debug logging for things that happen per-event or that scale with event throughput. You can safely use debug logging for uncommon cases, for example, something that happens every 1000th event.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  needs to worry about.
```suggestion
  Info logging is appropriate for logical or temporal events. Examples include notifications when components are stopped and started, or other high-level events that do not require operator attention.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  they just took completed successfully.
```suggestion
  **INFO** is primarily used for information that tells an operator that an action completed successfully.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  level, but it shouldn't be informing them of things serious enough to require immediate attention.
```suggestion
- **WARN**: Something unexpected happened, but no data has been lost and nothing crashed. The system can recover from it without an issue. Do not use **WARN** for events that require immediate attention.
```

2025-01-15 17:34 UTC, urseberry commented on docs/dev/logger.md
> +  ratio in the observability tooling that operators themselves are using.
```suggestion
- **ERROR**: This level includes data loss, unrecoverable errors, and anything else that will require an operator to intervene and recover from. Error logs should be rare to maintain a high signal-to-noise ratio in observability tooling.
```

2025-01-15 21:45 UTC, sgnn7 reviewed
@misteriaud Left some comments

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +It is accessible via `pkg/util/log` and the `comp/core/log` component wrapper.
`wrapper` -> `wrappers` from the suggestion

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +(good) log message:
```suggestion
In general, there are a few rules and a few suggestions to follow when it comes to writing
good log messages:
```

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  American English, British English, Canadian English, etc.
I'd probably opt that we remove the reference to dialect. If we keep the dialect comment, we may want to use `American English` since it would be more consistent with spelling of some key terms in the codebase (e.g. `Initialize`  with ~600+ occurrences vs `Initialise` with ~20 occurences)

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +- Sentences must be capitalized, and end with a period.
@misteriaud This may not apply to formatting errors in Golang so maybe it should note something along the lines of `where applicable`

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  backticks or quotes.  Wrapping with special characters can be helpful in drawing the users eye to
`quotes` -> `quotes (single or double)`

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  explaining the event, with a link to external documentation that explains further.
```suggestion
- If the message is longer than one or two sentences, it's probably better suited as a single sentence briefly
  explaining the event, with a link to external documentation that explains things further.
```

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +excess logging (even if we filter it out and it never makes it to the console).
`Choosing the right level can be important` -> `Choosing the right level is also very important`

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  logging an event at all.
`logging an event can incur a small overhead.` -> `logging an event can incur overheads.`

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  they just took completed successfully.
`that an action completed successfully.` -> `that a notable action completed successfully.`

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  level, but it shouldn't be informing them of things serious enough to require immediate attention.
I'd reword this as:

>  **WARN** should be used for potentially problematic but non-critical events where the software can continue operating, potentially in a degraded state and/or recover from the problem. Do not use **WARN** for events that require operator's immediate attention.

2025-01-15 21:45 UTC, sgnn7 commented on docs/dev/logger.md
> +  ratio in the observability tooling that operators themselves are using.
Maybe:
> - **ERROR** level should be used for events indicating severely problematic issues that require immediate operator visibility and remediation. This includes logging related to events that may lead to data loss, unrecoverable states, and any other situation where a required component is faulty but the software is unable to remediate the problem on its own. Error logs should be extremely rare in normally operating software to ensure high signal-to-noise ratio in observability tooling.

2025-01-16 12:40 UTC, misteriaud commented on docs/dev/logger.md
> +  level, but it shouldn't be informing them of things serious enough to require immediate attention.
I think I tend to prefer @sgnn7 because it's less absolute and let places to cases where data could be lost for exemple.
I just replaced `operator` by `user` in a matter of  consistency.

2025-01-16 12:52 UTC, misteriaud commented on docs/dev/logger.md
> +  ratio in the observability tooling that operators themselves are using.
> ERROR level should be used for events indicating severely problematic issues that require immediate user visibility and remediation. This includes logging related to events that may lead to data loss, unrecoverable states, and any other situation where a required component is faulty, causing the software to be unable to remediate the problem on its own. Error logs should be extremely rare in normally operating software to ensure high signal-to-noise ratio in observability tooling.

I just changed:
- `operator` -> `user` (for a matter of consistency)
- `, causing the software to be unable to remediate the problem on its own`: makes the causality clearer.

2025-01-16 13:04 UTC, misteriaud commented
Thanks a lot @urseberry and @sgnn7 for your relevant feedbacks ! I updated the document based on it, let me know what you think.

2025-01-16 20:12 UTC, sgnn7 approved these changes

2025-01-17 22:21 UTC, urseberry approved these changes

2025-01-21 10:15 UTC, misteriaud commented
/merge

2025-01-21 12:22 UTC, misteriaud commented
/remove

2025-01-22 10:36 UTC, misteriaud commented
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

2025-01-22 10:38 UTC, misteriaud commented
/merge

2025-01-22 12:05 UTC, merged