Fix Issue when cluster-agent seams enable, but dca client not initialized
DataDog/datadog-agent pull request #3383
Opened 2019-04-26 16:15 UTC by clamoriniere

### What does this PR do?

Fix an Agent issue, when configuration says that Cluster-Agent is activated but the cluster-agent is not available (connection failed).

In addition to the check if Cluster-Agent is activated, we check that the DCAClient is properly created.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2019-04-26 16:26 UTC, mfpierre commented
WDYT about rather setting `c.clusterAgentEnabled` to `false` here https://github.com/DataDog/datadog-agent/pull/3383/files#diff-58691a42377df7d0ee1ed4b57a9cf436R56 so we don't have to check for both thing everytime which could be error prone in the futur?

2019-04-26 17:04 UTC, clamoriniere commented
@mfpierre PR ready for a second review

2019-04-26 17:16 UTC, mfpierre requested changes
Unit tests are failing

2019-04-29 09:02 UTC, clamoriniere commented
@mfpierre unit-tests should work now.

2019-04-29 09:28 UTC, mfpierre approved these changes

2019-04-29 10:31 UTC, merged