Updating Cluster Agent changelog
DataDog/datadog-agent pull request #3422
Opened 2019-05-07 10:09 UTC by clamoriniere

### What does this PR do?

add missing version title

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2019-05-07 10:11 UTC, mfpierre submitted a review, later dismissed

2019-05-08 13:54 UTC, CharlyF requested changes
One comment on something that was added in [here](https://github.com/DataDog/datadog-agent/pull/3420/files#diff-922354e511dff93919e32b8ec2b78782R49) but this is not clear, it makes it look like all info logs will be in debug. I don't think it necessarily has to be in the changelog but if you want to have it, let's make sure it's clearer.

Secondly, let's also clarify [this](https://github.com/DataDog/datadog-agent/pull/3420/files#diff-922354e511dff93919e32b8ec2b78782R43) with something like:
> Add cluster_checks.extra_tags option to allow users to add tags globally to the cluster level checks

2019-05-31 16:03 UTC, CharlyF commented on CHANGELOG-DCA.rst
> +- Move some logs info to debug, in order to not generates useless logs in normal case.
```suggestion
- Move some logs from info to debug, in order to generates fewer noisy logs when running correctly.
```

2019-05-31 16:06 UTC, CharlyF approved these changes

2019-05-31 16:49 UTC, merged