Don't require inv params to build a dev agent
DataDog/datadog-agent pull request #3437
Opened 2019-05-09 11:14 UTC by albertvaka

Makes the agent built with default inv commands work (no need to pass `--embedded-path` to inv nor to use `LD_LIBRARY_PATH` to point to dev/lib when loading the binary), just build and run with:

```
    inv six.build
    inv six.install
    inv agent.build
    ./bin/agent/agent
```

2019-05-09 15:33 UTC, hush-hush requested changes

2019-05-09 15:33 UTC, hush-hush commented on README.md
> +5. build the agent with `invoke agent.build --build-exclude=systemd` (with `--use-venv` to use a python virtualenv)
`use-env` is no longer used, we could remove it from our tasks. You need to use `python-home-2` and `python-home-3`

2019-05-09 16:20 UTC, hush-hush commented on docs/dev/agent_dev_env.md
> +- Specify the path when building the agent:
you're more likely to set both to be able to switch using the conf.

2019-05-09 16:20 UTC, hush-hush commented on README.md
> +      using `virtualenv` and then use the `invoke` parameter  `--python-home-2=<venv_path>` or
same here it's `or`/`and`

2019-05-10 15:07 UTC, masci approved these changes
LGTM, thanks for fixing the docs

2019-05-10 15:18 UTC, hush-hush approved these changes

2019-05-10 15:57 UTC, merged