Send logs over HTTP
DataDog/datadog-agent pull request #3497
Opened 2019-05-19 21:50 UTC by achntrl

### What does this PR do?

The PR implements a HTTP client to send logs to our HTTP endpoints. For now, it's not the default behavior, and the HTTP client is hidden behind the new `logs_config.use_http` option

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2019-05-28 12:57 UTC, ajacquemot requested changes
Left a bunch of comments, there is still a bunch of work to do.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/pipeline/pipeline.go
> +	if coreConfig.Datadog.GetBool("logs_config.use_http") {
nits: I think we could merge sender and encoder constructions inside the same block

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/pipeline/pipeline.go
> +		encoder = processor.NewHTTPEncoder()
I don't think we should processing and network are different concerns so the encoder used `with` (not `for`) HTTP should not be called HTTPEncoder but JSONEncoder instead.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/pipeline/pipeline.go
> +		encoder = processor.NewTCPEncoder(endpoints.Main.UseProto)
For this one, we should have ProtoEncoder or RawEncoder depending on use_proto config flag.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/processor/encoder.go
> +var aJsonEncoder jsonEncoder
Let's be consistent
```suggestion
var jsonEncoder json
```

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/config.go
> +const httpEndpointPrefix = "https://http-intake.logs."
what if we want to use `http` instead of `https` ?

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/sender.go
> +			case *tcp.FramingError:
`sender` should be agnostic from the inner transport so we should not have a reference to the `tcp` package.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/sender.go
> +type Sender interface {
it feels like there is an implementation per protocol so I would put the tcp logic under a `tcp` package and the `http` logic under a `http` package

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/sender.go
> +		messageBuffer: NewMessageBuffer(20, 2000000), // TODO change this to paramter
2MB is too high I think, I would lower it down to 1MB

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/sender.go
> +			sendNow, appendAgain := b.messageBuffer.tryAppendToBuffer(payload)
I think append to buffer should not return any logic to know when to send, when to append, this logic should be done inside this method.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +	byteBuffer     []byte
We should use a `bytes.Buffer`, see https://golang.org/pkg/bytes/#Buffer

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +type MessageBuffer struct {
There is no public method for this class.

2019-05-28 12:57 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +	messageBuffer  []*message.Message
there is no need to store the message buffer just to track it's content length, we could just use a counter instead.

2019-05-28 20:55 UTC, ajacquemot commented on pkg/logs/sender/config.go
> +func buildHTTPEndpoints() (*logsConfig.Endpoints, error) {
@ajacquemot add support for `logs_config.logs_dd_url`

2019-05-28 20:57 UTC, ajacquemot commented on pkg/logs/sender/config.go
> +func buildHTTPEndpoints() (*logsConfig.Endpoints, error) {
@ajacquemot fix `useSSL`

2019-05-28 21:00 UTC, ajacquemot commented on pkg/logs/client/http/destination.go
> +	endpoint            config.Endpoint
@ajacquemot remove this, not needed

2019-05-29 06:23 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +	// doesn't fit, which can only be caused by not enough space in byteBiffer
```suggestion
	// doesn't fit, which can only be caused by not enough space in byteBuffer
```

2019-05-29 06:30 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +	// increase the slice length, TODO can optimized this by not using append
and use a bytes.Buffer for example which has been designed to append bytes in an optimized way ? ;)

2019-05-29 06:43 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +type MessageBuffer struct {
This class has two responsibilities, buffering messages and building the payload and I feel like we should rename it as well as define a clear API.
For example:
```
type BatchPayloadBuilder interface {
  func TryAddMessage(msg message.Message) bool
  func Build() []byte
  func Clear()
  func GetMessages() [] message.Message
  func IsEmpty() bool
  func IsFull() bool
}
```

2019-05-29 06:44 UTC, ajacquemot commented on pkg/logs/sender/batch_sender.go
> +	if b.messageBuffer.isEmpty() {
I feel like this check should be done in the callee

2019-05-29 06:47 UTC, ajacquemot commented on pkg/logs/sender/batch_sender.go
> +func (b *BatchSender) sendBuffer() {
this method is a duplicate, let's factorise it.

2019-05-29 06:53 UTC, ajacquemot commented on pkg/logs/client/http/destination.go
> -	resp, err := d.client.Post(d.url, contentType, strings.NewReader(string(payload)))
Why can't we stick to this method, it looks cleaner IMO ? We don't do anything fancy on the request.

2019-05-29 06:54 UTC, ajacquemot commented on pkg/logs/client/http/destination.go
> +	req, err := http.NewRequest("POST", d.url, strings.NewReader(string(payload)))
We need a bunch of constants here:
- POST
- ContentType
- ApplicationJSON
- ...

2019-05-30 13:36 UTC, ajacquemot commented on pkg/logs/sender/message_buffer.go
> +func (mb *MessageBuffer) GetPayload() []byte {
We could also use `NJON` witch content type `text/plain` for better performances.

2019-06-03 16:24 UTC, achntrl reviewed
LGTM, I like how things are packaged 👍

2019-06-03 16:43 UTC, ajacquemot approved these changes

2019-06-03 16:45 UTC, merged