Merge partial logs for kubernetes
DataDog/datadog-agent pull request #3529
Opened 2019-05-22 12:28 UTC by tt810

### What does this PR do?

* Refactor on logs/decoder, logs/line_handler
* Add logic to aggregate partial logs to one full log

### Motivation

Client requests

### Additional Notes

The process logic changed to fix the issue with "...TRUNCATED..." prepend before timestamp.

2019-05-22 15:35 UTC, gaetan-deputier commented on pkg/logs/input/kubernetes/line_handler.go
> +
Worth sharing that method in a util file?

2019-05-22 15:44 UTC, gaetan-deputier commented
LGTM

2019-05-22 15:44 UTC, gaetan-deputier approved these changes

2019-05-23 10:57 UTC, ajacquemot commented on pkg/logs/decoder/line_handler.go
> +type LineHandlerRunner interface {
Why Runner ? Does it run something ?

2019-05-23 10:59 UTC, ajacquemot requested changes
Did not finish to review this, please wait before merging.

2019-05-27 13:04 UTC, ajacquemot reviewed
Left some comments, I think we have all the code, let's reorganise it now to make sur it's easy to read and maintainable.

2019-05-27 13:04 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler.go
> +	content, status, timestamp, flag, err := h.ParseFull(line)
```suggestion
	content, status, timestamp, tag, err := h.ParseFull(line)
```
Does kubernetes call it a `tag` or a `flag` ? Let's be consistent

2019-05-27 13:04 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler.go
> +func (h *LineHandler) process(line []byte) {
I feel like this method is complicate to read and hard to reason about which can be caused by the design we chose, let's discuss it IRL.

2019-06-03 07:02 UTC, ajacquemot reviewed
Left a bunch of comments and a bunch of questions that I think you should address first.

2019-06-03 07:02 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler.go
> +		lineBuffer:      decoder.NewLineBuffer(),
do we really have to use a line buffer here ? Why does this class need to a proper go routine ?

2019-06-03 07:02 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler.go
> +func (h *LineHandler) Start() {
Why does this class need a Start and Stop ?

2019-06-03 07:02 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler.go
> +	go h.RunWithTimer(h.flushTimeout, h.process, h.sendAndReset)
Why does this class need a timer ?

2019-06-03 07:03 UTC, ajacquemot commented on pkg/logs/input/kubernetes/line_handler_test.go
> +func TestMultiLineHandler_SendMultiKubesLines(t *testing.T) {
nits: none of our unit tests follow this format, can you tell me why we should go for this format ?  Can we stay consistent and either update all the code base (in another PR) or keep the current convention ? Thanks!

2019-06-03 08:11 UTC, achntrl reviewed
Agreed with @ajacquemot, I think we have all the code we need to make this work. 

We should setup a meeting to discuss the design of this: 

I find it weird that we pass `contentLenLimit` everywhere even though the value we use is always the same (except in tests) 

I don't like the `LineHandlerRunner` naming either, but I like the pipeline-like design of the LineHandler in k8s that forwards it to the regular LineHandler. But we should probably discuss about the packaging of this code, I'm not sure it should live in the k8s folder

2019-08-29 13:19 UTC, tt810 commented
-

2019-08-29 13:19 UTC, closed without merging