[windows] add `system.mem.pagefile.*` metrics back to memory corecheck.
DataDog/datadog-agent pull request #3582
Opened 2019-05-28 20:29 UTC by derekwbrown

Restores metric lost from A5->A6, so that customers upgrading don't lose
metrics

2019-05-31 11:55 UTC, olivielpeau submitted a review, later dismissed
Nit on the release note, other than that LGTM 👍 

@derekwbrown can you confirm the units for the metrics sent by v6 will be correct in DD?

2019-05-31 11:55 UTC, olivielpeau commented on releasenotes/notes/winpagefilemetrics-b7f354de00af0342.yaml
> +    On Windows, restore the system.mem.pagefile.* metrics
```suggestion
    On Windows, restore the ``system.mem.pagefile.*`` metrics
```

2019-06-01 01:34 UTC, hush-hush requested changes

2019-06-01 01:34 UTC, hush-hush commented on pkg/collector/corechecks/system/memory_windows_test.go
> +	mock.On("Gauge", "system.mem.pagefile.total", 120000.0/mbSize, "", []string(nil)).Return().Times(1)
We no longer send those metrics I think.

2019-06-01 03:37 UTC, hush-hush approved these changes

2019-06-01 03:37 UTC, merged