Do not stop collecting external metrics after 3 failures
DataDog/datadog-agent pull request #3727
Opened 2019-06-20 13:06 UTC by timothysmith0609

### What does this PR do?

- Do not give up trying to refresh external metrics after repeated failures trying to [list external metrics](https://github.com/DataDog/datadog-agent/blob/master/pkg/clusteragent/custommetrics/provider.go#L91)

- Stop trying to refresh external metrics if the underlying ConfigMap is deleted

### Motivation

The `cluster-agent` is responsible for refreshing the external metrics consumed by [HorizontalPodAutoscalers](https://www.datadoghq.com/blog/autoscale-kubernetes-datadog/). The current behaviour, explicitly stated as a code comment, is as follows:
`// If we exceed 3 retries trying to access the ConfigMap, we permafail and stop trying to refresh the External Metrics.` ([see ref](https://github.com/DataDog/datadog-agent/blob/master/pkg/clusteragent/custommetrics/provider.go#L81))

Unfortunately, the API-server may become temporarily unreachable due to reasons both routine and unforeseen. This has led to the following scenario:

- A deployment is managed by an HPA
- A flapping master causes the API-server to become unreachable for a few minutes
- The `cluster-agent` stops updating external metrics and they become stale
- The API-server becomes reachable again, but we have stopped trying to refresh metrics
- The HPA managing the deploy is now useless until we manually kick the `cluster-agent`

In light of this, it makes more sense for the `cluster-agent` to continually retry, instead of bailing out prematurely.

### Additional Notes

The default timeout between attempts is 30 seconds; the cost of continually trying to connect to the API-server in the event of unreachability is therefore quite small. As a first pass, I think this PR is sufficient, but it might be worthwhile in the future to account for various different failure modes. the `k8serrors` package has been imported to provide an easier interface when checking against API-server responses.

2019-06-21 22:46 UTC, irabinovitch commented
@timothysmith0609 Thanks for the PR. We'll take a look soon. In the meantime could you follow the CLA workflow so we're unblocked on licensing?  https://cla.datadoghq.com/DataDog/datadog-agent?pullRequest=3727

Thanks!

2019-06-24 11:47 UTC, hkaj requested changes
Thanks for the contrib @timothysmith0609 !
This part of the code was on our radar as well, except we would prefer improving it with a backoff policy. There are two problems here:
* a missing ConfigMap will make the external metrics provider fail in a single try
* we keep retrying at a constant frequency on the configmap when we could be leaner with an exponential backoff

Could you implement a RateLimiter here instead? Otherwise we'll do it when we get to that task (it's not too far in the backlog). Here's what we were planning on using for this case: https://github.com/kubernetes/client-go/blob/master/util/workqueue/default_rate_limiters.go#L77

Thanks again, and let me know if you have any question or need some guidance.

2019-06-25 12:29 UTC, timothysmith0609 commented
Thanks for the feedback, I'm waiting to hear back on the CLA signing but will sign it as soon as I get the go-ahead.

I was initially going to implement some form of exponential backoff, but didn't want to make too substantive of a change to the logic before hearing the thoughts of those with more experience in this repo (hence why I've opted to start with a very basic PR). I'll update to add proper rate limiting.

>a missing ConfigMap will make the external metrics provider fail in a single try

Hmm, what kind of behaviour would you like to see here? We could log at the error level and continue with exponential backoff as normal. Unless I'm mistaken, this seems like a very rare failure mode and would indicate an issue outside of the cluster-agent itself... in that sense, perhaps rate limiting and logging is the way to go, and app maintainers can setup the necessary alerting as required. What do you think?

2019-06-26 13:15 UTC, hkaj commented
> I was initially going to implement some form of exponential backoff, but didn't want to make too substantive of a change to the logic before hearing the thoughts of those with more experience in this repo.

That makes sense 👍 

> We could log at the error level and continue with exponential backoff as normal. Unless I'm mistaken, this seems like a very rare failure mode and would indicate an issue outside of the cluster-agent itself... in that sense, perhaps rate limiting and logging is the way to go, and app maintainers can setup the necessary alerting as required. What do you think?

This is exactly what I had in mind. This way users can inspect logs, see what's up, create the configmap, and the cluster-agent will pick it up and start working.

2019-07-02 20:35 UTC, timothysmith0609 commented
I'm taking a look at this after doing some other work last week and have a few questions now that I have fresh eyes on this.

>we keep retrying at a constant frequency on the configmap when we could be leaner with an exponential backoff

Currently, the default wait time between requests is 30 seconds, no matter what. That already seems pretty lean. How often _should_ we be updating these metrics? E.g. every 2 seconds, 5 seconds, etc? Intuitively, I would think 30 seconds should be around the _max_ backoff time, or am I mistaken?

>Could you implement a RateLimiter here instead?

To do this, I think I'm going to have to do away with the `Tick.C` channel and wrap the attempts inside a goroutine for loop, while still making accommodations for the `ctxCancel.Cancel` to do appropriate cleanup (that is, gracefully stop the goroutine).

I took a look at the linked rate limiter: I think it will be easier to handroll a `withRetries` helper, instead. The only question to answer at this point is how long to wait between _successful_ requests. Any guidance here is appreciated.

2019-07-05 09:22 UTC, hkaj commented
> Currently, the default wait time between requests is 30 seconds, no matter what. That already seems pretty lean. How often should we be updating these metrics? E.g. every 2 seconds, 5 seconds, etc? Intuitively, I would think 30 seconds should be around the max backoff time, or am I mistaken?

Oh I didn't check what the default was for `maxAge`, 30s seems like a good max backoff time indeed (starting with 2s, 5s, etc. as you suggest).

> To do this, I think I'm going to have to do away with the Tick.C channel and wrap the attempts inside a goroutine for loop, while still making accommodations for the ctxCancel.Cancel to do appropriate cleanup (that is, gracefully stop the goroutine).

Yeah that sounds reasonable.
As for the wait between successful requests let's keep the current behavior governed by Tick.C: waiting for maxAge to be reached, i.e. 30s.

2019-07-08 20:03 UTC, timothysmith0609 commented
One final question: do we need to worry about datadog API rate limits, here? From what I can see, this code only queries the k8s API server, and the metrics themselves are updated out of band, so I don't _think_ it's an issue.

The reason I ask is that we were recently stung by exceeding our DD API rate limit, which broke our HPAs :(

2019-07-08 20:44 UTC, hkaj commented
Oh no! Sorry you hit the api rate limit. We batch metrics queries together in the cluster agent to make as few queries to DD as possible, explicitly to prevent that.

And as you guessed, we also don't trigger a query on the retries you're touching, so that won't be an issue here.

2019-07-09 17:56 UTC, timothysmith0609 commented
Thanks for all the feedback. I've pushed a change that introduces exponential backoff to the `externalMetricsSetter` loop. I opted to do it in a fairly naive way, since the use-case is pretty straightforward and simple (e.g. only 1 cluster-agent ever running at a time). Take a look and let me know what you think.

2019-07-09 21:25 UTC, hkaj reviewed
Thanks @timothysmith0609, that looks good to me. Could you rebase with master? That should fix the CI failure.

2019-07-10 15:21 UTC, timothysmith0609 commented
Re: codecov CI failure: It looks there weren't really any tests for this before my change and it seems quite difficult to actually model in the test suite as it stands. I _did_ validate the structural changes (e.g. ensuring the `select` section works as expected) with some PoC code, so I'm not worried about that. 

Let me know what you want me to do here, please! Thanks

2019-07-10 22:34 UTC, hkaj approved these changes
We'll ignore the codecov failure, it's not relevant here. Just tested your change and it works **great**! Thanks @timothysmith0609

2019-07-10 22:35 UTC, merged

2019-07-11 12:11 UTC, timothysmith0609 commented
Thanks for bearing with me during my first contribution! Do you have an idea of when we can expect this to be released?

2019-07-15 13:41 UTC, hkaj commented
We're aiming at releasing 1.14 in 2 weeks, it should sail with this release. No hard timeline yet but that's the ballpark estimate.

2019-08-29 17:19 UTC, timothysmith0609 commented
@hkaj just wanted to follow up with the release date for DAC 1.4.0. Looks like there's no firm target date yet. Do you have any insight on when we might expect it? Thanks.

2019-09-03 19:25 UTC, CharlyF commented
Hey @timothysmith0609 - Indeed no firm date yet but we would like to target a code freeze before the end of September.

Best,
.C