Added common utility for socks5 proxy and use it for logs
DataDog/datadog-agent pull request #3733
Opened 2019-06-21 06:29 UTC by ajacquemot

### What does this PR do?

Added a common utility for socks5 proxy and use it for logs

### Motivation

Make sure the logs-agent won't break for customers that use a socks5 proxy when they switch to using HTTP.

### Additional Notes

TODO: write unit-tests

2019-07-10 00:03 UTC, ofek requested changes
Hello there!

Have you considered making the scheme influence the underlying behavior, similar to `requests`? https://2.python-requests.org/en/master/user/advanced/#socks

We have this way documented in `integrations-core` https://github.com/DataDog/integrations-core/blob/2d585e871ae29dc968e1dadd1beeb9e340e2c010/spark/datadog_checks/spark/data/conf.yaml.example#L3-L22

2019-07-10 20:15 UTC, hush-hush requested changes

2019-07-10 20:15 UTC, hush-hush commented on pkg/logs/config/config.go
> +		ProxyAddress: proxyAddress,
Could we rename that field to `Socks5ProxyAddress` or something similar with `Socks5` in it ?

2019-07-15 06:24 UTC, ajacquemot commented
Thanks @ofek for the tips, I'll try, if this works, we won't need any of this work.

2019-08-27 08:14 UTC, closed without merging