Explicitly prevent `secrets` from building on windows for the process
DataDog/datadog-agent pull request #3742
Opened 2019-06-22 23:50 UTC by derekwbrown

agent

2019-06-23 14:51 UTC, olivielpeau requested changes

2019-06-23 14:51 UTC, olivielpeau commented on tasks/process_agent.py
> +        build_tags.remove("secrets")
I think this line will actually raise an exception if "secrets" is not in the list of tags, so let's only remove it if it's indeed in the list

2019-06-24 02:53 UTC, olivielpeau approved these changes

2019-06-24 14:12 UTC, sfluor approved these changes

2019-06-24 15:44 UTC, merged