Merge previous audit
DataDog/datadog-agent pull request #3785
Opened 2019-07-01 18:48 UTC by derekwbrown

### What does this PR do?

Merges result of previous audit

### Motivation

Make sure audit is completed

2019-07-02 09:34 UTC, albertvaka submitted a review, later dismissed

2019-07-02 09:34 UTC, albertvaka commented on rtloader/common/builtins/datadog_agent.c
> +error:
I like the old name "done" better, since we end up here even if there are no errors.

2019-07-02 09:43 UTC, olivielpeau requested changes
Thanks! Added a few inline nits, and one important note on an undesired behavior change

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/builtins/datadog_agent.c
> +    // Py_arg_ParseTuple returns a pointer to the existing string in &key
```suggestion
    // PyArg_ParseTuple returns a pointer to the existing string in &key
```

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/builtins/datadog_agent.c
> +    // Py_arg_ParseTuple returns a pointer to the existing string in &message
```suggestion
    // PyArg_ParseTuple returns a pointer to the existing string in &message
```

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/builtins/datadog_agent.c
> +error:
I'd rather call this `done` since it's not only intended to be executed on error

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/builtins/datadog_agent.c
> +            error = 1;
we must not set error here since we want to ignore this item and simply continue iterating through the list

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/stringutils.c
> + * @param object  A Python string to be converted to C-string.
nit: we seem to use the `\` instead of `@` in other files as the doxygen command prefix, I think we should try to be consistent across files.

2019-07-02 09:43 UTC, olivielpeau commented on rtloader/common/stringutils.c
> + * @return A standard C string (NULL terminated character pointer)
ditto

2019-07-08 17:19 UTC, olivielpeau approved these changes
LGTM, nice! :shipit:

2019-07-09 14:11 UTC, merged