[releasenotes] Clarify purpose and usage of the `Upgrade Notes` section
DataDog/datadog-agent pull request #3932
Opened 2019-07-25 13:30 UTC by olivielpeau

### What does this PR do?

Clarifies the purpose and the usage of the `Upgrade Notes` section.

### Motivation

Allow devs to understand what this section is for. Notes in this section should remain rare so that it's easy for a user to quickly know what they need to pay attention to before upgrading.

2019-07-25 13:33 UTC, gbbr submitted a review, later dismissed
Thank you

2019-07-25 18:19 UTC, ruthnaebeck requested changes
Small change

2019-07-25 18:19 UTC, ruthnaebeck commented on docs/dev/contributing.md
> +- `upgrade`: List actions to take or limitations that could arise upon upgrading the agent. Notes here must include steps that users can follow to 1. know if they're affected and 2. handle the change
```suggestion
- `upgrade`: List actions to take or limitations that could arise upon upgrading the Agent. Notes here must include steps that users can follow to 1. know if they're affected and 2. handle the change gracefully on their end.
```

2019-07-26 18:16 UTC, ruthnaebeck approved these changes
👍 for docs

2019-08-05 10:12 UTC, KSerrania approved these changes

2019-08-05 10:13 UTC, merged