[metadata] [checks] check status reported in status command and in metadata
DataDog/datadog-agent pull request #396
Opened 2017-07-20 22:34 UTC by gmmeyer

### What does this PR do?

In the Agent5, we track the check status after every check run. We track if it finished successfully, if there was a warning, or if there was an error. 

We report this on the info page. 

And, we also report this to the Datadog Platform twice:

First with a [service check](https://github.com/DataDog/dd-agent/blob/6f107f8ed7f55f4ffa1724b81916cafb64d91614/checks/collector.py#L446-L452). 

Second with a [metadata upload](https://github.com/DataDog/dd-agent/blob/master/checks/collector.py#L708-L734).

The service check is only used in the same way that any service check is used. The metadata upload is what's used on the infrastructure page to report on check status and print out check errors or warnings.

I agree that it seems odd to duplicate check status like this, and we should see if we can dedupe it at some point. However, at the same time, it probably saves a bit of bandwidth by not sending the errors and warnings on every run, but instead only every 10 minutes. So, it's also likely a minor optimization. And, because of the way the pipeline is structured, the inclusion of this in the metadata instead of in a service check does make sense.

### Additional Notes

I discussed some of these features with @olivielpeau while I was writing it. For example, we put the Warn in the sender to make it clear that this is not just a logging shim of some sort, it's also sending the warning to Datadog.

2017-07-25 09:46 UTC, hush-hush requested changes

2017-07-25 11:07 UTC, masci requested changes
Left few comments, the main concern is the coupling with the Sender that doesn't seem needed.
As a side note, can you fill the PR description to ease reviews?

2017-07-28 15:03 UTC, hush-hush requested changes

2017-07-31 11:17 UTC, masci requested changes

2017-08-02 08:20 UTC, hush-hush approved these changes

2017-08-07 13:30 UTC, masci requested changes

2017-08-10 09:19 UTC, masci approved these changes

2017-08-10 09:20 UTC, merged