Make Python 3 linter timeout configurable
DataDog/datadog-agent pull request #4049
Opened 2019-08-21 16:23 UTC by KSerrania

### What does this PR do?

The Python 3 default linter timeout has been set to 8s, and the option is now configurable in the datadog.yaml configuration file.

### Motivation

The 4s timeout for the Python 3 linter is not enough for some custom checks which take a really long time to be linted.

### Additional Notes

Does this warrant a release note?
Should we advertise this option in the template `datadog.yaml` file?

2019-08-21 17:00 UTC, truthbk reviewed
Can we also improve the logging in case the linter fails? No logging sucks currently, probably something at the info level.

2019-08-21 17:07 UTC, ofek requested changes

2019-08-21 17:07 UTC, ofek commented on pkg/collector/python/py3_checker.go
> +	linterTimeout = time.Duration(config.DataDog.GetInt("python3_linter_timeout")) * time.Second
```suggestion
	linterTimeout = time.Duration(config.Datadog.GetInt("python3_linter_timeout")) * time.Second
```

2019-08-21 17:14 UTC, ofek requested changes
Can you please also log every linter warning (if any)?

2019-08-21 19:15 UTC, truthbk approved these changes
Not sure why the build flaked. I'll take a look if I get a minute, this looks good to me though.

2019-08-21 20:19 UTC, ofek approved these changes

2019-08-22 10:33 UTC, merged

2019-08-22 18:40 UTC, olivielpeau commented on pkg/collector/python/loader.go
> +				log.Warn(warning)
Is `Warn` the right level? I've heard from @therve that the linter could find tens to hundreds of issues for a given check, if that's the case I think we should warn them with `Debug` for example, and mention in the previous log message to `set the log level to "debug" and restart the Agent to have the linter warnings logged` for example