[Doc] Integration Management
DataDog/datadog-agent pull request #4104
Opened 2019-08-30 15:28 UTC by ruthnaebeck

### What does this PR do?
- Remove content and point to the public documentation

### Motivation
- Create a single source for this documentation

### Additional Notes
- Single sourcing approved by Agent team

2019-09-02 07:44 UTC, l0k0ms submitted a review, later dismissed

2019-09-03 15:49 UTC, KSerrania requested changes

2019-09-03 15:49 UTC, KSerrania commented on docs/agent/integration.md
> +Information on integration management is available in the Datagdog documentation:
```suggestion
Information on integration management is available in the Datadog documentation:
```

2019-09-03 17:26 UTC, hush-hush approved these changes

2019-09-05 15:29 UTC, KSerrania approved these changes

2019-09-05 15:41 UTC, merged