Flush data from the aggregator and forwarder when stopping the agent.
DataDog/datadog-agent pull request #4129
Opened 2019-09-06 20:17 UTC by hush-hush

### What does this PR do?

Flush data from the aggregator and forwarder when stopping the agent.

The aggregator will now flush aggregated metrics (closed time buckets and finish check's metrics) to the forwarder. In turn the forwarder will send any waiting new transaction to the backend before stopping (transactions in the retry queue are not retried).

2019-09-09 11:47 UTC, ogaca-dd submitted a review, later dismissed
LGTM

2019-09-09 19:37 UTC, hush-hush commented on pkg/forwarder/worker_test.go
> +
Good idea.

2019-09-29 22:00 UTC, ofek requested changes

2019-09-29 22:00 UTC, ofek commented on releasenotes/notes/flush-data-on-stop-f8a1ab6521076fc9.yaml
> +    `aggregator_stop_timeout` and `forwarder_stop_timeou`.
```suggestion
    `aggregator_stop_timeout` and `forwarder_stop_timeout`.
```

2019-10-03 21:43 UTC, ofek submitted a review, later dismissed

2019-10-04 13:30 UTC, truthbk submitted a review, later dismissed
I don't see anything wrong with this, just a few comments. But it LGTM!

2019-10-07 13:06 UTC, ogaca-dd submitted a review, later dismissed

2019-10-07 16:40 UTC, hush-hush commented on pkg/config/config_template.yaml
> +## You can set the maximum amount of time, in seconds, allocated to the
By default systemd has a 90s default timeout for stopping a service. Windows SCM has a default of 30s. So our 4s default if fine. In both case a user increase the agent timeout they can/have to change the default of our service through systemd and Windows.

But I don't think we will encounter the issue.

2019-10-07 16:41 UTC, hush-hush commented on pkg/aggregator/aggregator.go
> +	agg.stopChan <- struct{}{}
Yes, the goal is to purge data that are ready.

2019-10-07 17:08 UTC, hush-hush commented on pkg/aggregator/aggregator.go
> +		if waitForSerializer {
Yes :+1:

2019-10-07 19:07 UTC, merged