Fix the integration show command
DataDog/datadog-agent pull request #4163
Opened 2019-09-16 21:20 UTC by FlorianVeaux

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2019-09-16 21:23 UTC, trishankatdatadog submitted a review, later dismissed
LGTM

2019-09-16 21:39 UTC, ofek commented on cmd/agent/app/integrations.go
> +	freezeCmd := exec.Command(pythonPath, "-mpip", "freeze", "--no-cache-dir")
Nit
```suggestion
	freezeCmd := exec.Command(pythonPath, "-m", "pip", "freeze", "--no-cache-dir")
```

2019-09-17 14:09 UTC, ofek submitted a review, later dismissed

2019-09-17 18:11 UTC, therve requested changes

2019-09-17 18:11 UTC, therve commented on releasenotes/notes/Use-pip-freeze-to-get-the-version-of-integrations-0af058b8fb39c548.yaml
> +---
I think you want to remove those comments.

2019-09-17 18:11 UTC, therve commented on releasenotes/notes/Use-pip-freeze-to-get-the-version-of-integrations-0af058b8fb39c548.yaml
> +    Use 'pip freeze' to collect the version of the integrations
`pkg_resources` instead.

2019-09-17 18:13 UTC, therve commented on cmd/agent/app/integrations.go
> +print(pkg_resources.get_distribution('%s')._version)
Why not `.version`?

2019-09-18 00:40 UTC, ofek commented on releasenotes/notes/Use-pkg_resources-to-get-the-version-of-integrations-0af058b8fb39c548.yaml
> +    Use 'pkg_resources' to collect the version of the integrations
```suggestion
    Use ``pkg_resources`` to collect the version of the integrations
```

2019-09-23 20:38 UTC, ofek submitted a review, later dismissed

2019-09-24 06:34 UTC, therve submitted a review, later dismissed

2019-09-24 09:28 UTC, AlexandreYang submitted a review, later dismissed
LGTM.

A minor comment.

2019-09-24 09:28 UTC, AlexandreYang commented on cmd/agent/app/integrations.go
> +	version, err := semver.NewVersion(string(outputStr))
(nit) Why the cast is needed here ?

2019-09-24 15:56 UTC, FlorianVeaux commented on cmd/agent/app/integrations.go
> +	version, err := semver.NewVersion(string(outputStr))
It was not :)

2019-09-24 15:57 UTC, AlexandreYang approved these changes

2019-09-24 17:23 UTC, albertvaka approved these changes

2019-09-25 19:44 UTC, merged