Add Invoke as task runner
DataDog/datadog-agent pull request #458
Opened 2017-08-14 13:37 UTC by masci

### What does this PR do?

Adds [invoke](http://www.pyinvoke.org/) as task runner.
To test it out, install Invoke via `brew` or simply via `pip install invoke`.

It already supports parametric tasks but can be further improved, a few examples:
```
inv test
```
behaves like `rake test` but can be also invoked like this:
```
inv test --targets=./pkg/collector/check,./pkg/aggregator
```
to limit the scope of the task to only two packages. Other options can be passed like this (self explanatory):
```
inv test --race
```
The default values for each task (when no command line args are passed) are listed in the `invoke.yaml` file.

Build commands now have a better handling of the bits composing the agent, for example this will build everything except support for SNMP:
```
inv agent.build --build-exclude=snmp
```

There's also its companion:
```
inv agent.build --build-include=zlib
```

You can look at the docstrings for more insights on the commands available.

The README was updated accordingly but the rakefiles are still there, until we're sure that everything works as expected.

### Motivation

Beside my personal hate for Ruby in general and Rake in particular, the rakefiles to build the agent started to be quite complex to maintain and offer way less in terms of features if compared to other task runners like Invoke. Also, having to depend on a working Ruby environment (when we already depend on a working Python env) just for the sake of building the agent locally looks very wrong to me.

### Additional Notes

Invoke tasks can be fully tested, I decided not to follow this path for now but this might change in the future.
By switching to Invoke, Rake won't be needed anymore and Ruby+Bundler will be only needed to build the Omnibus packages.

2017-08-17 11:50 UTC, truthbk reviewed
Man, this is totally awesome! 🍰  

I added some feedback on minor things, but overall this looks great already. I think we're probably ready to  cleanup the rakefiles a lot more too.

2017-08-17 15:50 UTC, hush-hush requested changes

2017-08-17 16:05 UTC, hush-hush requested changes

2017-08-17 16:23 UTC, hush-hush requested changes
Side note: I don't know why but the command `invoke docker.build` is linked to `invoke dogstatsd.build`. Is that on purpose ?

2017-08-17 16:43 UTC, hush-hush requested changes

2017-08-18 08:24 UTC, hush-hush approved these changes

2017-08-18 09:34 UTC, merged