Nate perkins trim forward slashes from config urls
DataDog/datadog-agent pull request #4843
Opened 2020-02-05 19:50 UTC by darthnater007

### What does this PR do?
On agent configuration files, a trailing forward slash was causing URL's to have an unexpected '//' in the agent config object.  This PR adds a function that will trim extraneous forward slashes from the end of URL's to avoid scattered reports of this causing issues during runtime with submission.

It adds a function called rimTrailingSlashFromURLS in pkg/config/config.go and a corresponding test.  The function is called during created of the global Datadog config object.

### Motivation
Issue here:  https://github.com/DataDog/datadog-agent/pull/4827

Dev Card: https://trello.com/c/jU06Pend/1487-handle-trailing-in-ddurl-and-site

### Additional Notes

This PR addresses both dd_url and all additional_endpoints, including apm, process, and logs

2020-02-06 10:05 UTC, prognant reviewed
Don't forget to add the team label and a milestone for your PR.

2020-02-06 16:34 UTC, darthnater007 commented on pkg/config/config_test.go
> +    testingapm.com/:
I added an indefinite that will trim slashes from the end of the urls unless the last character in them is not '"/" in commit 60d09e8

2020-02-07 16:09 UTC, prognant commented
LGTM 👍

2020-02-07 16:10 UTC, prognant submitted a review, later dismissed

2020-02-12 08:55 UTC, prognant commented on pkg/config/config.go
> +				}
This one may failed if domain is equal to "", it should not append in normal case, but I think we should handle it. You can handle it the same way you did above, as it does not change the runtime behaviour.

2020-02-13 16:48 UTC, hush-hush requested changes

2020-02-13 16:48 UTC, hush-hush commented on pkg/config/config.go
> +	trimTrailingSlashFromURLS(config)
We should do this after we apply the overrides (ie next line)

2020-02-13 16:48 UTC, hush-hush commented on pkg/config/config.go
> +		}
This could be replaced by https://golang.org/pkg/strings/#TrimRight

2020-02-13 16:48 UTC, hush-hush commented on pkg/config/config.go
> +		if len(key) == 0 {
When checking for and empty string in go use `key != ""` instead.

2020-02-13 16:48 UTC, hush-hush commented on pkg/config/config.go
> +			}
Same here we could just do:

```go
sanitizedAdditionalEndpoints[domain] = strings.TrimRight(key, '/')
```

2020-02-14 18:40 UTC, hush-hush approved these changes

2020-02-14 19:35 UTC, merged