Upgrade pip-tool to 4.2.0
DataDog/datadog-agent pull request #4890
Opened 2020-02-13 10:36 UTC by AlexandreYang

### What does this PR do?

Upgrade pip-tool to 4.2.0.

One of the integration need URLs package: https://github.com/DataDog/integrations-core/pull/5729/files#diff-6d8f54f01f5ace930bcbbd5c8fe0283cR20

And pip-tool only support URL packages since 3.7.0: https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#370-2019-05-09

```
piptools.exceptions.UnsupportedConstraint: pip-compile does not support URLs as packages, unless they are editable. Perhaps add -e option? (constraint was: git+https://github.com/vmware/vsphere-automation-sdk-python@efe345a21b4ab7b346b65e1cb58d56412edd1c10 (from -r /.omnibus/src/datadog-agent-integrations-py2/integrations-core/agent_requirements-py2.in (line 20)))
```

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2020-02-13 13:14 UTC, hithwen submitted a review, later dismissed

2020-02-13 14:18 UTC, ofek approved these changes

2020-02-13 16:50 UTC, ofek requested changes

2020-02-13 16:50 UTC, ofek commented on releasenotes/notes/fix-upgrade-pip-tool-9e1624ae8d646165.yaml
> +upgrade:
```
Upgrade notes should be rare: only list known/potential breaking changes,
    or major behaviorial changes that require user action before the upgrade.
    Notes here must include steps that users can follow to 1. know if they're
    affected and 2. handle the change gracefully on their end.
```

```suggestion
enhancements:
```

2020-02-13 17:25 UTC, ofek approved these changes

2020-02-14 14:48 UTC, AlexandreYang commented
Closing we will use `requests` to query vSphere rest api instead. That will avoid few issues:

- not having to use git+ requirements
- vsphere-automation-sdk-python contain a lot of deps and are quite large https://github.com/vmware/vsphere-automation-sdk-python/blob/master/setup.py
- there is an issue when pip-tools compile is used during agent build

```
python -m piptools compile --verbose vsphere/requirements.in
...
    unpack_file(from_path, location, content_type, link)
  File "/Users/alexandre.yang/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 732, in unpack_file
    unzip_file(
  File "/Users/alexandre.yang/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 610, in unzip_file
    zipfp = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/tm/r8m0vyxs1_q0gqttgn969pc80000gn/T/pip-req-build-dik62xy7/lib/nsx-python-sdk/nsx_python_sdk-2.5.1.0.1.15419398-py2.py3-none-any.whl'
```

Ca fait beaucoup:
- obligé d’utliser git package dans requirements.in
- des wheel dans le repo git
- la quantité et la taille des deps

2020-02-14 15:44 UTC, AlexandreYang commented
Reopening since upgrading the deps is still a good thing and that will match py3 deps versions

2020-02-17 10:16 UTC, albertvaka approved these changes

2020-02-17 16:18 UTC, merged

2020-02-17 16:21 UTC, AlexandreYang commented
Last build is not passing, but full passing built already happened https://github.com/DataDog/datadog-agent/pull/4890 and new changes are only about release notes.