Update proxy setting to handle different scheme.
DataDog/datadog-agent pull request #554
Opened 2017-09-12 14:34 UTC by hush-hush

### What does this PR do?

Configuration of proxies now allow the user to set a different proxy per scheme and a list of 'no_proxy'.

2017-09-12 16:22 UTC, truthbk reviewed
In general buttery smooth - very nice! 💯 

Just a small comment regarding the YAML...

Also, I _think_ we want to log a message if the `http_proxy` and `https_proxy` environment variables are set but nothing is set in the datadog.yaml, just so the customer/support isn't confused if the proxy settings are not getting applied as they might expect.

2017-09-13 08:11 UTC, masci requested changes

2017-09-13 16:47 UTC, truthbk reviewed
Added a small comment. I think there's an outstanding comment from massi to address.

2017-09-14 11:57 UTC, masci approved these changes

2017-09-14 12:13 UTC, merged