Support cloud_provider_metadata in tags and ecs
DataDog/datadog-agent pull request #5581
Opened 2020-05-20 16:14 UTC by hush-hush

### What does this PR do?

Support cloud_provider_metadata in tags and ecs. We missed a few exposed function in the original PR.

2020-05-20 16:23 UTC, prognant approved these changes
LGTM from core perspective.
For container integration, does it make sense to support turning off metadata for fargate/ecs ?

2020-05-20 19:03 UTC, CharlyF requested changes
The call to disable the metadata is in the hostpath to collect metrics/tags etc (at least for ECS) I think we should block this before when deciding if we should enable the collector overall

2020-05-20 19:03 UTC, CharlyF commented on pkg/util/ecs/common.go
> +	if !config.IsCloudProviderEnabled(CloudProviderName) {
This call is in the hot path to retrieve containers, I think we should instead disable the overall collector 
https://github.com/DataDog/datadog-agent/blob/master/pkg/util/containers/collectors/detector.go

2020-05-21 16:57 UTC, CharlyF approved these changes
GetTags are respectively only called in `pkg/metadata/host/host_tags.go` when `collect_ec2_tags` or `collect_gce_tags` are set.
The latter being true by default, we will just see the error "cloud provider is disabled by configuration" for gce by default, but no call to the CP.

2020-05-21 17:10 UTC, merged