[circleci] MacOS source tests
DataDog/datadog-agent pull request #5850
Opened 2020-06-29 11:44 UTC by KSerrania

2020-06-29 12:31 UTC, mx-psi requested changes

2020-06-29 12:31 UTC, mx-psi commented on .circleci/config.yml
> +            pip install -r requirements.txt
```suggestion
            python3 -m pip install -r requirements.txt
```
(or `python2` if it's Python 2)

2020-06-29 13:00 UTC, albertvaka approved these changes

2020-06-30 09:41 UTC, mx-psi approved these changes

2020-07-10 13:50 UTC, p-lambert approved these changes

2020-07-10 14:39 UTC, merged