Adds an install script
DataDog/datadog-agent pull request #607
Opened 2017-09-22 15:11 UTC by gmmeyer

### What does this PR do?

It adds an install script. We should probably place it elsewhere, but I don't know where to put it.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2017-09-27 10:13 UTC, masci requested changes

2017-09-27 12:15 UTC, truthbk reviewed
Added some feedback, but this looks pretty good to me.

2017-09-27 14:16 UTC, truthbk reviewed
elaborated a little bit

2017-09-28 10:40 UTC, truthbk requested changes
find should be called with the `sudo_cmd`

2017-09-28 14:48 UTC, masci approved these changes

2017-09-28 14:49 UTC, merged