Send a SIGTERM signal to the secret backend before SIGKILL
DataDog/datadog-agent pull request #6395
Opened 2020-09-17 11:20 UTC by L3n41c

### What does this PR do?

Send a `SIGTERM` signal to the secret backend before `SIGKILL`.

### Motivation

Now, if the secret backend is too slow to decode the secrets, a timeout fires in the `datadog-agent` that kills the secret backend with `SIGKILL`.
The secret backend cannot catch this signal to do some cleanup and log where is was blocked.

The goal of this change is to have the `datadog-agent` send a `SIGTERM` signal that the secret backend can catch before sending the `SIGKILL` signal that will forcibly terminate the secret backend.

This mimics the behaviour of `systemd`, `docker` or any other init system.

Combined with DataDog/datadog-vault-secrets#3, if the secret backend freezes, we’ll have a stack trace of where the secret backend was blocked.
This will give us a clue as wether the issue was a DNS resolution issue, or a network connectivity issue, or a vault issue.

### Additional Notes

### Describe your test plan

Package `datadog-agent` with a version of the `datadog-vault-secrets` that contains DataDog/datadog-vault-secrets#3 and validate that, in case of time-out, get get the details about where the secret backend was blocked.

2020-09-17 18:50 UTC, olivielpeau approved these changes
LGTM overall, the implementation looks great 👌 (very nice handling of the hierarchy of timeouts with contexts)

Left a few comments, would appreciate a review from @hush-hush as well, but once my comments are addressed no need for further approval from me 👍

2020-09-17 18:50 UTC, olivielpeau commented on pkg/config/config_template.yaml
>  # secret_backend_timeout: 5
```suggestion
# secret_backend_term_timeout: 5
```

2020-09-17 18:50 UTC, olivielpeau commented on pkg/secrets/fetch_secret.go
> -			exitCode = "timeout"
the `exitCode` is used as a tag value for telemetry, I think it's useful to keep `timeout` as a possible value, any reason to remove this?

2020-09-17 18:50 UTC, olivielpeau commented on releasenotes/notes/send-SIGTERM-to-the-secret-backend-f0d12454ad45e013.yaml
> +    will now first send a ``SIGTERM`` signal before sending the ``SIGKILL`` one.
nit: can you mention the 2 config options to control these timeouts?

2020-09-17 19:52 UTC, hush-hush reviewed
A few comment. My main concern is Windows, have we tested the new behavior on it ?

2020-09-17 19:52 UTC, hush-hush commented on pkg/secrets/fetch_secret.go
> +					log.Debugf("Failed to send SIGTERM to %s (%d): %v", secretBackendCommand, cmd.Process.Pid, err)
This should be a error in my opinion.

2020-09-17 19:52 UTC, hush-hush commented on pkg/secrets/secrets.go
> +	secretBackendKillTimeout = killTimeout
I think we should check that termTimeout < killTimeout and log a warning if not. This should also be done in the `secret` command (see https://github.com/DataDog/datadog-agent/blob/master/pkg/secrets/info.go).

2020-09-22 14:52 UTC, hush-hush requested changes

2020-09-22 14:52 UTC, hush-hush commented on pkg/secrets/fetch_secret_darwin.go
> +// Unless explicitly stated otherwise all files in this repository are licensed
Why duplicate the linux code for darwin ? We could just have a windows version and a non windows version.

2020-10-07 18:14 UTC, kayayarai reviewed
no documentation impact

2021-09-07 16:08 UTC, derekwbrown approved these changes
code lgtm. 
I would also want to see some active testing on Windows before merging.

2021-09-23 12:06 UTC, closed without merging