Tracemalloc: Rename white/blacklist to include/exclude
DataDog/datadog-agent pull request #6413
Opened 2020-09-18 16:37 UTC by albertvaka

### What does this PR do?

Rename, keeping compatibility with the old names.

### Additional Notes

Needs corresponding changes in integrations-core: https://github.com/DataDog/integrations-core/pull/7626

### Describe your test plan

Not tested.

2020-09-18 20:18 UTC, ofek requested changes
👍

2020-09-18 20:19 UTC, ofek approved these changes

2020-09-21 09:05 UTC, mx-psi approved these changes

2020-10-02 10:07 UTC, hush-hush approved these changes

2020-10-02 18:36 UTC, ruthnaebeck approved these changes
👍 for docs

2020-10-26 18:34 UTC, merged