[ec2] IMDSv2 logic adjustments & comments
DataDog/datadog-agent pull request #6426
Opened 2020-09-22 10:23 UTC by prognant

### What does this PR do?
Add comments.
Relocate a `config.Datadog.GetInt(...)` that was called before loading the configuration.

### Motivation
Fix configuration.
Readability.

### Additional Notes
N/A

### Describe your test plan
Check runtime config non-default value for `ec2_metadata_token_lifetime`.

2020-09-22 10:53 UTC, hush-hush requested changes

2020-09-22 10:53 UTC, hush-hush commented on pkg/util/ec2/ec2.go
> +	if time.Now().Before(token.expirationDate.Add(-1 * tokenRenewalWindow)) {
Could we subtract that second when we set the expiration date rather than when we check if it's expired ?

2020-09-22 17:14 UTC, truthbk approved these changes
Looks good to me after addressing the last comment from @hush-hush 👍

2020-09-23 08:22 UTC, ogaca-dd approved these changes

2020-09-23 08:57 UTC, hush-hush approved these changes

2020-09-23 08:57 UTC, merged