Db/win omnibus packaging
DataDog/datadog-agent pull request #644
Opened 2017-09-27 22:47 UTC by derekwbrown

Match windows omnibus packaging strategy to linux.
Requires https://github.com/DataDog/omnibus-ruby

2017-10-02 17:17 UTC, truthbk requested changes
Added some feedback

2017-10-02 17:26 UTC, derekwbrown commented on omnibus/Gemfile
> +gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', branch: 'db/generic_extraconfs'
No, has to be changed back.  But, won't pass CI (and therefore won't be allowed to merge) w/o that, until the companion PR  https://github.com/DataDog/omnibus-ruby/pull/47 is pushed.

2017-10-02 17:26 UTC, derekwbrown commented on omnibus/Gemfile.lock
> +GIT
wasn't intentional; I'll back it out.

2017-10-02 17:26 UTC, derekwbrown commented on omnibus/config/software/datadog-agent-finalize.rb
> +        #move "#{install_dir}/etc/datadog-agent/process-agent.conf", conf_dir
Process agent will not ship with windows initially; left this here as a placeholder for when it is added.

2017-10-02 17:28 UTC, derekwbrown commented on omnibus/config/projects/agent.rb
> +  extra_package_files "#{Omnibus::Config.source_dir()}\\etc\\datadog-agent\\extra_package_files"
I may have named `extra_package_files` poorly, given the existence of extra package `extra_package_file`.  They do provide a similar functionality, though.  Makes much more sense when you consider https://github.com/DataDog/omnibus-ruby/pull/47

2017-10-04 16:59 UTC, truthbk approved these changes
:shipit:

2017-10-04 17:00 UTC, merged