Always use a 64K buffer in the UDP listener
DataDog/datadog-agent pull request #6470
Opened 2020-09-29 08:44 UTC by CAFxX

### What does this PR do?

Always use a 64K buffer when receiving UDP.

### Motivation

datadog-go allows to send bigger UDP packets than this, and there is really no reason to conflate the size of the size of the receive buffer with that of the buffers in the internal queue.

Increasing the size of the receive buffer to the maximum allowed UDP size will remove a footgun and simplifies configuration, as now the buffer size controls a single thing (the size of buffers in the queue), not two. Because there is a single receive buffer, memory increase is very limited (+56KB).

This change is discussed in https://github.com/DataDog/datadog-go/issues/168, that provides additional context why allowing bigger UDP packets *by default* makes sense.

### Additional Notes

Reading https://github.com/DataDog/datadog-go/issues/168 will help.

### Describe your test plan

The only meaningful test would be sending, to an agent with the default configuration, a statsd UDP packet of size >> 8192 bytes. If it works, all is good.

2020-09-29 08:51 UTC, remeh commented
Hey @CAFxX,
Thanks for the very interesting point-of-view and detailed issue. I will give a look into it and we also have benchmarks / scenarios here I'm interested to run this against.
You've addressed it but I'll carefully validate that it won't just trade RAM usage against throughput, which is something which is an issue in a lot of real-world scenarios. (but you've mentioned in the datadog-go issue and you're right that tweaking the `dogstatsd_queue_size` could do the job).
In all honesty, maybe not in detail this week but I'll look into this soon, it's very interesting.

2020-09-30 18:49 UTC, ruthnaebeck requested changes
Docs review

2020-09-30 18:49 UTC, ruthnaebeck commented on docs/dogstatsd/configuration.md
> +The `dogstatsd_buffer_size` parameter configures how many bytes maximum the PacketAssembler should put into one packet.
```suggestion
The `dogstatsd_buffer_size` parameter configures the maximum number of bytes the PacketAssembler should put into one packet.
```

2020-09-30 18:49 UTC, ruthnaebeck commented on docs/dogstatsd/configuration.md
> +Please note that increasing this buffer size, together with `dogstatsd_queue_size`, has a huge impact on the maximum memory usage:
```suggestion
**Note**: Increasing this buffer size, together with `dogstatsd_queue_size`, has a huge impact on the maximum memory usage:
```

2020-09-30 18:49 UTC, ruthnaebeck commented on docs/dogstatsd/configuration.md
> +of the pipeline is having slow-down for any reasons. Each packet is of size `dogstatsd_buffer_size`.
```suggestion
of the pipeline is slowing down for any reason. Each packet is of size `dogstatsd_buffer_size`.
```

2020-10-02 18:25 UTC, ruthnaebeck approved these changes
👍 for docs

2021-01-20 16:29 UTC, truthbk commented
Hi @CAFxX thank you for your patience. We hadn't forgotten about this PR, but other work around the dogstatsd server processing pipeline derailed us a little bit. While I definitely agree that the UDP socket receive buffer and the internal buffers are different, disjoint elements, the internal representation of the messages is somewhat coupled; let me explain.

It's definitely true that the maximum size for UDP datagrams is 64kB, and that currently requires setting `dogstatsd_buffer_size` to said value, otherwise we just can't carry the dogstatsd payload through the processing pipeline. You mention the size of the socket receive buffer and these internal buffers should not be conflated; however it doesn't make much sense to read more than we can store in these buffers from the socket. Consider the following:

1. We read 64kB from the socket (but say our internal buffers can only hold 8kB `dogstatsd_buffer_size`).
2. We pass the receive buffer from (1) to the packet assembler, but it will only be able to copy 8kB because it's the most the internal buffers hold, so that message will likely be dropped while parsed. Or worse, it could potentially correctly parse a truncated message. Probably the safe thing to do here is just drop the message in the packet assembler in this event, something we're not currently doing.

Increasing the size of internal buffers to 64kB would certainly have an impact in memory usage (8-fold increase for the shared packet pool by default), all while remembering we use that shared packet pool also for unix domain sockets. We'd probably not want to do this by default to avoid using too much memory with the shared packet pool, this is why it's configurable.

So while you're absolutely correct about the receive buffer being it's own beast, it doesn't buy us much to always set it to 64kB because we can't internally carry a message larger than `dogstatsd_buffer_size` through the pipeline. One could argue that the current design is reasonable, as having the socket receive buffer match the internal buffer size allows us to weed out large messages that we'd be unable to process immediately.

I hope this makes sense.

2021-02-01 14:43 UTC, truthbk commented
Closing this PR for the time being. Please see the comment above for more details on the reasoning. Regardless, thank you very much for your help and contribution (and a very valid point!) @CAFxX. We'll keep this in mind for further dogstatsd development.

2021-02-01 14:43 UTC, closed without merging