Simplify the Forwarder interface by removing the argument `priority`
DataDog/datadog-agent pull request #7077
Opened 2020-12-30 18:58 UTC by ogaca-dd

### What does this PR do?

Simplify the Forwarder interface by removing the argument `priority`

Note: `SubmitMetadata` and `SubmitHostMetadata` were unused.
Before, `Serializer.SendMetadata` and `Serializer.SendHostMetadata` called `Forwarder.SubmitV1Intake`.
Now  these 2 functions call respectively `Forwarder.SubmitMetadata` and `Forwarder.SubmitHostMetadata` which perform the same as `Forwarder.SubmitV1Intake` (`Forwarder.SubmitHostMetadata` use TransactionPriorityHigh)

### Describe your test plan
The code should behave the same as before.

- Check metadata and hostmetadata payloads are send correctly.
- Check the hostmetadata payloads are always kept in the forwarder retry queue (because of TransactionPriorityHigh)

2020-12-31 10:47 UTC, prognant approved these changes
LGTM

2020-12-31 12:53 UTC, hush-hush requested changes

2020-12-31 12:53 UTC, hush-hush commented on pkg/forwarder/forwarder.go
> +func (f *DefaultForwarder) submitV1Intake(
Could we rename this function, having 2 functions with the same name in upper and lower case is confusing.

2021-01-04 11:07 UTC, hush-hush approved these changes

2021-01-11 13:11 UTC, merged