Ian.bucad/timestamps utc
DataDog/datadog-agent pull request #7229
Opened 2021-01-21 02:56 UTC by ian28223

### What does this PR do?

Displays UTC time and timestamp in milliseconds in status log.
Uses UTC in flare's filename

### Motivation

- AC-760
- Useful when NTP offset information is unavailable. Time in filename can be compared to Zendesk upload date/time
- Timestamp in milliseconds included as it is commonly used in partlows and dogq queries

### Additional Notes

- Example when system time is not in GMT+0: `2021-01-20 21:47:10.571 AEDT / 2021-01-20 10:47:10.571 UTC (1611139630571)`
- Example when system time is already GMT+0: `2021-01-20 10:47:10.571 UTC (1611139630571)`

### Describe your test plan

- On system set in GMT+0 timezone, `datadog-agent status` only adds timestamp in milliseconds
- On system set in GMT+N timezone, `datadog-agent status` adds converted UTC time in addition to the timestamp in milliseconds

2021-01-21 15:12 UTC, prognant reviewed
LGTM, only a few minor remarks.
I tested it on mac with the `TZ` env var and it works as expected.

2021-01-21 17:45 UTC, prognant commented
LGTM, few minor remarks.
Tested it on my mac with the `TZ` env var it works as expected.

2021-01-22 14:32 UTC, prognant requested changes
I'm not sure it's really useful to keep the old behaviour, regarding template helpers I think we should keep those as simple as possible to keep it readable.

2021-01-22 14:32 UTC, prognant commented on pkg/status/status.go
> +	stats["agent_start_nano"] = startTime.UnixNano()
I'm not sure it brings much benefit as this force us to call `formatUnixTime` with new parameter. If that's really helpful to keep sub-second precision, I think we should have `formatUnixTime` & `formatUnixTimeNano` to increase template readability.

2021-01-25 05:58 UTC, ian28223 commented on pkg/status/helpers.go
> +	*/
decided to keep it simple. thanks!

2021-02-03 12:44 UTC, prognant approved these changes
LGTM 👍

2021-02-05 00:44 UTC, merged