Fix SQL query leak when obfuscation fails
DataDog/datadog-agent pull request #7302
Opened 2021-01-28 16:37 UTC by nunofgs

### What does this PR do?

Does not expose the full SQL query when obfuscation fails.

### Motivation

We found some traces that contained the full query in Datadog, unobfuscated. Example:

![pg](https://user-images.githubusercontent.com/92085/106169135-f3479a00-6186-11eb-870f-7c5c705b872c.png)

2021-02-01 09:49 UTC, gbbr approved these changes
LGTM. Thanks!

2021-02-01 15:52 UTC, gbbr requested changes
You have to sign our CLA and add a release note to your PR. You can copy this one. Simply place the file at the same location with the same contents and it should be fine: https://github.com/DataDog/datadog-agent/blob/5addc604099d76243ec6551782d510576883d2a1/releasenotes/notes/apm-nonparsable-resource-leak-a16ab87fb2c04c36.yaml

2021-02-01 23:07 UTC, nunofgs commented
@gbbr, thanks! I've updated the PR.

2021-02-02 08:49 UTC, gbbr approved these changes
Thanks a lot!

2021-02-02 12:45 UTC, merged