[docker] port capped_metrics option
DataDog/datadog-agent pull request #743
Opened 2017-10-24 14:37 UTC by xvello

### What does this PR do?

- wrap aggregator.Sender in a custom cappedSender
- implement configurable rate limiting on metrics
- update dist and tests

### Motivation

See https://github.com/DataDog/integrations-core/pull/412 for original implementation reasons

2017-10-24 15:02 UTC, hkaj requested changes

2017-10-24 15:02 UTC, hkaj commented on pkg/collector/corechecks/containers/docker.go
> +	sender, err := d.updateCappedSender()
Does that mean we always use it? If so we always use the custom `Rate` method. Could we only use the CappedSender when `capped_metrics` is set instead?

2017-10-24 15:02 UTC, hkaj commented on pkg/collector/corechecks/containers/docker_rate_capping.go
> +	delta := value - previousValue
should we compute the rate here instead of the delta? I think when users set the cap they expect it to apply to the rate as they see it in the app.

2017-10-25 12:24 UTC, xvello commented on pkg/collector/corechecks/containers/docker_rate_capping.go
> +	timestamp time.Time // Current time at check Run()
Added here instead of checking `time.Now()` for performance + testability (see `GetSender` for the update of that value)

2017-10-25 12:34 UTC, xvello commented on pkg/collector/corechecks/containers/docker_rate_capping.go
> +	dockerRateCachingDuration = time.Minute
One cache entry per context, let's expire them quicker than the default

2017-10-30 15:27 UTC, hkaj approved these changes
neat

2017-10-30 15:28 UTC, merged