[WIP] DSD Static Deploys
DataDog/datadog-agent pull request #747
Opened 2017-10-25 19:05 UTC by gmmeyer

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

2017-10-26 06:51 UTC, xvello commented
The dsd static binary is generated [without symbol tables nor debug information](https://github.com/DataDog/datadog-agent/blob/c0476b9aa3df3cdd5cb49b22cc470e7ff72ebeca/tasks/utils.py#L62), in order to keep a binary size < 15 MB despite it being statically linked. This was an acceptable tradeoff to be able to run on alpine's musl for the lightweight dogstatsd alpine docker image, but I really think we should avoid using it out of this context.

For non-dockerized environments, it think it's better to build dynamically-linked binaries and distribute them as deb / rpm packages via the repo. This way, we avoid statically linking in the libc, and have debug symbols if needed.

2017-10-26 17:35 UTC, gmmeyer commented
@xvello I'm setting this up to run in the cloud foundry containerized environment

2017-10-26 17:44 UTC, gmmeyer commented
@xvello It's the same use case, I agree that this shouldn't be publicly available, but I cannot install a package in there and I have no guarantees about what will be in there. Compiling will be a frustrating user experience and cause vastly increased app deploy times. So, providing a staticly linked binary is likely the best way to do this.

2017-10-26 17:44 UTC, gmmeyer commented
https://github.com/DataDog/datadog-cloudfoundry-buildpack

2017-10-26 17:45 UTC, gmmeyer commented
On our heroku buildpack we use the agent5 apt package, which works because we know heroku runs ubuntu containers (maybe they're debian). However, on Cloud Foundry we have no such guarantee.

2017-10-27 12:46 UTC, xvello commented
OK. Although a "dynamic" dsd (`inv dogstatsd.build`) is "static enough" that it'll run on both debian&centos, and virtually anywhere providing a decent glibc (that means every distro but alpine).
I think you should investigate other buildpacks they provide (to see if they have compiled binaries), but it's probably safe to assume a glibc will be present.

2017-10-27 18:11 UTC, gmmeyer commented
Many of them do provide binaries. I've surveyed a bunch of them about this and talked with Pivotal. This is a pretty normal strategy. I can provide that instead of the static binary. If it causes trouble I'll start providing the static one instead.

2017-10-27 18:28 UTC, gmmeyer commented
@xvello I changed it to just be the binary instead of the static binary

2017-10-27 21:52 UTC, gmmeyer commented
I think this is now good to go, now that the cloudops PR has been merged.

2017-10-30 08:54 UTC, xvello requested changes
That looks better to me, some issues with the paths and comments

2017-10-30 08:54 UTC, xvello commented on .gitlab-ci.yml
> +  DOGSTATSD_BINARIES_DIR: bin/static
that should be `bin/dogstatsd`, right?

2017-10-30 08:54 UTC, xvello commented on .gitlab-ci.yml
> +# deploy rpm packages to yum staging repo
comment needs updating

2017-10-30 17:20 UTC, gmmeyer commented on .gitlab-ci.yml
> +# deploy rpm packages to yum staging repo
done!

2017-10-30 17:20 UTC, gmmeyer commented on .gitlab-ci.yml
> +  DOGSTATSD_BINARIES_DIR: bin/static
it should be yes!

2017-10-31 16:04 UTC, xvello submitted a review, later dismissed
LGTM

2017-11-02 18:29 UTC, masci approved these changes

2017-11-02 18:43 UTC, merged