Document forwarder option in config_template.yaml
DataDog/datadog-agent pull request #7474
Opened 2021-02-18 11:29 UTC by ogaca-dd

### What does this PR do?

Document several forwarder parameters.

### Describe your test plan

Check that invalid settings (invalid path, negative value, zero) do not make the Agent crash for:
- forwarder_storage_path
- forwarder_outdated_file_in_days
- forwarder_flush_to_disk_mem_ratio
- forwarder_storage_max_size_in_bytes
- forwarder_storage_min_size_in_bytes
- forwarder_storage_max_disk_ratio

2021-02-19 16:23 UTC, sarina-dd approved these changes

2021-02-19 17:32 UTC, sgnn7 requested changes
@ogaca-dd Just a few nits that could use changing

2021-02-19 17:32 UTC, sgnn7 commented on pkg/config/config_template.yaml
> +## is reached or when the disk usage exceeds 95% of the disk capacity.
```suggestion
## `forwarder_storage_max_disk_ratio` defines the disk capacity limit for storing transactions.
## `0.9` means the Agent can store transactions on disk until `forwarder_storage_max_size_in_bytes` 
## is reached or when the disk mount for `forwarder_storage_path` exceeds 90% of the disk capacity,
## whichever is lower.
```

2021-02-19 17:32 UTC, sgnn7 commented on pkg/config/config_template.yaml
> +## `forwarder_outdated_file_in_days` days ago, it is removed.
```suggestion
## This value specifies how many days the overflow transactions will remain valid before
## being discarded. During the Agent restart, if a retry file contains transactions that were
## created more than `forwarder_outdated_file_in_days` days ago, they are removed.
```

2021-02-19 17:32 UTC, sgnn7 commented on pkg/config/config_template.yaml
> +
Extra newline here isn't needed

2021-02-19 17:32 UTC, sgnn7 commented on pkg/config/config_template.yaml
> +
Extra newline here isn't needed

2021-02-22 15:18 UTC, sgnn7 approved these changes
👍

2021-02-23 10:12 UTC, merged