Agent.build now honors embedded_path for rtloader
DataDog/datadog-agent pull request #7616
Opened 2021-03-09 14:56 UTC by vboulineau

### What does this PR do?

Currently building the Agent with `agent.build` will not work properly with custom `embedded_path` as implicitly built rtloader will not be installed there but in `./dev` anyway.
It's useful to build Agent binaries that can be hotswapped easily in containers.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

No QA

2021-03-09 17:07 UTC, sgnn7 reviewed
@vboulineau Do you mind adding some info on this to https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_dev_env.md?

2021-04-09 10:02 UTC, vboulineau commented
> @vboulineau Do you mind adding some info on this to https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_dev_env.md?

Added a doc about target usage of this change

2021-04-12 08:28 UTC, mx-psi approved these changes, later dismissed

2021-04-12 08:28 UTC, mx-psi commented on docs/dev/agent_build.md
> +Building an Agent Docker image from strach through an embedded build is a slow process.
```suggestion
Building an Agent Docker image from scratch through an embedded build is a slow process.
```

2021-04-12 08:28 UTC, mx-psi commented on docs/dev/agent_build.md
> +Sometimes, you may want to quickly test a change or bufix in a containerized environment (Docker, Kubernetes, ECS, etc.).
```suggestion
Sometimes, you may want to quickly test a change or bugfix in a containerized environment (Docker, Kubernetes, ECS, etc.).
```

2021-04-12 08:28 UTC, mx-psi commented
woops, meant to be a comment, not an approval

2021-04-12 09:15 UTC, mx-psi approved these changes
LGTM, CI errors are probably fixed by merging/rebasing master

2021-04-12 17:54 UTC, jtappa requested changes

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +Sometimes, you may want to quickly test a change or bugfix in a containerized environment (Docker, Kubernetes, ECS, etc.).
```suggestion
You can quickly test a change or bug fix in a containerized environment (such as Docker, Kubernetes, or ECS).
```

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +One way to do it is to patch the Agent binary from official Docker image, with a simple Dockerfile:
```suggestion
One way to do this is to patch the Agent binary from an official Docker image, with a Dockerfile:
```

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +- Your change needs to be done on top of `<AGENT_VERSION>` tag from our repository.
```suggestion
- Your change needs to be done on top of the `<AGENT_VERSION>` tag from the DataDog repository.
```

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +- You need to run invoke task with proper embedded path `inv -e agent.build -e /opt/datadog-agent/embedded`.
```suggestion
- You need to run the invoke task with the proper embedded path `inv -e agent.build -e /opt/datadog-agent/embedded`.
```

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +Note that this will make `invoke` to install the builds artifacts in `/opt/datadog-agent/embedded` folder. Make sure folder exists and current user has write permissions.
```suggestion
**Note**: This makes `invoke` install the build's artifacts in the `/opt/datadog-agent/embedded` folder. Make sure the folder exists and the current user has write permissions.
```

2021-04-12 17:54 UTC, jtappa commented on docs/dev/agent_build.md
> +However, for this to work properly, two things are important:
```suggestion
For this to work properly, two things are important:
```

2021-04-14 16:36 UTC, jtappa approved these changes

2021-05-11 13:54 UTC, merged