switch zstd path to github.com/DataDog/zstd_0
DataDog/datadog-agent pull request #7634
Opened 2021-03-10 18:41 UTC by niamster

### What does this PR do?
Switch `zstd` repository from `github.com/DataDog/zstd` to `github.com/DataDog/zstd_0`

### Motivation
The latest `v1.x` version of zstd is not compatible with the legacy binary format.
To ensure that both versions can coexist in the same project it's preferred to have a dedicated repository with mangled names.

### Additional Notes

`zstd` diff: https://github.com/DataDog/zstd_0/compare/2bf71ec48360...586c1286621ffa183e6b66eb1df0aa52596b5ca2

Agent payload diff: https://github.com/DataDog/agent-payload/compare/v4.59.0...v4.62.0

### Describe your test plan

Trust CI. This should be a `noop` since it's exactly the same revision of the lib.

2021-03-10 19:42 UTC, olivielpeau approved these changes
Thanks!

The repo is in code freeze for 7.27.0, and I assume this isn't urgent, so setting the milestone to 7.28.0.

Tagging @nammn for a review as well since the `github.com/DataDog/agent-payload` version bump includes changes to the orchestrator payloads

2021-03-10 21:49 UTC, nammn approved these changes
LGTM! Orchestrator payload bump should be fully compatible

2021-03-11 08:39 UTC, niamster commented
Thanks @olivielpeau . Indeed it's not urgent. Please let me know when it's the best time to merge this.

2021-03-11 08:50 UTC, L3n41c approved these changes

2021-03-11 10:15 UTC, niamster commented
> 👍 I'll track this PR as something to merge when the code freeze is lifted

Perfect, thank you 🙇

2021-03-23 15:56 UTC, hush-hush requested changes

2021-03-23 15:56 UTC, hush-hush commented on go.mod
> +	github.com/DataDog/datadog-go v4.4.0+incompatible
I think you reverted datadog-go

2021-03-24 09:29 UTC, nammn approved these changes

2021-03-24 10:16 UTC, hush-hush approved these changes

2021-03-24 10:30 UTC, merged