Deprecate undocumented `process_agent_config.host_ips` in favor of `process_config.docker_host_ips`
DataDog/datadog-agent pull request #7694
Opened 2021-03-21 14:23 UTC by lbunschoten

### What does this PR do?

Fixes #5081 
- Get rid of the class cast warning noise when trying to read the `process_agent_config.host_ips` property
- Deprecated `process_agent_config.host_ips` in favor of `process_config.docker_host_ips`. The old variables naming scheme is incosistent with other properties for the process agent. The old property is still supported. When both properties are used, the new one will take precedence.
- Added missing documentation for this property
- Added sane default (list of empty string)
- This bit of code was hardly tested, so I've added a couple of tests

### Motivation

I am opening this pull request to address the issue described in https://github.com/DataDog/datadog-agent/issues/5081. The default configuration for the process agent causes a warning to be logged every couple of hours. This is just noise, that can lead to confusion. The main reason seems to be an incorrect default (nil vs empty list)

### Additional Notes

This is my first PR for the datadog-agent. I tried to follow allow the guidelines, but please do let me know if I have missed something.

### Describe your test plan

- The automatic tests should pass
- Set the new property in the config and verify that the property is picked up.
- Set both the new and the deprecated property in the config. Verify that the new property is picked up.
- Set the deprecated property in the config. Verify that the deprecated property is picked up.
- Using the default process_agent config, verify that the log line `2020-03-05 05:45:40 UTC | PROCESS | WARN | (pkg/config/viper.go:168 in GetStringSlice) | failed to get configuration value for key "process_agent_config.host_ips": unable to cast <nil> of type <nil> to []string` is not printed

2021-03-25 16:55 UTC, ruthnaebeck requested changes
Docs review

2021-03-25 16:55 UTC, ruthnaebeck commented on releasenotes/notes/proces-agent-add-docs-host-ip-config-1cd97e31ec2ae586.yaml
> +# Each section from every release note are combined when the
```suggestion
# Each section from every release note is combined when the
```

2021-03-25 16:55 UTC, ruthnaebeck commented on releasenotes/notes/proces-agent-add-docs-host-ip-config-1cd97e31ec2ae586.yaml
> +    Changed the attribute name to define the host IPs for the process agent
```suggestion
    Changed the attribute name to define the host IPs for the process Agent
```

2021-03-25 16:55 UTC, ruthnaebeck commented on releasenotes/notes/proces-agent-add-docs-host-ip-config-1cd97e31ec2ae586.yaml
> +    docker container from `process_agent_config.host_ips` to
```suggestion
    Docker container from `process_agent_config.host_ips` to
```

2021-03-25 16:55 UTC, ruthnaebeck commented on releasenotes/notes/proces-agent-add-docs-host-ip-config-1cd97e31ec2ae586.yaml
> +    The process agent no longer logs a cast warning message when no
```suggestion
    The process Agent no longer logs a cast warning message when no
```

2021-03-25 16:55 UTC, ruthnaebeck commented on releasenotes/notes/proces-agent-add-docs-host-ip-config-1cd97e31ec2ae586.yaml
> +    host IPs have been configured.
```suggestion
    host IPs are configured.
```

2021-03-25 19:55 UTC, ruthnaebeck approved these changes
👍  for docs

2021-04-10 14:07 UTC, lbunschoten commented
Would anyone from the team also be available to review the actual code? There are quite some +1s on the related issue, so I'd appreciate it if we could work towards fixing this

2022-02-24 09:03 UTC, clamoriniere approved these changes

2022-02-24 09:49 UTC, olivielpeau reviewed
Requesting a review from @DataDog/processes to review the code changes in the context of the recent improvements to the process agent config options (and whether it makes sense to rebase this PR on top of them).

2022-02-25 09:34 UTC, mbotarro commented
Thanks for pointing it out, @olivielpeau. In fact we should rebase this PR on top of the config refactor that is introduced on process-agent `7.35.0`. I'll leave some comments on the PR about what should be changed.

2022-02-25 09:37 UTC, mbotarro commented on pkg/config/config.go
> +	config.BindEnvAndSetDefault("process_config.docker_host_ips", []string{})
We should move the setting declaration to the `setupProcess` in the new `pkg/config/process.go` file and use `procBindEnv`. This helper function will automatically bind the env vars  `DD_PROCESS_CONFIG_DOCKER_HOST_IPS` and `DD_PROCESS_AGENT_DOCKER_HOST_IPS` to it.

2022-02-25 20:13 UTC, lbunschoten commented
Nice to see that there is some sudden interest in this PR :)  It has been a while since I've created it. I don't think I'll be able to help out much anymore, since I haven't worked with the datadog-agent lately and can't tell if this is still an issue. But, feel free to continue with it and still merge it in (once the conflicts and so on are resolved) :)

2026-02-20 15:37 UTC, jacjtito commented
Hi,

We are closing this PR as there was no recent activity on it. Feel free to reopen it if you still need the feature.
Thanks

2026-02-20 15:37 UTC, closed without merging