Fix windows string conversions.
DataDog/datadog-agent pull request #7986
Opened 2021-04-27 05:42 UTC by derekwbrown

String conversions were done with manual, inefficient loops rather than
built in primitives

### What does this PR do?

Fixes very poor implementation of string conversions from windows APIs.

### Motivation

it is possible that these conversions are triggering a deadlock in the go runtime.

2021-04-27 15:18 UTC, brycekahle requested changes
I added some comments about more defensive handling of NULL terminators.

2021-04-27 15:18 UTC, brycekahle commented on pkg/util/winutil/winstrings.go
> +		return []string{}
You can return `nil` here, which is a zero value for slices.

2021-04-27 15:18 UTC, brycekahle commented on pkg/util/winutil/winstrings.go
> +		if c == 0 {
If the double NULL, indicating the end of the list, occurs anywhere but the end of the slice, this code will not handle it properly. The previous implementation did though. I'd suggest following its structure, and just replacing the string decoding parts.

2021-04-27 15:18 UTC, brycekahle commented on pkg/util/winutil/winstrings.go
> +	if winput[len(winput)-1] == 0 {
Is it possible to have the NULL terminator anywhere other than the end?

2021-04-27 15:18 UTC, brycekahle commented on pkg/util/winutil/winstrings.go
>  func ConvertASCIIString(input []byte) string {
I don't think this function is used, and can be removed since it is essentially just a cast.

2021-04-27 16:21 UTC, brycekahle approved these changes

2021-05-13 16:48 UTC, shang-wang approved these changes

2021-05-13 16:50 UTC, truthbk reviewed
Looks good for the most part, some units tests for this would be amazing.

2021-05-26 19:51 UTC, truthbk approved these changes

2021-05-28 23:50 UTC, merged