Add cgroup memory controller
DataDog/datadog-agent pull request #8166
Opened 2021-05-17 10:49 UTC by lebauce

### What does this PR do?

Proactively call GC when memory used is aboved a specified threshold or when memory pressure events are sent by the kernel

### Motivation

Avoid OOM kills

2021-08-11 14:10 UTC, djmitche approved these changes

2021-08-11 14:13 UTC, djmitche requested changes
I believe this needs an update to [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml)

2021-08-11 14:13 UTC, djmitche commented
..and perhaps a release note, since this is introducing an enhancement?

..and a rebase, since the dogstatsd size has increased recently :)

2021-09-30 15:49 UTC, Gui774ume approved these changes

2021-12-14 21:50 UTC, brycekahle commented on cmd/system-probe/utils/memory_monitor_linux.go
> +			if err := pprof.WriteHeapProfile(memProfile); err != nil {
Should we log out the location of the memory profile file?

2022-01-25 13:41 UTC, lebauce commented
@djmitche Thanks for the review and sorry for the LONG delay. I addressed your comments and updated the config template. I'm not sure about the release notes though as this is mostly for troubleshooting purposes.

2022-01-25 19:28 UTC, alai97 commented on pkg/config/config_template.yaml
> +    ## The action can be either:
Either implies one or the other (not three options).

```suggestion
    ## The action can be:
```

2022-01-25 19:28 UTC, alai97 commented on pkg/config/config_template.yaml
> +    ## The actions are the same than for thresholds (see above).
```suggestion
    ## The pressure level is 'low', 'medium', or 'critical'.
    ## The actions are the same for thresholds (see above).
```

2022-01-25 19:29 UTC, alai97 approved these changes
Looks good, just two copy nits. Should we maybe update `// Copyright 2016-2020 Datadog, Inc.` to `2016-2022 Datadog, Inc.`?

2022-01-25 19:54 UTC, djmitche reviewed
The config template change looks OK for agent-core.

But, I want to be sure: is this something we'd like customers to know about and tweak on their own?  Or is it for internal / support use?  If the latter, then including it in the template may not be a good idea.

2022-01-26 09:02 UTC, vboulineau commented
@lebauce Would it make sense to add this feature to our own `cgroups` package: https://github.com/DataDog/datadog-agent/pull/9121?

2022-01-27 15:43 UTC, lebauce commented
@vboulineau Yes, it totally makes sense.

@djmitche This is for internal / support but it's hidden behind a boolean `InternalProfiling` false by default

@alai97 Applying your suggestions

2022-01-31 16:51 UTC, djmitche approved these changes
config template changes look good

2022-02-02 09:09 UTC, merged