[AD] Allow skipping secret backend for check configs
DataDog/datadog-agent pull request #8492
Opened 2021-06-24 12:41 UTC by ahmed-mez

### What does this PR do?

Support skipping secret backend calls when discovering checks.

### Motivation

Avoid decrypting cluster checks at the Cluster Agent level.

### Describe how to test your changes

- Configure secret backend on both the Cluster Agent and the CLC Runner as per [this documentation](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux#kubernetes-secrets).
- Enable `DD_SECRET_BACKEND_SKIP_CHECKS` in the Cluster Agent config
```
  env:
  - name: DD_SECRET_BACKEND_SKIP_CHECKS
    value: "true"
```
- Configure a cluster check with `ENC[<key>]` in its config
- Cluster Agent should log this debug line `'secret_backend_skip_checks' is enabled, not decrypting configuration <check name>`
- `agent clusterchecks` should show the field encrypted (`ENC[<key>]`)
- The CLC Runner should decrypt the secret and run the check

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

2021-06-24 18:04 UTC, ruthnaebeck requested changes
Docs review, please ping if you need a re-review

2021-06-24 18:04 UTC, ruthnaebeck commented on releasenotes-dca/notes/support-skipping-sb-for-configs-9b4b589b8ba09638.yaml
> +    The Cluster Agent can now be instructed to dispatch cluster checks without decrypting secrets.
```suggestion
    The Cluster Agent can be instructed to dispatch cluster checks without decrypting secrets.
```

2021-06-24 18:04 UTC, ruthnaebeck commented on releasenotes-dca/notes/support-skipping-sb-for-configs-9b4b589b8ba09638.yaml
> +    The node Agent or the Cluster Check Runner will fetch the secrets once they get the configurations from the Cluster Agent.
```suggestion
    The node Agent or cluster check runner fetch the secrets after receiving the configurations from the Cluster Agent.
```

2021-06-24 18:04 UTC, ruthnaebeck commented on releasenotes-dca/notes/support-skipping-sb-for-configs-9b4b589b8ba09638.yaml
> +    This can enabled by setting ``DD_SECRET_BACKEND_SKIP_CHECKS`` to ``true`` in the Cluster Agent config.
```suggestion
    This can be enabled by setting ``DD_SECRET_BACKEND_SKIP_CHECKS`` to ``true`` in the Cluster Agent config.
```

2021-06-28 17:09 UTC, ruthnaebeck approved these changes
👍  for docs

2021-06-29 09:16 UTC, clamoriniere approved these changes
Small comment about log level. 
Otherwise look good 👍

2021-06-29 09:16 UTC, clamoriniere commented on pkg/autodiscovery/autoconfig.go
> +		log.Debugf("'secret_backend_skip_checks' is enabled, not decrypting configuration %q", conf.Name)
maybe it should be "Trace" here

2021-06-29 10:14 UTC, ogaca-dd approved these changes

2021-06-29 10:15 UTC, ahmed-mez commented on pkg/autodiscovery/autoconfig.go
> +		log.Debugf("'secret_backend_skip_checks' is enabled, not decrypting configuration %q", conf.Name)
```suggestion
		log.Tracef("'secret_backend_skip_checks' is enabled, not decrypting configuration %q", conf.Name)
```

2021-06-29 10:50 UTC, hush-hush approved these changes

2021-06-29 11:51 UTC, merged