Xvello/fixhostname
DataDog/datadog-agent pull request #853
Opened 2017-11-24 12:46 UTC by xvello

### What does this PR do?

Rework the hostname detection logic.

### Motivation

`master` currently fails on EC2 hosts because the error handling is inconsistent between the different providers.
This PR reworks the detection logic by iterating over an array to make sure all providers have the same error handling.

Also, validate all hostnames with `ValidHostname` to handle EC2 returning `"", nil` sometimes. We can now put it on the first bucket, with GCE, for consistent cross-cloud behaviour.

2017-11-24 14:33 UTC, JulienBalestra requested changes
lgtm, a few tricks for the quote formatting and see if we remove the string parameter in the `HostnameProvider`

2017-11-24 14:33 UTC, JulienBalestra commented on pkg/util/ec2/ec2.go
> -	if ecs.IsInstance() || IsDefaultHostname(hostName) {
Maybe we can change the signature of HostnameProvider(s) from
`func HostnameProvider(hostName string) (string, error)` to `func HostnameProvider() (string, error)` ?

2017-11-24 14:33 UTC, JulienBalestra commented on pkg/util/hostname.go
We can make a simple call of the log for both lines.

2017-11-24 14:33 UTC, JulienBalestra commented on pkg/util/hostname.go
> +			log.Infof("got hostname \"%s\" from %s", name, provider.Name)
ditto for `%q`

2017-11-24 14:33 UTC, JulienBalestra commented on pkg/util/hostname.go
> +	return "", fmt.Errorf("Unable to reliably determine the host name. You can define one in the agent config file or in your hosts file")
s/Unable/unable

2017-11-25 17:58 UTC, tmichelet commented on pkg/util/hostname.go
> +		for _, provider := range providers {
I would hardcode the list of providers, so we keep the order constant

2017-11-26 15:48 UTC, hkaj requested changes

2017-11-26 15:48 UTC, hkaj commented on pkg/util/hostname/providers.go
> +type ProviderPriority uint
This is way overkill. As @tmichelet mentioned above we should probably just hardcode providers.

2017-11-27 09:46 UTC, closed without merging