Store HTTP latencies as seconds represented by float64
DataDog/datadog-agent pull request #8562
Opened 2021-07-06 22:14 UTC by brycekahle

### What does this PR do?

APM requested we store the HTTP latencies in the sketches as seconds. We are also matching their gamma/bias settings.

### Motivation

Reduce conversion error when converting sketch latencies.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.

2021-07-06 22:17 UTC, p-lambert requested changes

2021-07-06 22:17 UTC, p-lambert commented on pkg/network/http/model.go
> +	return float64(uint64(tx.response_last_seen-tx.request_started) / uint64(time.Second))
I don't think we want to do this integer division (otherwise you will truncate values < 1s

2021-07-06 22:23 UTC, p-lambert approved these changes

2021-07-06 22:26 UTC, p-lambert commented
PS.: You can test your stuff using the `http://unix/debug/http_monitoring`

2021-07-08 19:23 UTC, jdgumz approved these changes

2021-07-08 19:59 UTC, merged