[gitlab] Refactor functional tests definition
DataDog/datadog-agent pull request #8815
Opened 2021-08-05 15:00 UTC by KSerrania

### What does this PR do?

Refactors the system-probe and security-agent kitchen test definitions to make them easier to read & group them to make the pipeline UI more readable.

### Motivation

Make pipeline & pipeline config more readable.

### Additional Notes

We may also shorten the job names by removing the `kitchen_` prefix, making them easier to read in Gitlab. It shouldn't be an issue as long as there aren't two jobs with the same name in the pipeline.

### Describe how to test your changes

Run a pipeline with system-probe and security-agent kitchen tests.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

2021-08-06 09:24 UTC, paulcacheux commented
This looks good to us in the `team/agent-security`. We'll see how it works like that and maybe do the suggested changes in the job names

2021-08-06 11:51 UTC, paulcacheux approved these changes

2021-08-06 12:11 UTC, mx-psi approved these changes

2021-08-09 18:41 UTC, brycekahle requested changes

2021-08-09 18:41 UTC, brycekahle commented on .gitlab/functional_test/system_probe.yml
> +        KITCHEN_OSVERS: "centos-77,rhel-81"
This needs to remain `centos-76`

2021-08-12 15:02 UTC, brycekahle approved these changes

2021-08-16 08:17 UTC, merged