[Serverless] skip hostname resolution in Serverless context
DataDog/datadog-agent pull request #8845
Opened 2021-08-10 16:34 UTC by maxday

### What does this PR do?

Skip hostname resolution in serverless context when loading and validation the agent config

### Motivation

Extension start time / cold start improvements

### Describe how to test your changes

Unit testing 

### Checklist

- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-08-10 17:04 UTC, nhinsch commented on pkg/serverless/trace/trace_test.go
> +func TestLoadConfigShouldBeFast(t *testing.T) {
:100:

2021-08-10 17:06 UTC, nhinsch commented on pkg/trace/config/config.go
> +// This will skip hostname resolution as hostname need to be empty in a serverless context
Nit:
```suggestion
// This will skip hostname resolution as hostname is empty in a serverless context
```

2021-08-10 17:07 UTC, nhinsch approved these changes
Looks great! 🥇

2021-08-10 18:12 UTC, gbbr commented on pkg/trace/config/config.go
> +func (c *AgentConfig) validate(hostNameResolution bool) error {
Please don't take this approach. Simply just add a new boolean field to `*AgentConfig` called `DisableGRPCHostname` and return from `acquireHostname` early with an error if it's set:
```go
return errors.new("disabled by config")
```

2021-08-10 18:15 UTC, gbbr commented on pkg/trace/config/config.go
> +func (c *AgentConfig) validate(hostNameResolution bool) error {
Oh, wait. You can't do that.

2021-08-10 18:18 UTC, gbbr requested changes
I don't think this is a good approach. Design-wise boolean args are smells and functionality wise I don't think it's a good idea to disable hostname acquisition regardless of situation. The data should be shared between agents.

The right path here is to fix the gRPC client so that it fails early (and doesn't stall by timing out) if the endpoint is not available.

2021-08-11 13:53 UTC, maxday commented
Closing this one since this should be a better implementation : https://github.com/DataDog/datadog-agent/pull/8850

2021-08-11 13:53 UTC, closed without merging