Add support for sourcing tags from Kubernetes environment variables
DataDog/datadog-agent pull request #8921
Opened 2021-08-18 19:44 UTC by csssuf

### What does this PR do?

Add support for a new config, `kubernetes_container_env_as_tags`, which applies tags to Kubernetes containers based on environment variable values. This is done similarly to the existing `kubernetes_pod_labels_as_tags`/`kubernetes_pod_annotations_as_tags` features.

### Motivation

We would like to apply custom tags to our pods based on values from the downward API. Previously, we did so via the `DD_DOCKER_ENV_AS_TAGS` feature, since we could set envvars with downward API values, and Datadog would pick up the envvars from the containers themselves. However, we've recently begun migrating our Kubernetes clusters to containerd, and so `DD_DOCKER_ENV_AS_TAGS` will no longer work for us. Reading the envvars directly from the Kubernetes pod spec itself provides a replacement for `DD_DOCKER_ENV_AS_TAGS`.

(Since downward API values are not currently interpreted by the Kubelet tag collector, I have a followup PR which adds that functionality as well.)

### Additional Notes

An alternate approach (for our original usecase) would be to simply skip the environment variable plumbing altogether and support directly mapping downward API fields to tag names. Would that be a preferable approach? Even if so, would _this_ PR still be useful?

### Describe how to test your changes

- New unit test for envvar tag mapping added and passing
- Full agent container built and deployed with `DD_KUBERNETES_CONTAINER_ENV_AS_TAGS` configured; verified desired tags are reported back to Datadog.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

2021-08-19 17:11 UTC, ruthnaebeck requested changes
Docs review

2021-08-19 17:11 UTC, ruthnaebeck commented on pkg/config/config_template.yaml
> +## The Agent can extract container environment variable values and set them as metric tags values associated to a <TAG_KEY>.
```suggestion
## The Agent can extract container environment variable values and set them as metric tag values associated to a <TAG_KEY>.
```

2021-08-19 17:11 UTC, ruthnaebeck commented on pkg/config/config_template.yaml
> +## If you prefix your tag name with `+`, it will only be added to high cardinaly metrics.
```suggestion
## Prefix your tag name with `+`, to only add the values to high cardinality metrics.
```

2021-08-19 17:54 UTC, csssuf commented
Pushed docs fixes, thanks!

2021-08-20 14:21 UTC, djmitche approved these changes

2021-08-20 14:53 UTC, ahmed-mez reviewed
Hi @csssuf 

Thanks for the contribution!

We understand the need and the use-case, it's been already on our radar but we're also evaluating other alternatives that could solve similar problems at once (like implementing separate `containerd` collector). 

We'll get back to you in the coming days.

Thanks!

2021-08-25 15:08 UTC, csssuf commented
Hi @ahmed-mez,

Glad to hear this is being worked on! Do you have a more concrete estimate for when a solution will be available?

2021-08-25 15:33 UTC, ahmed-mez commented
@csssuf 👋 

Our vision is to provide a generic option `container_env_as_tags` regardless of the container runtime (it will replace `docker_env_as_tags` eventually). So adding a `kubernetes_container_env_as_tags` config is not the best approach now unfortunately.

We have plans to refactor the whole container metadata collection logic which is a requirement for supporting `container_env_as_tags`. 

Please open an official feature request by contacting our [support team](https://www.datadoghq.com/support/) so you can track the progress.

Thank you!

2021-09-24 17:51 UTC, closed without merging