Add a new flag to the Windows installer to allow overriding the install method
DataDog/datadog-agent pull request #8940
Opened 2021-08-19 15:28 UTC by julien-lebot

### What does this PR do?

This PR adds a new flag to the installer to allow to override the `install_info`.

### Motivation

Allow writing the `install_info` from install methods that cannot execute additional code after install (e.g. winget).

### Additional Notes

The `install_info` will always be written now, regardless of the quiet `/q` flag.

### Describe how to test your changes

Run the installer with the GUI, check that the `install_info` file is created and contains `windows_msi_gui`.
Run the installer with the CLI with the `/q` flag, check that the `install_info` is created and contains `windows_msi_gui`.
Run the installer with the CLI with the `/q` flag (or not) and `OVERRIDE_INSTALLATION_METHOD=winget` (or other value than `winget`), check that the `install_info` is created and contains the value entered.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.

2021-08-20 07:53 UTC, mx-psi requested changes

2021-08-20 07:53 UTC, mx-psi commented on tools/windows/install-help/cal/FinalizeInstall.cpp
> +    std::wstring customInstallMethod = L"windows_msi_gui";
When running the installer with `/q` we won't have a GUI thus I think the install method should be something else (like `windows_msi_cli`) or be absent as before.

2021-08-20 07:53 UTC, mx-psi commented on tools/windows/install-help/cal/FinalizeInstall.cpp
> +    std::wofstream installInfoOutputStream(installInfoFile);
This will override the existing install_info file, right? We don't want that since it will erase the Chocolatey install info files.

2021-08-20 07:53 UTC, mx-psi commented on tools/windows/install-help/cal/FinalizeInstall.cpp
> +bool writeInstallInfo(const CustomActionData &customActionData)
Can we add unit tests for (1) when there was no file present and (2) when there was an install info file present (like with chocolatey)?

2021-08-20 13:53 UTC, albertvaka commented on omnibus/resources/agent/msi/source.wxs.erb
> -      </Component>
We want to continue doing this old logic if OVERRIDE_INSTALLATION_METHOD isn't set.

2021-09-02 07:46 UTC, mx-psi approved these changes
LGTM!

> if the file exists it will overwrite it, if not it will create it.

I think that's not what we were doing up until now (if there was a file we left it there), but I think it's better to override it actually; it makes more sense to have the latest way the Agent was installed. So, I am approving!

2021-09-02 11:23 UTC, albertvaka commented
I think this assumption makes sense here. On Linux we didn't do it this way, because if you first use chef and then you do an `apt upgrade` we didn't want to have `apt` "win". But that doesn't apply on Windows.

2021-09-02 13:37 UTC, merged