Telemetry that count the number of tags in the contextes of the aggregator
DataDog/datadog-agent pull request #8944
Opened 2021-08-19 17:43 UTC by ogaca-dd

### What does this PR do?

Add a new telemetry that count the number of tags in the contextes of the aggregation.

### Describe how to test your changes

Send metrics with high number of contextes and tags (For example with DogStatsD) and check the value of the telemetry.

### Checklist

- [X] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [X] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [X] The appropriate `team/..` label has been applied, if known.
- [X] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [X] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-08-19 18:10 UTC, djmitche requested changes, later dismissed

2021-08-19 18:10 UTC, djmitche commented on pkg/aggregator/aggregator.go
> +	aggregatorExpvars.Set("EventPlatformEventsErrors", &aggregatorEventPlatformEventsErrors)
I'm not sure why this is duplicated?

2021-08-19 18:31 UTC, sgnn7 approved these changes
@ogaca-dd One small question and if we don't need to decrement the value, LGTM.

2021-08-19 18:31 UTC, sgnn7 commented on pkg/aggregator/context_resolver.go
> +		tlmContextsTagsCount.Add(float64(len(tags)))
@ogaca-dd I would assume if we want the number of tags in the aggregator contexts, then contextKey evictions should reduce the value. Am I misunderstanding the intended use of this telemetry var?

2021-09-16 10:04 UTC, ogaca-dd commented
This telemetry is not needed anymore.

2021-09-16 10:04 UTC, closed without merging