Exposing docker labels to docker.Container
DataDog/datadog-agent pull request #917
Opened 2017-12-07 19:49 UTC by sunhay

### What does this PR do?

Exposing the docker labels from `ecs.Container` & `types.Container` to `docker.Container`

### Motivation

We'll be ingesting docker labels via the [datadog-process-agent](https://github.com/DataDog/datadog-process-agent) soon. I'm basing this PR against `haissam/new-ecs-listener` since it's a small change + the process agent is currently pinned to it.

2017-12-07 21:51 UTC, conorbranagan reviewed
Looks good to me. Not sure why the AppVeyor builds are failing

2017-12-11 09:48 UTC, xvello requested changes
I'd rather not add it to the `Container` object itself and continue decoupling data and metadata.
FYI, the tagger extracts docker labels as tags with a [configurable mapping](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L258) allowing to get more expressive tag names and whilelist high card tags.

If you still want to collect tags in a different code path, you can use [dockerutil's AllContainerLabels()](https://github.com/DataDog/datadog-agent/blob/master/pkg/util/docker/docker_util.go#L481) method in a metadata collector. But the best would be to use the same code, to be consistent across pipelines.

2017-12-11 12:22 UTC, conorbranagan commented
Is the Tagger something that can be used externally without initializing other agent packages? Is there any example of this anywhere?

2017-12-11 14:03 UTC, conorbranagan commented
I found this example which seems like it should work for our case: https://github.com/DataDog/datadog-agent/pull/920/files#diff-aee9c7d47d58391c414374696f7732d6R216.

Does this require initialization with the yaml file? Is there a way to make this continue to work with Agent5?

2017-12-11 15:36 UTC, xvello commented
You can import the `pkg/tagger` package and use the global `Init` and `Tag` methods from https://github.com/DataDog/datadog-agent/blob/master/pkg/tagger/global.go

For labels to be extracted, you need to init the `pkg/config` package with the good path for `datadog.yaml`. Aren't you already using it anyway to connect to the kubelet?

This would work on a standalone process-agent running with agent5, as long as users set their label mapping in a datadog.yaml file

2017-12-11 15:37 UTC, conorbranagan commented
We have just added initialization with the yaml file but it's only on `master` so far but it sounds like the tagger should work here. Are there sane defaults here if they don't have a `datadog.yaml` file, as in the case for v5?

2017-12-11 15:51 UTC, xvello commented
Indeed, we have sane defaults, but the default for label extraction (in both agent5 and agent6) is to collect nothing, instead of collecting potentially high-card tags

2017-12-11 17:06 UTC, hkaj commented
It's better to use Tagger for label collection as it means we'll only need to update metadata collection in one place in the future. However if you do need the labels in the Container struct for other reasons I'm fine with it. It fits here. Let me know if that's needed and I'll ✅

2017-12-11 17:12 UTC, conorbranagan commented
I'm good with the tagger approach, we'll change this up

2017-12-11 17:44 UTC, sunhay commented
Thanks @xvello & @hkaj: I'll switch to using the tagger :)

2017-12-11 17:44 UTC, closed without merging