Fix cgroup parsing for PCF containers
DataDog/datadog-agent pull request #9245
Opened 2021-09-24 14:14 UTC by NouemanKHAL

### What does this PR do?

Fix the `cgroup` collector to correctly pickup PCF containers.

### Motivation

Bugfix.

### Additional Notes

Anything else we should know when reviewing?

### Describe how to test your changes

Deploy a `process-agent` in a PCF environment, the `Live Container View` should display metrics correctly.

### Checklist

- [X] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-09-24 14:19 UTC, zippolyte approved these changes

2021-09-27 08:48 UTC, vboulineau approved these changes

2021-09-27 14:13 UTC, zippolyte requested changes

2021-09-27 14:13 UTC, zippolyte commented on releasenotes/notes/fix-pcf-containers-metrics-collection-299f02a5bbf180d1.yaml
> +    Fix the cgroup collector to correctly pickup PCF containers.
```suggestion
    Fix the cgroup collector to correctly pickup Cloud Foundry containers.
```

2021-09-27 14:14 UTC, zippolyte approved these changes

2021-09-27 15:35 UTC, merged