Add additional best-practices for testing
DataDog/datadog-agent pull request #9335
Opened 2021-09-30 18:27 UTC by djmitche

This attempts to reflect existing best-practices, rather than
introducing new practices.

### Motivation

A rising tide that lifts all test-reliability boats :)

2021-09-30 18:50 UTC, djmitche commented
(I didn't mention aliasing here since this is a testing-related document.. we can add that separately)

2021-09-30 19:34 UTC, albertvaka approved these changes

2021-09-30 19:59 UTC, ruthnaebeck requested changes
Docs review

2021-09-30 19:59 UTC, ruthnaebeck commented on docs/dev/testing.md
> +This document describes some best-practices for unit testing in the agent.
```suggestion
This document describes some best-practices for unit testing in the Agent.
```

2021-09-30 19:59 UTC, ruthnaebeck commented on docs/dev/testing.md
> +Note that the code will never completely reflect these practices, although we hope to get continually closer.
```suggestion
**Note**: The code will never completely reflect these practices, although we hope to get continually closer.
```

2021-09-30 19:59 UTC, ruthnaebeck commented on docs/dev/testing.md
> +For example, given an error, `assert.NoError(t, err)` will cause the test to be marked as a failure, but will continue on to the next statement, possibly leading to a nil dereference or other such fa
```suggestion
For example, given an error, `assert.NoError(t, err)` causes the test to be marked as a failure, but continues to the next statement, possibly leading to a nil dereference or other such failure.
```

2021-09-30 19:59 UTC, ruthnaebeck commented on docs/dev/testing.md
> +In contrast, `require.NoError(t, err)` will abort the test when an error is encountered.
```suggestion
In contrast, `require.NoError(t, err)` aborts the test when an error is encountered.
```

2021-09-30 20:53 UTC, djmitche commented
What other languages would that include?  I can add some text to scope these practices to Go, anyway.

2021-10-01 13:46 UTC, djmitche commented
Cool, thanks.  I have no objections to best-practices for other languages, too, but I also don't know what those best practices would be, so I'll let others write them or wait until I _do_ know :)

2021-10-01 13:49 UTC, djmitche commented
(These docs may also evolve to be more than just _testing_ best practices, and cover non-testing code too.. time will tell!)

2021-10-01 14:12 UTC, djmitche commented on docs/dev/testing.md
> +## Prefer `require` over `assert`
That's a good way to phrase it.

2021-10-01 14:24 UTC, mx-psi approved these changes

2021-10-01 14:24 UTC, mx-psi commented
Thanks for doing this!! 🙇

2021-10-01 15:51 UTC, ruthnaebeck approved these changes
👍 for docs

2021-10-01 15:59 UTC, merged