[Serverless] Add check for the extension cold start duration
DataDog/datadog-agent pull request #9481
Opened 2021-10-12 12:45 UTC by maxday

### What does this PR do?

Update the existing Serverless check to : 
- build the extension
- package it into a docker container
- run 5 invocations (cold-start forced)
- check for starting time
- compare against a threshold
- exit 1 / 0 depending on whether or not the threshold has been reached

### Motivation

Avoid unwanted performance regression

### Additional Note
<img width="836" alt="Screen Shot 2021-10-12 at 5 52 57 PM" src="https://user-images.githubusercontent.com/864493/137035122-678fb4f9-2282-46eb-9e7e-5523ae88f493.png">

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [x] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-10-12 22:05 UTC, DarcyRaynerDD approved these changes
LGTM, left some nits

2021-10-15 14:59 UTC, mx-psi approved these changes

2021-10-15 14:59 UTC, mx-psi requested changes
didn't mean to approve, I wanted to request changes instead 😅

2021-10-18 08:32 UTC, mx-psi approved these changes

2021-10-18 08:35 UTC, vboulineau approved these changes

2021-10-26 15:26 UTC, merged