Code Scanning Configs for datadog-agent
DataDog/datadog-agent pull request #9566
Opened 2021-10-18 16:57 UTC by ganeshkumarsv

### What does this PR do?

Adds Configurations to scan `Datadog/datadog-agent` and push Code Scanning results to Github. The PR also contains fixes for uncontrolled data in path expression.

### Motivation

What inspired you to submit this pull request?
Datadog is expanding the CodeQL adoption on its open source repositories. 

### Additional Notes

Anything else we should know when reviewing?

For more info on how Github Code Scanning works: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

### Describe how to test your changes
Enable Code Scanning on Datadog/datadog-agent from the repository's settings page. Once the PR gets merged, the CodeQL github action runs on `main` branch and you can see the security findings getting pushed under the repository's `Security` -> `Code Scanning Alerts` tab.

### Checklist

- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-10-18 17:05 UTC, djmitche approved these changes

2021-10-19 07:16 UTC, mx-psi requested changes
Using a new CI system means a lot of new issues, if you can use Gitlab, Appveyor or CircleCI it would be much easier for us to maintain. I am reviewing here assuming you can't but please explore that option.

2021-10-19 09:17 UTC, vickenty requested changes

2021-10-21 19:58 UTC, ganeshkumarsv commented
>Using a new CI system means a lot of new issues, if you can use Gitlab, Appveyor or CircleCI it would be much easier for us to maintain. I am reviewing here assuming you can't but please explore that option.

@mx-psi The main reason why we wanted to use Github actions is because, its available free for the public repositories. So we are aiming to make use of the Github actions in setting up the Code Scanning on all Datadog public repos. 
cc: @stephengroat

2021-10-22 07:32 UTC, mx-psi approved these changes

2021-10-22 13:30 UTC, vickenty approved these changes

2021-10-22 14:01 UTC, merged