Split scrubbing into ./pkg/util/scrubber
DataDog/datadog-agent pull request #9618
Opened 2021-10-21 18:06 UTC by djmitche

This breaks the "scrubbing" functionality out of ./pkg/util/log and into its own package.  

It also renames things to consistently use "scrub" and its various conjugations.

### Motivation

Poorly-isolated functionality :)

### Additional Notes

This new package is a module, like ./pkg/util/log.  Mostly because ./pkg/util/log depends on it!

With this PR merged, I'd like to make a few followups:
 * Move the scrubbing functionality currently implemented for flares into the new ./pkg/util/scrubber package
 * Refactor scrubbing a bit to better define the "things" that can be scrubbed.  It's designed to scrub YAML files.  Its function names suggest it can scrub files, bytes, and URLs.  And in practice it's used to scrub strings that are none of those things (e.g., calling `ScrubURL(somethingThatIsNotAURL)`).
 * Clarify the distinction between scrubbing and the orchestrator's "redaction" support.  I think these are distinct, at least :)

### Describe how to test your changes

To test config scrubbing:
* Start an agent
* Run `agent config` and check that the API key is scrubbed

To test the `flare_stripped_keys` config:
* Set `flare_stripped_keys` to include a key in your config, e.g., `flare_stripped_keys: [logs_enabled]`
* Run `agent config` and check that the key is scrubbed

To test that logs are being scrubbed:
* Grep your agent log for `hasValidAPIKey` and see that it scrubbed the API key

2021-10-22 11:01 UTC, olivielpeau reviewed
If I understand the code correctly, a significant behavior difference this PR introduces is that `pkg/util/log` doesn't apply any scrubbing by default when imported as a module (~i.e. when imported from outside the datadog-agent repo).
I'm not sure we're comfortable with that behavioral change though. Typically I believe the OTLP collector's DD exporter imports this module cc @mx-psi .

Maybe we'd simply want to define `pkg/util/scrubber` as its own module to avoid the "funny business" you mention in the code? WDYT @djmitche ?

2021-10-22 13:45 UTC, mx-psi requested changes

2021-10-22 14:13 UTC, mx-psi approved these changes

2021-10-25 17:30 UTC, olivielpeau approved these changes
LGTM once my comment is addressed. Please update the PR description as well (it currently reflects the PR's state before you made the new package a module).

2021-10-26 14:27 UTC, paulcacheux approved these changes

2021-10-26 14:50 UTC, mfpierre approved these changes
LGTM for @DataDog/container-app

2021-10-26 15:49 UTC, merged