[windows] [npm] Switch to release-signed driver which contains fix to test.
DataDog/datadog-agent pull request #9630
Opened 2021-10-22 15:16 UTC by derekwbrown

Enable TestUDPSendAndReceive test

### What does this PR do?

Incorporates new driver which contains fix to npm correctness

### Additional Notes

Change includes enabling automated test (which had exposed the driver problem to begin with).

### Describe how to test your changes

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.

2021-10-28 17:53 UTC, brycekahle approved these changes

2021-11-03 11:43 UTC, vickenty approved these changes

2021-12-17 16:47 UTC, alai97 requested changes

2021-12-17 16:47 UTC, alai97 commented on releasenotes/notes/fixudpnpmcorrectness-2bde6c1434723c3b.yaml
> +    was inbound, it would not be counted correctly.
```suggestion
    Fixes an NPM issue on Windows where if the first packet on a UDP flow
    is inbound, it is not counted correctly.
```

2021-12-17 16:48 UTC, alai97 approved these changes
Looks good for docs!

2021-12-17 21:01 UTC, merged