Maxime/add oracle cloudprovider
DataDog/datadog-agent pull request #9748
Opened 2021-11-03 17:12 UTC by hush-hush

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe how to test your changes

Write here in detail how you have tested your changes
and instructions on how this should be tested in QA.

Describe or link instructions to set up environment 
for testing, if the process requires more than just
running the agent on one of the supported platforms.

### Checklist

- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

2021-12-09 17:03 UTC, ruthnaebeck requested changes
Docs review

2021-12-09 17:03 UTC, ruthnaebeck commented on releasenotes/notes/add-oracle-cloud-12445d3962a5d4b0.yaml
> +    Cloud provider detection now support Oracle Cloud. This includes cloud provider detection, host aliases and NTP
```suggestion
    Cloud provider detection now supports Oracle Cloud. This includes cloud provider detection, host aliases, and NTP
```

2021-12-10 15:34 UTC, djmitche approved these changes

2021-12-10 15:34 UTC, djmitche commented on pkg/config/config_template.yaml
>  ## and alibaba providers. Some cloud provider are not enabled by default to not
```suggestion
## alibaba and oracle providers. Some cloud provider are not enabled by default to not
```

2021-12-10 18:25 UTC, ruthnaebeck approved these changes
👍  for docs

2021-12-13 13:07 UTC, merged