autoconfig: automatically starts the docker listener
DataDog/datadog-agent pull request #986
Opened 2017-12-27 16:36 UTC by JulienBalestra

### What does this PR do?

This PR add the docker listener if the docker socket is present on the host.

2017-12-27 16:38 UTC, mfpierre commented on pkg/config/config.go
> +func isDockerSocket() bool {
`Mounted` or `Present` at the end of the function name would sound nicer

2017-12-27 16:43 UTC, xvello commented
I'm not a fan of having that kind of detection logic out of the `util/docker` package. Plus, we might want to use the `kubelet` listener instead, or even disable AD altogether (think about a gitlab runner host).

I'd rather:

- have an explicit `auto` setting, that might become the default:
```
listeners:
  - name: auto
```
- reuse the `Retrier` interface instead of creating new detection code, see https://github.com/DataDog/datadog-agent/pull/861 for how the tagger implements it

2017-12-27 17:07 UTC, mfpierre commented on pkg/config/config.go
> +		log.Infof("docker socket found: add docker listener")
s/add/adding

2017-12-29 15:28 UTC, masci requested changes
Left a couple of comments but I might miss the point of this changes, can you please elaborate the use case and the solution implemented in the PR description?

2017-12-29 15:28 UTC, masci commented on pkg/config/config_template.yaml
> +# Choose "auto" if you want to let the agent find any relevant listener on your host
Can we make this more clear with an example showing how to choose "auto"?

2017-12-29 15:28 UTC, masci commented on pkg/config/auto_listener.go
> +func AutoAddListeners(listeners []Listeners) []Listeners {
The semantic is not clear to me: what happens if I select "auto" and "docker"? Or, in the future, "auto" and "kubelet"?

2017-12-29 15:28 UTC, masci commented on pkg/config/auto_listener.go
> +func isDockerRun() bool {
I'd call this `isDockerRunning`

2018-01-08 12:48 UTC, hkaj requested changes
Looks good, just need to update the headers for the new year (🎉 ) and let's merge it.

2018-01-08 13:11 UTC, JulienBalestra commented
@hkaj I rebased and updated the dates :+1:

2018-01-08 13:21 UTC, hkaj approved these changes
🚢 it

2018-01-08 13:24 UTC, merged