Add an `sslkeylogfile` parameter to store the TLS master secrets
DataDog/datadog-agent pull request #9992
Opened 2021-11-24 15:09 UTC by L3n41c

### What does this PR do?

Add a `sslkeylogfile` config parameter and its corresponding `DD_SSLKEYLOGFILE` environment variable to specify a file to store the TLS secrets used by the agent.
This file can then be used by wireshark to decipher the encrypted traffic.

### Motivation

There are classes of issues that require to inspect the network traffic for troubleshooting.
Typically, when an agent sends a payload to an intake and the intake rejects that payload, we need to have a way to look at what is precisely the rejected query.

### Additional Notes

This option compromises security and should only be used for debugging.

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

Check that the [“Dump the encrypted traffic generated by a datadog agent” howto](https://datadoghq.atlassian.net/l/c/xVLQ9i1C) works as expected.

### Reviewer's Checklist

- [X] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [X] The appropriate `team/..` label has been applied, if known.
- [X] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [X] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [X] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [X] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [X] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

2021-11-24 18:24 UTC, ruthnaebeck requested changes
Docs review

2021-11-24 18:24 UTC, ruthnaebeck commented on pkg/config/config_template.yaml
> +## sslkeylogfile optionally specifies a destination for TLS master secrets
```suggestion
## sslkeylogfile specifies a destination for TLS master secrets
```

2021-11-24 18:24 UTC, ruthnaebeck commented on pkg/config/config_template.yaml
> +## in NSS key log format that can be used to allow external programs
```suggestion
## in NSS key log format to allow external programs
```

2021-11-24 18:24 UTC, ruthnaebeck commented on pkg/config/config_template.yaml
> +## See https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format.
```suggestion
## For more details, see https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format.
```

2021-11-25 09:10 UTC, clamoriniere approved these changes

2021-12-01 09:30 UTC, tetrillard-datadog approved these changes

2021-12-01 17:41 UTC, ruthnaebeck approved these changes
👍 for docs

2021-12-02 16:52 UTC, djmitche approved these changes
Looks good.  I appreciate the acknowledgement that this compromises security.  Any case where an attacker could modify this setting are cases where the agent is already compromised, so this does not increase the attack surface or introduce a new vulnerability.

2021-12-07 09:56 UTC, merged